### ISSUE TITLE
Add connection speed tracking

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#109]
Nice to have.

See [hack 69](http://books.google.com/books?hl=en&id=v3ebu7RJT3oC&dq=web+analytics+demystified&printsec=frontcover&source=web&ots=-DZlvUfYXb&sig=aHHNvEWYsU-zjw1Sfq3yhtEj4i0&sa=X&oi=book_result&resnum=5&ct=result#PPA272,M1) in Web Analytics Demystified for one implementation approach.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/226
