### ISSUE TITLE
br_version field not set for Snowplow users running Clojure Collector in VPC

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1111]
This is a really odd one...

For users running the Clojure Collector in a VPC, it appears that the `br_version` field is never populated. That is inspite of the fact that otherwise the useragent is successfully parsed and all the other browser fields are correctly populated.

We can see for users who've migrated from the Cloudfront to the Clojure collector that the `br_version` field is no longer populated using the following query:

``` sql
SELECT
CASE WHEN br_version IS NULL THEN 0 ELSE 1 END AS br_version,
v_collector,
COUNT(*)
FROM atomic.events
GROUP BY 1,2
ORDER BY 1,2
```

We've confirmed that user agents that are present in those data sets are successfully parsed for `br_version` for the Clojure collector running in a non-VPC environment and for users running the Cloudfront collector.

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
