### ISSUE TITLE
StorageLoader: add support for multi-part copies for file moves

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1122]
Currently, StorageLoader doesn't successfully archive files that are > 5GB, owing to an AWS S3 PUT limitation that only supports files up to 5GB.

The workaround is to use a multipart copy (the AWS CLI does this using Boto under the covers). I don't know if Fog supports this - it does seem to support multipart uploads see [here](http://baldowl.github.io/2011/02/18/multipart-uploads-with-fog.html) for an example.

**Comment by alexanderdean** [comment]
Closing given #2548
