### ISSUE TITLE
Tracking item views

### ISSUE THREAD

**Issue by kingo55** [snowplow/snowplow#113]
I've always wanted to be able to track views of products on ecommerce sites similar to how Google AdWords tracks ad views in different positions on a page. I've thought about how this could work and I believe we would need to track the following parameters:

* Area on page (e.g. category listing, similar products, recently viewed)
 * Product SKU
 * Position within area (e.g. 1, 2, 3 and so on)

If not passing it through events, I would imagine it could be tracked as follows and then deserialised during the ETL:

```
snaq.push(['trackOffers','category listing',{Array of SKUs in the order they are displayed in the area}]);
snaq.push(['trackOffers','recently viewed',{Array of SKUs in the order they are displayed in the area}]); // Count of ranking continues from previous area
```

This would be a killer of an analytics feature to be able to offer out of the box - particularly for product managers. You could look at a product's CTR and conversion rate alongside all of SnowPlow's other metrics.

Thoughts?

EDIT: Can also work for a news site / blog in terms of article link clickthrough rates.

**Comment by alexanderdean** [comment]
Closing as this will be implemented in the JavaScript Tracker (doesn't require any updates to core).
