### ISSUE TITLE
Add upgrade steps to the wiki

### ISSUE THREAD

**Issue by smugryan** [snowplow/snowplow#1136]
It would be great for the full upgrade steps that are posted to the blog to be added to the wiki. This way all the upgrade steps are located in one section.

**Comment by EZWrighter** [comment]
I am about to start the daunting task of migrating from 0.9.1 to the lastest so the AWS emr service will keep running :-(  Something like this would be super helpful.  Even a page with all of the release blogs posts would give me a starting point.

**Comment by alexanderdean** [comment]
A couple of tips:

1. Upgrade just to R64 as that's the one with IAM role support
2. You'll have to upgrade to Hadoop Enrich 0.14.1 for compatibility with the latest EmrEtlRunner
3. You'll have to upgrade from Redshift 0.3.0 straight through to 0.6.0

Hope that helps

**Comment by kingo55** [comment]
Try this handy link for a list of releases without digging through the
blog.

http://snowplowanalytics.com/categories.html#releases

**Comment by EZWrighter** [comment]
Also, the translation of old config properties to new is super helpful here: https://groups.google.com/d/msg/snowplow-user/1k6DIpRHKwA/DIoXhMH7ZmMJ  If there are other places to help navigate the config file aka: history file that would also be very helpful!

**Comment by EZWrighter** [comment]
Ok...upgraded and running normally again.

Couple notes on Migrating from 0.9.2 --> r64

1.  Update to r64 codebase
2.  Migrate Postgres from 2-->3-->4-->5 with scripts in storageloader s
3.  Update cloudfront collector pixel.
4.  Update config file based on the link I added above to Alex's translations of old config
5.  Add --skip shred since I am using postgres and it doesn't seem to do anything with the emr processed shred files.
6.  Change out all buckets to remove any periods in their names.
7.  Success :-)

**Comment by alexanderdean** [comment]
Great to hear it! Thanks for taking the time to document this Eric.

Alex

**Comment by ihortom** [comment]
@alexanderdean - Added the page [locally](https://github.com/ihortom/snowplow-wiki-temp/wiki/Upgrading-Steps). For now it covers releases r65 through r76. Will add earlier releases soon.

**Comment by alexanderdean** [comment]
Pushed: https://github.com/snowplow/snowplow/wiki/Upgrading-Steps

This is great - keep it coming @ihortom !

**Comment by alexanderdean** [comment]
I wouldn't go past v0.9.0 - diminishing returns

**Comment by ihortom** [comment]
@alexanderdean - Added releases r60 - r64 and slightly updated the layout as discussed as well as renamed the page

**Comment by alexanderdean** [comment]
Thanks - pushed!

**Comment by ihortom** [comment]
@alexanderdean - Added releases v0.9.5 - v0.9.14.

**Comment by alexanderdean** [comment]
Thanks, I've repushed your local copy

**Comment by ihortom** [comment]
@alexanderdean - Added the remaining agreed releases v0.9.0 - v0.9.4. Could be closed now.

**Comment by alexanderdean** [comment]
Great job, closing
