### ISSUE TITLE
Kinesis S3 Sink: extend to support storing enriched events to S3

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1155]

**Comment by kazjote** [comment]
:+1:

**Comment by alexanderdean** [comment]
Hey @kazjote - please let us know:

1. What processing tool you want to use with the enriched events in S3 (Hadoop / Spark / Hive / something else)
2. What format you would like the enriched events stored in (sequence files? parquet?)
3. What folder structure you would like the enriched events partitioned into

**Comment by kazjote** [comment]
Thanks for your interest in the topic.

1. I am using Spark to analyze data
2. Anything that Spark can read will do
3. The best would be split by appId

**Comment by alexanderdean** [comment]
I think for starters we just follow the [Secor project](https://github.com/pinterest/secor#output-file-formats) and write new line delimited raw text files for enriched events. This will let them be picked up by Spark and Spark Streaming.

**Comment by kazjote** [comment]
It works for me. For debugging purposes we are using mainly Ruby scripts - reading parquet files could be problematic with Ruby (however, still possible with JRuby)
