### ISSUE TITLE
EmrEtlRunner: add tags for monitoring to config.yml

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1163]
Useful for tracking prod vs dev, different instances etc

**Comment by alexanderdean** [comment]
Let's push this back until it's supported by Elasticity too.

**Comment by alexanderdean** [comment]
Hey @fblundun - this one isn't working I'm afraid. What is happening is:

* The tag field names are being converted into symbols
* The symbols are then failing the Contract check

Expected:

    :monitoring=>{:tags=>#<Contracts::HashOf:0x32442dd0 @value=String, @key=String>

Got:

    :monitoring=>{:tags=>{:client=>"snowplow", :job=>"snplow2"}

**Comment by fblundun** [comment]
Sorry about this! It should be working now.

**Comment by alexanderdean** [comment]
Thanks Fred!
