### ISSUE TITLE
Formalize conversion of schema to table name

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1189]
I'm trying to do this automatically in the Elasticsearch sink shredder in a way that matches how we have been converting e.g. `"iglu:org.w3/PerformanceTiming/jsonschema/1-0-0"` to "`org_w3_performance_timing_1"`, but there's still some potential for ambiguity.

For example my regex would convert the schema name `"abcDEF"` to `"abc_d_e_f"` which is probably not quite what we're looking for.

Maybe the rule for converting the name should be

``` scala
name.replaceAll("([^_A-Z])([A-Z])", "$1_$2").toLowerCase
```

rather than

``` scala
name.replaceAll("([^_])([A-Z])", "$1_$2").toLowerCase
```

This would convert `"abcDEF"` to "`abc_def`" because it puts an underscore in front of every capital letter preceded by something other than an underscore or a capital letter.

Not sure if there are other edge cases I'm missing...

It would be nice to decide on a definitive regex that our schemas have to match. Right now I'm using

``` scala
""".+:([a-zA-Z0-9_\.]+)/([a-zA-Z0-9_]+)/[^/]+/(.*)"""
```

which has room for improvement.

**Comment by BenFradet** [comment]
done in loader, closing
