### ISSUE TITLE
Update StorageLoader so that loads a specified run of data to atomic.events

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1198]
Currently, when StorageLoader loads shredded data into Redshift, it specified a path to the shredded file as part of the Redshift `copy` statement which includes the etl_tstamp in it.

It does not do this when loading data from the enriched events table - instead it loads everything in the enriched/good bucket.

If we could specify the precise location of the enriched files to be copied, the way we do with the shredded files, it would make it less likely that in the event that there's an overlap between two runs, data would be loaded twice.

**Comment by chuwy** [comment]
It seems StorageLoader was able to load from enriched good at some point. Closing as this is not the case with RDB Loader.
