### ISSUE TITLE
Make all file moves and locations in enrichment process etl_tstamp specific

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1199]
Building on https://github.com/snowplow/snowplow/issues/1198...

Currently in some places in the data pipeline on S3, the data lives in a folder that indicates which processing run it belongs to. (E.g. in enrichment out and in enrichment archive.)  However, when the data is in processing, we do not know what run it belongs to. This means we have to be very careful never to let processing runs overlap.

If we saved the data to be processed in 'processing/etl_tstamp', and then made all the processing and file move operations act on the specified directly including the etl_tstamp, it would be possible to run the pipeline multiple times with overlap / in parallel, with individual runs not interferring with one another. This would make managing the pipelines more straightforward and robust.

**Comment by alexanderdean** [comment]
Superceded
