### ISSUE TITLE
Scala Kinesis Enrich: convert bad rows to new format

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1207]
See https://github.com/snowplow/iglu-central/issues/74#issuecomment-64601257

Edit: this ticket now refers to converting the errors field from a list of strings to a list of processing message JSONs as in #1936

**Comment by fblundun** [comment]
Rescheduling...

**Comment by alexanderdean** [comment]
Note that when this is done, an upgrading user must switch to a new index in ES for their new-style bad rows, because https://github.com/snowplow/snowplow/issues/824#issuecomment-138937853

/cc @fblundun @jbeemster

**Comment by fblundun** [comment]
We don't fully get this for free with the SCE version bump because of custom-made errors which don't fit the format: https://github.com/snowplow/snowplow/blob/8d04a5ee48c3b5a24827f7de66c1cf5d3d1e97e8/3-enrich/scala-kinesis-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sources/AbstractSource.scala#L75-L111

We need to update the SCE bad row class to permit a "size" field instead of a "line" field, and use that instead.

**Comment by alexanderdean** [comment]
Makes sense...

**Comment by fblundun** [comment]
Bad rows now look like this:

```
{
  "failure_tstamp": "2016-02-16T09:14:23.574Z",
  "errors": [
    {
      "message": "Error deserializing raw event: Cannot read. Remote side has closed. Tried to read 2 bytes, but only got 1 bytes. (This is often indicative of an internal error on the server side. Please check your server logs.)",
      "level": "error"
    }
  ],
  "line": "cGFjayBteSBib3ggd2l0aCBmaXZlIGRvemVuIGxpcXVvciBqdWdzCg=="
}
