### ISSUE TITLE
Kinesis Elasticsearch Sink: convert bad rows to new format

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1208]
See https://github.com/snowplow/iglu-central/issues/74#issuecomment-64601257

**Comment by fblundun** [comment]
Rescheduling...

**Comment by alexanderdean** [comment]
Note that when this is done, an upgrading user must switch to a new index in ES for their new-style bad rows, because https://github.com/snowplow/snowplow/issues/824#issuecomment-138937853

/cc @fblundun @jbeemster

**Comment by fblundun** [comment]
Sample bad row in the new format:

```json
{
  "failure_tstamp": "2016-02-16T09:18:05.260Z",
  "errors": [
    {
      "message": "Event contained only 1 tab-separated fields",
      "level": "error"
    }
  ],
  "line": "---"
}
```
