### ISSUE TITLE
Scala Hadoop Shred: bump Iglu Scala Client to 0.3.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1221]
That way, we don't have to do an expensive resolution process on every single event which is referencing a non-existent schema

**Comment by alexanderdean** [comment]
This is one of the most painful failure states we have currently...

**Comment by fblundun** [comment]
Should this ticket move to iglu-scala-client? It seems like the best place to make the change is in the Resolver class itself.

**Comment by alexanderdean** [comment]
Completely agree!
