### ISSUE TITLE
Scala Hadoop Enrich: added test dependency on SnowplowRawEvent and CollectorPayload

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1248]
The SnowplowRawEvent class is never used, so it doesn't need to be a dependency.

**Comment by fblundun** [comment]
Actually we will now have a test dependency on SnowplowRawEvent and CollectorPayload due to #669. I'm renaming the ticket accordingly...

**Comment by alexanderdean** [comment]
Makes sense, thanks Fred...
