### ISSUE TITLE
Create packages for common OS platforms

### ISSUE THREAD

**Issue by smugryan** [snowplow/snowplow#1262]
It would be great if Snowplow could release packages for common OS's like Ubuntu and others for running the EMR/ETL and storage loader jobs. This would greatly simplify snowplow installation and management. 

Currently with some trial and error we've been able to packagize RVM and the snowplow git repo into a RPM for ease of deployment and backup when running in an environment like AWS where machines are not permanent. We have an auto-scaling group of 1 machine that installs this package via puppet, unfortunately we have to do manual configuration after the fact (will file a separate ticket for this).

**Comment by alexanderdean** [comment]
Closing this - deployment from Bintray is fine, and makes it much easier to run multiple different versions of Snowplow CLI alongside each other.
