### ISSUE TITLE
Update LookML models to create a simpler basic model

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1272]
Now that we've worked with a bunch of clients to integrate Snowplow + Looker, we've learnt that:
1. Simpler models are better. Even if that means they miss on some nice features - analysts prefer working from a simple basis before adding their own business logic to the models.
2. There were some mistakes in the original models that caused derived tables to fail to load successfully

**Comment by paulboocock** [comment]
Closing as we're currently not maintaining our existing LookML models. Once the work is complete on our new and updated [data models](https://github.com/snowplow/data-models), revisiting our LookML support (which will be a complete rebuild) might be on the cards.
