### ISSUE TITLE
SQL Runner: add basic sessions / visits / page views model that can be pivoted on directly from any BI tool

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1273]
These are the same basic tables that are generated by the basic LookML models. 

This is useful for:

1. Looker users who want to move the table generation outside Looker, because either they have other applications that want to access the derived tables, or because they want to update those tables incrementally (rather than rebuilt them from scratch each time)
2. Snowplow users who for whatever reason are not using Looker, so that they can still benefit from working with derived (modelled) tables

**Comment by yalisassoon** [comment]
Note that the models in this will be equivalent to those in https://github.com/snowplow/snowplow/issues/1272

**Comment by alexanderdean** [comment]
@yalisassoon - can you confirm your 6 commits in this branch:

https://github.com/snowplow/snowplow/commits/feature/sql_data_models

relate to this (and only this) ticket?

**Comment by yalisassoon** [comment]
Confirming!

On Tue, Jan 20, 2015 at 2:48 PM, Alexander Dean <notifications@github.com>
wrote:

> @yalisassoon <https://github.com/yalisassoon> - can you confirm your 6
> commits in this branch:
>
> https://github.com/snowplow/snowplow/commits/feature/sql_data_models
>
> relate to this (and only this) ticket?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/1273#issuecomment-70664169>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>
