### ISSUE TITLE
Kinesis Elasticsearch Sink: send Snowplow hearbeat

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1280]
Possible states: starting, running, shutting down, hanging.

Hanging is when the app can't send events to Elasticsearch (e.g. because no nodes are available). It will loop indefinitely until the event is successfully sent.

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by fblundun** [comment]
I think this is covered by these four tickets:

#1702  
#1703  
#1704   
#1706 

The difference is that in those tickets, the initialization, shutdown, heartbeat, and failed write events are all separate, but in this ticket, the heartbeat would be the only event and would contain information about which state the app is in.

I think that separate events is the better option. Using the heartbeat-only approach, the app might shutdown between heartbeats so that no shutdown heartbeat event is ever sent.

**Comment by alexanderdean** [comment]
Completely agree! This ticket was a rename from a Serf/Consul "what is the current state" ticket? The rename was confusing, I should have just closed the ticket...
