### ISSUE TITLE
Scala Kinesis Enrich: add ability to retrieve resolver and enrichments from DynamoDB

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1289]
As per [this doco](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html) you can have the same table name in two different DynamoDB regions, therefore the format should be:

    --enrichments dynamodb:region/table/full-or-partial-key

Example for resolver:

    --resolver dynamodb:us-east-1/snowplow-config/enrich-resolver

Example for enrichments:

    --enrichments dynamodb:us-east-1/snowplow-config/enrich-enrichments-

In the second example, we will build the final enrichments JSON from all values stored in keys which **start with** `enrich-enrichments-`

**Comment by alexanderdean** [comment]
This is business-level data - it would be great to have it sitting in DynamoDB as it makes it super-easy to update without re-deploying servers...

**Comment by alexanderdean** [comment]
This would actually be really useful for the Hadoop flow too, because there are issues in the Hadoop flow with trying to pass too much configuration data as Hadoop command-line arguments.

So we should probably be thinking of this as a Scala Common Enrich thing with hooks into Scala Kinesis Enrich and Scala Hadoop Enrich.

**Comment by alexanderdean** [comment]
Bringing forwads. The Scala DynamoDB library is ready to go now: https://github.com/piotrga/async-dynamo

**Comment by alexanderdean** [comment]
@fblundun - I have updated the desc as per our chat - over to you!

**Comment by fblundun** [comment]
According to [this documentation](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html), there is no way to query every items whose hash key begins with a particular string, so instead I am using a scan to get all items from the table and filter them locally. This involves examining every item in the table so it's best if the table doesn't contain too many extraneous items. What do you think of this approach @alexanderdean ?

**Comment by alexanderdean** [comment]
Hey Fred - when you say all items, do you mean all items or all keys?

**Comment by fblundun** [comment]
I mean all items.

**Comment by alexanderdean** [comment]
Okay - I can't see a way around this without restricting all configurations to total less than 400kb. Let's go ahead with your approach. The table will be called something like snowplow-configuration and thus won't contain a lot of extraneous items.
