### ISSUE TITLE
Develop and test an enableDarkSocial function

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#130]
"Dark social" refers to users who come to a website because they have been given a link to a webpage e.g. in an email or IM client. However, because they enter tend to paste the URL directly into browser address bar, the visit gets attributed as a "Direct visit", even though it is socially driven. Some initial calculations suggest dark social is very important source of traffic: we can, for example, assume that any direct traffic arriving on a very specific landing page is dark social, because users never type detailed URLs from scratch into their address bars. (See article on [The Atlantic](http://www.theatlantic.com/technology/archive/2012/10/dark-social-we-have-the-whole-history-of-the-web-wrong/263523/) for details.)

One idea to aid the tracking of dark social users has been suggested by [Richard Fergie](https://plus.google.com/u/0/109159729997909875172/posts/Jk8n5nhqC6c)\- it involves using HTML5 pushState API to append tracking parameters to the URL bar after the page has loaded. That way, if a user copies and pastes the address bar (e.g. into a chat client or an email), appropriate `utm_source`, `utm_medium` and/or `utm_campaign` attributes can be set. The suggested code is:

``` javascript
function addTrackingParameters() {
    if (history.pushState) { //feature detection
        var currentURL = window.location.href;
        var trackingParams = '?utm_src=ctrl-c+share&utm_medium=direct';
        var newURL = currentURL + trackingParams;
        window.history.pushState(null, document.title, newURL);
    }
    else {
        alert("Your browser does not support the pushState API");
    }
}
```

It would make sense to implement this as an experimental feature (similar to [browser fingerprinting](https://github.com/snowplow/snowplow/blob/master/1-trackers/javascript-tracker/js/src/tracker.js#L913)).

**Comment by alexanderdean** [comment]
Closing this (leaving the JS Tracker issue open)
