### ISSUE TITLE
Dynamic scripting support - Dependencies placeholder

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1314]
Tracks dependencies for this milestone:
- https://github.com/snowplow/iglu-central/issues/111
- https://github.com/snowplow/snowplow/issues/784
- https://github.com/snowplow/snowplow/issues/785
- https://github.com/snowplow/snowplow/issues/786
- https://github.com/snowplow/snowplow/issues/787

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/172
