### ISSUE TITLE
Mixpanel ingest - Dependencies placeholder

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1315]
This is dependent on these tickets in other milestones/other projects:
- https://github.com/snowplow/iglu-utils/issues/4
- https://github.com/snowplow/schema-guru/issues/28
- https://github.com/snowplow/iglu-central/issues/113

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/173
