### ISSUE TITLE
Snowplow Common Enrich: add JsonLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1317]
This is a general purpose Loader for ingesting JSONs stored in flat files like so:

```
{json}/newline
{json}/newline
{json}/newline
```

This should allow us to ingest JSONs exported from Mixpanel, Segment, Swrve etc...

**Comment by alexanderdean** [comment]
Ping @alexanderdean before starting on this one as I have some code to help with this...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/174
