### ISSUE TITLE
Snowplow Common Enrich: add MixpanelAdapter

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1318]
This is an adapter which converts Mixpanel-exported JSONs into Snowplow unstructured events. It should support:
1. Custom Mixpanel events defined by the Mixpanel user - e.g. "New user sign up"
2. Mixpanel people tracking events - see e.g. https://github.com/mixpanel/mixpanel-ruby/blob/master/lib/mixpanel-ruby/people.rb

Note that this will be our first user-configurable JSON - we will have a mapping of Mixpanel event names to Iglu-compatible schemas (e.g. "Add to Basket" -> com.acme/add_to_basket/jsonschema/1-0-0")

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/175
