### ISSUE TITLE
Consider changing storageloader user in docs to one with more permissions

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1328]
If so, change these pages:
- https://github.com/snowplow/snowplow/wiki/setting-up-redshift#61-creating-a-user-for-the-storageloader
- https://github.com/snowplow/snowplow/wiki/2-Using-the-StorageLoader#3-running

**Comment by yalisassoon** [comment]
Update the permissions so you can perform vacuums? Or do you have something
else in mind?

On Mon, Jan 19, 2015 at 6:24 PM, Alexander Dean <notifications@github.com>
wrote:

> Assigned #1328 <https://github.com/snowplow/snowplow/issues/1328> to
> @yalisassoon <https://github.com/yalisassoon>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/1328#event-221150315>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by alexanderdean** [comment]
Yep, specifically that... Related to recent snowplow-user thread: https://groups.google.com/forum/#!topic/snowplow-user/4Di915aRLI4

**Comment by BenFradet** [comment]
closing
