### ISSUE TITLE
Clojure Collector: add CORS-style support for ActionScript3 Tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1330]
See: https://github.com/snowplow/snowplow-actionscript3-tracker/issues/19#issuecomment-70657444

**Comment by alexanderdean** [comment]
Hey @natilivni - how is this: http://astracker.snplow.com/crossdomain.xml

Let me know if that's correct or needs tweaking...

**Comment by natilivni** [comment]
Hi @alexanderdean, the filename and location are correct, but it needs a valid policy file syntax.  (reference is here: http://www.adobe.com/devnet/articles/crossdomain_policy_file_spec.html )

The most open crossdomain file looks like this:

```xml
<cross-domain-policy>
  <allow-access-from domain="*" secure="false" />
</cross-domain-policy>
```

**Comment by alexanderdean** [comment]
No problem @natilivni - how about now? http://astracker.snplow.com/crossdomain.xml

**Comment by natilivni** [comment]
Perfect!  Thanks!
