### ISSUE TITLE
Adwords enrichment

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1339]
Automatically fetch data from on Adwords clicks based on the gclid.

The value of the glid can be used to pull data from the click performance report: https://developers.google.com/adwords/api/docs/appendix/reports#click

Note we would need to pull the data from other Adwords to reports to pull the all important cost of click information.

**Comment by yalisassoon** [comment]
Need to specify the string of API calls necessary, and how long after teh click ID we need to leave it before the data can be fetched from the Adwords API

**Comment by yalisassoon** [comment]
Depends on https://github.com/snowplow/snowplow/issues/1073

**Comment by Kimblebrook** [comment]
Hi Yali

We've done some work on this, if you'd like to discuss detail. Very cool
initiative, by the way. Our approach was more about batch loading into
RedShift, but we have figured out a fair amount about what the various
reports mean and how the gclids work.

Regards
Stewart

**Comment by lubasch** [comment]
We can add that it's really worth to wait up to 16-24 hours for full data being available in adwords via API. Otherwise your numbers will never match for the later part of the day.

Cheers,
Christian

**Comment by Kimblebrook** [comment]
Christian, out of interest, are you using the Snowplow pipeline to load the
data or do you load it directly to your analytics database?

**Comment by lubasch** [comment]
We decided to not touch the SP pipeline with this case, but import data straight into the db (Redshift). Kept everything a bit more separated at that times.

**Comment by Kimblebrook** [comment]
As it happens, that's how we're doing it too.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/176
