### ISSUE TITLE
EmrEtlRunner: add missing require time_diff to emr_job.rb

### ISSUE THREAD

**Issue by mlively** [snowplow/snowplow#1346]
[emr-etl-runner]# bundle exec bin/snowplow-emr-etl-runner --config config/config.yml --enrichments config/enrichments --debug --skip staging,s3distcp,enrich
D, [2015-01-21T20:18:51.540035 #28195] DEBUG -- : Initializing EMR jobflow
D, [2015-01-21T20:18:52.689088 #28195] DEBUG -- : EMR jobflow j-3R1ASRYYRNSI0 started, waiting for jobflow to complete...
F, [2015-01-21T20:24:53.374990 #28195] FATAL -- : 

NoMethodError (undefined method `diff' for Time:Class):
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:399:in `get_elapsed_time'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:233:in `call'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:233:in `call_with'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/decorators.rb:157:in `get_elapsed_time'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:373:in `block in get_failure_details'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:367:in `each'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:367:in `each_with_index'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:367:in `each'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:367:in `map'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:367:in `get_failure_details'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call_with'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/decorators.rb:157:in `get_failure_details'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:282:in `run'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call_with'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/decorators.rb:157:in `run'
    /home/centos/snowplow/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:60:in `run'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/contracts.rb:230:in `call_with'
    /home/centos/snowplow/3-enrich/emr-etl-runner/vendor/bundle/ruby/1.9.1/gems/contracts-0.4/lib/decorators.rb:157:in `run'
    bin/snowplow-emr-etl-runner:39:in `<main>'

I am by no means a ruby developer but it seems like emr_job.rb is just missing a require 'time_diff'

**Comment by alexanderdean** [comment]
Thanks for raising @mlively - we've seen intermittent problems both with this and with the attempted fix. We'll schedule this back into the next release.

**Comment by alexanderdean** [comment]
Superceded by #1310, closing.
