### ISSUE TITLE
Redshift: change JSON field encodings to lzo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1350]
Suggested by @epantera

Documentation: http://docs.aws.amazon.com/redshift/latest/dg/lzo-encoding.html

Don't implement yet - still being discussed in this thread: https://groups.google.com/forum/#!topic/snowplow-user/ztVDNJZTZ_E

**Comment by fblundun** [comment]
Should we also change the encoding for [nested JSON fields](https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/com.snowplowanalytics.snowplow/submit_form_1.sql#L32-L33) in tables like submit_form?

**Comment by alexanderdean** [comment]
No let's leave it in existing ones, but make a mental note to change going forwards...
