### ISSUE TITLE
Scala Collector always creates streams on us-east-1

### ISSUE THREAD

**Issue by sr-ix** [snowplow/snowplow#1356]
With the below conf, the scala snowplow-stream-collector-0.1.0 always tries to use/create the stream on us-east-1, despite selecting other, valid regions for the value `collector.sink.kinesis.stream.region`.

```aconf
collector {
  interface = "0.0.0.0"
  port = 8080

  production = false

  p3p {
    policyref = "/w3c/p3p.xml"
    CP = "NOI DSP COR NID PSA OUR IND COM NAV STA"
  }

  cookie {
    expiration = 365 days
  }

  sink {
    enabled = "kinesis"

    kinesis {
      aws {
        access-key: "cpf"
        secret-key: "cpf"
      }

      stream {
        region: "us-west-2"
        name: "example_kinesis_stream"
        size: 1
      }
    }
  }
}

akka {
  loglevel = OFF # 'OFF' for no logging, 'DEBUG' for all logging.
  loggers = []
}

spray.can.server {
  remote-address-header = on

  uri-parsing-mode = relaxed
  raw-request-uri-header = on

  parsing {
    max-uri-length = 32768
  }
}
```

**Comment by alexanderdean** [comment]
This was fixed in snowplow-stream-collector-0.2.0: https://github.com/snowplow/snowplow/blob/master/CHANGELOG#L78

**Comment by sr-ix** [comment]
Ahh, did not see that there was a new version of the collector.

The link to the CDN download on the Hosted Assets page still points to version 0.1.0

**Comment by alexanderdean** [comment]
Oh sorry, that's fixed now! From the next release onwards all the Kinesis apps will be bundled in a single zipfile so should be a bit easier to get started. Preview is here:

https://bintray.com/snowplow/snowplow-generic/snowplow/r60-bee-hummingbird/view?sort=&order=#files

**Comment by sr-ix** [comment]
:tada: I like it.
