### ISSUE TITLE
StorageLoader: move ANALYZE statements after VACUUM statements

### ISSUE THREAD

**Issue by smugryan** [snowplow/snowplow#1361]
Per Redshift and PostgreSQL docs, Snowplow should run `ANALYZE` after a `VACUUM`. Currently Snowplow runs an `ANALYZE` after a `COPY` and then runs `VACUUM`.

**Comment by alexanderdean** [comment]
Thanks @smugryan !

**Comment by alexanderdean** [comment]
Ah I remember why this bug was introduced: it's because a `VACUUM` cannot be done in a transaction, and so the `ANALYZE` was incorrectly done first. Needs fixing.
