### ISSUE TITLE
Redshift: add primary key constraint to event_id for query optimization purposes

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1364]
http://docs.aws.amazon.com/redshift/latest/dg/t_Defining_constraints.html

**Comment by fblundun** [comment]
Isn't this already done here https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/atomic-def.sql#L156?

**Comment by alexanderdean** [comment]
Yes, should have scrolled down! Thanks, closing
