### ISSUE TITLE
Kinesis BigQuery: use insertId to prevent duplicate row upload

### ISSUE THREAD

**Issue by MrCurtis** [snowplow/snowplow#1376]
Bigquery has an optional insertId field associated with each row - by using the snowplow event id as the insertId it will be possible to ensure that row aren't duplicated in each table.

**Comment by alexanderdean** [comment]
Better still - if we make the insertId the event ID *and* event fingerprint, we can stop all duplicates. /cc @bogaert

**Comment by alexanderdean** [comment]
This is an implementation detail (does not need to be a separate ticket/commit when completed).

**Comment by bogaert** [comment]
That is very interesting! Looking forward to this.

**Comment by BenFradet** [comment]
no cross cloud, see https://github.com/snowplow-incubator/snowplow-bigquery-loader
