### ISSUE TITLE
Common: update kinesis push to remove sub-folders from zipfile

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1378]
Currently unzipping the kinesis zip file gives:

    dist/snowplow_kinesis_r60-bee-hummingbird/snowplow-*-*-x.x.x

The two layers of folder structure are unnecessary - the zip file should contain the apps only.

**Comment by fblundun** [comment]
My addition of the `zip -j` option above completely flattens the structure so that unzipping the zipfile simply adds all the kinesis apps to the current working directory. Is this the desired behaviour?

**Comment by alexanderdean** [comment]
That's brilliant!
