### ISSUE TITLE
Scala Stream Collector: add validation that Kinesis stream has correct schema tag

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1380]
Idea is:
- We tag each Kinesis stream with a tag schema=iglu:schema_of_events_in_stream
- When we start up the Scala Stream Collector, we validate that the Kinesis stream's tag maps onto a version of the schema that our Scala Stream Collector speaks

**Comment by alexanderdean** [comment]
This is basically a way of giving Kinesis streams "optional type annotations"

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/179
