### ISSUE TITLE
EmrEtlRunner: change Clojure Collector log timestamp format to match CloudFront logs

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1398]
Currently we can't use the filename to know what time period the log file covers. As a result, if an output file from a particular run is accidentally deleted, the only way to ensure that no data is lost is to rerun processing on the entire data set, which for users with large volumes of data can be time consuming

**Comment by alexanderdean** [comment]
The syntax is here:

https://github.com/softwarepublico/sgf/blob/a0fb3ab0f09e3611b2cc14f616d5d3318304c221/WebContent/META-INF/context.xml#L8

**Comment by yalisassoon** [comment]
Can we also update the way that the files are renamed as part of EmrEtlRunner so that the instance ID is added to the filename? Currently the instance ID is prepended to the filename - this means that if you list the files in any s3 editor or the cli, they don't list in chronological order

**Comment by alexanderdean** [comment]
Sure thing, https://github.com/snowplow/snowplow/issues/1404

**Comment by alexanderdean** [comment]
The suggested `server.xml` addition of `fileDateFormat="yyyy-MM-dd-HH"` won't work - this is because that configuration option covers Tomcat's built-in log file rotation option, but in fact on Beanstalk we are using Amazon's own rotation scripts. So we would have to change Amazon's own rotation scripts to accomplish this

**Comment by alexanderdean** [comment]
From further discussions with @jbeemster - the number already in the access log filename is the rotation time as a Unix secs since epoch. All we need to do is convert this timestamp to yyyy-MM-dd-HH and we should be good to go.
