### ISSUE TITLE
Scala Common Enrich: add support for ti_nm for transaction item name as well as ti_na

### ISSUE THREAD

**Issue by ssingh195** [snowplow/snowplow#1401]
From the Javascript Tracker , the GET request for Transaction Item name is going as parameter: ti_nm .
BUt while enriching it searches for Parameter ti_na as per EnrichmentManager.scala 
file location:snowplow\3-enrich\scala-common-enrich\src\main\scala\com.snowplowanalytics.snowplow.enrich\common\enrichments

So the transaction name is not getting populated in Enriched logs.

**Comment by alexanderdean** [comment]
Thanks, moved to: https://github.com/snowplow/snowplow-javascript-tracker/issues/321

**Comment by alexanderdean** [comment]
Reopening and scheduling.
