### ISSUE TITLE
Link Updates in Wiki - Scala Kinesis setup guide

### ISSUE THREAD

**Issue by r-com** [snowplow/snowplow#1402]
Not sure if this is the right place to leave this or not, if not please point me to the right place :)

In Scala Kinesis Connector and Scala Kinesis Enrich setup guides the links to the config files are outdated and need to be changed

NOW: https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/resources/application.conf.example
SHOULD BE: https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/resources/config.hocon.sample

NOW: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-kinesis-enrich/src/main/resources/default.conf
SHOULD BE: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-kinesis-enrich/src/main/resources/config.hocon.sample

**Comment by alexanderdean** [comment]
Thanks @r-com , @fblundun can you fix these? Plus anything else in the Kinesis doco which has changed with the r60 release...

**Comment by fblundun** [comment]
I've updated the links and mentioned the new "thrift" collector_format in the wiki's example config yaml. Thanks @r-com !
