### ISSUE TITLE
Scala Kinesis Enrich: add support for PutRecords API

### ISSUE THREAD

**Issue by kazjote** [snowplow/snowplow#1418]
During load testing we found out that Enrich step is a bottleneck in the Kinesis Snowplow workflow.

We ran the test on m3.medium instance. The problem is that Enrich reads data much faster ( > 10 times) than it can write to the Enriched Kinesis stream.

What is worst, it checkpoints data as soon as it is read. This makes huge amount of data to be not processed even after Enrich restart.

Because read data can't be stored fast enough, process memory goes up very quickly. Process has to be restarted. Unprocessed data is lost as Enrich resumes with much later sequence number than the one from last stored event.

 1. Checkpointing should happen only when the data is processed and stored
 1. Events should be stored in batches (this would give incredible speedup) - it is possible with AmazonKinesisClient library: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kinesis/AmazonKinesisClient.html#putRecords(com.amazonaws.services.kinesis.model.PutRecordsRequest)

**Comment by alexanderdean** [comment]
Sounds essential - scheduling into Kinesis #5...

**Comment by alexanderdean** [comment]
Blocked by https://github.com/cloudify/scalazon/pull/14
