### ISSUE TITLE
Scala Common Enrich: make IpLookupsEnrichment failure message more informative

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1426]
Here: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/IpLookupsEnrichment.scala#L204

The original exception should be in the failure message.

**Comment by alexanderdean** [comment]
Good thinking

**Comment by alexanderdean** [comment]
Please do this into this branch: https://github.com/snowplow/snowplow/tree/feature/r66-common-enrich
