### ISSUE TITLE
Update shredded bad rows so that include details on *which* JSON failed the test

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1433]
Currently the bad rows reports the field that caused the issue, and the error message generated, but it doesn't identify which JSON / context / unstructured event the error occurred processing, which makes debugging a lot more time consuming. (Because you've got to parse out all the different JSONs from the raw line and check each against each error.)

**Comment by alexanderdean** [comment]
How should a failing JSON be identified?

**Comment by yalisassoon** [comment]
Ideally via the schema field

**Comment by alexanderdean** [comment]
Okay makes sense...

**Comment by alexanderdean** [comment]
Superceded by new bad rows
