### ISSUE TITLE
EmrEtlRunner: move `include Contracts` into classes and modules

### ISSUE THREAD

**Issue by iaingray** [snowplow/snowplow#1438]
It looks like using `include Contracts` in the global namespace is being deprecated due to issues it has caused for some users.

https://github.com/egonSchiele/contracts.ruby/issues/81

Looks like you can just move it within 'Storageloader' or 'Snowplow' though.

(apologies, opened issue under another account by mistake, so have closed)

**Comment by alexanderdean** [comment]
Thanks for raising!

**Comment by waterlink** [comment]
Actually the best way to utilize `contracts` is to include them in classes and modules that actually need them, explicitly. That way you don't need to change any code, except adding these `include Contracts` to classes/modules, that have contracts inside them; and removing this inclusion from global scope.

I imagine that, if you would like to just namespace `Contracts`, then you will need to namespace any builtin contracts references too.

**Comment by alexanderdean** [comment]
Thanks @waterlink!
