### ISSUE TITLE
Placeholder for Ruby Tracker doco updates

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1459]
- This is confusing language: ":buffer_size is the number of events which will be queued before they are all sent, a process called "flushing". When using GET, it defaults to 0 because each event has its own request. When using POST, it defaults to 10, and the buffered events are all sent together in a single request."
- Is it `Snowplow::` or `SnowplowTracker::` ?

**Comment by BenFradet** [comment]
moved to docs, closing
