### ISSUE TITLE
(For reference) Scala Kinesis Enrich: Consider changing the enriched event format

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1470]
The output of Scala Kinesis Enrich is super-brittle because it's a TSV. Every time we upgrade the TSV, we have to also upgrade any downstream apps.

Why not make it so that Scala Kinesis Enrich emits a self-describing JSON which versions the enriched event? That way, we could upgrade the downstream apps so that they support both the old and the new versions of the enriched event.

This would be super-flexible and would allow us to innovate on the format of the enriched event much faster.

It should also be easier for ops, because a single stream of enriched events can contain multiple different versions of the enriched event schema...

**Comment by alexanderdean** [comment]
This would also be nicer for people building KCL, Spark Streaming, Storm et al apps. The first thing those people have to do is convert the TSV into something sensible like a JSON anyway...

**Comment by yalisassoon** [comment]
Love it - great idea

On Wed, Mar 4, 2015 at 9:20 PM, Alexander Dean <notifications@github.com>
wrote:

> /cc @yalisassoon <https://github.com/yalisassoon>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/1470#issuecomment-77251355>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by kazjote** [comment]
:+1: it would make my life much easier... Counting columns in TSV files is quite challenging ;)

**Comment by alexanderdean** [comment]
See also: #1630, where the conversation is going into some detail...

**Comment by alexanderdean** [comment]
Duplicate of other tickets in this milestone, but leaving open for reference...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/182
