### ISSUE TITLE
Scala Stream Collector: add support for PutRecords API

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1511]

**Comment by fblundun** [comment]
My current approach is to have a configurable TimeThreshold, RecordThreshold, and ByteThreshold. Every TimeThreshold milliseconds, all stored events are sent in a single PutRecords API call. Additionally, all records are sent whenever the total number of stored records reaches RecordThreshold or the total stored bytes reaches ByteThreshold.

**Comment by alexanderdean** [comment]
where RecordThreshold and ByteThreshold reflect current Kinesis PutRecords limits?

**Comment by fblundun** [comment]
That's right - they will be configurable in case the limits change in the future.

**Comment by alexanderdean** [comment]
Sounds great!

**Comment by fblundun** [comment]
I've changed how the timer works - it resets every time the buffer is flushed for any reason. Otherwise the collector will occasionally send a large PutRecords request when RecordThreshold is reached, and immediately afterwards send a small one because TimeThreshold has been reached.

**Comment by alexanderdean** [comment]
Yep I was going to ask about that! Sounds good!

**Comment by fblundun** [comment]
Closing as duplicate of #1227
