### ISSUE TITLE
Kinesis Elasticsearch Sink: remove elasticsearch cluster name if not used anywhere

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1516]

**Comment by fblundun** [comment]
Closing since it is actually used here: https://github.com/snowplow/snowplow/blob/master/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/SnowplowElasticsearchEmitter.scala#L130
