### ISSUE TITLE
Scala Kinesis Enrich: remove outdated comment about ClasspathPropertiesFileCredentialsProvider from sample config file

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1519]

**Comment by gabrielcrowdtilt** [comment]
I was failing on this for a couple hours while setting up for first time today:

 [main] INFO com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Initialization attempt 1
[main] INFO com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Initializing LeaseCoordinator
[main] ERROR com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Caught exception when initializing LeaseCoordinator

Then I switched from iam to env and it started working right away. The same iam worked for scala-stream-collector-0.4.0 though.

**Comment by alexanderdean** [comment]
See #1518 for rationale.

**Comment by fblundun** [comment]
This is a mistake in the comment in the sample config file - the app doesn't currently support cpf.
