### ISSUE TITLE
Decide whether it should be possible, at data capture time, to set a scope for custom dimensions or metrics

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#152]
SiteCatalyst enables users to persist custom dimensions (i.e. eVars) for periods of time. this is used with e.g. campaign tracking so that events that occur for all users who've clicked on an ad, for 30 days after the ad click, can easily be aggregated.

I don't *think* we need to enable such a feature, someone performing analysis on SnowPlow data can pretty easily develop a query to return all events 30 days after a specific event (e.g. an ad click). Because we expose the individual event-level data, we can enable a decision to be made about the scope of dimensions set with a specific events at analysis time rather than data-capture time. But I'm open to suggestion. 

/cc @shermozle  

**Note**: I should have made the title clearer: this relates to custom dimensions and metrics that are tied to specific events (e.g. an add-to-basket, video view, page load) rather than custom dimensions that are set independent of a specific event on the user journey). These are discussed separately on: https://github.com/snowplow/snowplow/issues/153

**Comment by alexanderdean** [comment]
Closing as out of date with current Snowplow approach...
