### ISSUE TITLE
Looker: simplify LookML model and make it consistent with Redshift data models

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1522]
There may be opportunities to simplify and clarify the LookML [here](https://github.com/snowplow/snowplow/tree/feature/update_lookml).

This LookML has been tested with a lot of clients - so I'd only update it if you think there's scope to improve it significantly. (Particularly around the efficiency of the SQL tables.)

I recommend:

1. Creating a new 'looker' user for snplow1 in Redshift with read permissions on the atomic schemas and ownership of a looker_scratch schema
2. Create a new connection in our Looker account
3. Testing and developing the updated model there

**Comment by yalisassoon** [comment]
We want to end up with two versions of the LookML

**1. For people who are not using the SQL data modeling**
For these users Looker will still be responsible for generating the derived tables. We need to take the current models and update the SQL in them so that they are consistent with the SQL in the latest versions of the data models - note especially the much cleaner approach to frame-first and frame-last in the sessions processing.

**2. For people who are running SQL Runner**
For these users we don't need Looker to manage the process for generating the derived tables. We simply need to update the first version so that it includes the same views (events / sessions / visitors) but that they are read directly from Redshift. This should mean updating the first part of the LookML views definitions for those views and removing any views that create intermediary tables.

**Comment by alexanderdean** [comment]
Reopening till merge to master

**Comment by yalisassoon** [comment]
Can this be closed now?

On Thu, Apr 16, 2015 at 1:22 PM, Alexander Dean <notifications@github.com>
wrote:

> Reopening till merge to master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/1522#issuecomment-93720637>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>
