### ISSUE TITLE
Common: add top-level data modeling folder

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1523]
Add a top-level folder for data models (maybe just rename the analytics folder)

**Comment by alexanderdean** [comment]
@yalisassoon has this been done in a branch?

**Comment by yalisassoon** [comment]
No it hasn't...

**Comment by alexanderdean** [comment]
Okay let's do this one last...

**Comment by alexanderdean** [comment]
Worth running a check across the repo for "5-storage" to prevent broken links...
