### ISSUE TITLE
Update setup guide with new structure

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1525]
https://github.com/snowplow/snowplow/wiki/Setting-up-Snowplow

Data modeling vs analytics

In the data modeling section should have links or explanations to setting up SQL-Runner.
In the analytics section should talk through integrating the differen BI / analytics tools. These can use:
1. New VMs for Python / R 
2. Data models to access directly

**Comment by BenFradet** [comment]
moved to docs, closing
