### ISSUE TITLE
Explore events with 192.168.* IP address

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1528]
In a sufficiently large dataset using Clojure Collector 0.8.0+ (which has `X-Forwarded-For` parsing), 1 in 1000 events (0.11%) will have a private IP address.

One explanation for these internal IP addresses would be some form of client-side proxy introducing an X-Forwarded-For header into the outbound request. The `X-Forwarded-For` parsing in the Clojure Collector, and by extension probably the equivalent functionality in Scala Common Enrich (#1372), would then report the internal as the final IP address.

To investigate further depends on #1527.

**Comment by yalisassoon** [comment]
Just done another analysis on a decent sized data set and found that 0.11% of events were recorded against IP's beginning with 192.168

```sql
SELECT
CASE WHEN user_ipaddress LIKE '192.168.%' THEN 'IP starts 192.168' ELSE 'Normal IP' END,
COUNT(*)
FROM atomic.events
GROUP BY 1
ORDER BY 1
```

Returns:

```
IP starts 192.168	5745723
Normal IP	5093314942
```

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/185
