### ISSUE TITLE
Specify approach to custom dimensions that are not tied to specific events

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#153]
We need to specify a way to enable users to set custom dimensions that have scope that extends beyond events e.g. for users. (Is the user a member? What type of member?) Or sessions. Or potentially other scopes. 

**Questions we need to answer**

1. What scopes should we enable dimensions to be set for? Users? Sessions? Anything else?
2. Do we want to store a flag that indicates whether e.g. the user dimension should be projected back in time, before it was set? (For example - if we suddenly discover a user is 'female', it's likely she was a female a month ago before she revealed this data point to us.) There are other user dimensions that we might not want to persist back (e.g. this person is a "member".) But maybe we shouldn't be setting that as a user-level variable - we should be capturing a "membership sign up event" and then a "renewal" event or "cancelleation" event. (I.e. *only* using custom dimensions to capture dimensions that endure independent of the customer journey.)

/cc @shermozle

**Comment by alexanderdean** [comment]
Closing as out of date with current Snowplow approach...
