### ISSUE TITLE
Explore timeuuids for Snowplow

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1531]
More a placeholder than anything, but UUIDs which can have a timestamp backed out of them are pretty neat:

http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/uuid_type_r.html

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/186

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/224
