### ISSUE TITLE
Finalise the specification for transaction events

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#154]
We currently follow the approach taken by GA.

This has many limitations:
- Does not capture _add-to-basket_ or _remove-from-basket_ events
- Does not capture discounts  at an item or basket level (e.g. voucher codes)
- Does not distinguish paying for physical goods / digital goods / prepay / subscription payment / renewals / automatic payments
- Does not capture _refund_ events

It is possible to capture the "missing" data currently using generic event tracking (to capture _add-to-basket_ events, or _refund_ events, for example. It will be possible to e.g. distinguish payment for physical goods / digital goods / prepay / subscription / renewals etc. using custom dimensions, when we implement these for transaction events. But there are strong arguments for including these as first class citizens, given they are likely very common requirements for people implementing SnowPlow. 

/cc @shermozle

**Comment by alexanderdean** [comment]
Closing, this would be handled in Iglu Central / tracker repos these days...

**Comment by SyedWasiHaider** [comment]
Hi @alexanderdean. Would passing a negative value count as a "refund" event for transaction/item events or is refund just not supported? (This is in the context of using something like the .NET library for instance).

**Comment by alexanderdean** [comment]
Hi @SyedWasiHaider - please discuss on our forums:

https://discourse.snowplowanalytics.com/
