### ISSUE TITLE
Scala Common Enrich: add additional click ID definitions to campaign attribution enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1547]
The ones we know about are:

``` scala
"gclid" -> "Google",
"msclkid" -> "Microsoft",
"dclid" -> "DoubleClick"
```

If you know of any others, please add them to this ticket and we will add them into a future release.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/188
