### ISSUE TITLE
elasticsearch-sink-0.1.0 uses string type for geo_location instead of geo_point

### ISSUE THREAD

**Issue by drewgillson** [snowplow/snowplow#1548]
Is this a known issue? The docs indicate that the field type should be a geo_point, but it's a string, therefore Kibana can't plot geolocation on a map.

**Comment by alexanderdean** [comment]
@fblundun - can you take a look please?

**Comment by alexanderdean** [comment]
Also weirdly I can't see geolocation in here: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/elasticsearch_enriched_event/jsonschema/1-0-0

**Comment by fblundun** [comment]
Hello @drewgillson ,

Did you explicitly use Elasticsearch's geo_point mapper type? If you don't then Elasticsearch will interpret the geo_location field as a plain string. See [here](https://github.com/snowplow/snowplow/wiki/Kinesis-Elasticsearch-Sink-Setup#defining-the-mapping) for the recommended way to create the mapping for the Snowplow enriched event type.

@alexanderdean - that's an omission from the schema, I'll update it now.

**Comment by drewgillson** [comment]
Perfect, thanks @fblundun. I'm not sure how I missed that step (to set up the mapping) but I guess I did. Works like a charm.
