### ISSUE TITLE
Specify a first class event type for video plays 

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#155]
Promote video-related events to capture:

* Plays
* Pauses
* Fast forward / skip forward
* Rewind / skip backward

We need a set of dimensions to capture metadata related to the video (Video ID etc...)

We need a set of metrics related to the video view e.g. start time, finish time, number of ads shown, CPM etc.

We need to decide which would be supported by standard named dimensions / metrics, and which would only be supported by individual clients using custom dimensions / metrics.

/cc @shermozle

**Comment by alexanderdean** [comment]
Migrated to JS Tracker, closing
