### ISSUE TITLE
Scala Common Enrich: new derived_tstamp enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1550]
The calculation for `derived_tstamp` is:

    if dvce_sent_tstamp is not null then
      dvce_delta = dvce_sent_tstamp - dvce_created_tstamp
      if dvce_delta > 0      
        collector_tstamp - dvce_delta
      else
        collector_tstamp
      end
    else
      collector_tstamp
    end if

So derived_tstamp will get more accurate as more trackers add support for dvce_sent_tstamp.

Edge cases:

* If user changes their timezone between created and sent (because dvce_sent_tstamp is local tz)
* If user updates their clock between created and sent

/cc @yalisassoon

**Comment by alexanderdean** [comment]
TBC if there are any implications when the user is setting the dvce_created_tstamp themselves - I don't think there are...

**Comment by alexanderdean** [comment]
Consider adding derived_tstamp local as well...

**Comment by fblundun** [comment]
Will dvce_sent_tstamp and dvce_created_tstamp both be fields in EnrichedEvent rather than derived contexts?

**Comment by alexanderdean** [comment]
Hey @fblundun ! I think they are already in atomic.events?

**Comment by fblundun** [comment]
They are - I was forgetting that dvce_created_tstamp is actuallly just called dvce_tstamp.
