### ISSUE TITLE
Scala Hadoop Enrich: add support for S3 client-side encryption

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1555]
https://aws.amazon.com/blogs/aws/amazon-emr-supports-s3-client-side-encryption/

Depends on the EMR 3.6.0 AMI, which uses Hadoop 2.4.0, so we are blocked until Scalding upgrades to Hadoop 2.x.

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/ami-versions-supported.html

**Comment by BenFradet** [comment]
done in https://github.com/snowplow/snowplow/milestone/145
