### ISSUE TITLE
Add derived_tstamp to data model

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1556]
Hey @fblundun - can you split this into the standard Redshift, PG and Scala Common Enrich POJO tickets and implement through?

No need to implement the actual logic in this release, we will save that for a subsequent release.

**Comment by fblundun** [comment]
Closing since this has been split into other tickets: #1557 #1558 #1559

**Comment by alexanderdean** [comment]
Thanks Fred!
