### ISSUE TITLE
Issue in Storage Loader "Missing New Line"

### ISSUE THREAD

**Issue by anishdevasia** [snowplow/snowplow#1561]
I am using "snowplow_kinesis_r60_bee_hummingbird" release to setup entire data pipeline. 
When storage loader executes following error is consistently popping up

 Missing newline: Unexpected charact
er 0x4f found at location 3

Missing newline: Unexpected charact
er 0x0 found at location 0

**Comment by alexanderdean** [comment]
Hi @anishdevasia - I'm not sure I follow. snowplow_kinesis_r60_bee_hummingbird sets up the Kinesis pipeline, which doesn't use StorageLoader.

Can you add a comment providing more detail on your exact setup?

**Comment by anishdevasia** [comment]
Thanks for quick reply.

I am using following components to setup kinesis pipeline
1. Scala Collector(snowplow-stream-collector-0.3.0)
2. Scala Enrichment( snowplow-kinesis-enrich-0.3.0)
3. S3 Sink (snowplow-lzo-s3-sink-0.1.0)

All these steps works perfectly and I am getting "lzo" files in S3.

At 4th setup where I try to load "lzo" files from S3 to Redshift using Storage loader I am getting the above reported error.

**Comment by anishdevasia** [comment]
I think, I should have posted this issue in the forum first.

**Comment by alexanderdean** [comment]
Hi @anishdevasia - ah, I understand, that makes a lot more sense.

Would you mind posting it into the forum? I'll then answer it there.
