### ISSUE TITLE
StorageLoader: convert stl_load_errors into bad rows / Snowplow events

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1598]
Basic idea is: after a load, we extract the errors from stl_load_errors for this load.

Let count be the number of error rows returned.
Let maxerror be the number of errors required to trigger a load failure in Redshift.

If count == 0, then do nothing.

If count >= maxerror, then these load errors are explanations of why the load failed - so these errors should be reported in a Snowplow event.

If count <= maxerror, then these load errors are _actual rows missing from a successful load_ - so these error rows should be stored in a new bad bucket.

/cc @yalisassoon 

Need to check SQL perms on stl_load_errors.

**Comment by BenFradet** [comment]
migrated to snowplow/snowplow-rdb-loader#121, closing
