### ISSUE TITLE
mkt_clickid fields are too short

### ISSUE THREAD

**Issue by danisola** [snowplow/snowplow#1602]
Google's `gclid` parameter can range from 25 to 100 chars, so it cannot fit in the defined `mkt_clickid` columns in [Redshift](https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/migrate_0.4.0_to_0.5.0.sql#L168) and [Postgres](https://github.com/snowplow/snowplow/blob/master/4-storage/postgres-storage/sql/migrate_0.3.0_to_0.4.0.sql#L164), which are both `varchar(64)`.

Source: http://googleadsdeveloper.blogspot.co.uk/2014/02/changes-to-gclid-field-length-in.html

**Comment by alexanderdean** [comment]
@bogaert - heads' up: we will be changing this field in r64.

**Comment by alexanderdean** [comment]
Thanks for letting us know @danisola ! @fblundun let's set the field to 128 characters.

**Comment by fblundun** [comment]
I can't find anything on msclkid and dclid sizes - should we change them too?

**Comment by fblundun** [comment]
Never mind - they end up in the same field anyway

**Comment by fblundun** [comment]
I've split this into #1603, #1604, #1605, and #1606

**Comment by alexanderdean** [comment]
Thanks Fred!
