### ISSUE TITLE
Scala Kinesis Enrich: send a warning via Snowplow if no enrichment JSONs are retrieved from DynamoDB

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1621]

**Comment by alexanderdean** [comment]
Good idea

**Comment by fblundun** [comment]
The point of this one is that if you are getting enrichments from DynamoDB and make a typo in the prefix you are looking for (e.g. if all your enrichments start with "enrichment_" but you configure the enricher to get all enrichments which start with "enrichment-") then no enrichments will be found but the app will still run. In this situation there should be some sort of indication that a mistake may have been made.

**Comment by alexanderdean** [comment]
Yes good idea Fred - this should be a Snowplow event being fired...
