### ISSUE TITLE
Problem with similar paths in snowplow-etl-runner

### ISSUE THREAD

**Issue by igc1** [snowplow/snowplow#1623]
I think I just found a problem when you have similar paths in the same bucket with emr-etl runner.

If you have:

s3://my-processing-bucket/keyname/  as a Snowplow processing bucket
and
s3://my-processing-bucket/keyname-someotherstuff/  which has non-sp files in it.

EMREtlRunner will fail after EMR step with a "files don't match pattern" error.  I suspect this may be caused by path globbing in Sluice, so I'm guessing it will happen in other parts of the ETL process.

Cheers,
Iain Gray

**Comment by alexanderdean** [comment]
Yep, this is a confusing gotcha with S3. A folder has no semantic meaning in S3, so a glob for:

    s3://my-processing-bucket/keyname*

will match:

    s3://my-processing-bucket/keyname/filename
    s3://my-processing-bucket/keyname-someotherstuff/filename

There might be a fix in Fog for this now - not sure. Feel free to raise a ticket in Sluice.
