### ISSUE TITLE
Kinesis Elasticsearch Sink: don't analyze text fields by default

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1624]
For example, page URLs shouldn't be tokenized.

**Comment by fblundun** [comment]
For unstructured events and custom contexts, we might not know all the field names beforehand. So we need to actually change Elasticsearch's default rather than individually changing how each text field is indexed.

[This thread](http://elasticsearch-users.115913.n3.nabble.com/Help-understanding-keyword-vs-not-analyzed-td4028283.html) suggests that using the keyword analyzer is equivalent to using no analyzer.

[This thread](http://elasticsearch-users.115913.n3.nabble.com/Disabling-default-analyzer-td2932819.html) has an example:

curl -XPUT localhost:9200/test -d '{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "default" : {
                    "type" : "keyword"
                }
            }
        }
    }
}'

**Comment by alexanderdean** [comment]
Sounds good...

**Comment by fblundun** [comment]
I think this is what we want:

```
curl -XPUT 'http://localhost:9200/snowplow' -d '{
    "settings": {
        "analysis": {
            "analyzer":{
                "default":{
                    "type":"keyword"
                }
            }
        }
    },
    "mappings": {
        "enriched": {
            "_timestamp" : {
                "enabled" : "yes",
                "path" : "collector_tstamp"
            },
            "_ttl": {
              "enabled":true,
              "default": "604800000"
            },
            "properties": {
                "geo_location": {
                    "type": "geo_point"
                }
            }
        }
    }
}'
```

**Comment by fblundun** [comment]
We can then tokenize whichever specific fields we want:

```
curl -XPUT 'http://localhost:9200/snowplow' -d '{
    "settings": {
        "analysis": {
            "analyzer": {
                "default": {
                    "type": "keyword"
                }
            }
        }
    },
    "mappings": {
        "enriched": {
            "_timestamp" : {
                "enabled" : "yes",
                "path" : "collector_tstamp"
            },
            "_ttl": {
              "enabled":true,
              "default": "604800000"
            },
            "properties": {
                "geo_location": {
                    "type": "geo_point"
                },
                "some_tokenized_field": {
                    "type": "string",
                    "analyzer": "english"
                }
            }
        }
    }
}'
```

**Comment by fblundun** [comment]
I've updated the documentation on how to do this [here](https://github.com/snowplow/snowplow/wiki/Kinesis-Elasticsearch-Sink-Setup#defining-the-mapping).

**Comment by fblundun** [comment]
Closing since this was done in r65 (but only involved changing documentation)

**Comment by rverma-nikiai** [comment]
@fblundun These configurations are no longer valid with es > 5.0 since the _timestamp and _ttl fields are gone. 
Getting below error
`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Failed to parse mapping [enriched]: [_timestamp] is removed in 5.0. As a replacement, you can use an ingest pipeline to add a field with the current timestamp to your documents."
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [enriched]: [_timestamp] is removed in 5.0. As a replacement, you can use an ingest pipeline to add a field with the current timestamp to your documents.",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "[_timestamp] is removed in 5.0. As a replacement, you can use an ingest pipeline to add a field with the current timestamp to your documents."
    }
  },
  "status": 400
}`
