### ISSUE TITLE
Kinesis Elasticsearch Sink: configure the Elasticsearch version number

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1627]
The Amazon Kinesis Connector Library assumes 1.2.1 but we actually use 1.4.4. This doesn't cause any problems yet but might in the future.

See here: https://github.com/awslabs/amazon-kinesis-connectors/blob/2e2c1a80265cc8ebdcff29bcee15c98d77d120a0/src/main/java/com/amazonaws/services/kinesis/connectors/KinesisConnectorConfiguration.java#L172

**Comment by BenFradet** [comment]
migrated to snowplow/snowplow-elasticsearch-loader#27
