### ISSUE TITLE
Scala Common Enrich: add ability to match internal domains based on a regex

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1628]

**Comment by alexanderdean** [comment]
Can you create a sibling ticket in the referer-parser project @fblundun ?

**Comment by fblundun** [comment]
Here it is: https://github.com/snowplow/referer-parser/issues/101

**Comment by colmsnowplow** [comment]
This has recently become the focus for clients with a large number of subdomains, and whose subdomains will change over time (new products launching, or rolling out new tracking in phases across a large property set).

**Comment by alexanderdean** [comment]
Thanks for flagging, added a Trello card to track this

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/246
