### ISSUE TITLE
Javascript Tracker: Irregular behaviour of session index

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#1629]
Findings based on the differences between the domain_sessionidx and a session index calculated using SQL (30 minutes lag). Events are sorted on dvce_tstamp. The index sometimes decreases, increases when it shouldn't (< 30 minutes) or doesn't increase where it should.

Example reports in Mode:

https://modeanalytics.com/snowplowanalytics/reports/ec581df7c7a7 (index doesn't increase)
https://modeanalytics.com/snowplowanalytics/reports/d8d0b1a34771 (index decreases)

**Comment by BenFradet** [comment]
migrated to snowplow/snowplow-javascript-tracker#590
