### ISSUE TITLE
Scala Common Enrich: support new Avro enriched event format

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1634]
To maintain compatibility between the Hadoop pipeline (which will continue to use the TSV format for now) and the Kinesis pipeline (which can evolve to using the new Avro format much quicker), we should make this an outbound facade. In other words, Scala Common Enrich should be able to emit both formats.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/194
