### ISSUE TITLE
Scala Common Enrich: port JSON Schema validation from Scala Hadoop Shred

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1637]
This will validate:

1. unstructured events
2. custom contexts

Note that Scala Hadoop Shred will retain its existing validation code too (i.e., we won't assume an enriched event is valid).

**Comment by alexanderdean** [comment]
@danisola will work on this.

**Comment by pvdb** [comment]
> `:g/will/s/will/might/g`

:smile:

**Comment by alexanderdean** [comment]
From an architecture perspective, my suggestion is to:

1. Extract the current JSON Validation logic from Scala Hadoop Shred into Common Enrich
2. Use the Common Enrich's JSON Validation logic in Scala Hadoop Shred, Scala Hadoop Enrich and Scala Kinesis Enrich

**Comment by alexanderdean** [comment]
Duplicate of #1947
