### ISSUE TITLE
Explore validating the graph for each incoming event

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1638]
Currently we validate the _types_ within an event, and we enforce that certain fields in our legacy Tracker Protocol are correctly set, but we don't validate the _event semantics_ as a whole.

To give some examples:
- An iOS screen view lacking a geolocation context is a _valid event_
- A PagerDuty event consisting of a single entity ("incident_raised") is a _valid event_
- An event sent by a Snowplow Tracker without a verb is an _invalid event_
- An ecommerce order without any line items is an _invalid event_

Relevant writing from Snowplow:
- http://snowplowanalytics.com/blog/2013/08/12/towards-universal-event-analytics-building-an-event-grammar/
- http://snowplowanalytics.com/blog/2014/03/11/building-an-event-grammar-understanding-context/
- http://snowplowanalytics.com/blog/2015/01/18/modeling-events-through-entity-snapshotting/

This looks interesting: http://www.knewton.com/tech/blog/2012/02/graphlint-creating-a-domain-specific-language-for-graph-validation/

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/146
