### ISSUE TITLE
Scala Common Enrich: add SNS as a new webhook

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1644]
For reference:
- http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/ASGettingNotifications.html
- https://github.com/ifeelgoods/aws-sns-proxy/blob/master/main.go

We just need to do something clever about confirming the subscription. Maybe we should build an auto-confirmer in Lambda.

Suggested approach:
- If the SNS notification is a recognized and supported type (e.g. AutoScaling), then we have unstructured event set to the supported type, and a custom context for the notification envelope
- If the SNS notification is not a supported type, then we just pass in the notification envelope as the unstructured event, no custom contexts

Alarmingly, I can't see any piece of header information which will tell you what service or what notification type a given POST contains. Hopefully I'm just missing something, otherwise we will have to write custom sniffing code...

**Comment by jbeemster** [comment]
The actual CloudWatch trigger gets included with the event so we should be able to determine what the event is about and why it happened.  But yes there will be a fair amount of interpretation..

```
  "Trigger": {
      "MetricName": "CPUUtilization",
      "Namespace": "AWS/EC2",   <- Namespace limits what metrics and dimensions are available
      "Statistic": "AVERAGE",
      "Unit": "Percent",
      "Dimensions": [
        {
          "name": "AutoScalingGroupName", <- Tells us what dimensions this is for
          "value": "snowplow-autoscaling-group-name"
        }
      ],
      "Period": 60,
      "EvaluationPeriods": 5,
      "ComparisonOperator": "LessThanThreshold",
      "Threshold": 60
    }
```

I think we will need to include quite extensive dictionaries of the available AWS dimensions and namespaces but it should be possible to figure out what service each event correlates to!

**Comment by alexanderdean** [comment]
Ah that's great research - thanks Josh!

**Comment by jbeemster** [comment]
There is something else fun with Amazon SNS however.  We will need to have code that confirms that we want to Subscribe to the SNS Topic before it will publish anything.  On SNS Topic creation we will need to provide an endpoint, the POST will contain a SubscribeURL which just needs to be pinged to set it up.  

As the endpoint should be a Snowplow Collector will we be okay to embed this setup step somewhere in the Pipeline?

**Comment by alexanderdean** [comment]
Hey Josh - yes I was trying to understand this and couldn't quite. Is the subscribe URI the same as the notification URI, or do we have the possibility of using a separate one?

**Comment by jbeemster** [comment]
The subscribe URI is something that is generated for you on SNS Topic creation, it is included in a POST to whatever endpoint you specify.  Which could be: `http://collector-acme/com.amazon/sns`.  

I am not sure I understand what you mean by notification URI?

**Comment by alexanderdean** [comment]
Ah! I just meant, is the URI which is used to request a subscription the same URI as the one which is used to send notifications to, if the subscription request is approved? i.e. we have to use the collector URI for both?

**Comment by jbeemster** [comment]
I will see if we can change the endpoint after authenticating, that could be neater.

**Comment by jbeemster** [comment]
We have to use the Collector URI for both unfortunately.  There is no changing after authentication as far as I can see.

**Comment by jbeemster** [comment]
So I guess the question now is if we want to handle authorising the Subscription within common-enrich or if we want to try to do it earlier...

**Comment by alexanderdean** [comment]
Or later? We could just have an AWS Lambda app which auto-confirms the subscriptions (i.e. reads the enriched events from Kinesis and curls the confirmation URI)...

**Comment by jbeemster** [comment]
That could work as well!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/148
