### ISSUE TITLE
EmrEtlRunner: throw exception if processing thrift with --skip s3distcp or AMI 2.x.x

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1648]
It won't work, because of https://github.com/snowplow/snowplow/issues/1647

**Comment by ninjabear** [comment]
While I'm here shall I fix this too @fblundun / @alexanderdean ?

**Comment by ninjabear** [comment]
Oh I see there's already a commit for it! The two changes are about to conflict

**Comment by alexanderdean** [comment]
Aha!
