### ISSUE TITLE
Scala Stream Collector: don't attempt to send records of over 51200 bytes

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1650]

**Comment by alexanderdean** [comment]
Thanks Fred!

**Comment by alexanderdean** [comment]
Fred to check if this is already done.

**Comment by fblundun** [comment]
Yes, this is already done: https://github.com/snowplow/snowplow/blob/feature/kinesis-5/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L227-L229
