### ISSUE TITLE
Links to Docs are broken on github readme.

### ISSUE THREAD

**Issue by keyscores** [snowplow/snowplow#1653]
Can't click through to read more about it. Specifically snowplow/3-enrich/scala-common-enrich

**Comment by alexanderdean** [comment]
Thanks for raising!

**Comment by alexanderdean** [comment]
Will be fixed by #1669, closing

**Comment by ihortom** [comment]
@alexanderdean I don't see anything broken [here](https://github.com/snowplow/snowplow/tree/master/3-enrich/scala-common-enrich) unless I'm looking at the wrong page.

**Comment by alexanderdean** [comment]
Hey @ihortom - I think I forgot to close it back in May last year...
