### ISSUE TITLE
Kinesis Elasticsearch Sink: specify character encoding in SnowplowElasticsearchTransformer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1654]
In this line:

https://github.com/snowplow/snowplow/blob/master/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/SnowplowElasticsearchTransformer.scala#L334

We should be specifying UTF-8 as the encoding.

**Comment by fblundun** [comment]
Weirdly the amazon-kinesis-connectors library doesn't specify an encoding (https://github.com/awslabs/amazon-kinesis-connectors/search?utf8=%E2%9C%93&q=getdata). Is that just an oversight by them?

**Comment by alexanderdean** [comment]
@fblundun - yep, it's a very common oversight in Java land...
