### ISSUE TITLE
Scala Common Enrich: calculated derived_tstamp_local

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1662]
As in, the derived_tstamp in local time. Useful for understanding e.g. what daypart the user was in when an event occurred.

**Comment by alexanderdean** [comment]
Need further tickets for Redshift, Postgres etc.

Depends on: #1550

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/149
