### ISSUE TITLE
Update Technology wiki page to include data modeling sub-system

### ISSUE THREAD

**Issue by bigsnarfdude** [snowplow/snowplow#1670]
1. Documentation on the wiki:
https://github.com/snowplow/snowplow/wiki/Technical-architecture
appears to behind github repo.
https://github.com/snowplow/snowplow

2. Specifically the images are different with the introduction of "data modeling" sub-system:

https://github.com/snowplow/snowplow/wiki/Snowplow-technical-documentation

https://camo.githubusercontent.com/05914f02874cfc540e98af29bd68bf0d6818f54e/68747470733a2f2f64336936666d7331636d316a30692e636c6f756466726f6e742e6e65742f6769746875622d77696b692f696d616765732f736e6f77706c6f772d6172636869746563747572652e706e67

3. There isn't a current method to edit or contribute to wiki, last updated July 2014.

**Comment by alexanderdean** [comment]
Yep that page is behind - we will bring it up to-date Vincent!

You are right, contributing to GitHub wikis which are collaborator-write-only is a little difficult - but there are some instructions here: https://gist.github.com/larrybotha/10650410

**Comment by ihortom** [comment]
@alexanderdean - updated locally

**Comment by alexanderdean** [comment]
Awesome, closing
