### ISSUE TITLE
Documentation: replace Hive ETL references with Kinesis Enrich in Scala Hadoop Enrich's README

### ISSUE THREAD

**Issue by bigsnarfdude** [snowplow/snowplow#1671]
1.  [ 3-enrich/scala-hadoop-enrich/README.md ] The Snowplow Hadoop ETL process is an alt
2.  [ 3-enrich/scala-hadoop-enrich/README.md ] https://github.com/snowplow/s

**Comment by alexanderdean** [comment]
Thanks!
