### ISSUE TITLE
Update AWS screenshots across setup guide

### ISSUE THREAD

**Issue by melmalfa** [snowplow/snowplow#1674]
AWS has updated their screenshots and all of the information that is needed when setting this up. The currently listed info is outdated.

**Comment by alexanderdean** [comment]
Thanks Melodie! Are there any particularly bad/confusing examples we should prioritize?

**Comment by fwahlqvist** [comment]
Hi Alex, Have been using the set-up guide and so far got all the way up to Enrich, however as the elastic-mapreduce is outdated it would be great if that section could be prioritise.

**Comment by ihortom** [comment]
@alexanderdean - Updated screenshots for Cloudfront collector setup and added AWS CLI commands as an alternative approach. You could view the changes in local fork:
1. [Setup a bucket on S3 for the pixel](https://github.com/ihortom/snowplow-wiki-temp/wiki/1-Setup-a-bucket-on-S3-for-the-pixel)
2. [Upload the tracking pixel](https://github.com/ihortom/snowplow-wiki-temp/wiki/2-upload-the-tracking-pixel)
3. [Create a bucket for Cloudfront logs](https://github.com/ihortom/snowplow-wiki-temp/wiki/3-create-a-bucket-for-cloudfront-logs)
4. [Create a Cloudfront distribution](https://github.com/ihortom/snowplow-wiki-temp/wiki/4-create-a-Cloudfront-distribution)

**Comment by alexanderdean** [comment]
This is really nice @ihortom ! How do you do the yellow highighting?

**Comment by alexanderdean** [comment]
Pushed to master

**Comment by ihortom** [comment]
@alexanderdean - Updated screenshots for _Clojure collector setup_. You could view the changes in local fork:
1. [Create a new application in Elastic Beanstalk and upload the WAR file into it](https://github.com/ihortom/snowplow-wiki-temp/wiki/Create-a-new-application-in-Elastic-Beanstalk-and-upload-the-WAR-file-into-it)
2. [Enable logging to S3](https://github.com/ihortom/snowplow-wiki-temp/wiki/Enable-logging-to-S3)
3. [Configuring the Clojure collector](https://github.com/ihortom/snowplow-wiki-temp/wiki/Configuring-the-Clojure-collector)
4. [Additional configuration options](https://github.com/ihortom/snowplow-wiki-temp/wiki/Additional-configuration-options)

**Comment by ihortom** [comment]
@alexanderdean - Updated the screenshots for [Setting up PostgreSQL](https://github.com/ihortom/snowplow-wiki-temp/wiki/setting-up-postgresql) <- local copy

**Comment by ihortom** [comment]
@alexanderdean - Looks like those are all the pages referencing AWS screenshots. The ticket could be closed. If anything missed accidentally, will be dealing on case-by-case basis. I am aware of one page with old screenshots ([Troubleshooting jobs on Elastic MapReduce](https://github.com/snowplow/snowplow/wiki/Troubleshooting-jobs-on-Elastic-MapReduce)) but I do not have a suitable (failure) example to get it updated.

**Comment by alexanderdean** [comment]
Hi @ihortom - great, that's been pushed now. Closing!
