### ISSUE TITLE
Kinesis Elasticsearch Sink: update amazon-kinesis-connectors to 1.1.2 

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1675]
Blocked by https://github.com/awslabs/amazon-kinesis-connectors/issues/48

**Comment by uniuser** [comment]
I have the same issue. Without the update to 0.1.2 I am not able to connect to frankfurt (eu-central-1).

**Comment by alexanderdean** [comment]
@uniuser - please follow up in the blocker ticket too

**Comment by alexanderdean** [comment]
The blocking issue is fixed, so we can bring this forward now.
