### ISSUE TITLE
Scala Stream Collector: handle case where IP is not present

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1680]
The partition key for a Kinesis record should never be `null`.

**Comment by jbeemster** [comment]
Hey @fblundun with this ticket where is the best place to be checking for the null value?  And are we only checking for null or also for empty strings as well?

I see that the IP is being converted to a string here: https://github.com/snowplow/snowplow/blob/release/r67/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/CollectorService.scala#L89

...and if it were a null value it would no doubt throw a NPE.  Should it then instead be passing the ip through untouched and then processing it in the ResponseHandler?

**Comment by fblundun** [comment]
I think that's a good idea - handle the null in the ResponseHandler. The key argument to storeRawEvent should probably be randomly generated if IP is null.

**Comment by fblundun** [comment]
As far as I know, empty IP address strings shouldn't come up...

**Comment by alexanderdean** [comment]
Agree

**Comment by fblundun** [comment]
We could use the toOption method like [this example](http://spray.io/documentation/1.1.2/spray-routing/misc-directives/clientIP/)

**Comment by alexanderdean** [comment]
Looks good!

**Comment by jbeemster** [comment]
I like the toOption option.  Is unknown an okay identifier for these cases?

**Comment by alexanderdean** [comment]
It should have some entropy no?

**Comment by jbeemster** [comment]
We can add entropy but wouldn't it just make it harder to identify how many events are actually coming through as unknown?

**Comment by alexanderdean** [comment]
This is just for the partition key right? We can still query for missing IP addresses in Elasticsearch or Redshift... Entropy is to avoid hotspotting on one shard. Let me know if I'm missing something...

**Comment by jbeemster** [comment]
Oh right yes it would just be for the partition key.  Never mind previous comment!
