### ISSUE TITLE
Add extra column with page view/ping UUID in data model

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#1684]
Related to this issue: https://github.com/snowplow/snowplow-javascript-tracker/issues/369

**Comment by fblundun** [comment]
Would this be covered by the [domain_sessionid field](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala#L230)? (It isn't currently populated by any tracker.)

**Comment by alexanderdean** [comment]
No the session ID would be separate - would span multiple page views...

**Comment by bogaert** [comment]
Indeed Alex. The purpose of this page view ID is to make the aggregation of page view and ping events into a single row easier. The page view event would have a new UUID, and each subsequent page ping on that page would have the same UUID (until a new page view event occurs).

For example: If a user opens 2 different pages in 2 tabs, and switches between them, the page ping events will alternate. While it's possible to roll these events up into the original page view event during the data modeling step, it's (needlessly) complicated to cover all edge cases in SQL. It's also an issue when the derived views are updated using only incremental data.

The page view UUID would make this all a lot simpler.

**Comment by fblundun** [comment]
I see - thanks for explaining!

**Comment by bogaert** [comment]
This has been implemented.
