### ISSUE TITLE
EmrEtlRunner / StorageLoader: make sure _SUCCESS files are written last

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1695]
When we e.g. move files from HDFS to S3, we don't copy the _SUCCESS file necessarily last.

It would be nice to always write the _SUCCESS file last, so a downstream process that is monitoring the bucket knows that the next step can kick off.

Note that intra-AWS processes can always use an SNS notification to achieve the same without flag files.

/cc @yalisassoon

**Comment by BenFradet** [comment]
This is done as part of #3137, closing
