### ISSUE TITLE
Clojure Collector: suggest adding Lifecycle Management hooks to the auto scaling group

### ISSUE THREAD

**Issue by andrioni** [snowplow/snowplow#1696]
Since mid-2014 Amazon started to support adding [Lifecycle Management  hooks](https://aws.amazon.com/blogs/aws/auto-scaling-update-lifecycle-standby-detach/) to allow actions to be done either on creation or destruction of instances on auto scaling groups, including delaying the termination of a instance for up to 24 hours.

A suggestion could be made in the documentation to use these hooks to automate the decommissioning of Clojure Collector instances whenever the demand is low (currently the suggestion is to allow the cluster only to automatically scale up, not down).

**Comment by andrioni** [comment]
The manual decommissioning process described [here](https://github.com/snowplow/snowplow/wiki/Troubleshooting-Clojure-Collector-instances-to-prevent-data-loss) could probably be automated.

**Comment by yalisassoon** [comment]
This is a great idea Alessandro - we're discussing this internally - thanks
for raising!

On Mon, May 18, 2015 at 11:42 PM, Alessandro Andrioni <
notifications@github.com> wrote:

> The manual decommissioning process described here
> <https://github.com/snowplow/snowplow/wiki/Troubleshooting-Clojure-Collector-instances-to-prevent-data-loss>
> could probably be automated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/1696#issuecomment-103238423>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
