### ISSUE TITLE
Scala Common Enrich: add referral spam enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1697]
Flags an event as being referral spam based on the referer being on Piwik's referrer spam blacklist:

https://github.com/piwik/referrer-spam-blacklist

**Comment by alexanderdean** [comment]
Couldn't we just add a Spam: section into the existing referer-parser database?

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/150
