### ISSUE TITLE
Kinesis Elasticsearch Sink: add Scala Tracker dependency

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1705]

**Comment by fblundun** [comment]
We could add an optional section in the hocon like this:

```hocon
tracking {
  endpoint = "mycollector.cloudfront.net"
  appId = "productionSink"
}
```

Alternatively we could use the DynamoDB app-name as the appId.

I don't know whether there is any reason to make the tracker namespace (tna) configurable.

I can't think of anything else that should be configurable.

**Comment by alexanderdean** [comment]
Hey Fred! This is all I came up with for the EmrEtlRunner:

https://github.com/snowplow/snowplow/commit/3ef384705a93f261fccf3109af4ec7ee1d0681bd

I think collector_uri is probably preferable to endpoint or collector...

Agree, I think tna is not needed.

On the hocon section - I think `monitoring { snowplow {` might be more futureproof than `tracking {`...
