### ISSUE TITLE
EmrEtlRunner: bump Sluice to 0.4.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1708]
This will bring support for new AWS regions including eu-central-1.

**Comment by alexanderdean** [comment]
Bringing forward as this will save some pain!

**Comment by kytori** [comment]
yep really if i knowing this before to start deployment of all my stuff on eu-central-1 i dont waste so many time to move everything on ireland to be sure that is work , you have a date for this ?

**Comment by alexanderdean** [comment]
We don't commit to release dates but it should be in around 3 releases' time.

**Comment by kytori** [comment]
any workaround for this?

**Comment by alexanderdean** [comment]
See https://github.com/snowplow/sluice/issues/30

**Comment by gincor** [comment]
Hi, 

still getting the "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.", so I assume this issue is still open. Not asking for a release date, but could you update the "3 releases" guesstimate if you have the chance? 

thanks a lot

**Comment by alexanderdean** [comment]
Hey @gincor - I'm sorry this one has been hanging for so long. Bringing it forwards...

**Comment by gincor** [comment]
Hi Alex,

thanks for the quick reply. Just wanted to add my (temporary) workaround which works well for testing and doesn't take a lot of time in case anyone with the same issue finds this.

If you setup everything for an unsupported region, all you have to do is manually sync the s3 bucket where your collector dumps the files to a bucket you create in a supported region and adjust the paths in your config.yaml. Same for your 'output bucket'. If you setup replication, I'd hope this would work pretty well automatically after the first setup/sync.

best regards from Berlin (also to @yalisassoon)

**Comment by alexanderdean** [comment]
Thanks @gincor - you are right, you can work around the limitation with some usage of `aws s3`... All the best with it!

**Comment by jurgenweber** [comment]
That is quite slow and annoying if you collect a lot of data.

Super interested to see this live.

**Comment by jessealama** [comment]
+1

**Comment by gincor** [comment]
EMR apparently also has some issue in central-1 as juergenweber pointed out: https://groups.google.com/forum/#!msg/snowplow-user/9fuknNXXjjc/CMPjMXEjIgAJ

running into the exact same thing.
