### ISSUE TITLE
Update Postgres setup documentation

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1709]
https://github.com/snowplow/snowplow/wiki/Setting-up-PostgreSQL#3-create-the-snowplow-events-table-and-views-in-postgresql

To reflect removal of cubes etc.

**Comment by ihortom** [comment]
@alexanderdean / @yalisassoon - AWS screenshots were updated a while ago. Apart from that, would need to get a clarification/list on what is expected to be updated...

**Comment by ihortom** [comment]
@alexanderdean - Removed cube related instructions. Added a warning that we are working on new data models and recipes as discussed with @bogaert. Local copy is [here](https://github.com/ihortom/snowplow-wiki-temp/wiki/Setting-up-PostgreSQL). Could be closed now.

**Comment by alexanderdean** [comment]
Pushed! Closing.
