### ISSUE TITLE
Scala Kinesis Enrich: log all bad rows

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1722]
This would make debugging a lot easier...

**Comment by jbeemster** [comment]
Hey @fblundun do you mean logging the error just here:

https://github.com/snowplow/snowplow/blob/release/r67/3-enrich/scala-kinesis-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.kinesis/sources/AbstractSource.scala#L183-L185

Or was there a different spot that you were thinking of logging at?

**Comment by fblundun** [comment]
Doing it there mostly works but it doesn't see bad rows caused by oversized events (which are only introduced [here](https://github.com/snowplow/snowplow/blob/release/r67/3-enrich/scala-kinesis-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.kinesis/sources/AbstractSource.scala#L218)). So I think that the logging should either be done in the enrichAndStoreEvents method or the KinesisSink's storeEnrichedEvents method.

This should only happen if the app is writing bad rows to Kinesis rather than stderr (since if bad events are being written to stderr logging adds nothing and pollutes stderr.)

**Comment by jbeemster** [comment]
That makes sense!  Okay I will add it to the KinesisSink only.  Thanks for the clarification.
