### ISSUE TITLE
Scala Hadoop Shred: process enriched events for atomic.events removing JSON fields

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1731]
Question by @digdeep:

> why does atomic events store the context Json in a field when you have a table for the context already?

It's an artifact of the fact that our enriched event format is used twice:

1. Once as the row to load into atomic.events
2. Once as the input into the shredding process

Originally we didn't have a shredding process, so we had to include those JSONs in atomic.events so people could try to use the Redshift JSON functions on them. **BUT**:

1. These JSONs take up a lot of storage in Redshift
2. They are basically impossible to query on
3. Not sure how often the JSONs in atomic.events are useful for debugging a pipeline - @yalisassoon ?

As context: in any case we will be breaking the 1:1 relationship between the enriched event format and the atomic.events loaded into Redshift; the plan is to port the enriched event to Avro; following this the TSV file for atomic.events will be prepared by the shredder, alongside the JSON tables.

Thus, rather than implement #1481, we could implement an initial modest reformatter of enriched events to load into atomic.events, which would remove the JSON fields.

Thoughts @yalisassoon ?

**Comment by alexanderdean** [comment]
Update from @yalisassoon - these fields are in fact v useful for debugging bad rows. Therefore we can say that this ticket is blocked by this ticket: #824, which provides an alternative way of debugging bad rows...

**Comment by digdeep** [comment]
Thanks for update Alex,

On the specifics of debugging, do bad rows for contexts still get loaded
with atomic events that are good? is this the reason it is used for
debugging to see what is causing the error?

For what it is worth, we use a basic install of Splunk for bad rows, super
simple to read in S3.

**Comment by alexanderdean** [comment]
Yes, an invalid context (say) will still be present in atomic.events (today), as long as the JSON is valid JSON.

**Comment by andrioni** [comment]
:+1:, this would make atomic.events table smaller and more manageable
