### ISSUE TITLE
Kinesis Elasticsearch Sink: update the Elasticsearch version

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1734]
There are intermittent errors in the TransportClient which could be loosely related to the fact that the amazon-kinesis-connectors library is using quite an old version of Elasticsearch (1.2.1).  Would be good to bump this to a later version - 1.4.*.

**Comment by alexanderdean** [comment]
Here is some sbt-fu to replace an old version of a transitively bundled dependency with a newer one: https://github.com/snowplow/snowplow/blob/feature/r66-hadoop2/3-enrich/scala-hadoop-enrich/project/Dependencies.scala#L58

**Comment by alexanderdean** [comment]
This ticket will only work if the subset of the Java API we use is compatible from 1.2.1 to 1.4.4

**Comment by alexanderdean** [comment]
This is done and tested and working
