### ISSUE TITLE
Kinesis Elasticsearch Sink: investigate turning on Elasticsearch Transport Sniffing

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1735]
This setting could potentially allow better recovery from an inability to find a node.

Information on clients: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html

By default sniffing is `false`:

https://github.com/awslabs/amazon-kinesis-connectors/blob/2e2c1a80265cc8ebdcff29bcee15c98d77d120a0/src/main/java/com/amazonaws/services/kinesis/connectors/KinesisConnectorConfiguration.java#L164

**Comment by fblundun** [comment]
@jbeemster - I think we came to the conclusion that this doesn't help?

**Comment by jbeemster** [comment]
We did indeed.  I think with the timeout kill and reset setup we need not worry about this ticket.

**Comment by fblundun** [comment]
Ok, closing.
