### ISSUE TITLE
Scala Common Enrich: add Full Contact Enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1741]
http://www.metricmogul.co.uk/profiling-users-google-analytics-plugin/

We would look up into Full Contact based on email address.

This would be a good test of the functionality we need to write where you key an enrichment off a JSON Path to a field in an event or context...

https://github.com/fullcontact/fullcontact4j

**Comment by kingo55** [comment]
Nice! Take a look at Stack Lead - we use them on our site. 

They're probably a better candidate for web hooks but they have a nice and easy API, and they're considerably cheaper for low volumes: https://stacklead.com/dev

**Comment by alexanderdean** [comment]
StackLead is dead no? http://stacklead.com/blog/

**Comment by kingo55** [comment]
Hah - that would explain the silence!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/153
