### ISSUE TITLE
Scala Kinesis Enrich: change back-off algorithm

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1744]
Current algo leads to this:

```
sPUT-fPUT..........sPUT-fPUT..............sPUT-fPUT
```

where sPUT is a successful write to the stream and the fPUT is a failure (causing back-off).

We want something more like this:

```
sPUT-fPUT.sPUT-fPUT..sPUT-sPUT-fPUT.sPUT
```

**Comment by fblundun** [comment]
Does this actually require a change in the algorithm rather than just making the minBackoff and maxBackoff smaller?

**Comment by alexanderdean** [comment]
Good Q! Making the period smaller definitely works as a workaround. Let's push back this ticket and think about it some more...

**Comment by jbeemster** [comment]
Does this ticket require any work or are we happy to leave it up to the back-off timings?

**Comment by alexanderdean** [comment]
This is Kinesis #7 so already pushed back...

**Comment by jbeemster** [comment]
My issues got confused with my milestones sorry!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/155
