### ISSUE TITLE
EmrEtlRunner: make in bucket an array

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1750]
This will make it easier to e.g. upgrade collectors (because we can be fetching from two in buckets in the same run)...

**Comment by alexanderdean** [comment]
Moving forwards!

**Comment by fblundun** [comment]
If an "in" buckets is empty or nonexistent, EmrEtlRunner doesn't give a warning (or an error) - is this something we should change in Snowplow Sluice?

**Comment by alexanderdean** [comment]
Hey Fred, good question but no that's deliberate - it means no data to process since last time, which is not in itself a failure

**Comment by alexanderdean** [comment]
Hey @fblundun - can we move this up to R67 too? It will be super-helpful for @yalisassoon upgrading users' Clojure Collectors.

**Comment by fblundun** [comment]
Of course! It's in the r67 branch now.

**Comment by alexanderdean** [comment]
Thanks Fred!
