### ISSUE TITLE
Scala Kinesis Enrich: tries to send 503 records

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1756]
https://groups.google.com/forum/#!topic/snowplow-user/SKzunb6oM6o

**Comment by fblundun** [comment]
I think I understand the problem. In writing the app I assumed that each thread would have its own instance of the KinesisSink. Actually it seems that if there are enough shards, an instance of the KinesisSink class can get shared between multiple threads. This leads to race conditions.

We can get around this either with synchronization or giving each thread its own copy of the KinesisSink using ThreadLocal. I think the second option will give better performance.

**Comment by alexanderdean** [comment]
Ah - thanks Fred. Second option sounds good...

**Comment by fblundun** [comment]
Until the above fix is released, a partial workaround is to change the record-limit field of the configuration hocon to something less than 500 so that if the race condition causes too many records to be set at once, it won't trigger an AWS exception.
