### ISSUE TITLE
Snowplow CLI: automatically create new tables on first use

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1765]
> If the SQL for an event is named canonically, why don't the pipelines execute the create statement? It seems like a needless manual step.

If Redshift DDL is available under the jsonpaths assets path (say), then we could perform this algorithm:
1. Check if table exists by executing SELECT or inspecting Redshift metadata
2. If doesn't exist, fetch DDL from jsonpaths assets path and execute DDL against database

This would require create table permissions.

This is more code to have to factor out when we move table definitions to Iglu (along with JSON Paths files), but given that that will take some time, this could be a good way of getting started with automated entity creation in dbs.

Thoughts @yalisassoon ?

**Comment by yalisassoon** [comment]
Love it
