### ISSUE TITLE
Snowplow CLI: whitelist to control which entities to load?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1768]
Background is in this ticket: https://github.com/snowplow/snowplow-javascript-tracker/issues/373

From @benhoyt:

> We don't really care about 1 or 2 stray events coming in from another site. But what is a bit painful is 
> that our nightly automated script to run Snowplow storage-loader fails hard, so we have to dig into the 
> problem, figure out what’s happening, delete the stray events in shredded events S3 bucket, and 
> re-run manually. It would be much nicer if the Snowplow process (maybe at the EmrEtlRunner level?) 
> simply ignored events or schemas it wasn’t looking for.

This should be considered alongside #1765 - we don't want a bad actor to be able to flood a user's Redshift with new tables...

**Comment by alexanderdean** [comment]
A whitelist could look something like this:

* `com.snowplowanalytics.snowplow/link_click`
* `com.mandrill/*`
* `com.acme/*`

**Comment by benhoyt** [comment]
Thanks! Yeah, that kind of thing would be great.
