### ISSUE TITLE
Redshift: widen domain_sessionidx column in atomic.events from smallint to integer

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#1788]
Some clients with frequently visited services will record values higher than the `32767` enforced by having `domain_sessionid` set to `smallint` in Redshift.
Suggest updating it to integer?

**Comment by alexanderdean** [comment]
Scheduling into atomic.events update

**Comment by alexanderdean** [comment]
Per:

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala#L66

The underlying field is a Java Integer, values from -2147483648 to 2147483647, inclusive per:

https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.2

This maps onto a Redshift INTEGER, INT, or INT4, values -2147483648 to +2147483647, per:

http://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html#r_Numeric_types201-integer-types
