### ISSUE TITLE
Scala Common Enrich: add ability to lookup a context from DynamoDB

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1791]
We can fetch a whole item from DynamoDB as a JSON using http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/JavaDocumentAPIItemCRUD.html#JavaDocumentAPIGetItem

Configuration options we will need:
- Details on the DynamoDB table to look in
- A way of specifying the key to lookup (DynamoDB keys can be string, binary, number)
- A schema URI to attach to the returned document
- LRU cache size
- Bonus points: a way of renaming or eliding columns (probably won't get around to this)

The way of specifying the key to lookup is interesting. I think there are two ways of doing this:
1. Configuration: provide a syntax for specifying possible places where the key could live. Difficulty: this would have to include the "legacy" POJO fields as well as the contents of the unstructured event and custom contents. So a bit of Java reflection would be involved
2. Scripting: let the user write a little piece of JavaScript which isolates the key. More flexible, although we will probably have to write a helper script to make it easy to get at the unstructured event or custom contexts on a by-name basis

/cc @yalisassoon, @fblundun

**Comment by fblundun** [comment]
Would it be possible to incorporate this into the existing JS enrichment, maybe by letting users access an LRU cache and the DDB lookup method?

**Comment by alexanderdean** [comment]
I thought about that idea, but I think there's too much scope for pilot error... Or to put it another way, I think there's a lot of overlap in the functionality but it's better to have a new enrichment which guides the user in how to do this (even if it uses a lot of the same functionality under the hood).

Also I am leaning towards implementing the 1. Configuration option first, as again it should reduce the complexity of the enrichment for users...

**Comment by alexanderdean** [comment]
Also - the DynamoDB enrichment is somewhat easier because of the JSON support. For the HBase or Cassandra or MySQL cousin enrichments we would have to do a lot more hand-holding...

**Comment by alexanderdean** [comment]
Duplicate of #2345, closing

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/156
