### ISSUE TITLE
Docs: Clojure Connector Setup for JS tracker

### ISSUE THREAD

**Issue by keyscores** [snowplow/snowplow#1796]
On the wiki https://github.com/snowplow/snowplow/wiki/integrating-javascript-tags-onto-your-website

Seems like there is an example missing in the JS tracker page. The Clojure tracker example is the same as the Cloudfront.

See the code section below the text
"If you are using another Collector type, for example a Clojure Collector ..."

**Comment by alexanderdean** [comment]
Fixed! Thanks.

**Comment by keyscores** [comment]
Thanks. BTW can you give that page, or another, some more detail about how mechanics of the clojure connector. Does it use pixels? Does it use REST requests? As a newbie I don't see how the requests happen. 
Thanks!

**Comment by alexanderdean** [comment]
https://github.com/snowplow/snowplow/wiki/Clojure-collector
