### ISSUE TITLE
Scala Common Enrich: write out event_vendor/name/format/version fields

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1800]
I think the most futureproof way of doing this would be to have a structure in atomic.events like this:

```
event       | event_vendor                   | event_name  | event_format | event_version
-----------------------------------------------------------------------------------------
unstruct    | com.snowplowanalytics.snowplow | ad_click    | jsonschema   | 1-0-0
page_view   | com.snowplowanalytics.snowplow | page_view   | jsonschema   | 1-0-0
struct      | com.google.analytics           | event       | jsonschema   | 1-0-0
transaction | com.snowplowanalytics.snowplow | transaction | jsonschema   | 1-0-0
```

The rationale here is:

* Anybody using the existing event column can continue to do so
* Anybody using unstructured events can use the new event_vendor/name/format/version columns, which map directly onto the Iglu URI components
* As we convert our legacy events (e.g. GA-style 5-field structured events) into JSONs, then the corresponding event_vendor/name/format/version columns are futureproofed - their values won't change

Depends on #1637

**Comment by alexanderdean** [comment]
@danisola will work on this

**Comment by pvdb** [comment]
> `:g/will/s/will/might/g`

:smile:
