### ISSUE TITLE
Kinesis Elasticsearch Sink: allow use of AWS creds instead of DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1803]
This line https://github.com/snowplow/snowplow/blob/release/r67/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/ElasticsearchSinkApp.scala#L123 prevents you from directly inserting AWS Credentials through the config as there is no Credentials lookup before creating the sink.

**Comment by fblundun** [comment]
Good point! At the moment it looks like the credentials from the config file are used for getting records from Kinesis but not for writing to the bad stream.

**Comment by jbeemster** [comment]
Exactly!  I figure it is meant to be used for both.

**Comment by fblundun** [comment]
Yes, this was my mistake...

**Comment by jbeemster** [comment]
Easy fix no worries!  I doubt it would ever really come up as most people would use IAM or ENV for anything production...
