### ISSUE TITLE
Scala Hadoop Shred: bump common enrich to 0.15.0

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1812]

**Comment by alexanderdean** [comment]
This can wait till R69

**Comment by jbeemster** [comment]
I did it already, the commit is in the commit to bump common enrich to 0.15.0.  It is all updated.  I can revert that section if you want?

**Comment by alexanderdean** [comment]
Yep please revert - let's keep this release Kinesis-only...

**Comment by jbeemster** [comment]
No worries shall do.

**Comment by fblundun** [comment]
Duplicate of #1935, closing...
