### ISSUE TITLE
Snowplow CLI: consider logging more while waiting for the EMR job to complete

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1822]
These are some of the EMR job data which we could log:

https://github.com/rslifka/elasticity/blob/master/lib/elasticity/job_flow_status_step.rb#L5-L9
https://github.com/rslifka/elasticity/blob/master/lib/elasticity/job_flow_status.rb#L5-L21

Not sure whether this would actually be useful.

**Comment by alexanderdean** [comment]
It's good thinking! Let's discuss on Monday
