### ISSUE TITLE
Explore using sbt-native-packager for Kinesis apps

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1829]
https://github.com/sbt/sbt-native-packager

**Comment by christoph-buente** [comment]
Wouldn't it be more desirable to provide an sbt task that dockerizes the kinesis apps? That would make it much easier to deploy with AWS beanstalk or opsworks for example.

**Comment by alexanderdean** [comment]
Definitely something to explore! Created #2492, #2493

**Comment by chuwy** [comment]
Already used.
