### ISSUE TITLE
RDB Loader: use Redshift-specific driver to connect to Redshift

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1830]
See http://docs.aws.amazon.com/redshift/latest/dg/c_redshift-postgres-jdbc.html

I haven't yet tested connecting to Redshift using the PostgreSQL driver jar - if it doesn't work, this issue will need to go into r68.

**Comment by epantera** [comment]
Hi @fblundun 

seems that we have an issue here with the r70 and the move to postgres jdbc driver.
We can't connect to Redshift.

Did you already managed to connect to Redshift with r70 ?

thx,

**Comment by epantera** [comment]
Hmm, seems to work better when adding `?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`
to the connection_url in postgres_loader.rb

**Comment by alexanderdean** [comment]
Do you have SSL validation switched on for your cluster? This PR: https://github.com/snowplow/snowplow/pull/1980

has been merged into R71. If you want to try out R71, there's a rc build already available on Bintray:

https://bintray.com/snowplow/snowplow-generic/snowplow/r71-stork-billed-kingfisher/view#files

**Comment by fblundun** [comment]
Note that if you do try that build, the YAML key is now "ssl_mode" rather than "ssl_mode".
