### ISSUE TITLE
StorageLoader Failure Error if enriched good bucket has periods.

### ISSUE THREAD

**Issue by EZWrighter** [snowplow/snowplow#1838]
If attempting to use a bucket with periods the storageloader fails to download events and quits prematurely with the following error:

Unexpected error: hostname does not match the server certificate (OpenSSL::SSL::SSLError)

Workaround: Removing the periods from the bucket name allows the process to complete normally.

I understand that periods in bucket names are not optimal for secure virtual host reasons, but they are completely valid bucket names and should not cause the process to abort.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/15
