### ISSUE TITLE
Kinesis Elasticsearch Sink: investigate case where sink stops getting events from the stream

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1840]
Hey @fblundun @alexanderdean have noticed a weird case whereby the sink stops fetching any events from the input stream.  No errors are thrown but some of the Kinesis Connectors Magic seems to be able to break without warning.

It feels like somehow the app stops being in sync with its shard and then it just stops pulling events into the buffer.  A restart of the application immediately resolved the issue.

**Comment by alexanderdean** [comment]
Thanks for raising Josh. Question - would this have been detected as stream lag? It sounds like it would have...

**Comment by fblundun** [comment]
I think it would - if the app stops getting records then it probably also stops checkpointing.

**Comment by BenFradet** [comment]
migrated to snowplow/snowplow-elasticsearch-loader#25
