### ISSUE TITLE
Scala Kinesis Enrich: etl_tstamp should be Redshift Formatted not raw

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#1842]
https://github.com/snowplow/snowplow/blob/release/r67/3-enrich/scala-kinesis-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sources/AbstractSource.scala#L182

**Comment by denismo** [comment]
Also, would like to throw in that the timestamp (originally) was in local time, not UTC. Not sure whether the current fix handles that.

**Comment by jbeemster** [comment]
Hey @denismo yes this does indeed fix not UTC as well!  Instead of it being a raw timestamp it is now being processed using this formatter: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EventEnrichments.scala#L39

So it should always be redshift compatible and in UTC from now on.
