### ISSUE TITLE
Redshift: update atomic.events column encoding

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#1846]
Update table encodings based on what Redshift suggests as the optimal encoding.

https://groups.google.com/forum/#!topic/snowplow-user/1It4i1Ex-6g
http://docs.aws.amazon.com/redshift/latest/dg/r_ANALYZE_COMPRESSION.html

**Comment by alexanderdean** [comment]
That's a great idea. I suggest we ANALYZE COMPRESSION on a few users' atomic.events and then merge the results (because any one user won't be using all the fields)...

**Comment by alexanderdean** [comment]
Scheduling

**Comment by yalisassoon** [comment]
Looks like for users with lots of custom context, the 'contexts' field accounts for almost 50% of the space taken, so fingers crossed switching the encoding to `lzo` will result in big space savings...

**Comment by bogaert** [comment]
Interesting. I'll update the encoding when R69 is done.

Christophe

Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0) 203 589 6116
+44 (0) 7598 006 851

**Comment by alexanderdean** [comment]
There is (currently) a sister ticket, #1849, in this milestone which will remove the JSON fields including contexts. So it's looking like this milestone will massively reduce Redshift space requirements...

**Comment by bogaert** [comment]
For future reference: http://docs.aws.amazon.com/redshift/latest/dg/t_Verifying_data_compression.html

In almost all cases encode lzo has by far the best compression.

**Comment by bogaert** [comment]
Depending on user, it looks like updating the encoding can reduce disk usage between 20 and 50%.

**Comment by alexanderdean** [comment]
Cool! This milestone should lead to big Redshift space savings...

**Comment by danielzohar** [comment]
We've seen about 45% reduction in size with one billion rows. down from 750GB to 400GB (approximately)

**Comment by kingo55** [comment]
Adding to this thread, migrating our table from the OOB encoding to Redshift's documented encoding, we saw a ~61% saving in space.

Happy to submit a pull request for the migration script. Not sure if you guys have done some work internally which serves the community as a whole better though.

@danielzohar - is your encoding similar to mine?:

https://groups.google.com/forum/#!topic/snowplow-user/0pGdjV-vjYQ

**Comment by vceron** [comment]
We used this [script](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility) proposed in [AWS Labs](https://github.com/awslabs) and we gained 50% of atomic.events disk space (from 530Gb to 250Gb) with 1.07 billion rows.
The output sql script is similar to [Gabriel's script](https://groups.google.com/forum/#!topic/snowplow-user/1It4i1Ex-6g)

**Comment by alexanderdean** [comment]
Thanks for sharing @vceron !

**Comment by tclass** [comment]
This ticket is already a little bit old, but with the new zstd encoding, the results would be even better for some columns. https://aws.amazon.com/de/about-aws/whats-new/2017/01/amazon-redshift-now-supports-the-zstandard-high-data-compression-encoding-and-two-new-aggregate-functions/

**Comment by yalisassoon** [comment]
The team at Snowflake-Analytics has experimented with this and found large `atomic.events` table only take up 1/3 of the space as with the current set of defaults: http://snowflake-analytics.com/blog/infrastructure/snowplow-redshift-zstd/.

Also worth looking into if we need to be careful compressing sort keys: https://twitter.com/snowflake_data/status/885020933131554816

**Comment by alexanderdean** [comment]
Can we close this, superseded by R93?

**Comment by bogaert** [comment]
Yep. Closing.
