### ISSUE TITLE
Redshift: remove JSON fields from atomic.events

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1849]
See #1731

**Comment by danielzohar** [comment]
I'm interested in trying to tackle this. This field takes about 30% of our atomic.events storage. Can anyone point out what needs to be done in order to accomplish this? Thanks

**Comment by alexanderdean** [comment]
Hi! This is the ticket: #1731. @fblundun - please let @danielzohar know when you would be starting on this (and thus whether it's worth him getting started on this or not).
