### ISSUE TITLE
Deduplication: add a step that deduplicates events

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#1866]
- move duplicate events to a temporary table
- delete those events from atomic.events
- combine natural copies and insert back into atomic.events
- move synthetic copies to their own tables

**Comment by alexanderdean** [comment]
See #24 for a detailed treatment of the problem

**Comment by bogaert** [comment]
Thanks @alexanderdean.

I discussed this with @yalisassoon this morning, and the idea was to have this as a SQL Runner step after each load. Natural copies get deduplicated, while synthetic copies get moved to a separate events table.

**Comment by alexanderdean** [comment]
Sounds good!
