### ISSUE TITLE
EmrEtlRunner: recover from IOError when checking job status

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1881]
See #1828

**Comment by fblundun** [comment]
@alexanderdean do you think it would be better to just catch all nonfatal errors rather than having this growing list of specific errors?

(This assumes that all the exceptions we want to catch really do descend from StandardError...)

**Comment by alexanderdean** [comment]
Hey @fblundun - it's not a bad idea at all... My nervousness is that if we make the catch too expansive and there is some unrecoverable issue and the EmrEtlRunner just sits there retrying for ever.

What about a ticket for the next CLI release where we:

1. Catch all nonfatal
2. Keep a counter of non-fatals in a row and die after N non-fatals in a row
