### ISSUE TITLE
EmrEtlRunner: bump Elasticity to 6.0.2

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1903]
The error this will fix is:

> ArgumentError (DescribeJobFlows API is deprecated. Please refer to http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html for further information):

This is required to handle the recent AWS EMR API changes. New users of Snowplow (who haven't run a cluster on AWS before) won't be able to monitor their EMR jobs through EmrEtlRunner (though the job will start). 

Depends on https://github.com/rslifka/elasticity/issues/87

The manual workaround in the meantime is to:

1. Run your job as usual with EmrEtlRunner
2. The job will submit to the cluster but then monitoring of the job will fail
3. Wait for the job to complete in the AWS EMR console
4. Run the EmrEtlRunner job again but with `--skip staging,emr`

**Comment by alexanderdean** [comment]
@fblundun - in the meantime (i.e. while waiting for the Elasticity 6 release), please get EmrEtlRunner upgraded to the latest Elasticity release (5.0.3), so that we can fix any Ruby dependency issues in good time.

**Comment by fblundun** [comment]
Current status on this:

Using Ruby 2.2.1 and an existing AWS account, EmrEtlRunner:

works with Elasticity 5.0.1
doesn't work with Elasticity 5.0.2 (apparently because of https://github.com/rslifka/elasticity/issues/86, which was fixed in 5.0.3)
doesn't work with Elasticity 5.0.3 - for some reason, the JobFlow.steps method is returning `nil`.

**Comment by alexanderdean** [comment]
Hey @fblundun - thanks for diving into this. I'll /cc @rslifka in this thread so that he is aware of the 5.0.3 issue we are having...

**Comment by fblundun** [comment]
I just edited my comment above to say that it is JobFlow.status, not JobFlow.steps, which is returning `nil`.

**Comment by alexanderdean** [comment]
Cool, thanks @fblundun . BTW - I have pinged Rob to ask if there's any way we can help out on the Elasticity 6 release to get it out sooner...

**Comment by fblundun** [comment]
Good idea!

**Comment by fblundun** [comment]
More information on what's going wrong:

[Here](https://github.com/rslifka/elasticity/blob/v5.0.3/lib/elasticity/emr.rb#L7-L25) in 5.0.1, the AwsRequest returns an XML string which is correctly parsed by Nokogiri::XML.

[Here](https://github.com/rslifka/elasticity/blob/v5.0.3/lib/elasticity/emr.rb#L7-L25) 5.0.3, the AwsSession instead returns a JSON string which Nokogiri basically ignores. This is what causes the `nil` value for JobFlow.status.

**Comment by rslifka** [comment]
@fblundun Yep, AWS has changed the return and submission protocols, hence our conundrum :)  Fortunately they're backwards compatible on the submission protocols but it turns out when Elasticity was updated to the V4 signature format, it switched to the new format on the send side.  In the process of implementing the new APIs now.  Follow along for 6.0 - https://github.com/rslifka/elasticity/milestones/6.0%20-%20New%20Amazon%20API

**Comment by fblundun** [comment]
Thanks for the update @rslifka ! Looks like it's going well.

**Comment by fblundun** [comment]
I've updated to use the new API. Here's a sample error message from when I manually terminate a job:

```
Snowplow::EmrEtlRunner::EmrExecutionError (EMR jobflow j-3J8LOJN8AWOOU failed, check Amazon EMR console and Hadoop logs for details (help: https://github.com/snowplow/snowplow/wiki/Troubleshooting-jobs-on-Elastic-MapReduce). Data files not archived.
r67 Job: TERMINATING [USER_REQUEST] ~ elapsed time n/a [2015-07-20 10:25:24 +0000 - ]
 - 1. Elasticity S3DistCp Step: Raw S3 -> HDFS: COMPLETED ~ 00:01:53 [2015-07-20 10:25:24 +0000 - 2015-07-20 10:27:17 +0000]
 - 2. Elasticity Scalding Step: Enrich Raw Events: CANCELLED ~ elapsed time n/a [2015-07-20 10:27:17 +0000 - ]
 - 3. Elasticity S3DistCp Step: Enriched HDFS -> S3: CANCELLED ~ elapsed time n/a [ - ]):
```

I've tried to make it identical to the error messages from the last version.

**Comment by alexanderdean** [comment]
Looks great Fred!

**Comment by rslifka** [comment]
6.0.2 released, will help with some of the error messages you're getting.  Let me know if there's anything else!

**Comment by alexanderdean** [comment]
Thanks so much @rslifka!
