### ISSUE TITLE
Scala Common Enrich: bump user-agent-utils to 1.16

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1905]

**Comment by fblundun** [comment]
Looks like user-agent-utils has moved to Maven Central: http://www.bitwalker.eu/blog/user-agent-utils-now-at-maven-central

So we can also remove the GitHub-hosted repo as a dependency.

**Comment by alexanderdean** [comment]
Nice!

**Comment by fblundun** [comment]
Hey @bogaert , could you give me some of the useragent strings which were resulting in surprising Opera versions so that I can see if version 1.16 of the library makes a difference?

**Comment by bogaert** [comment]
I had another look at the original email, and I'm surprised by the versions
numbers in the GA screenshot (Opera is on version 28 now), so I would
ignore that part of the email. It appears that our parsing was correct in
the past, but the useragent changed when Opera moved to Blink/Chromium.
​
These parse correctly:

Opera/9.80 (Windows NT 6.1) Presto/2.12.388 Version/12.17
Opera/9.80 (Windows NT 6.2; WOW64) Presto/2.12.388 Version/12.17
Opera/9.80 (Android; Opera Mini/8.0.1739/35.6680; U; es) Presto/2.8.119
Version/11.10

These more recent ones return NULL:

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60 (Edition Yx)
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60


Christophe

Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0) 203 589 6116
+44 (0) 7598 006 851

**Comment by fblundun** [comment]
Looks like 1.16 is more effective - it returns `26.0.1656.60` as the browser version for all four of the recent useragent strings you listed.

**Comment by bogaert** [comment]
Thanks @fblundun.
