### ISSUE TITLE
EmrEtlRunner: name the processing bucket in its associated "is not empty" error

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1911]
The error message should explicitly name the processing bucket which is not empty.

Similar to this much more descriptive error:

    Snowplow::EmrEtlRunner::DirectoryNotEmptyError (Should not stage files for enrichment, s3n://snowplow-goldstar-us-west-2-enrichment-output/enriched/good/ is not empty):

**Comment by alexanderdean** [comment]
This can be done in R68 or R70 as you prefer @fblundun !

**Comment by fblundun** [comment]
Might as well keep it in r68...
