### ISSUE TITLE
Scala Kinesis Enrich: add health check endpoint

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1912]
The old description is below - but I think this is an odd architecture, and it would be better to have a passive endpoint inside SKE that any external healthcheck system could use...

### Old description

It is possible to monitor a long-running application using the Consul TTL health check:
- https://groups.google.com/d/msg/consul-tool/22X5_Op_V7A/GioJW27rjlYJ
- https://www.consul.io/docs/agent/checks.html

Take a look here:
- https://consul.io/docs/agent/http/agent.html#agent_check_pass

You want the `/v1/agent/check/{pass,warn,fail}/` endpoints.

Let's assume that our provisioning has registered the check ID.

Therefore the SKE HOCON should contain something like:

``` json
  consul {
    check-id: "xxx"
    get-frequency: x.seconds
  }
```

**Comment by danielzohar** [comment]
That'll be great!

**Comment by alexanderdean** [comment]
Could use HTTP or gRPC or Serf...

**Comment by andrebrov** [comment]
Hi guys, any news on this feature?

**Comment by BenFradet** [comment]
hey @andrebrov , we're going to way of metrics you can read more about it in [our RFC](https://discourse.snowplowanalytics.com/t/observability-for-the-snowplow-streaming-pipeline/1955)

**Comment by sphinks** [comment]
@BenFradet is any news regarding monitoring componenets of Stream Pipeline, especially Stream Enricher.

**Comment by BenFradet** [comment]
We have included a set of metrics in beam-enrich (section "Implementation" in the RFC) and we're planning on doing the same for stream-enrich but there is no clear timeline at this time.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by zoubinirani** [comment]
Why was this closed? Was the feature added?

**Comment by chuwy** [comment]
Hi @zoubinirani. I was migrating all ticket to the new repository for enrich assets and something went wrong with this one (as doesn't show the proper link). Re-created it in https://github.com/snowplow/enrich/issues/243
