### ISSUE TITLE
Scala Hadoop Shred: use BadRow case class from Scala Common Enrich

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1914]
It's duplicated into each Hadoop project currently.

**Comment by fblundun** [comment]
At the moment I think there are 2 versions of this class: one in common enrich which uses Strings and one in hadoop shred which uses ProcessingMessages. Should we standardize on ProcessingMessages for the shared class?

**Comment by alexanderdean** [comment]
Hey Fred - good question. I think we should standardize on ProcessingMessages as they are richer...

**Comment by fblundun** [comment]
Sounds good!
