### ISSUE TITLE
64 Palila stuck in hadoop processing - S3DistCp Step: Enriched HDFS -> S3

### ISSUE THREAD

**Issue by EZWrighter** [snowplow/snowplow#1916]
Processing a very small amount of data, stuck for > 18 hours.

Stdout/err show nothing, but syslog ends with this:

2015-07-20 01:22:00,265 INFO org.apache.hadoop.mapred.JobClient (main):  map 0% reduce 0%
2015-07-20 01:22:29,412 INFO org.apache.hadoop.mapred.JobClient (main):  map 100% reduce 0%
2015-07-20 01:22:49,548 INFO org.apache.hadoop.mapred.JobClient (main):  map 100% reduce 33%
2015-07-20 01:22:58,591 INFO org.apache.hadoop.mapred.JobClient (main):  map 100% reduce 66%

I forced manual termination of cluster and I am re-running after resetting logs from processing, and cleaning up out.events.  I will report if it processes normally from there.

**Comment by EZWrighter** [comment]
It processed normally in 16 minutes on reprocessing.  But still concerning that the EMR gets stuck for so long.

**Comment by alexanderdean** [comment]
Hey Eric - yes, sometimes S3DistCp hangs indefinitely. It's very unpredictable who it happens to (we have very rarely seen it among our Managed Service customers; there are some community members who experience it regularly). Please capture the logs for the hung jobflow and share it with your AWS support contact. Closing as this is a S3DistCp issue.

**Comment by EZWrighter** [comment]
Thanks Alex...I assumed it might be.  Just wanted to make sure you guys were aware.

**Comment by alexanderdean** [comment]
No problem, always good to raise things like this.
