### ISSUE TITLE
Documentation: update Scala Stream Collector setup instructions

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1917]
This page needs updating: https://github.com/snowplow/snowplow/wiki/Configure-the-Scala-Stream-Collector

Following this release: https://github.com/snowplow/snowplow/commit/c0b9d0d2ad492c5bf6ccc1f33440055e836e8dbb

**Comment by ihortom** [comment]
@alexanderdean - I don't really see what needs to be updated here. The mentioned release addresses addition of the `bad` stream which is already referenced in the doc? Anything specific which I missed?

**Comment by alexanderdean** [comment]
I think you're right - this has already been done, closing...
