### ISSUE TITLE
Stream Enrich: make partition key for enriched event stream user-configurable

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1924]
Widened the scope of this ticket following: http://discourse.snowplowanalytics.com/t/partition-key-for-kinesis/849

**Was: partition enriched event stream on event_id ready for de-duplication**

If we have the enriched event stream partitioned by event ID, then we can build a minimal-state\* de-duplication engine as a library*\* for embedding in KCL apps.

/cc @fblundun, @bogaert 

\* Not stateless. It will need to store event IDs and event fingerprints in DynamoDB to de-dupe across micro-batches.

*\* De-duplication as a KCL app doesn't work for natural duplicates, because the KCL app can itself introduce natural duplicates. You literally have to embed this library into whatever functionality cares about there being no duplicates.

**Comment by bogaert** [comment]
That sounds good.

Natural copies will have the same fingerprint, so that case is covered. What are the options when it comes to dealing with synthetic copies (in particular: same event ID, different event)? The first event will have passed through, but we might want to exclude it from analysis as well because something fishy is going on.

**Comment by alexanderdean** [comment]
That's a really good point - with a mobile network's adult content detector, the first event is the synthetic copy, it's the second event which is the "true" event. But the first event will have already passed through and been e.g. sunk to Redshift. Needs further thought!

**Comment by pkallos** [comment]
What type of de-duplication window are you exploring? 2 mins? 2 hours?

Depending on the window size, this may be a good opportunity to explore Spark Streaming to process batches and do the event de-duplication within a trailing window of time, might avoid the complication of persisting to DynamoDB.

**Comment by alexanderdean** [comment]
> What type of de-duplication window are you exploring? 2 mins? 2 hours?

We haven't looked at the time duplication of dupes yet, but it's pretty easy to imagine a pair of dupes which are 14 hours apart (send event, get on SF->LHR flight, land, send dupe).

The trouble with using Spark Streaming for de-duplication (vs using it for e.g. identity stitching or sessionization) is that we have to write the de-duplicated output somewhere, and if we write it to Kinesis then we are immediately introducing dupes again. My hunch is that de-duplication needs to be available as a library to be embedded inside any Kinesis app which actually cares about duplicates. For example: the hypothetical Kinesis Redshift Sink would embed this de-duplication library so that no duplicates are written to Redshift...

**Comment by pkallos** [comment]
>The trouble with using Spark Streaming for de-duplication (vs using it for e.g. identity stitching or sessionization) is that we have to write the de-duplicated output somewhere, and if we write it to Kinesis then we are immediately introducing dupes again.

Ah I see, good point :)

**Comment by alexanderdean** [comment]
Only loosely related, but we have actually implemented our first dedupe code here: #2246
