### ISSUE TITLE
EmrEtlRunner: add support for Amazon EMR 4.x.x series

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1926]
https://aws.amazon.com/about-aws/whats-new/2015/07/amazon-emr-release-4-0-0-with-new-versions-of-apache-hadoop-hive-and-spark-now-available/

**Comment by derdeka** [comment]
As Amazon does not support AMI 3.7 [#1959](https://github.com/snowplow/snowplow/issues/1959) for new clusters at any locations anymore and 3.8 [#1834](https://github.com/snowplow/snowplow/issues/1834) will not be supported, what is the current workaround to get emrrtlrunner running?

**Comment by alexanderdean** [comment]
Hi @derdeka ! The shred probably may have been fixed in R71. Do you want to try R71 (or R72) in 3.9.0 and report back?

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by alexanderdean** [comment]
Blocked by https://github.com/rslifka/elasticity/issues/121

**Comment by robert2d** [comment]
fixed in https://github.com/rslifka/elasticity/pull/120 but yet to be merged
