### ISSUE TITLE
Prevent sample hocons from being added to jar file

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1934]
This would make the jar slightly smaller for Kinesis Enrich, ES Sink, and S3 Sink.

**Comment by alexanderdean** [comment]
Sounds wise

**Comment by fblundun** [comment]
Moving these files will cause links to the example configuration will break. But I think it's still worth it - if we leave them in `src/main/resources` it looks as though they are meant to go in the final jar. I think we should give each subproject a directory named "examples" and move the corresponding example hocon there.

The alternative is to configure sbt not to include them, using something like `unmanagedResourceDirectories in Compile := Nil`.

**Comment by alexanderdean** [comment]
Completely agree - I think it's odd having example files in resources...

**Comment by fblundun** [comment]
I have split this into #2566, #2567, and #2568.
