### ISSUE TITLE
EmrEtlRunner: add `lint` command which validates Iglu resolver and enrichments

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1946]
Basic algorithm:
1. Lint iglu-resolver.json using the embedded schema repo
2. Configure full Iglu client using iglu-resolver.json
3. Lint enrichments using #2

**Comment by alexanderdean** [comment]
Depends on a new iglu-ruby-client: https://github.com/snowplow/iglu-ruby-client

**Comment by alexanderdean** [comment]
Storage target linting dependent on release of R88 (@chuwy's)

**Comment by BenFradet** [comment]
Should this be broken down into two commands:

- `lint resolver`
- `lint enrichments`

?

**Comment by alexanderdean** [comment]
Hey @BenFradet - that sounds good I think. Do we add `lint all` to simplify things for a CI/CD script?

**Comment by BenFradet** [comment]
We could, would we need `generate all` as well for #3105 ?

**Comment by alexanderdean** [comment]
Yep that would be nice

**Comment by BenFradet** [comment]
follow up #3364
