### ISSUE TITLE
Scala Hadoop Enrich: bad rows for Thrift payloads should contain the original 

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1950]
Kinesis Enrich will base 64 encode the original Thrift bytes and use the resulting string as the "line" field of the BadRow class.

But it looks like Hadoop Enrich just calls `toString` on the ByteArray, resulting in:

```
{"line":"[B@f102b98","errors":["Error deserializing raw event: Cannot read. Remote side has closed. Tried to read 2 bytes, but only got 0 bytes. (This is often indicative of an internal error on the server side. Please check your server logs.)"]}
```

**Comment by alexanderdean** [comment]
Good catch!

**Comment by derdeka** [comment]
Same problem here. This make it impossible to debug why data is invalid. We have millions of this lines:
{"line":"[B@c4ba42b","errors":["error: instance type (object) does not match any allowed primitive type

**Comment by alexanderdean** [comment]
Right - this will be fixed in R72.

**Comment by fblundun** [comment]
This is going into r71.
