### ISSUE TITLE
Scala Stream Collector: java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1955]
https://groups.google.com/forum/#!topic/snowplow-user/aTFlfPGk_oo

**Comment by jbeemster** [comment]
Ideas on how to recreate:

* Run the collector without an ELB in front

**Comment by BenFradet** [comment]
isn't this just a matter of raising the number of open files on the machine?

**Comment by jbeemster** [comment]
It is yes @BenFradet nothing that can be done apart from maybe raising a helpful error stating that fact?

**Comment by BenFradet** [comment]
yup, maybe

**Comment by BenFradet** [comment]
On second thought, I think inspecting the exception and providing a better message is quite clumsy and I don't think it's that useful, wdyt?

**Comment by knservis** [comment]
@jbeemster What are these files? What is creating them?

**Comment by BenFradet** [comment]
they're incoming connections

**Comment by BenFradet** [comment]
Descheduling and labelling as won't fix, this error is widely known and it's not worth the trouble.
