### ISSUE TITLE
Scala Common Enrich: new enrichment to derive an event fingerprint

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#1965]
It would be helpful to have an event fingerprint that is generated using all client-sent fields (except perhaps device timestamp, maybe others - TBD). This can perhaps be done as a Javascript enrichment?

This would be helpful because the unstructured event and context fields need to be taken into account  when distinguishing between natural and synthetic duplicates. In Redshift, joining these tables is tricky because event ID is duplicated, and the JSON columns will be removed from atomic.events in a future version.

Interested in hearing thoughts on this.

**Comment by alexanderdean** [comment]
This is a great idea! I would say this should be a new enrichment which outputs a dedicated new JSON. We need to come up with a good hashing algorithm. Assigning to @fblundun - Fred if we can get this into R71 that would be amazing...

**Comment by alexanderdean** [comment]
Update: in the short-term this needs to go into atomic.events itself. This is because currently deduping is done in Redshift, and if this is in a separate table (a shredded context) then we have a chicken-and-egg situation where we have to join to dedupe, but we can't join because we have dupes.

**Comment by fblundun** [comment]
This can indeed go into r71.

The fields set by the client in the querystring are listed [here](https://github.com/snowplow/snowplow/blob/3b8cfcca39a1df1cd77247ff78a149c8239b2fd5/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L110-L189).

We can calculate the hash based on all of those fields, possibly minus some subset. `user_ipaddress` can be set either in the querystring or based on the actual origin of the event. Similarly, the `page_url` field set from the querystring can be overriden based on the Cloudfront log's referer field. So maybe these fields should be excluded.

**Comment by alexanderdean** [comment]
Thanks @fblundun - with `user_ipaddress` and `page_url`, how difficult would it be to access the original QS values when generating the hash. I.e. think of it as a very "early" enrichment...

**Comment by bogaert** [comment]
Thanks @fblundun. I would only exclude `dvce_sent_tstamp`, unless there's anything I missed.

**Comment by alexanderdean** [comment]
Why would you exclude `dvce_sent_tstamp`?

**Comment by alexanderdean** [comment]
Makes sense

**Comment by fblundun** [comment]
OK - sounds like we are going to just calculate a hash based on the original querystring / post body hash, minus stm (which corresponds to dvce_sent_tstamp)

**Comment by alexanderdean** [comment]
That sounds right to me. Note that if the same event is sent by two different tracker instances, there is a good chance the fingerprints will **not** match (because e.g. different `tna`s, or different auto-attached contexts), but think this is unavoidable...

**Comment by alexanderdean** [comment]
For this enrichment, I think let's have a couple of configuration options:

```
  "hashAlgorithm": "xxx"
  "excludeParameters": ["stm"]
```

Obviously we will only support one hash algorithm for launch.
