### ISSUE TITLE
Placeholder for adding true_timestamp

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1968]
Quick points:

* true_timestamp is for when the instrumentor knows the real timestamp for the events being sent
* true_timestamp != device_created timestamp
* There should be a flag in a given tracker to specify whether a user-specified timestamp should be the true timestamp or device-created
* If true_timestamp is set, this should be used for the derived timestamp

**Comment by fblundun** [comment]
Would this be a new field in atomic.events, or would the true timestamp just go directly into the derived_tstamp field?

**Comment by alexanderdean** [comment]
I think it would be a new field **and** fed into derived_tstamp

**Comment by alexanderdean** [comment]
Note on this:

> There should be a flag in a given tracker to specify whether a user-specified timestamp should be the true timestamp or device-created

When a tracker has an event builder pattern, we can make the specification of true timestamp versus device-created on a per track() basis, which will be more elegant.
