### ISSUE TITLE
Run JavaScript Enrichment after all other derived contexts have been added to the event

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1973]
That way the user's JS can access derived contexts such as the ua-parser context.

What do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
I think that's a good idea!

**Comment by alexanderdean** [comment]
This becomes more important as more contexts move into derived_contexts (hence milestone).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/247
