### ISSUE TITLE
Redshift: rename dvce_tstamp to dvce_created_tstamp

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1993]
@alexanderdean - I can't remember whether we decided to do this?

**Comment by alexanderdean** [comment]
Hey @fblundun - thanks for checking in on this. I think given that we can do a `alter table atomic.events
rename dvce_tstamp venueseats to dvce_created_tstamp;`, we should go ahead and clean this up.

(If Redshift didn't support col renames, I would have pushed this back to the non-additive Redshift milestone, https://github.com/snowplow/snowplow/milestones/atomic.events%200.8.0)
