### ISSUE TITLE
Documentation: update tracker status table

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#1999]
https://github.com/snowplow/snowplow/tree/master/1-trackers

I think this is out of date - e.g. isn't the Android Tracker production-ready now?

**Comment by fblundun** [comment]
Sister of #1975

**Comment by fblundun** [comment]
Does a commit exist for this?

**Comment by alexanderdean** [comment]
Not yet - if you could add that would be great. I said to @ihortom yesterday that we could mark all trackers as prod ready apart from AS3 and Unity, which we should flag as beta...

**Comment by fblundun** [comment]
I have done this.
