### ISSUE TITLE
Add event-specific validation to Scalding ETL

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#200]
We need to augment the standard ETL with event-type-specific validations.

For example, if `e=se` (structured event), then we should check that we have a category and action field set too, and if not then we should error the row.

Suggest in the `Enrichment Manager`, once we have disassembled the tracker payload, we add a final step that validates that the row makes "sense" given the event type.

/cc @yalisassoon

**Comment by chuwy** [comment]
This will be implemented by #2260
