### ISSUE TITLE
Snowplow CLI: auto-adjust node Heap using instance type

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2000]
We can potentially increase Heap using the instance type:

``` ruby
@jobflow.add_bootstrap_action(Elasticity::HadoopBootstrapAction.new('-m', 'mapred.child.java.opts=-Xmx4G'))
```

Thoughts @epantera?

**Comment by epantera** [comment]
Hey @alexanderdean 

seems that the following approach is an elegant way to tune JVM;

**1) Create a custom bootstrap script file hosted in S3**

eg: `s3://viadeo-snowplow-processing/bootstrap-actions/snowplow-emr-customize-heap-size.sh` with content :
```sh
#!/bin/sh
/usr/share/aws/emr/scripts/configure-hadoop -m mapred.child.java.opts=-Xmx2G
```

**2) Declare the custom bootstrap action script in the snowplow config file**
```
:emr:
  ...
  :bootstrap:
    - s3://viadeo-snowplow-processing/bootstrap-actions/snowplow-emr-customize-heap-size.sh
```


Simple and non intrusive - works well for us.

**Comment by alexanderdean** [comment]
Awesome - thanks for sharing Eric!

**Comment by bhattdeepak90** [comment]
This approach is not working for AMI version 4.3.0, can you please suggest any other method to increase java heap space.

The error I am getting is : "/mnt/var/lib/bootstrap-actions/1/emr-customize-bootsize_unix.sh: line 2: /usr/share/aws/emr/scripts/configure-hadoop: No such file or directory".

I think the script configure-hadoop which we are trying to access is not available in this AMI version. Please share the workaround.

Thanks!
Deepak Bhatt

**Comment by rbolkey** [comment]
Also running into this on AMI version 4.5.0, and getting the error that @bhattdeepak90 is seeing.

**Comment by BenFradet** [comment]
done through spark settings, closing
