### ISSUE TITLE
Common: add tests for subprojects other than Scala Common Enrich to .travis.yml

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2001]

**Comment by alexanderdean** [comment]
Good idea! How easy do you think this will be to do?

**Comment by fblundun** [comment]
It shouldn't be too hard - we just need to publishLocal CommonEnrich before we do the tests for projects which have it as a dependency. I can't think of any other obstacles at the moment...

**Comment by fblundun** [comment]
Moving back since I think there's enough in r73 already.

**Comment by BenFradet** [comment]
this is done, closing
