### ISSUE TITLE
Scala Common Enrich: add Shopify webhooks

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2008]
https://docs.shopify.com/api/webhooks/using-webhooks

**Comment by alexanderdean** [comment]
Great idea! Here's the wiki page to get you started: https://github.com/snowplow/snowplow/wiki/How-to-integrate-a-webhook-into-Snowplow

**Comment by alexanderdean** [comment]
(Note that adding webhooks to Snowplow is much, much simpler now that Schema Guru exists.)

**Comment by christoph-buente** [comment]
@alexanderdean How would i start collecting JSON instances in the first place in the simplest way? Is there a piece of software to take POST requests and dump the JSON body payload to an S3 bucket? Or is this supported by AWS out of the box? Can you point me to a starting point to read on this?

**Comment by alexanderdean** [comment]
Hey @christoph-buente - my suggestion would be to setup a Snowplow Clojure Collector in Beanstalk, then you'll get all the files landing in S3.

A nice trick is to do the POST to `<<collector_uri>>/com.shopify/v1`, because that means that later you can use these same log files to test the webhook adapter running inside your Snowplow code.

**Comment by christoph-buente** [comment]
Ok, i set it up and registered several webhooks. Mainly add-to-cart, update-cart, create-customer, update-customer.

Now i get logs. I think we are interested in those types of logs: ```_var_log_tomcat8_rotated_localhost_access_log.txt1449763262```

Is it wise to have a separete url for every web hook action like mentioned above? Like this http://<<endpoint>>/com.shopify/cart-create-v1 and http://<<endpoint>>/com.shopify/order-create-v1

And then i strip out the column with base64 encoded JSON payload and pass it to the schema guru? So i end up with a separate schema per webhook pub/sub topic?

**Comment by alexanderdean** [comment]
Probably no need to have a separate URI for each webhook action - check out Schema Guru's schema-by CLI argument, which lets you use a property of each JSON instance to determine which JSON Schema this specific instance should help to derive.

> And then i strip out the column with base64 encoded JSON payload and pass it to the schema guru? 

Yes you will need to do that. Depending on volumes, you could write a shell script or Hadoop job to extract the payloads...

**Comment by christoph-buente** [comment]
Ok, i'll keep collecting data now. But in the end i will have a schema for every singe webhook topic?

```schemas/com.shopify/create_cart/jsonschema/1-0-0```
```schemas/com.shopify/update_cart/jsonschema/1-0-0```
```schemas/com.shopify/create_order/jsonschema/1-0-0```
```schemas/com.shopify/update_order/jsonschema/1-0-0```

And so on? Now then what? How can i turn those schemas into a valid webhook implementation?

**Comment by alexanderdean** [comment]
Correct - you'll have a schema for each webhook event type. Once you've got your schemas ready to go, open the PR into Iglu Central and we can then arrange some time on the phone to talk you through the Scala webhook adapter part of what's needed.

**Comment by christoph-buente** [comment]
Awesome, thx a bunch

**Comment by alexanderdean** [comment]
How's it going @christoph-buente - have you had any luck schema'ing the Shopify webhooks?

**Comment by christoph-buente** [comment]
Hi @alexanderdean i'm still collecting, not sure if i have enough data from my own shop. Is there a rule of thumb how many events i need to see for a given endpoint?

**Comment by alexanderdean** [comment]
Good question! It really depends on how complex the webhooks look to be, and how many edge cases they might have...

**Comment by christoph-buente** [comment]
I collected over 27MB if gzipped event data now. The problem i see now: How can i see from the request, to which webhook endpoint this request belongs? A typical event looks like this:

> 2016-02-21	21:23:00	-	-	23.227.xxx.xxx	POST	23.227.xxx.xxx	/com.shopify/v1	200	-	Ruby	&cv=clj-1.1.0-tom-0.2.0&nuid=7ccf5558-4b87-45a5-b3e5-91bd42c4ba2d	-	-	-	application%2Fjson	eyJjcmVhdGVkX2F0IjoiMjAxNi0wMi0yMVQyMToyMzowMC4wNzFaIiwidXBkYXRlZF9hdCI6IjIwMTYtMDItMjFUMjE6MjM6MDAuMDcxWiIsImlkIjoiYTI4NDI5NGU3NjM3ZTMxYTlkYjI3Mzg1MDg4MTdkNDIiLCJ0b2tlbiI6ImEyODQyOTRlNzYzN2UzMWE5ZGIyNzM4NTA4ODE3ZDQyIiwibGluZV9pdGVtcyI6W3siaWQiOjE0MjM1NzkyMzI3LCJwcm9wZXJ0aWVzIjpudWxsLCJxdWFudGl0eSI6MSwidmFyaWFudF9pZCI6MTQyMzU3OTIzMjcsInRpdGxlIjoiQmlvIEVkZWxzY2hpbW1lbC1TYWxhbWkgdm9tIFNhdHRlbHNjaHdlaW4gLSBTY2h3ZWluIDIxMyBcLyAxODAgZyIsInByaWNlIjoiOS45MCIsImxpbmVfcHJpY2UiOiI5LjkwIiwidG90YWxfZGlzY291bnQiOiIwLjAwIiwiZGlzY291bnRzIjpbXSwic2t1IjoiRWRlbFNhLUhTVC1SUy1TTjIwMy0xODAiLCJncmFtcyI6MTkwLCJ2ZW5kb3IiOiJCYXVlciBIZW5yaWsgU3RhYXIiLCJwcm9kdWN0X2lkIjozNTk3MTY4MDcxLCJnaWZ0X2NhcmQiOmZhbHNlfV19

As i setup the webhooks to use the very same collector endpoint path, i cannot see what type of event i'm looking at. Is there a way of figuring out?

Thx, Christoph

**Comment by alexanderdean** [comment]
Hey @christoph-buente - almost always, a webhook event payload will contain some field in it which tells you the event type. I've decoded your attached Base64 payload, and I can't see the event type. This is very unusual.

Do you agree that Shopify event payloads don't seem to specify what type of event they are? In that case, we may need to revert to an approach where you specify the path to each event type separately, eg:

```
<<collector_uri>>/com.shopify/v1/add-to-cart
<<collector_uri>>/com.shopify/v1/create-customer
<<collector_uri>>/com.shopify/v1/...
```

What do you think @christoph-buente ?

**Comment by christoph-buente** [comment]
The payload is very different, depending on the type of event. So an actual transaction event is much longer and contains address, lineitems and transaction information.

So i guess my initial approach would have saved us a bit time. Ok, I'll setup the webhooks accordingly and delete old data.

**Comment by alexanderdean** [comment]
Yes, sorry - that is a little unusual of the Shopify guys (haven't seen it before)...

**Comment by christoph-buente** [comment]
Ok, i setup a little processing tool for all the log files. But i have an issue with some JSON files. When i try to base64 decode the log file, sometime parts of the JSON object is missing. Can i configure the clojure collector to not base64 encode in the log files?

This is how i create all the schemas:

    ./schema-guru-0.5.0 schema \
    --enum 20 \
    --vendor com.shopify \
    --name $name \
    --output schemas/$name \
    $directory

Here is an example of the output. Would that be something useful?

[create-cart.txt](https://github.com/snowplow/snowplow/files/148908/create-cart.txt)

**Comment by alexanderdean** [comment]
Hey @christoph-buente - this is an excellent start! The best next step is to open a PR into Iglu Central with all of these schemas, so we can review them.

The most important thing to do will be for you to manually inspect the JSON Schemas and tune them by hand - basically if you don't have a huge sample size of JSONs to feed into Schema Guru, then the JSON Schemas generated will tend to be a bit over-prescriptive. For example:

```json
          "vendor" : {
            "type" : "string",
            "minLength" : 17,
            "maxLength" : 29,
            "enum" : [ "Bauer Henrik Staar", "Bauer Bernd Schulz", "Bauer Jasper Metzger Petersen", "Bäuerin Kirsten Hänsel", "Bauer Hanno Offen" ]
          },
```

You probably want to "relax this" to become:

```json
          "vendor" : {
            "type" : "string",
            "maxLength" : 256
          },
```

But yes - this is a great start. Exciting!

**Comment by christoph-buente** [comment]
Thx for the feedback. Any idea about the non decodable base64 encoded text?

`eyJpZCI6NDEwMjIwNzExMSwidGl0bGUiOiJCaW8tQnJhdGVuIHZvbSBTYXR0ZWxzY2h3ZWluIChLZXVsZSkiLCJib2R5X2h0bWwiOiJcdTAwM2NwXHUwMDNlQnJhdGVuIGF1cyBkZXIgS2V1bGUgKG9obmUgS25vY2hlbikgdm9tIFNhdHRlbHNjaHdlaW4sIGdlc2Nob3NzZW4gYXVmIGRlciBXZWlkZSB2b24gR3V0IEhpcnNjaGF1ZTogRWluIFRyYXVtIGbDvHIgamVkZW4gYmVXdXJzdGVuIEdlbmllw59lciFcdTAwM2NcL3BcdTAwM2Vcblx1MDAzY3BcdTAwM2VcdTAwM2NzdHJvbmdcdTAwM2VBQ0hUVU5HOlx1MDAzY1wvc3Ryb25nXHUwMDNlwqBWZXJzYW5kIGltIElzb2xpZXJrYXJ0b24gbWl0IEvDvGhsZ2VsLVBhZHMgYW0gRG9ubmVyc3RhZywgMjUuMDIuMjAxNiEgRHUgbXVzc3Qgc2ljaGVyc3RlbGxlbiwgZGFzcyBkdSBkYXMgUGFrZXQgYW0gMjYuMDIuMjAxNiBlbnRnZWdlbiBuZWhtZW4ga2FubnN0ICg5NSUgYWxsZXIgREhMLVBha2V0ZSBrb21tZW4gYW0gbsOkY2hzdGVuIFRhZyBhbiwgZGllIEvDvGhsdW5nIGltIEthcnRvbiBow6RsdCBjYS4gNDggU3R1bmRlbilcdTAwM2NcL3BcdTAwM2Vcblx1MDAzY3BcdTAwM2VHZWvDvGhsdCBtaW5kZXN0ZW5zIGhhbHRiYXIgYmlzIDA1LjAzLjIwMTYuXHUwMDNjXC9wXHUwMDNlXG5cdTAwM2NwXHUwMDNlXHUwMDNjaW1nIGFsdD1cIlwiIHNyYz1cImh0dHBzOlwvXC9jZG4uc2hvcGlmeS5jb21cL3NcL2ZpbGVzXC8xXC8xMDc2XC80MzEwXC9maWxlc1wvYmlvX3NtYWxsLmpwZz8zMTA0Mzc1NzEyNTc0NzQ2NjY0XCJcdTAwM2VcdTAwM2NpbWcgYWx0PVwiXCIgc3JjPVwiaHR0cHM6XC9cL2Nkbi5zaG9waWZ5LmNvbVwvc1wvZmlsZXNcLzFcLzEwNzZcLzQzMTBcL2ZpbGVzXC9FVV9CaW9Mb2dvX3NtYWxsLmpwZz8zMTA0Mzc1NzEyNTc0NzQ2NjY0XCJcdTAwM2VcdTAwM2NcL3BcdTAwM2Vcblx1MDAzY3BcdTAwM2VERS3DlktPLTAzOVx1MDAzY1wvcFx1MDAzZVxuXHUwMDNjcFx1MDAzZVByZWlzXC9LZzogMjksMDAg4oKsIChpbmtsLiBNd1N0LilcdTAwM2NcL3BcdTAwM2Vcblx1MDAzY3BcdTAwM2VWZXJzYW5kOiA3LDkwIOKCrFx1MDAzY1wvcFx1MDAzZSIsInZlbmRvciI6IkJhdWVyIEhlbnJpayBTdGFhciIsInByb2R1Y3RfdHlwZSI6IkZyaXNjaGZsZWlzY2giLCJjcmVhdGVkX2F0IjoiMjAxNi0wMS0yMVQxMzo0Njo1NCswMTowMCIsImhhbmRsZSI6ImJpby1rZXVsZS12b20tc2F0dGVsc2Nod2Vpbi1vaG5lLWtub2NoZW4iLCJ1cGRhdGVkX2F0IjoiMjAxNi0wMi0yM1QxNzo1NDozOCswMTowMCIsInB1Ymxpc2hlZF9hdCI6bnVsbCwidGVtcGxhdGVfc3VmZml4IjpudWxsLCJwdWJsaXNoZWRfc2NvcGUiOiJ3ZWIiLCJ0YWdzIjoiU2Nod2VpbiIsInZhcmlhbnRzIjpbeyJpZCI6MTQwNzA5ODg5OTksInByb2R1Y3RfaWQiOjQxMDIyMDcxMTEsInRpdGxlIjoiOTIwIGciLCJwcmljZSI6IjI2LjY4Iiwic2t1IjoiQmlvS2V1LUhTVC1GRi1TTlgtOTIwIiwicG9zaXRpb24iOjEsImdyYW1zIjoxMDAwLCJpbnZlbnRvcnlfcG9saWN5IjoiZGVueSIsImNvbXBhcmVfYXRfcHJpY2UiOm51bGwsImZ1bGZpbGxtZW50X3NlcnZpY2UiOiJtYW51YWwiLCJpbnZlbnRvcnlfbWFuYWdlbWVudCI6InNob3BpZnkiLCJvcHRpb24xIjoiOTIwIGciLCJvcHRpb24yIjpudWxsLCJvcHRpb24zIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAxNi0wMS0yMVQxMzo0OToyMSswMTowMCIsInVwZGF0ZWRfYXQiOiIyMDE2LTAyLTIzVDE3OjUzOjMwKzAxOjAwIiwicmVxdWlyZXNfc2hpcHBpbmciOnRydWUsInRheGFibGUiOnRydWUsImJhcmNvZGUiOiIiLCJpbnZlbnRvcnlfcXVhbnRpdHkiOjEsIm9sZF9pbnZlbnRvcnlfcXVhbnRpdHkiOjEsImltYWdlX2lkIjpudWxsLCJ3ZWlnaHQiOjEuMCwid2VpZ2h0X3VuaXQiOiJrZyJ9LHsiaWQiOjE2NDk1MDEwMTgzLCJwcm9kdWN0X2lkIjo0MTAyMjA3MTExLCJ0aXRsZSI6IjY4MCBnIiwicHJpY2UiOiIxOS43MiIsInNrdSI6IkJpb0tldS1IU1QtRkYtU05YLTY4MCIsInBvc2l0aW9uIjoyLCJncmFtcyI6MTAwMCwiaW52ZW50b3J5X3BvbGljeSI6ImRlbnkiLCJjb21wYXJlX2F0X3ByaWNlIjpudWxsLCJmdWxmaWxsbWVudF9zZXJ2aWNlIjoibWFudWFsIiwiaW52ZW50b3J5X21hbmFnZW1lbnQiOiJzaG9waWZ5Iiwib3B0aW9uMSI6IjY4MCBnIiwib3B0aW9uMiI6bnVsbCwib3B0aW9uMyI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMTYtMDItMjNUMTc6NTI6MDkrMDE6MDAiLCJ1cGRhdGVkX2F0IjoiMjAxNi0wMi0yM1QxNzo1MzozMCswMTowMCIsInJlcXVpcmVzX3NoaXBwaW5nIjp0cnVlLCJ0YXhhYmxlIjp0cnVlLCJiYXJjb2RlIjoiIiwiaW52ZW50b3J5X3F1YW50aXR5IjoxLCJvbGRfaW52ZW50b3J5X3F1YW50aXR5IjoxLCJpbWFnZV9pZCI6bnVsbCwid2VpZ2h0IjoxLjAsIndlaWdodF91bml0Ijoia2cifV0sIm9wdGlvbnMiOlt7ImlkIjo1MDM0ODExMjA3LCJwcm9kdWN0X2lkIjo0MTAyMjA3MTExLCJuYW1lIjoiR2V3aWNodCIsInBvc2l0aW9uIjoxLCJ2YWx1ZXMiOlsiOTIwIGciLCI2ODAgZyJdfV0sImltYWdlcyI6W3siaWQiOjk3NTI0NDU1MTEsInByb2R1Y3RfaWQiOjQxMDIyMDcxMTEsInBvc2l0aW9uIjoxLCJjcmVhdGVkX2F0IjoiMjAxNi0wMi0yM1QxNzo1NDozOCswMTowMCIsInVwZGF0ZWRfYXQiOiIyMDE2LTAyLTIzVDE3OjU0OjM4KzAxOjAwIiwic3JjIjoiaHR0cHM6XC9cL2Nkbi5zaG9waWZ5LmNvbVwvc1wvZmlsZXNcLzFcLzEwNzZcLzQzMTBcL3Byb2R1Y3RzXC9TY2h3ZWluZUJyYXRlbl9IaXJzY2hhdWUuSlBHP3Y9MTQ1NjI0NjQ3OCIsInZhcmlhbnRfaWRzIjpbXX1dLCJpbWFnZSI6eyJpZCI6OTc1MjQ0NTUxMSwicHJvZHVjdF9pZCI6NDEwMjIwNzExMSwicG9zaXRpb24iOjEsImNyZWF0ZWRfYXQiOiIyMDE2LTAyLTIzVDE3OjU0OjM4KzAxOjAwIiwidXBkYXRlZF9hdCI6IjIwMTYtMDItMjNUMTc6NTQ6MzgrMDE6MDAiLCJzcmMiOiJodHRwczpcL1wvY2RuLnNob3BpZnkuY29tXC9zXC9maWxlc1wvMVwvMTA3NlwvNDMxMFwvcHJvZHVjdHNcL1NjaHdlaW5lQnJhdGVuX0hpcnNjaGF1ZS5KUEc_dj0xNDU2MjQ2NDc4IiwidmFyaWFudF9pZHMiOltdfX0`

translates into this:

`{"id":4102207111,"title":"Bio-Braten vom Sattelschwein (Keule)","body_html":"\u003cp\u003eBraten aus der Keule (ohne Knochen) vom Sattelschwein, geschossen auf der Weide von Gut Hirschaue: Ein Traum für jeden beWursten Genießer!\u003c\/p\u003e\n\u003cp\u003e\u003cstrong\u003eACHTUNG:\u003c\/strong\u003e Versand im Isolierkarton mit Kühlgel-Pads am Donnerstag, 25.02.2016! Du musst sicherstellen, dass du das Paket am 26.02.2016 entgegen nehmen kannst (95% aller DHL-Pakete kommen am nächsten Tag an, die Kühlung im Karton hält ca. 48 Stunden)\u003c\/p\u003e\n\u003cp\u003eGekühlt mindestens haltbar bis 05.03.2016.\u003c\/p\u003e\n\u003cp\u003e\u003cimg alt=\"\" src=\"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/files\/bio_small.jpg?3104375712574746664\"\u003e\u003cimg alt=\"\" src=\"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/files\/EU_BioLogo_small.jpg?3104375712574746664\"\u003e\u003c\/p\u003e\n\u003cp\u003eDE-ÖKO-039\u003c\/p\u003e\n\u003cp\u003ePreis\/Kg: 29,00 € (inkl. MwSt.)\u003c\/p\u003e\n\u003cp\u003eVersand: 7,90 €\u003c\/p\u003e","vendor":"Bauer Henrik Staar","product_type":"Frischfleisch","created_at":"2016-01-21T13:46:54+01:00","handle":"bio-keule-vom-sattelschwein-ohne-knochen","updated_at":"2016-02-23T17:54:38+01:00","published_at":null,"template_suffix":null,"published_scope":"web","tags":"Schwein","variants":[{"id":14070988999,"product_id":4102207111,"title":"920 g","price":"26.68","sku":"BioKeu-HST-FF-SNX-920","position":1,"grams":1000,"inventory_policy":"deny","compare_at_price":null,"fulfillment_service":"manual","inventory_management":"shopify","option1":"920 g","option2":null,"option3":null,"created_at":"2016-01-21T13:49:21+01:00","updated_at":"2016-02-23T17:53:30+01:00","requires_shipping":true,"taxable":true,"barcode":"","inventory_quantity":1,"old_inventory_quantity":1,"image_id":null,"weight":1.0,"weight_unit":"kg"},{"id":16495010183,"product_id":4102207111,"title":"680 g","price":"19.72","sku":"BioKeu-HST-FF-SNX-680","position":2,"grams":1000,"inventory_policy":"deny","compare_at_price":null,"fulfillment_service":"manual","inventory_management":"shopify","option1":"680 g","option2":null,"option3":null,"created_at":"2016-02-23T17:52:09+01:00","updated_at":"2016-02-23T17:53:30+01:00","requires_shipping":true,"taxable":true,"barcode":"","inventory_quantity":1,"old_inventory_quantity":1,"image_id":null,"weight":1.0,"weight_unit":"kg"}],"options":[{"id":5034811207,"product_id":4102207111,"name":"Gewicht","position":1,"values":["920 g","680 g"]}],"images":[{"id":9752445511,"product_id":4102207111,"position":1,"created_at":"2016-02-23T17:54:38+01:00","updated_at":"2016-02-23T17:54:38+01:00","src":"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/products\/SchweineBraten_Hirschaue.JPG?v=1456246478","variant_ids":[]}],"image":{"id":9752445511,"product_id":4102207111,"position":1,"created_at":"2016-02-23T17:54:38+01:00","updated_at":"2016-02-23T17:54:38+01:00","src":"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/products\/SchweineBraten_Hirschaue.JPG?v=1456246478","variant_ids":[]`

Note the missing closing bracket at the end of the JSON string.

**Comment by alexanderdean** [comment]
Looks like some of the payloads might be getting truncated - we have a ticket to investigate this, here #2201

**Comment by christoph-buente** [comment]
Well, if i use this url http://base64decode.com/ and paste in the aforementioned base64 decoded text, it turns out to be fine.

`{"id":4102207111,"title":"Bio-Braten vom Sattelschwein (Keule)","body_html":"\u003cp\u003eBraten aus der Keule (ohne Knochen) vom Sattelschwein, geschossen auf der Weide von Gut Hirschaue: Ein Traum fÃ¼r jeden beWursten GenieÃer!\u003c\/p\u003e\n\u003cp\u003e\u003cstrong\u003eACHTUNG:\u003c\/strong\u003eÂ Versand im Isolierkarton mit KÃ¼hlgel-Pads am Donnerstag, 25.02.2016! Du musst sicherstellen, dass du das Paket am 26.02.2016 entgegen nehmen kannst (95% aller DHL-Pakete kommen am nÃ¤chsten Tag an, die KÃ¼hlung im Karton hÃ¤lt ca. 48 Stunden)\u003c\/p\u003e\n\u003cp\u003eGekÃ¼hlt mindestens haltbar bis 05.03.2016.\u003c\/p\u003e\n\u003cp\u003e\u003cimg alt=\"\" src=\"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/files\/bio_small.jpg?3104375712574746664\"\u003e\u003cimg alt=\"\" src=\"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/files\/EU_BioLogo_small.jpg?3104375712574746664\"\u003e\u003c\/p\u003e\n\u003cp\u003eDE-ÃKO-039\u003c\/p\u003e\n\u003cp\u003ePreis\/Kg: 29,00 â¬ (inkl. MwSt.)\u003c\/p\u003e\n\u003cp\u003eVersand: 7,90 â¬\u003c\/p\u003e","vendor":"Bauer Henrik Staar","product_type":"Frischfleisch","created_at":"2016-01-21T13:46:54+01:00","handle":"bio-keule-vom-sattelschwein-ohne-knochen","updated_at":"2016-02-23T17:54:38+01:00","published_at":null,"template_suffix":null,"published_scope":"web","tags":"Schwein","variants":[{"id":14070988999,"product_id":4102207111,"title":"920 g","price":"26.68","sku":"BioKeu-HST-FF-SNX-920","position":1,"grams":1000,"inventory_policy":"deny","compare_at_price":null,"fulfillment_service":"manual","inventory_management":"shopify","option1":"920 g","option2":null,"option3":null,"created_at":"2016-01-21T13:49:21+01:00","updated_at":"2016-02-23T17:53:30+01:00","requires_shipping":true,"taxable":true,"barcode":"","inventory_quantity":1,"old_inventory_quantity":1,"image_id":null,"weight":1.0,"weight_unit":"kg"},{"id":16495010183,"product_id":4102207111,"title":"680 g","price":"19.72","sku":"BioKeu-HST-FF-SNX-680","position":2,"grams":1000,"inventory_policy":"deny","compare_at_price":null,"fulfillment_service":"manual","inventory_management":"shopify","option1":"680 g","option2":null,"option3":null,"created_at":"2016-02-23T17:52:09+01:00","updated_at":"2016-02-23T17:53:30+01:00","requires_shipping":true,"taxable":true,"barcode":"","inventory_quantity":1,"old_inventory_quantity":1,"image_id":null,"weight":1.0,"weight_unit":"kg"}],"options":[{"id":5034811207,"product_id":4102207111,"name":"Gewicht","position":1,"values":["920 g","680 g"]}],"images":[{"id":9752445511,"product_id":4102207111,"position":1,"created_at":"2016-02-23T17:54:38+01:00","updated_at":"2016-02-23T17:54:38+01:00","src":"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/products\/SchweineBraten_Hirschaue.JPG?v=1456246478","variant_ids":[]}],"image":{"id":9752445511,"product_id":4102207111,"position":1,"created_at":"2016-02-23T17:54:38+01:00","updated_at":"2016-02-23T17:54:38+01:00","src":"https:\/\/cdn.shopify.com\/s\/files\/1\/1076\/4310\/products\/SchweineBraten_Hirschaue.Jÿÿÿv=1456246478","variant_ids":[]}}`

**Comment by alexanderdean** [comment]
Hmm - are you saying it was just a problem with your prior Base64 decoder?

**Comment by christoph-buente** [comment]
Not sure. Neither Linux+Mac commandline, openssl nor ruby clients could decode it successfully. But this online decoder can. But ... it is screwing up the german umlauts with wrong charset.

**Comment by christoph-buente** [comment]
I may found the answer to the faulty files. I have setup the webhook for each possible type of events in shopify like this: ```/com.shopify/v1/update-customer```
And i saw in the log files, that the collector answered with a 404 response code. Yesterday i changed the path to this: ```/com.shopify.v1/update-customer``` Which leads to a 200 status code. And non of those files seem to be corrupted in terms of borked base64 encoded body payload. Maybe that helps.

**Comment by alexanderdean** [comment]
Interesting - the first part makes sense: the collectors are wired to expect /foo/bar, not /foo/bar/bar, so you will get a 404. But the logging is orthogonal to the return code, so I wouldn't expect the 404 to result in a corrupted Base64 entry.

> Neither Linux+Mac commandline, openssl nor ruby clients could decode it successfully

Most of these probably aren't using Url-safe Base64 decoding, which might account for the discrepancy.

**Comment by christoph-buente** [comment]
I also tried the url_safe version from the ruby base64 library. But in case the string could not be parsed correctly it raises an exception. See here: http://ruby-doc.org/stdlib-2.3.0/libdoc/base64/rdoc/Base64.html#urlsafe_decode64-method

At least this way i can assure to have proper JSON object as result.

**Comment by christoph-buente** [comment]
Alright, i sent a PR to see what you think. https://github.com/snowplow/iglu-central/pull/365

**Comment by christoph-buente** [comment]
I have collected the data until today. I have ~6000 valid webhook calls. Some events, like cancel order just happened twice, and some events happened 600+ times. It's not evenly distributed. But i still have the issue with the crippled events from the closure collector. This means at least 30% of the data can not be base64 decoded and is garbage.

**Comment by alexanderdean** [comment]
Hey @christoph-buente - this is a great dataset to get us started! I think we can progress with this - but we will probably want to wait until we have "schema matching" in place before we release it.

I am going to write an RFC on schema inference (of which schema matching is the slightly primitive first step) hopefully soon.

**Comment by christoph-buente** [comment]
@alexanderdean have a look at my PR: https://github.com/snowplow/iglu-central/pull/365

**Comment by alexanderdean** [comment]
Thanks @christoph-buente !

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/163
