### ISSUE TITLE
Scala Kinesis Enrich: add configuration option for directory for database downloads etc

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2009]
At the moment it default to the directory from which Kinesis Enrich is started (may not be the directory which contains Kinesis Enrich), which is confusing.

https://groups.google.com/forum/#!topic/snowplow-user/RyjI8NL9djA

**Comment by fblundun** [comment]
Should the MaxMind database configuration live in the [ip_lookups configuration JSON](https://github.com/snowplow/snowplow/blob/master/3-enrich/config/enrichments/ip_lookups.json)?

**Comment by alexanderdean** [comment]
No this should be an app-wide config of a working directory. It's Kinesis
pipeline specific and orthogonal to any specific enrichment.

A

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/164
