### ISSUE TITLE
Extract ScalazArgs into Scala Common Enrich

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2010]
ScalazArgs is already duplicated in Hadoop Enrich and Hadoop Shred:
https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-shred/src/main/scala/com.snowplowanalytics.snowplow.enrich/hadoop/utils/ScalazArgs.scala
https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/utils/ScalazArgs.scala

And it will be useful in Hadoop Elasticsearch too.

**Comment by fblundun** [comment]
@alexanderdean - looks like notice that only one copy of the file has code for decoding "%3D". Do you know what the point of that is and whether it is necessary?

**Comment by alexanderdean** [comment]
Hey @fblundun - the %3D decoder is an artifact from when Scalding couldn't handle = signs in incoming arguments - it's fine to exorcise.

**Comment by fblundun** [comment]
Thanks Alex!

We can avoid having Scalding as a dependency of Common Enrich by using a structural type in place of `com.twitter.scalding.Args`: https://github.com/snowplow/snowplow/blob/128591c621d73b3c0b26e29ee4e3dd2df640fbf7/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/ScalazArgs.scala#L35-L37

**Comment by alexanderdean** [comment]
So elegant!
