### ISSUE TITLE
Documentation: add new version of Canonical Event Model wiki page for R71

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2018]
Releases which change the Canonical Event Model should create a new version of the [wiki page](https://github.com/snowplow/snowplow/wiki/canonical-event-model) and rename the old copy of the page based on which releases it applies to.

**Comment by alexanderdean** [comment]
@fblundun - has this one been done?

**Comment by fblundun** [comment]
Yes, closing...
