### ISSUE TITLE
Scala Common Enrich: investigate optimizing JavaScript enrichment

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2023]
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Optimization
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Requirements_and_Limitations

**Comment by alexanderdean** [comment]
Good thinking...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/165
