### ISSUE TITLE
Data modeling: rename dvce_tstamp to dvce_created_tstamp 

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#2024]
Related to #1993.

**Comment by bogaert** [comment]
@fblundun dvce_tstamp is now also renamed in the SQL queries.

**Comment by fblundun** [comment]
Thanks! Can I just cherry-pick this commit? https://github.com/snowplow/snowplow/commit/e95c262cede627edaec1b04ef17cfaf70041dce8
