### ISSUE TITLE
For discussion: turn ecommerce transactions into one event

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#203]
Currently, tracking an ecommerce transaction is transmitted, ETLed and stored as multiple events:
- 1 event for the transaction itself
- 1 event for each transaction item

In an Avro world, it might be cleaner just to send one event, which is a fatter envelope containing the transaction plus transaction items.

This would be dependent on:
1. Using Avro
2. The hub-and-spoke architecture in Redshift (events -> transactions -> transaction_items)
3. Add support for sending event as multiple GETs #20
4. Coming up with a way of expressing N transaction items within the tracker protocol (maybe moving to a full-JSON envelope)

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/228
