### ISSUE TITLE
Placeholder: convert all Kinesis app bad rows to use processing messages

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2031]

**Comment by alexanderdean** [comment]
Believe this is a dupe and can be closed...

**Comment by fblundun** [comment]
Note that the SSC and SKE both have a "size" field in their bad row JSONs. This probably means we should change the BadRow class in SCE to include this field.

**Comment by alexanderdean** [comment]
What is the "size" field - do you have a link to it @fblundun ?

**Comment by fblundun** [comment]
https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-kinesis-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sources/AbstractSource.scala#L108-L109

https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/utils/SplitBatch.scala#L130-L131

When discussing how to handle events which are too large for Kinesis, we realised that we couldn't put the whole bad event in the error JSON, so we added a size field saying how large it is instead.

**Comment by fblundun** [comment]
This was split into #1207 #2006 #2419
