### ISSUE TITLE
Scala Hadoop Enrich: write out Avro format instead of TSV

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2034]

**Comment by andrioni** [comment]
:+1:

**Comment by alexanderdean** [comment]
Initial format likely to be something like:

```json
{
  "schema": "xxx",
  "data": {
    "version": "x.x.x"
    "value": "xxx"
  }
}
```

**Comment by andrioni** [comment]
And then use a JSONPaths file to map it to the table schema? Sounds nice.

**Comment by ajitkshirsagar** [comment]
Is this is feature planned for the roadmap?

**Comment by BenFradet** [comment]
We are thinking of adopting a new format for the enriched data but we don't have a timeline yet.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/248
