### ISSUE TITLE
Scala Kinesis Enrich: write out Avro format rather than TSV

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2035]

**Comment by fblundun** [comment]
For reference, some code which can be used to serialize Avro to a string or byte array (e.g. prior to sending it to Kinesis): https://gist.github.com/fblundun/98e1892a9d8068e765c7

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/249
