### ISSUE TITLE
Scala Common Enrich: remove JSON length checks from EnrichmentManager

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2041]

**Comment by alexanderdean** [comment]
Suggest splitting in two: 1) remove JSON length checks, 2) move truncation code to shredder

**Comment by fblundun** [comment]
r72 will move some shredder logic into common enrich to get the event name, vendor, etc from unstructured event JSONs. As a side effect this will check whether unstructured events are valid JSONs. Should we continue to check whether contexts are valid JSONs in common enrich, or should that be the responsibility of later parts of the pipeline (currently hadoop shred and kinesis es sink)?

**Comment by fblundun** [comment]
One benefit of doing this check is that we could make common enrich's output slightly smaller by removing unnecessary whitespace from JSONs.

**Comment by alexanderdean** [comment]
Validating contexts in Common Enrich is important - it's part of our move
to fully validating our raw event early/eagerly. It's not storage target
related. Remember that our enriched event in S3 is becoming our canonical
format, so needs to be fully validated.
