### ISSUE TITLE
Scala Hadoop Shred: apply truncation logic to atomic-events TSV

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2042]
The logic currently is in EnrichmentManager.

**Comment by alexanderdean** [comment]
Logic will be moved out of Common Enrich as it is storage-target specific (actually Postgres-specific - Redshift `COPY` supports `TRUNCATECOLUMNS`

**Comment by fblundun** [comment]
For posterity, this is how I generated the full list of maximum field lengths:

```bash
cat atomic-def.sql | grep  '^\s*"' | awk '{print $2}' | awk -F' |\(|\)' '{if ($0 ~ /char/) print $2","; else print "null,"}'
```

Having access to an AST for the table would make this easier to do programmatically...
