### ISSUE TITLE
Redshift: add migration script for 0.7.0 to 0.8.0

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2048]

**Comment by alexanderdean** [comment]
Name's a bit cryptic?

**Comment by fblundun** [comment]
This release will involve removing the unstruct_event, contexts, and derived_contexts columns. So if the migration script upgrades tables in place, we should warn that the data in those columns will be gone for good.

**Comment by alexanderdean** [comment]
Agree!

**Comment by epantera** [comment]
Nice move !
