### ISSUE TITLE
Scala Common Enrich: replace use of erasure with runtimeClass

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2050]
Should fix some warnings:

``` scala
[warn] /vagrant/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/MapTransformer.scala:94: method erasure in trait ClassManifestDeprecatedApis is deprecated: Use runtimeClass instead
[warn]     val newInst = m.erasure.newInstance()
```

**Comment by fblundun** [comment]
Apparently Manifest itself is now deprecated and TypeTag should be used instead: http://stackoverflow.com/questions/10513336/how-do-the-new-scala-typetags-improve-the-deprecated-manifests

**Comment by alexanderdean** [comment]
Wow - okay!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/252
