### ISSUE TITLE
Rename No-JS Tracker everywhere in wiki and website to Pixel Tracker

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2059]
Confusing to define a tracker by what it's not rather than what it is!

**Comment by bogaert** [comment]
@alexanderdean Is the idea to keep this page? http://snowplowanalytics.com/no-js-tracker.html

I don't think the form works anymore.

**Comment by alexanderdean** [comment]
Hey @bogaert - my inclination would be to remove that page until as/when we have a Snowplow Event Studio that it can be a part of - but see what @yalisassoon thinks...

**Comment by yalisassoon** [comment]
It would be nice to fix that page - @bogaert can you please create a ticket
so we don't forget? Feel free to assign it to me...
When the event studio is launched we can take it off the public site and
pop it in there...

On Wed, Sep 30, 2015 at 2:05 PM, Alexander Dean <notifications@github.com>
wrote:

> Hey @bogaert <https://github.com/bogaert> - my inclination would be to
> remove that page until as/when we have a Snowplow Event Studio that it can
> be a part of - but see what @yalisassoon <https://github.com/yalisassoon>
> thinks...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/2059#issuecomment-144389620>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>

**Comment by alexanderdean** [comment]
Thanks @bogaert!
