### ISSUE TITLE
Hadoop Elasticsearch Sink: explore options for preventing duplication

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2060]
Copied and pasted from #824 :
- Have the job actually parse the bad row JSON strings and add an extra field which is a hash of the whole JSON. This hash would be used as the ES document ID of the bad row, ensuring uniqueness. It wouldn't actually need to go into the document (see https://github.com/elastic/elasticsearch-hadoop/issues/230).
- Add a UUID to all our bad rows. Use this as the ES document ID.
- Have some sort of Elasticsearch rotation system. For instance, write bad rows to a temporary index and when the EMR succeeds copy them to the main index.

The 1st and 2nd alternatives assume that you are just rerunning the "copy to ES" step, not the actual enrichment / shred which generated the bad rows (since that would change the timestamps (and possibly UUIDs) of the bad rows).

**Comment by chuwy** [comment]
Hadoop Elasticsearch Sink is deprecated.
