### ISSUE TITLE
Scala Kinesis Enrich rejecting trackStructEvent from JavaScript Tracker

### ISSUE THREAD

**Issue by xkidro** [snowplow/snowplow#2078]
Hello snowplow team and snowplow community,

I am using:

* //d1fc8wv8zag5ca.cloudfront.net/2.5.2/sp.js
* snowplow-stream-collector-0.5.0
* snowplow-kinesis-enrich-0.6.0
* snowplow-elasticsearch-sink-0.4.0

I configured some trackStructEvent events, they are being sent correctly 

Example post data:
```json
{
    "schema": "iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-3",
    "data": [{
        "e": "se",
        "se_ca": "widget",
        "se_ac": "click",
        "se_la": "Click via example.com",
        "se_pr": "savings",
        "se_va": "example.com",
        "tv": "js-2.5.2",
        "tna": "example_widget",
        "aid": "homepage",
        "p": "web",
        "tz": "Europe/Helsinki",
        "lang": "en-US",
        "cs": "windows-1252",
        "f_pdf": "1",
        "f_qt": "0",
        "f_realp": "0",
        "f_wma": "0",
        "f_dir": "0",
        "f_fla": "1",
        "f_java": "1",
        "f_gears": "0",
        "f_ag": "0",
        "res": "1280x800",
        "cd": "24",
        "eid": "9f761179-07b3-4940-b4cf-be9f70ef42e6",
        "dtm": "1443613105484",
        "vp": "1278x344",
        "ds": "1263x1265",
        "vid": "1",
        "sid": "e2097911-1863-4e3f-8fee-b9e70aa109bc",
        "fp": "1952324127",
        "url": "http://www.example.com/"
    }]
}
```

This my Kinesis Enriched bad stream (https://www.dropbox.com/s/nho5i72mlce1x77/Screenshot%202015-09-30%2014.47.45.png?dl=0 ): 
![Image of kinesis bad stream](https://photos-5.dropbox.com/t/2/AADUogp9_MQG2ilS14iBj10X1wjB81T0u9t8VfkiXPkPXQ/12/5652205/png/32x32/1/1443618000/0/2/Screenshot%202015-09-30%2014.47.45.png/CO392AIgASACIAMgBiAHKAEoAigH/UbHky86VblgJ3NaYRjCiUuXJXZCsnNq-J6FBZoTBBsQ?size=1024x768&size_mode=2)

I am pretty sure these are my trackStructEvent events because I don't usually see events in my bad stream.

Another thing is that they never show up in Kibana (https://www.dropbox.com/s/ig32fyxpc2be6k9/Screenshot%202015-09-30%2014.55.38.png?dl=0 )
![image of kibana]
(https://photos-6.dropbox.com/t/2/AABJGhVWCK3yhj_MtNr6eu8A7cQkECxhUfG2SoXsWHrqvQ/12/5652205/png/32x32/1/1443618000/0/2/Screenshot%202015-09-30%2014.55.38.png/CO392AIgASACIAMgBiAHKAEoAigH/J_atXgrFb0UpItn6wDjjGijUH-6ZfAKHeHGtDFNBA5o?size=1024x768&size_mode=2)

My wild guess is that the payload_data schema in the scala kinesis enricher is still iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-0 instead of iglu:com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-3

My resolver.conf is : 
```json
{
  "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-0",
  "data": {
    "cacheSize": 500,
    "repositories": [
      {
        "name": "Iglu Central",
        "priority": 0,
        "vendorPrefixes": [
          "com.snowplowanalytics"
        ],
        "connection": {
          "http": {
            "uri": "http://iglucentral.com"
          }
        }
      }
    ]
  }
}
```

How can I tell it that it should use the new payload schema ?

**Comment by fblundun** [comment]
Hi @xkidro , what version of Scala Kinesis Enrich are you using?

**Comment by xkidro** [comment]
snowplow-kinesis-enrich-0.6.0 , updated post right now

**Comment by fblundun** [comment]
The problem is your `se_va` field - a structured event's value should be a number, not a string. See the documentation here: https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#trackStructEvent
