### ISSUE TITLE
Clojure Collector: enable users to configure headers

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2082]
If you're using the Clojure collector to track email opens from Gmail, it is desirable to set headers to prevent Google from caching the image pixel. This means that it should be possible to track multiple opens of the same email. (Without it we believe that we're only tracking the first email open, after which the cached image is served.)

We would want the ability to set the header to `Cache-Control: no-cache, max-age=0`

**Comment by timelf123** [comment]
Does gmail actually respect that header? I was under the impression that they cache all images no matter what

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
