### ISSUE TITLE
StorageLoader: write JSON path file for com.amazon.aws.ec2/instance_identity_document

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2085]

**Comment by chuwy** [comment]
For the second instance I think proper name would be "instance_identity_document". It refers to URL where it can be found (/dynamic/instance-identity/document).

**Comment by alexanderdean** [comment]
I think we can probably get away with just "instance_identity" - i.e. the document is just a way of requesting the JSON version?

**Comment by chuwy** [comment]
There three more endpoints: signature, dsa2048 and pkcs7. All with meaningless keys (or some other base64).

**Comment by alexanderdean** [comment]
Okay cool - go with "instance_identity_document" then.
