### ISSUE TITLE
Remove network_userid from event_fingerprint algorithm

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2087]
Based on testing the new algorithm, I believe `network_userid` is one of the parameters used to feed it i.e. two events that are identical apart from having different `collector_tstamp` and `network_userid` values have different `event_fingerprint` values. I am sure that `collector_tstamp` is not included in the algorithm, which leads me to suspect that `network_userid` is.

I don't believe `network_userid` should be included - this value is appended to the data by the collector. For a single event that happens to be sent twice from the JS tracker to the Clojure collector on a computer that does not accept third party cookies, wouldn't the `network_userid` value change with both sends?

Does that make sense @fblundun @alexanderdean ?

**Comment by alexanderdean** [comment]
@yalisassoon - yes indeed, nuid is currently being used. Your explanation of why we should exclude it makes perfect sense - I am updating the release and blog post to exclude nuid...

**Comment by alexanderdean** [comment]
Removed from the example config, closing...

**Comment by fblundun** [comment]
Well spotted - I forgot that the collector adds some parameters.

https://github.com/snowplow/snowplow/blob/master/2-collectors/clojure-collector/java-servlet/war-resources/.ebextensions/server.xml#L138

Should we also disable `cv` to prevent the collector version affecting the fingerprint?

**Comment by alexanderdean** [comment]
Agree, let's disable cv. I've added this to the blog post... @fblundun please update the example JSON config and rebase...

**Comment by fblundun** [comment]
Done!

**Comment by alexanderdean** [comment]
Thanks!
