### ISSUE TITLE
Kinesis Elasticsearch Sink: cache the mapping of field name to field type

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2090]
The way this currently works, for every event, for every field, the code checks based on the name of the field how that field should be handled using the [converter function](https://github.com/snowplow/snowplow/blob/11bd35079a17f6976d08b1941a6c373a85c4e877/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/SnowplowElasticsearchTransformer.scala#L248-L274). This involves checking whether the string name of the field is a member of various sets. It would be faster to precompute and cache the correspondence between field names and handler functions. (Crude benchmarking appears to show that this roughly doubles the speed of the `jsonifyGoodEvent` function.)

**Comment by fblundun** [comment]
My benchmark was flawed because it didn't take JIT optimization into account - the actual performance increase is a lot smaller. Still, I think this design change is an improvement.

**Comment by alexanderdean** [comment]
Agree!
