### ISSUE TITLE
Deduplication: update SQL queries to use event fingerprint

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#2091]

**Comment by alexanderdean** [comment]
Is this ready for release @bogaert ?

**Comment by bogaert** [comment]
There are a few more queries I want to add (see #2110). Expect this to be done later this morning.

**Comment by alexanderdean** [comment]
Cool, thanks for the update

**Comment by bogaert** [comment]
This is now ready for release @alexanderdean (together with #2110).

**Comment by alexanderdean** [comment]
Great stuff!
