### ISSUE TITLE
Kinesis Elasticsearch Sink: add support for HTTP protocol

### ISSUE THREAD

**Issue by xkidro** [snowplow/snowplow#2092]
AWS just launched http://aws.amazon.com/elasticsearch-service/

How can I configure the Elasticsearch sink to stream events here with IAM authentication (I am using elastic beanstalk with docker for the scala elasticsearch sink)?

**Comment by alexanderdean** [comment]
Hey @xkidro - what's the particular problem you are having? We haven't used the Elasticsearch Service yet...

**Comment by xkidro** [comment]
I want to know if the Scala Elasticsearch sink AWS authentication applies to Elasticsearch also not only for the kinesis stream.

**Comment by xkidro** [comment]
in case anyone is wondering it doesn't work :)

I even tried a Lambda function with Kinesis Event source but that doesn't work either

**Comment by christoph-buente** [comment]
The problem with AWS ES service is, that they support the HTTP interface only not the binary TCP interface. See here, at the bottom of the page. http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#d0e9673

This renders the AWS service useless, unless the kinesis-es sink can be configured to use the HTTP interface for bulk inserts.

**Comment by christoph-buente** [comment]
Any news on that, or will this be obsolete with Snowplow Mini?

**Comment by alexanderdean** [comment]
No, it's still planned, but not yet scheduled...
