### ISSUE TITLE
Snowplow CLI: specify complete path to each jar in the config file

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2100]
At the moment the user configures the top-level bucket and the versions of the jars used in the job, and the EER works out the S3 bucket names. I think it would be simpler to just specify the full S3 path to every jar - the EER would no longer need to know about the internals of the hosted assets bucket. It would also make testing new versions of individual jars easier, as you wouldn't have to mirror the structure of the hosted assets bucket to do it. What do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
I like it! Less magic/secret knowledge in the Snowplow CLI is the right direction of travel...
