### ISSUE TITLE
Docs: Incorrect ordering of trackSocialInteraction arguments

### ISSUE THREAD

**Issue by mattmueller** [snowplow/snowplow#2101]
The documentation for tracking social interactions (https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#trackSocial) has incorrect ordering of the arguments, resulting in the network and action to be swapped when the event is stored.

It should read:

```javascript
snowplow_name_here('trackSocialInteraction', socialAction, network, target);
```

**Comment by alexanderdean** [comment]
Thanks @mattmueller ! We'll get this fixed...

**Comment by mattmueller** [comment]
:+1:

**Comment by fblundun** [comment]
Thanks @mattmueller , this is fixed now...
