### ISSUE TITLE
Kinesis Elasticsearch Sink: configure transport port

### ISSUE THREAD

**Issue by xkidro** [snowplow/snowplow#2102]
I searched the source code from https://github.com/snowplow/snowplow/tree/master/4-storage/kinesis-elasticsearch-sink I can't seem to find where the 9300 is hard coded and can't find a way to configure it as well.

**Comment by fblundun** [comment]
Hi @xkidro ,

9300 is the default value used in the [amazon-kinesis-connectors library](https://github.com/awslabs/amazon-kinesis-connectors/blob/9b34900413a25212f4dec9d7f1e64136df31db9b/src/main/java/com/amazonaws/services/kinesis/connectors/KinesisConnectorConfiguration.java#L163). We override several of these default values [here](https://github.com/snowplow/snowplow/blob/master/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/ElasticsearchSinkApp.scala#L191-L207), but the port is not (yet) one of them.

**Comment by xkidro** [comment]
Hello @fblundun thank you for the clarification, I have a question, it's not really related with this but it is related to the other issue I posted, didn't really study these but would it be possible for the sink to use the http api instead of the transport client? Does the kinesis connectors library support this? If so, would it be hard to modify the sink to work with that? I really want to use the new AWS elasticsearch service but it doesn't support the transport client :(

**Comment by fblundun** [comment]
Unfortunately not - we only support the transport client. Compatibility with Amazon Elasticsearch Service would be nice but as you say they don't support the transport client ([source](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html)). A pull request adding the option to use the HTTP client would be welcome!

**Comment by fblundun** [comment]
Note that we don't actually use the amazon-kinesis-connectors Elasticsearch emitter - we implement that ourselves: https://github.com/snowplow/snowplow/blob/9ee272a429dfa0da1aa1df6af8978948c2fd64ee/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/SnowplowElasticsearchEmitter.scala#L165

**Comment by alexanderdean** [comment]
Bringing forwards as pretty straightforward add
