### ISSUE TITLE
Kinesis: Investigate increaseStreamRetentionPeriod and decreaseStreamRetentionPeriod

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2103]
http://docs.aws.amazon.com/kinesis/latest/APIReference/API_IncreaseStreamRetentionPeriod.html

I don't remember seeing this before, although that page says it is API Version 2013-12-02. Maybe this lets you change the 24 hour limit?

**Comment by alexanderdean** [comment]
Interesting!

**Comment by fblundun** [comment]
We have done this...
