### ISSUE TITLE
Scala Hadoop Enrich: upgrade elephant-bird from 4.5 to 4.10

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2105]
Kinesis S3 rarely produces lzo files that need significant indexing. Lzo has obvious merits, and we should support lzo index for when we are processing compacted archives, but can we support a non-indexed version as well?

**Comment by alexanderdean** [comment]
One advantage of using lzo index everywhere is that we could do a run over both the compacted archive and the recent (post-archive) files from Kinesis S3.

**Comment by pkallos** [comment]
For what it's worth, on our internal applications that sink data to .thrift.lzo data to S3, we actually decided to disable writing of the lzo.index files because we found that there was not much benefit.

And there was also pretty significant overhead in trying to fetch and read all of the .index files (which is more of an issue when reprocessing archived data in hadoop)

**Comment by alexanderdean** [comment]
Thanks @pkallos, that's good to know. How did you disable the writing of the index files? Are the files still processable by Hadoop Enrich without them?

It feels like the lzo.index files are useful if e.g. you have a compacted archive with only one file per hour, but much less useful as originally generated by Kinesis Enrich...

**Comment by pkallos** [comment]
Basically the equivalent of changing `createIndexedOutputStream` to `createOutputStream` [here](https://github.com/snowplow/kinesis-s3/blob/master/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/serializers/LzoSerializer.scala#L77)

And not emitting the index file [here](https://github.com/snowplow/kinesis-s3/blob/master/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/serializers/LzoSerializer.scala#L108)

**Comment by alexanderdean** [comment]
Good to know, thanks! And does Hadoop Enrich happily process the format if the index files are missing, or did you have to fork that, or were you using a different process?

**Comment by pkallos** [comment]
I believe it will happily process the lzo files with missing index files, although it will still attempt to get file statuses for the index files (not a big deal).

Also worthwhile upgrading elephant-bird from 4.5 to 4.10, there are a handful of performance improvements (however you will need to take care to peg your thrift version down to <= 0.9.0)

Full disclosure that I haven't tested this with Snowplow Hadoop Enrich itself, but another project we have that uses elephant-bird. YMMV :)

**Comment by alexanderdean** [comment]
Thanks @pkallos - that's helpful. I am going to rename this ticket to upgrade elephant-bird to 4.10, and I'll create a separate ticket in kinesis-s3 to add a lzo mode (i.e. lzo not lzo-index)...

**Comment by BenFradet** [comment]
done as part of #3067 (to 4.14)
