### ISSUE TITLE
Scala Hadoop Enrich: use partition tap to write out both enriched events and bad rows

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2107]
According to @dennisatspaceape, it's possible to put heterogeneous data (in our case, `Success[EnrichedEvent]` and `Failure[BadRow]`) into different slots within the same partition tap.

This would significantly reduce processing time (even after #859), as there would no longer be two runs per event.

**Comment by BenFradet** [comment]
Not applicable anymore since the move to Spark, closing
