### ISSUE TITLE
Scala Kinesis Enrich: update Scala Tracker to 0.2.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2109]
@fblundun - please can you test this with a pre-release version of 0.2.0 so we can build confidence for the Scala Tracker release...

**Comment by alexanderdean** [comment]
Particularly want to check the EC2 context is working well...

**Comment by fblundun** [comment]
I edited the version 0.6.0 of SKE by adding the line `t.enableEc2Context` before tracking any events. I then ran the resulting jar on an EC2 instance. The monitoring events generated by the tracker (app_initialized and app_heartbeat) were correctly generated. But I haven't seen any EC2 context.

**Comment by fblundun** [comment]
Using curl, I verified that the instance identity document is indeed at the expected endpoint.

**Comment by chuwy** [comment]
Can we see any akka output? If it can't connect to the endpoint it logging errors.

**Comment by fblundun** [comment]
There isn't any akka output.
