### ISSUE TITLE
Snowplow CLI: investigate shortening startup time

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2117]

**Comment by fblundun** [comment]
On my machine, there is a 3-second pause between starting the CLI and Ruby code in the main snowplow-emr-etl-runner.rb file executing.

The biggest delay is the 5 seconds taken by the statement `require 'elasticity'`. This suggests that we should load Elasticity lazily, since some invocations of the CLI will not need to use it.

**Comment by fblundun** [comment]
For the storage-loader:

There is a 3-second pause before Ruby code in the main file begins executing.

Loading the net/http module in snowplow-ruby-tracker takes 2 seconds.

Loading fog takes 2 seconds.

**Comment by fblundun** [comment]
We decided that EER and SL aren't going to be combined in a single app after all, meaning that it won't be necessary to wait for all the SL code to load before EER does anything. So the startup time is not going to be as problematic as we thought. I think we can postpone this ticket.

**Comment by alexanderdean** [comment]
Sounds fine!

**Comment by alexanderdean** [comment]
Closing as not important
