### ISSUE TITLE
Scala Common Enrich: add new git sourcecode enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2121]
This is an idea borrowed from Sentry - if we have an event which is a code exception with a line number for the failure, we could do a lookup into the project source code in git for the given line number for the current build, and add a context with the -/+ 5 or 10 lines of code and a link back to the source.

**Comment by fblundun** [comment]
We could also use git blame to return the id of the last commit to touch that line.

**Comment by alexanderdean** [comment]
Love it!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/122
