### ISSUE TITLE
Scala Kinesis Enrich: How to change the log level at runtime?

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow#2122]
How can I change the log level at runtime for the Kinesis enricher? I have events that are failing, but I'm unable to see any details as to why, just that they're getting written to the bad stream.

**Comment by fblundun** [comment]
Hello @jramos ,

It isn't currently possible to change the log level - there are some thoughts about this in ticket #1526 

You can go through some slightly weird steps to edit the Kinesis Enrich executable and change the logging level:

```
tail -c +42 snowplow-kinesis-enrich-0.6.0 > snowplow-kinesis-enrich-0.6.0.jar
java -Dorg.slf4j.simpleLogger.defaultLogLevel=error -jar snowplow-kinesis-enrich-0.6.0.jar {{config options}}
```

The tail command strips off the initial shell script bytes of the file, leaving you with a normal jar file which is runnable using `java -jar`.

**Comment by fblundun** [comment]
Note that this won't actually tell you what went wrong with your events - for this you have to actually inspect the bad stream.

**Comment by alexanderdean** [comment]
Hi @jramos - the records in the bad stream will tell you why they are failing! The JSONs contain the raw event and the failure messages. You can load these into Elasticsearch using the kinesis-elasticsearch-sink for analysis. There is nothing meaningful logged to stdout/err around individual event failures.

**Comment by jramos** [comment]
Cool, thanks!

**Comment by jramos** [comment]
Actually, there's a `debug` log level that'll output the bad row. Thanks guys!
