### ISSUE TITLE
Documentation: supplement setup guide with AWS CLI examples

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2137]
In addition to screenshots we could append CLI example to each step, for example for [Redshift cluster](https://github.com/snowplow/snowplow/wiki/Setting-up-Redshift#launch):
```
aws redshift create-cluster --node-type dw.hs1.xlarge --number-of-nodes 1 --cluster-identifier snowplow --db-name pbz --master-username admin --master-user-password TopSecret1 
```
So it will be more readable and less chances to be outdated.

**Comment by chuwy** [comment]
Putting some commands here so we could take it from one place when we'll have a time for documentation.
**Setting up Clojure Collector**:
```
aws elasticbeanstalk create-application --application-name analytics

aws elasticbeanstalk create-application-version
    --application-name analytics
    --version-label clojure-collector
    --cli-input-json "{\"SourceBundle\":{\"S3Bucket\":\"snowplow-hosted-assets\",\"S3Key\":\"2-collectors/clojure-collector/clojure-collector-1.1.0-standalone.war\"}}"

aws elasticbeanstalk create-environment
    --application-name analytics
    --environment-name collector
    --solution-stack-name "64bit Amazon Linux 2015.09 v2.0.4 running Tomcat 8 Java 8"
    --version-label clojure-collector
```
Still need to enable S3 log rotation in AWS Console.

**Comment by alexanderdean** [comment]
Thanks @chuwy !

**Comment by chuwy** [comment]
Leaving here everything I collected so far.

This tutorial assumes it's your first installation and you probably want just to checkout platform,
thus many steps describe low-performance and unsecure installation. On real-world you may want to fix that.

#### Prepare your system

Before get started you need to have:

* Account on [Amazon Web Services](http://aws.amazon.com/)
* Installed [AWS CLI](https://aws.amazon.com/cli/)
* IAM user, first one need to be created in [AWS Console](https://console.aws.amazon.com/iam/home?#users)
* IAM user need to have attached `AdministratorAccess` ([permissions tab](https://console.aws.amazon.com/iam/home#users))
* Configured credentials on your local machine. you can use `aws configure` for it
* For some steps you may want to install [jq](https://stedolan.github.io/jq/). It's optional, but handy.

Everything else can be done from CLI.

#### Setting up EC2 instance for EmrEtlRunner/StorageLoader

In the end of this step you'll have an AWS EC2 instance, SSH access to it and key on local-machine. Nothing snowplow-specific though.

##### 1. Find your Default VPC ID

We will refer to it as `{{ VPC_ID }}`

```bash
$ aws ec2 describe-vpcs | jq -r ".Vpcs[0].VpcId"
```

##### 2. Create Security Group for SSH access

**TODO: For demo purpose probably would be better to create a single SG for all full-access (SSH, Redshift, etc). Also, investigate something more strict..**

On output you'll get GroupId, we will refer to it as `{{ SSH_SG }}`.

```bash
$ aws ec2 create-security-group 
    --group-name "EC2 SSH full access" 
    --description "Unsafe. Use for demonstration only" 
    --vpc-id {{ VPC_ID }} \
    | jq -r '.GroupId'
```

##### 3. Add rule allowing SSH access from anywhere

```bash
$ aws ec2 authorize-security-group-ingress 
    --group-id {{ SSH_SG }}
    --protocol tcp 
    --port 22 
    --cidr 0.0.0.0/0
```

##### 4. Create SSH key-pair named snowplow-ec2 on local machine:
```bash
$ aws ec2 create-key-pair --key-name snowplow-ec2 \
    | jq -r ".KeyMaterial" > ~/.ssh/snowplow-ec2.pem
$ chmod go-rwx ~/.ssh/snowplow-ec2.pem
```

##### 5. Run t2.small instance with Amazon Linux AMI with previously created SSH-key: 

On output you will get your instance id, we will refer to it as `{{ INSTANCE_ID }}`

```bash
$ aws ec2 run-instances
    --image-id ami-60b6c60a
    --count 1
    --instance-type t2.small
    --key-name snowplow-ec2 \
    | jq -r '.Instances[0].InstanceId'
```

##### 6. Attach security group to Instance

```bash
$ aws ec2 modify-instance-attribute 
    --instance-id {{ INSTANCE_ID }}
    --groups {{ SSH_SG }}
```

##### 7. Check public IP-address of newly created Instance:

Further we will refer to it as `{{ PUBLIC_IP }}`

```bash
$ aws ec2 describe-instances
    --instance-ids {{ INSTANCE_ID }}
    --profile prsn
    --region us-east-1 \
    | jq '.Reservations[0].Instances[0].PublicDnsName'
```

##### 8. Log-in
Fill-in `{{ PUBLIC_IP }}` from previous step.
```bash
$ ssh -i ~/.ssh/aws-ec2.pem ec2-user@{{ PUBLIC_IP }}
```

**Comment by chuwy** [comment]
#### Create Redshift cluster

In the end of this step you'll have running Redshift cluster. Your next step will be to create tables for your data and run StorageLoader.

##### 1. Create Redshift cluster

```bash
$ aws redshift create-cluster 
    --node-type dc1.large
    --cluster-type single-node
    --cluster-identifier snowplow
    --db-name pbz
    --master-username admin
    --master-user-password TopSecret1 
```

This command may take some time, if you'll get some errors on further steps, that probably because cluster isn't running yet.

##### 2. Create security group

On output you'll get GroupId, we'll refer to it as `{{ REDSHIFT_SG }}`.

```bash
aws ec2 create-security-group
    --group-name "Redshift unimited access"
    --description "Unsafe. Use for demonstration only"
    --vpc-id {{ VPC_ID }} \
    | jq -r '.GroupId'
```

##### 3. Add access rules to new security group

```bash
aws ec2 authorize-security-group-ingress
    --group-id {{ REDSHIFT_SG }}
    --protocol tcp
    --port 5439
    --cidr 0.0.0.0/0
```

##### 4. Tie previously created security to our cluster

On output you'll get cluster address, we'll refer to it as `{{ REDSHIFT_ADDRESS }}`

```bash
aws redshift modify-cluster 
    --cluster-id snowplow 
    --vpc-security-group-ids {{ REDSHIFT_SG }} \
    | jq -r '.Cluster.Endpoint.Address'
```

##### 5. Connect

```bash
$ psql -h {{ REDSHIFT_ADDRESS }} -U admin -d pbz -p 5439
```

**Comment by alexanderdean** [comment]
Thanks for capturing all this @chuwy !

**Comment by ninjabear** [comment]
Hi @chuwy, thanks for writing this! I just used it to set up a clojure collector on elastic beanstalk.

As time has passed unfortunately Amazon have changed the elasticbeanstalk setup UI to the point where it no longer matches up with the guide here https://github.com/snowplow/snowplow/wiki/Setting-up-the-Clojure-collector. So having the CLI instructions has really helped as they seem to change less.

I had to make a small alteration to get it to work as of today :-

```
 aws elasticbeanstalk create-environment \
    --application-name analytics \
    --environment-name collector \
    --solution-stack-name "64bit Amazon Linux 2015.09 v2.0.4 running Tomcat 8 Java 8" \
    --version-label clojure-collector \
    | jq -r '.EnvironmentId'
```

returned 

```
A client error (InvalidParameterValue) occurred when calling the CreateEnvironment operation: No Solution Stack named '64bit Amazon Linux 2015.09 v2.0.4 running Tomcat 8 Java 8' found.
```

So using 

```aws elasticbeanstalk list-available-solution-stacks```

I could see it's been updated to `64bit Amazon Linux 2015.09 v2.0.6 running Tomcat 8 Java 8`

replacing the solution-stack-name with this fixed it, however it didn't return the environment id. I found this by looking it up on the AWS web UI.

Everything else worked fine (I hope!). Thanks!

**Comment by chuwy** [comment]
Hey @ninjabear! I glad it helped someone and extremely appreciate your addition (since I haven't chance to test it meticulously). Hope someday it will evolve to full setup tutorial.

As for stack name, I'm pretty surprised they do not allow it. I'll need to update that most recent stack can be fetched with following:
```bash
$ aws elasticbeanstalk list-available-solution-stacks \ 
    | jq -r '.SolutionStacks[]' \
    | grep "Tomcat 8 Java 8" \ 
    | head -n 1
```

**Comment by ninjabear** [comment]
I think at least in terms of the clojure collector it could become a one-stop setup script - the instructions could be something like "run this" - `curl http://<something>/clojure-elasticbeanstalk.sh | bash`. 

Aside from saving the user a bit of time and possible headscratching it also gives the bonus of making the instructions provably correct - we can put them under test by running the script and quizzing aws afterwards. That would mean we don't need to play catchup with AWS quite so much.

**Comment by alexanderdean** [comment]
Augmenting the setup guide with `aws cli` commands is a great idea - assigning to @ihortom ...

**Comment by ihortom** [comment]
@alexanderdean / @chuwy - I added AWS CLI instructions to the relevant pages. Additionally, I created a new page (and set references to it) describing how to set up EC2 instance. All the instructions (with ocasional amendment) are taken from this issue page.

**Comment by alexanderdean** [comment]
Awesome - pushed! Thanks so much @ihortom
