### ISSUE TITLE
Kinesis Elasticsearch Sink: rename dvce_timestamp, add missing fields

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow#2141]
I get warnings with the current version of the sink about a difference in the number of fields. I also noticed that `dvce_timestamp` was not renamed to `dvce_created_timestamp`. This commit corrects both:

https://github.com/jramos/snowplow/commit/8790fd3671db54ba0fbb5dd6cafacb790517fe4c

**Comment by alexanderdean** [comment]
Duplicate of #2089
