### ISSUE TITLE
Create Erlang / Elixir tracker

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2146]
## Just a placeholder for a new tracker

With the release of **_elixir 1.0**_ http://elixir-lang.org/blog/2014/09/18/elixir-v1-0-0-released/ and **_phoenix framework**_ http://www.phoenixframework.org/ a new kid of web development frameworks in on the block. And of course these folks want to use snowplow for tracking their events.

**Comment by alexanderdean** [comment]
That would be seriously cool! Using actors would be a great approach to handling async event emitting to Snowplow.

I have stubbed the repo: https://github.com/snowplow/snowplow-erlang-tracker

Anybody interested in working on this - please follow up in this thread and we can arrange permissions on that repo for you...

**Comment by BenFradet** [comment]
closing

**Comment by goodhamgupta** [comment]
Hi @alexanderdean,

We were using snowplow extensively at Scripbox, and we managed to create an elixir SDK for it. It's available here: https://github.com/scripbox/snowplow-elixir-tracker

If this issue is still relevant, could we integrate this into the main repository?

Thanks!

**Comment by paulboocock** [comment]
Hi @goodhamgupta 
This is certainly something we'd be open to discussing further. Could you drop an e-mail to support@snowplowanalytics.com and I'll pick it up with you from there?

**Comment by goodhamgupta** [comment]
Hi @paulboocock,

Thanks for your quick response! I've sent an email and we can continue this discussion on the email thread.
