### ISSUE TITLE
 Scala Common Enrich: change transaction item quantity type to JInteger

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2157]
Referring to:

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L195

```scala
 ("ti_qu" , (ME.toTsvSafe, "ti_quantity")),
```

vs

```sql
	ti_quantity int,
```

**Comment by alexanderdean** [comment]
Sorry @chuwy could we bring this one forwards into R79? It should be a one-line fix.

**Comment by chuwy** [comment]
Can we rephrase the title so it could be in correspondence with commit and CHANGELOG?

**Comment by alexanderdean** [comment]
Changed the title!

**Comment by chuwy** [comment]
Thanks! I couldn't come up with how to describe a commit in correspondence with previous title :)
