### ISSUE TITLE
Optimize weather data cache

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2158]
Simplified example using a single spatial dimension called "displacement" rather than 2 spatial dimensions + time.

Assume that the user has specified a tolerance of 1km, meaning that our reported weather must be the actual weather somewhere within 1km of the event.

As I understand it, the current strategy is:

For each event, round its displacement to the nearest 2km. If the rounded displacement is in the cache, use the cached value; otherwise, look up the weather information, add it to the cache with the rounded displacement as key, and return it.

The disadvantage of this strategy is that the returned results are unnecessarily innaccurate.

An alternative strategy:

Instead of the cache being a Map[Displacement, Weather] we make it a Map[RoundedDownDisplacement, (ActualDisplacement, Weather)]. Each key represents an interval of 1km. For example, the key 7 represents the interval of all displacements between 7km and 8km.

For each event, let d be the actual displacement of the event in km. Check the cache for floor(d-1), floor(d), and ceiling(d). If any one of those keys is in the cache and if the corresponding actual displacement value of the key is within 1km of the non-rounded displacement of the event, use that key's weather. Otherwise, add `floor(d): (d, getWeather(d))` to the cache and return getWeather(d).

For example, suppose an event has displacement 3.7km, and the cache looks like this:

```
{
  2: (2.3, sunny),
  4: (4.4, rainy)
}
```

First we see that floor(3.7-1)=2 is in the cache, but the difference between 2.3 and 3.7 is more than 1 (our specified tolerance) so we cannot use this cached value. Next we see that floor(3.7-1)=3 is not in the cache at all. Finally we see that ceiling(3.7)=4 is in the cache and 4.4 - 3.7 < 1 so we use "rainy" as the weather value for the event.

If 4 had not been in the cache, we not be able to use any cached value and would have to look up 3.7 in the API and add it to the cache:

```
{
 2: (2.3, sunny),
 3: (3.7, slightly rainy)
}
```

Note that we look up the value from the API for 3.7km exactly, rather than 4km (as we would under the original strategy).

It should be possible to extend this idea from a single dimension to 3 dimensions (latitude, longitude, and time). Instead of intervals of 1km, the keys in the cache would represent cubes of 1km x 1km x 1hr, and we would check up to 27 keys rather than up to 3.

Any thoughts? Is there an easier way to achieve this? Does this make any sense at all?

**Comment by alexanderdean** [comment]
I think this makes sense - I think the missing piece is optimizing for the scenario where many events have the exact same values for latitude and longitude and relatively low variance of event time.

For example, it is highly likely that a user will have the same IP address for all events in a session, and thus will have the same longitude and latitude for that whole session.

In this scenario, it seems a shame to be potentially checking 27 keys per event just to retrieve the same value across 10s or 100s of events.

**Comment by alexanderdean** [comment]
To put it another way: we need to make sure we optimize the cache intra-user as well as inter-user.

**Comment by chuwy** [comment]
Thanks for details, Fred. I thought about additional dimensions a lot. One more idea about it (probably overengineering though) is that in some places on Earth weather is extremely stable, so for example we probably don't need to do requests for weather on Middle East even for 50km/3hrs difference.

**Comment by fblundun** [comment]
@alexanderdean - if we want to avoid checking all the keys in this situation, we can get by this by ensuring that the 27 keys are checked in the right order and that we terminate when a match is found, specifically:

(floor(x), floor(y), floor(t))
(floor(x), floor(y), floor(t-1))
(floor(x), floor(y), ceiling(t))
all the other cells

Then for a single user, normally only one key will be checked, and occasionally 2 or 3.

@chuwy - that's a very interesting point. It would be really useful if the API actually told you the "range" for which a specific weather datapoint is roughly valid...

**Comment by alexanderdean** [comment]
@fblundun - sounds good!

**Comment by fblundun** [comment]
A downside to this: if the same event is processed twice, it won't necessarily end up with the same weather context both times. The context can depend on whether another event with a nearby location was processed first.

**Comment by chuwy** [comment]
Very good point. Does it have significant drawbacks for us?

**Comment by chuwy** [comment]
I actually noticed many times while working with OWM that it could give you slightly different results for same request, so context for one event could be different any way.
On the other hand there's a chance it affects only current weather requests (I haven't fetched history yet).

**Comment by alexanderdean** [comment]
I think that's survivable, because the event fingerprint doesn't include derived contexts... (Therefore deduplication won't be affected).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/124
