### ISSUE TITLE
Kinesis Elasticsearch Sink: upgrade elasticsearch to a more recent version

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#2161]
We are currently using 1.4.4 however elasticsearch has now reached 2.0.0.  As it has reached a new major this would be a good time to think about upgrading.  However this is dependant on the Kinesis Connectors Library supporting this move as well..

**Comment by alexanderdean** [comment]
Can you follow up on this in the Kinesis Connectors Library and cross-link the tickets?

**Comment by jbeemster** [comment]
There is an issue open already: https://github.com/awslabs/amazon-kinesis-connectors/issues/52

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#10
