### ISSUE TITLE
recipes-basic import fails due to renamed dvce_tstamp

### ISSUE THREAD

**Issue by timelf123** [snowplow/snowplow#2166]
Due to renaming of the `dvce_tstamp` field https://github.com/snowplow/snowplow/issues/2111
 
The basic recipe fails:

`[Err] ERROR:  column "dvce_tstamp" does not exist in events`

Solution is to replace `dvce_tstamp` with `dvce_created_tstamp` on https://github.com/snowplow/snowplow/blob/master/6-analytics/recipes/redshift/recipes-basic.sql#L239-L244

**Comment by alexanderdean** [comment]
Thanks for raising @timelf123 ! Scheduling...

**Comment by bogaert** [comment]
That is done (cc @alexanderdean).

**Comment by alexanderdean** [comment]
Cool, bringing forwards...
