### ISSUE TITLE
snowplow-runner-and-loader.sh needs resolver config option for emr-etl-loader

### ISSUE THREAD

**Issue by timelf123** [snowplow/snowplow#2170]
Because the iglu config was moved out of the config.yml file in https://github.com/snowplow/snowplow/commit/8ac383168c41e5e81e4aacab11c00812dd73e55f

One must add  `--resolver /path/to/resolver.json` to the command line options for the emr-etl-loader to get around this error:
```
$ ./snowplow-runner-and-loader.sh 
F, [2015-11-06T16:30:37.179000 #8842] FATAL -- : 
Snowplow::EmrEtlRunner::ConfigError (Missing option: resolver

```

**Comment by fblundun** [comment]
Thanks for spotting this @timelf123 !
