### ISSUE TITLE
Clojure Collector: verify maxPostSize

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2201]
Seeing reports of truncation at around ~162kb, whereas this suggests 2Mb POSTs should be safe:

http://stackoverflow.com/questions/2943477/is-there-a-max-size-for-post-parameter-content

**Comment by alexanderdean** [comment]
Update: we have had a customer report that they have successfully had 2Mb POSTs (from Mandrill) landing in their Clojure Collector.

**Comment by alexanderdean** [comment]
Assigning to @jbeemster - I'd like this issue bottomed out as part of the Avalanche work...

**Comment by alexanderdean** [comment]
Worth testing this on Scala Stream Collector too - if a max post size is found there, it could be suggestive of an ELB limitation...

**Comment by christoph-buente** [comment]
I can also provide an bunch of files then seemed to be truncated when trying to catch shopify webhooks. Maybe that helps with the analysis.

**Comment by alexanderdean** [comment]
Please share!

**Comment by christoph-buente** [comment]
Can i send then directly to you? These files probably contain personal identifyable information about our clients and i don't want to expose them here.

**Comment by alexanderdean** [comment]
Yep that's fine.

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
