### ISSUE TITLE
Add a Clojure tracker?

### ISSUE THREAD

**Issue by andrioni** [snowplow/snowplow#2203]
Hi, do you have any plans or interest in writing a Clojure tracker?

**Comment by alexanderdean** [comment]
Hey @andrioni - no current plans. Are you thinking core.async and clj-http?

If you are interested, let me know and I can create a Snowplow repo and give you perms...

**Comment by andrioni** [comment]
Yup, and maybe a Ring middleware (if viable, I have yet to think a bit more about it).

Interested I am, but I am a bit newbie in Clojure, so the development might be a little slow.

**Comment by alexanderdean** [comment]
Stubbed! Good luck with it

https://github.com/snowplow/snowplow-clojure-tracker

**Comment by BenFradet** [comment]
closing
