### ISSUE TITLE
Complete the list of available trackers in the wiki

### ISSUE THREAD

**Issue by andrioni** [snowplow/snowplow#2204]
[The root page of documentation](https://github.com/snowplow/snowplow/wiki/SnowPlow-technical-documentation) is missing quite a lot of the trackers: PHP, Scala, Node.js...

**Comment by alexanderdean** [comment]
Thanks, scheduling...

**Comment by alexanderdean** [comment]
This is an easy one @ihortom

**Comment by ihortom** [comment]
@alexanderdean updated locally but no permissions to push.

**Comment by alexanderdean** [comment]
Please continue on your local fork @ihortom - we'll work out a way of merging them in once you have a set of tickets done...

**Comment by alexanderdean** [comment]
Fixed by @ihortom, closing
