### ISSUE TITLE
EmrEtlRunner: add support for additional_info in emr section

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2211]
This lets us try pre-release EMR features.

Blocked by https://github.com/rslifka/elasticity/issues/122

**Comment by fblundun** [comment]
Confusingly, the additional_info that you configure doesn't seem to show up anywhere in the AWS UI or the output of describe-cluster. But setting additional_info to a malformed JSON string causes the job creation to fail, so I assume it's working.

**Comment by alexanderdean** [comment]
Right! Thanks Fred
