### ISSUE TITLE
AWS is dropping deprecated API (DescribeJobFlows) on 12/14/2015

### ISSUE THREAD

**Issue by derdeka** [snowplow/snowplow#2213]
Hi,

we got the following Ticket from AWS support. As we recently updated to snowplow version 72, i'm not sure if this might be an issue for us. Was snowplow already updated to use the current API?

thanks, denny

> Hello EMR User, 
> 
> Based on our current records, you are currently using one of our deprecated API
> (DescribeJobFlows) to get the details for all of your EMR clusters.
> 
> Starting Midnight (24:00 UTC) 12/14/2015, we will require users to move to the new
> set of APIs. The newer set of APIs provide a much more granular and low
> latency access. 
> 
> Here is the list of new APIs: 
> 
> ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and
> ListBootstrapActions instead. 
> 
> API Documentation: http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_Operations.html
> 
> DescribeJobFlows API Doc:
> http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows
> 
> FAQ:
> 
> Q. WHY THIS IS REQUIRED?
> A. DescribeJobFlows API is deprecated more than a year ago. 
> 
> Q. WHAT DO I HAVE TO DO?
> A. Make sure you are not using DescribeJobFlows API. If you are using make code changes to
> use ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions
> instead.
> 
> Q. HOW SOON DOES THIS NEEDS TO GET ADDRESSED?
> A. This work needs to be completed by 12/14/2015.
>
> Best regards,
> EMR Service Team

**Comment by alexanderdean** [comment]
Hi @derdeka - thanks for raising. We are already using almost the latest version of Elasticity, but there may be a stray EMR API call or two which need updating. Assigned to R74 to investigate; we'll make sure to get R74 out before the AWS deadline of 12/14/2015.

**Comment by alexanderdean** [comment]
@rslifka - any idea what the legacy API calls could be?

**Comment by alexanderdean** [comment]
I don't think there are any legacy calls - neither in EmrEtlRunner nor Elasticity. I believe if you are running **Release 68 Turquoise Jay** or above, the deprecation on 12/14/2015 will not affect you.

Keeping this ticket open until we confirm this.

**Comment by alexanderdean** [comment]
See https://github.com/rslifka/elasticity/issues/88

**Comment by rslifka** [comment]
Elasticity release 6.0 in July 2015 removed all calls that were deprecated and updated to the latest APIs.  I'm not sure why you'd be getting this message :)

**Comment by alexanderdean** [comment]
Thanks for confirming @rslikfa! We are checking some of our internal monitoring tools for any cheeky DescribeJobFlows :-) I think we can safely close this anyway.
