### ISSUE TITLE
Scala Common Enrich: update ua-parser

### ISSUE THREAD

**Issue by bcharp** [snowplow/snowplow#2214]
Hi,
I run into a problem where Internet Explorer 12 Edge, is detected as Chrome 42, because ua-parser 1.3 seems to be a pretty old version.
<img width="1216" alt="capture d ecran 2015-11-25 a 16 26 59" src="https://cloud.githubusercontent.com/assets/472917/11419863/87c1cd2a-942a-11e5-921c-aa3e8ac71ce7.png">

I did'nt find an easy way to update the regexes.yaml that power it all, maybe I'm missing something.

Anyway the 1.3 version date back to 2013 (https://github.com/tobie/ua-parser/releases/tag/java-1.3.0)
and the repo has split into an org https://github.com/ua-parser
The java version seems to be old as well, and the conversation over it tend to promote the clojure version as a replacement https://github.com/ua-parser/uap-java/issues/1
It would be great if you could upgrade it !

Thanks for the awesome works.

**Comment by alexanderdean** [comment]
Hi @bcharp - sure thing, we will upgrade the version as part of #1568

**Comment by BenFradet** [comment]
superseded by #3811
