### ISSUE TITLE
Scala Hadoop Elasticsearch: use manifest for loading bad rows

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2215]
At the moment there is no manifest - the folder of bad rows to load is passed in on the command line (EmrEtlRunner figures out which folder(s) need loading and spawns a job for each).

Going forwards, we will maintain a manifest of which batches (defined by etl_tstamp) have already been loaded, and this will dictate which subsequent batches to load...

**Comment by chuwy** [comment]
Scala Hadoop Elasticsearch has been deprecated.
