### ISSUE TITLE
Clojure Collector: update AccessLogValve to replace empty useragent with "-"

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2216]
[This part](https://github.com/snowplow/snowplow/blob/355de1fce900934d3f8b6fba4f6ecd4adc3e756a/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CljTomcatLoader.scala#L56) of the regex rejects empty user agent strings

**Comment by alexanderdean** [comment]
Cheekily bringing forwards...

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
