### ISSUE TITLE
RDB Loader: use prepared statements

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2217]
Something like [this](https://en.wikipedia.org/wiki/Prepared_statement#Java_JDBC).

Otherwise SQL injection is possible by manipulating the `config[:aws][:s3][:region]` configuration entry used to generate [this statement](https://github.com/snowplow/snowplow/blob/71c90eb808ac7ed6dc99910c623cc712b71120ac/4-storage/storage-loader/lib/snowplow-storage-loader/redshift_loader.rb#L171).

This isn't a security hole at the moment since anybody who can do the injection already has the credentials necessary to directly query the database, but it would be nice to clean it up.

**Comment by alexanderdean** [comment]
Thanks @fblundun, great infosec catch!

**Comment by alexanderdean** [comment]
Hey @chuwy - has this been done in the re-write?

**Comment by chuwy** [comment]
@alexanderdean nope.

**Comment by alexanderdean** [comment]
So the RDB Loader doesn't use prepared statements?

**Comment by chuwy** [comment]
Yes, it uses plain strings.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/18
