### ISSUE TITLE
Update Snowplow Tracker Protocol documentation

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2218]
Suggests that data is sent via `GET`, when these days it's more common to send via `POST`
https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol

**Comment by ihortom** [comment]
@alexanderdean  / @yalisassoon - Added POST as yet another method (local fork).

**Comment by ihortom** [comment]
@alexanderdean could you, please, close this ticket?

**Comment by alexanderdean** [comment]
Sure, closing!
