### ISSUE TITLE
Hadoop Event Recovery: allow the source row to be transformed with JavaScript

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2223]
The idea is that you pass in a JavaScript function which lets you fixup the bad rows for reprocessing.

**Comment by yalisassoon** [comment]
This is genius

**Comment by alexanderdean** [comment]
This would allow eg:

> Write a JavaScript function that inspects the error messages on the bad rows, and where it sees error messages that indicate that a given field caused an issue, mutate the given field to a safe value
