### ISSUE TITLE
Upload to "Download the Clojure collector WAR file or compile it from source" doc page

### ISSUE THREAD

**Issue by iaingray** [snowplow/snowplow#2225]
Path here needs updating.

https://github.com/snowplow/snowplow/wiki/Download-the-Clojure-collector-WAR-file-or-compile-it-from-source

**From:**

Navigate into the clojure collector folder:

    $ cd 2-collectors/clojure-collector
Download the required dependencies:

    $ lein deps

**To:**

Navigate into the clojure collector folder:

    $ cd 2-collectors/clojure-collector/java-servlet
Download the required dependencies:

    $ lein deps

**Comment by alexanderdean** [comment]
Thanks @iaingray !

**Comment by ihortom** [comment]
Updated locally

**Comment by alexanderdean** [comment]
Pushed!
