### ISSUE TITLE
StorageLoader: add ability to retrieve AWS credentials from EC2 role

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2226]
Similar to this:

https://github.com/snowplow/sql-runner/blob/master/run/aws.go#L39

**Comment by fblundun** [comment]
This is technically already possible using ERB templating, e.g.

```
access_key_id: <%= require 'json'; JSON.parse(`curl http://169.254.169.254/latest/meta-data/iam/security-credentials/EMR_EC2_DefaultRole`)['AccessKeyId'] %>
```

In the Kinesis apps we mark that the credentials should come from the role by setting those fields to "iam". Should we do the same thing here?

Of course, if we have the same configuration file for both EER and StorageLoader then this assumes that EER is also running on EC2 with the necessary role.

**Comment by alexanderdean** [comment]
Hey @fblundun - neat trick re. ERB templating!

Agree, let's use "iam" to signify getting the roles from IAM.

> Of course, if we use the same configuration file for both EER and StorageLoader then this assumes that EER is also running on EC2 with the necessary role.
