### ISSUE TITLE
StorageLoader: add support for supplying config file as Base64-encoded string

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2227]
This is so that we can run the StorageLoader from the Hadoop master node.

**Comment by fblundun** [comment]
It is currently possible to do this outside StorageLoader like this:

```bash
./snowplow-storage-loader --config <(base64 --decode encodedconfig)
```

or

```bash
base64 --decode encodedconfig | ./snowplow-storage-loader --config -
```

This is a bit indirect since it requires wrapping SL in a script.

How about adding a new on/off `--base64-decode-config` switch?

**Comment by alexanderdean** [comment]
Neither of those solutions will work for the use case we want, which is
invoking StorageLoader inside Hadoop via script-runner.jar - fundamentally
we have to pass the config as an argument to a jobflow step via the AWS
API, so there is no notion of a config file at that point.

Why don't we add an alternative to the existing --config arg which is
--inline-config and is followed by the encoded string?

**Comment by fblundun** [comment]
Good point. We can have a `--base64-config-string` argument instead.

**Comment by alexanderdean** [comment]
Sounds good!

**Comment by fblundun** [comment]
What is the maximum length for jobflow step arguments? The example config file is 7728 bytes when base 64 encoded.

This functionality can be tested easily with this command:
```
./snowplow-storage-loader --base64-config-string $(base64 -w0 path/to/config.yml)
```

**Comment by alexanderdean** [comment]
I think it's 100-128k bytes...

**Comment by alexanderdean** [comment]
A good collection of enrichment config JSONs make it through okay so we should be fine...

**Comment by fblundun** [comment]
Great!
