### ISSUE TITLE
Document the output format for Scala Kinesis Enrich

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2231]

**Comment by alexanderdean** [comment]
https://github.com/snowplow/snowplow/tree/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs

in TSV format

**Comment by alexanderdean** [comment]
https://github.com/ihortom/snowplow-wiki-temp/wiki/Stream-Enrich

**Comment by ihortom** [comment]
@alexanderdean  - Added reference to the Canonical event model, which describes the fields. Please, push and close.

**Comment by alexanderdean** [comment]
Done, thanks, closing
