### ISSUE TITLE
Update snowplow-runner-and-loader.sh to use JRuby binaries

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2233]

**Comment by fblundun** [comment]
Would it actually download the binaries from Bintray (so it could be used without a local copy of the Snowplow repo), or just build them locally?

**Comment by alexanderdean** [comment]
Hey @fblundun - no deployment step, we would have a config line in the file which the user would edit to point to their local installed copies.

**Comment by fblundun** [comment]
Sounds sensible.
