### ISSUE TITLE
Placeholder for Event Transformer library

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2234]
See: https://github.com/snowplow/snowplow/tree/feature/event-transformers

**Comment by alexanderdean** [comment]
TODO: refresh this branch using 74-onto-73 (to get e.g. #2090)

**Comment by alexanderdean** [comment]
TODO: remove the data-modeling/spark folder from this branch

**Comment by BenFradet** [comment]
this is the analytics sdk, closing
