### ISSUE TITLE
Add dvce_screendensity to the canonical event model

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow#2236]
On mobile devices, the screen resolution doesn't matter much unless we have its density. Having this information on the canonical event model would help us make smarter design decisions, especially on the Android app, making sure the pages/screens work for the most common resolutions.

As a reference, this thread has a very complete explanation on screen resolution and density: http://stackoverflow.com/questions/22397030/difference-between-screen-size-and-screen-density-in-android

**Comment by alexanderdean** [comment]
Good idea, thanks for raising!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/129
