### ISSUE TITLE
Delete Ruby and RVM Setup page?

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2239]
https://github.com/snowplow/snowplow/wiki/Ruby-and-RVM-setup

We should encourage people to use Vagrant to build EER rather than setting up Ruby manually.

What do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
Totally agree - this is a relic from an earlier age. Let's remove.

**Comment by ihortom** [comment]
@alexanderdean - Is there a way to track down any references to the page to be deleted to have them removed proactively as well since deleting this page could raise "broken link" issues?

**Comment by alexanderdean** [comment]
@ihortom - one of our interns, @bamos, wrote a tool a while back: https://github.com/bamos/github-wiki-link-validator

**Comment by alexanderdean** [comment]
Fixed by @ihortom, closing
