### ISSUE TITLE
Add 3rd party (premium) enrichment partners

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#224]
Some partners which could be added:
- AlchemyAPI - for page topic analysis
- 51Degrees, DeviceAtlas, WURFL - for enhanced useragent parsing
- [MaxMind Omni](http://www.maxmind.com/en/web_services_omni) - for enhanced IP address lookup

Note: most of these services are based on API calls. We need to look into whether it's safe to add these into a Hadoop MR job. Some references:
1. http://www.quora.com/How-can-I-optimise-web-service-calls-from-a-hadoop-system
2. http://petewarden.typepad.com/searchbrowser/2011/05/using-hadoop-with-external-api-calls.html

Upstream in the tracking, could be cool to try out Cara from www.imrsv.com

**Comment by yalisassoon** [comment]
I think we can close this ticket and create new ones for any specific third parties we want to integrate?

**Comment by alexanderdean** [comment]
Yes sounds like a plan...
