### ISSUE TITLE
Configure campaign parameters without them being present in the URL (JavaScript Tracker)

### ISSUE THREAD

**Issue by xkidro** [snowplow/snowplow#2247]
Hello Snowplow Community,

I need do campaign tracking but I do not have the ability to set them up as query strings, is it possible to set them up manually for struct events and page views ?

For example :

```javascript
__sp('trackStructEvent', 'widget','click',name,product,position);
```

I have this event, how can I manually setup the utm_source=partner1 utm_campaign=health utm_medium=bottom_ad_unit parameters in the JavaScript Tracker?

**Comment by alexanderdean** [comment]
At the moment, I think your best approach would be to use the JS Tracker's `setCustomUrl` and manually add them to that - @fblundun do you think that would work?

In the future, the utm parameter fields will be moving out of `atomic.events` into a context, so it should be possible to just manually construct that context in the browser. But that's a way off.

**Comment by fblundun** [comment]
Yes, this should work. `setCustomUrl` will make the tracker use a string of your choice rather than `window.location.href`, so you just need to include the campaign parameters in that string's querystring.

**Comment by xkidro** [comment]
Awesome thanks!

**Comment by alexanderdean** [comment]
Closing as there's nothing for us to action here...
