### ISSUE TITLE
[Bug] Invalid locale

### ISSUE THREAD

**Issue by aragnon** [snowplow/snowplow#2248]
```
WARNING! Your environment specifies an invalid locale.
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
```

I don't think a properly configured _virtual_ machine should say this.

**Comment by aragnon** [comment]
The cause of all of this is that simply doing `vagrant ssh` as the instructions suggest is wrong, because incorrect/exotic settings on the client machine leak into the virtual machine. To fix this properly, it would be better to configure the virtual machine to not use the locale settings of the client by default and to have some custom configuration file for those people who want to do things differently

**Comment by BenFradet** [comment]
no more vagrant, closing
