### ISSUE TITLE
EmrEtlRunner: use S3DistCp for all collector_formats?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2252]
Placeholder. Believe we can simplify this logic - and that all input formats can be successfully S3DistCp'ed from processing to HDFS.

**Comment by ninjabear** [comment]
As a possibly relevant side note, I don't think the group by can work without advance knowledge of the filenames. I tried a group by of `(.*)` thinking that everything would be grouped into one file, however the result seemed to be that actually nothing was grouped. I could be wrong I was just going by the time it took my job to finish!

**Comment by alexanderdean** [comment]
I think you could well be right @ninjabear - as I remember it, the GroupBy is notoriously finicky...

**Comment by fblundun** [comment]
My understanding is that the groupBy completely filters out files which do not match the regex, then partitions files according to the captured group.

e.g. for the files

```
0a,
0b,
0c,
1a,
1b,
1c
```

and the regex `0-9(a-z)`, the files would end up in 3 groups like this:

```
0a 1a,
0b 1b,
0c 1c
```

but with the regex `(0-9)-x` they would be grouped like this:

```
0a 0b 0c,
1a 1b 1c
```

So the regex `(.*)` would only concatenate files with exactly the same name.

I haven't actually tried it - this is just based on reading http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_s3distcp.html

**Comment by alexanderdean** [comment]
Great summary @fblundun !

**Comment by alexanderdean** [comment]
If we use S3DistCp for the Thrift files, there is an open question whether or not we can make use of the `.lzo.index` files - and indeed whether it's necessary. `.lzo.index` is really designed for massive files - not the kind of small files that the Kinesis-S3 sink typically generates. So maybe we discard the `.lzo.index` files (and ultimately disable the indexing in Kinesis-S3).

**Comment by BenFradet** [comment]
done in #3136, closing
