### ISSUE TITLE
Update documentation to make clear that shred step is required for Postgres too

### ISSUE THREAD

**Issue by snowindy** [snowplow/snowplow#2261]
I used r71, everything was working okay with
config[:storage][:download][:folder] = /var/storageloader

I migrated to r73 and loading to Postgres stopped working (no events loaded), because file /4-storage/storage-loader/lib/snowplow-storage-loader/postgres_loader.rb was changed

`Dir[File.join(events_dir, '**', 'atomic-events', EVENT_FILES)].select { |f|`
VS PREV
`Dir[File.join(events_dir, '**', EVENT_FILES)].select { |f|`

There is nothing in migration guide http://snowplowanalytics.com/blog/2015/12/04/snowplow-r73-cuban-macaw-released/#upgrading telling about it.

Overall it feels really weird. After migrating to r73 my atomic.events table contains *127* columns while files produced by snowplow-emr-etl-runner contain *130* columns.

I manually tested r73 Postgres storage loading on one of the part_ files with 130 columns. It fails with error `ERROR: extra data after last expected column`

All my snowplow life I've been skipping shredding process (tutorial says it's for Redshift-only), maybe now shredding is mandatory somehow?

**Comment by alexanderdean** [comment]
Hi @snowindy - sorry for the confusion. The shred step is required for both Redshift and Postgres now. You should not be running `--skip shred` with Postgres any longer.

**Comment by alexanderdean** [comment]
Re-opened with new title

**Comment by fblundun** [comment]
Closing as I have updated both the migration guide and the wiki page on shredding.

**Comment by alexanderdean** [comment]
Thanks Fred!
