### ISSUE TITLE
StorageLoader: OOM "Java heap space" error in Postgres download phase

### ISSUE THREAD

**Issue by snowindy** [snowplow/snowplow#2267]
I use Snowplow r73.
There are around 6Gb (462 part files max up to 75 Mb) of shredded events in shredded/good s3 folder.
I try to load them to PG database with storage loaded. It failed with OOM Java heap space.
I skipped all steps except download and see problem persists, this means OOM happens in download phase.
I tried to tweak java heap opts to extend heap up to 1.5 GB which did not solve this problem, OOM still happens.

```
export java_args="-Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=memdump.hprof"
./snowplow-storage-loader -c config.yml -s delete,load,shred,analyze,archive_enriched
```

I see huge binary objects in java heap. Feels like something gets into memory for no reason.
Any way to overcome this?

Memory analyzer leak suspect output:

```
One instance of "org.jruby.RubyHash" loaded by "java.net.URLClassLoader @ 0xe06ce4e0" occupies 40,901,464 (10.92%) bytes. The memory is accumulated in one instance of "byte[]" loaded by "<system class loader>".

Keywords
java.net.URLClassLoader @ 0xe06ce4e0
org.jruby.RubyHash
byte[]


Class Name

Shallow Heap

Retained Heap


byte[40894464] @ 0xf0b38630 e100b94f-86df-4611-bf6e-f4a35a453c60.web.2015-12-23 14:50:00.112.2015-12-15 18:01:01.000..page_view.d64452c8-8eff-4cd6-9b62-ca2fa2df97c4..Studio-Common-Http.Studio-0.9.5.2.clj-1.1.0-tom-0.2.0.hadoop-1.3.0-common-0.18.0.f718a4ed-5a48-4aaa-bfc0-6a05bb26df06....
 40,894,480 40,894,480 
\bytes org.jruby.util.ByteList @ 0xe3f35810
 40 40,894,520 
.\value org.jruby.RubyString @ 0xe3ebc078
 40 40,894,560 
..\value org.jruby.RubyHash$RubyHashEntry @ 0xe3ebc050
 40 40,894,600 
...\[5] org.jruby.RubyHash$RubyHashEntry[11] @ 0xe3ebac68
 64 64 
....\table org.jruby.RubyHash @ 0xe3ebac30
 56 40,899,488 
.....\value org.jruby.RubyHash$RubyHashEntry @ 0xe3ebac08
 40 40,899,528 
......\[4] org.jruby.RubyHash$RubyHashEntry[11] @ 0xe3bff368
 64 64 
.......\table org.jruby.RubyHash @ 0xe3bff330
 56 40,901,464 
........+<Java Local> java.lang.Thread @ 0xe37db878 Ruby-0-Thread-3: /opt/snowplow-r73/snowplow-storage-loader!/gems/sluice-0.2.2/lib/sluice/storage/s3/s3.rb:426 Busy Monitor, Thread
 104 6,864 
........+[0] java.lang.Object[7] @ 0xe3bf1498 »
 48 127,104 
........+variableValueZero org.jruby.runtime.scope.OneVarDynamicScope @ 0xe3f11c80 »
 32 32 



 Accumulated Objects in Dominator Tree 



Class Name

Shallow Heap

Retained Heap

Percentage


org.jruby.RubyHash @ 0xe3bff330
 56 40,901,464 10.92% 
\org.jruby.RubyHash$RubyHashEntry @ 0xe3ebac08
 40 40,899,528 10.92% 
.\org.jruby.RubyHash @ 0xe3ebac30
 56 40,899,488 10.92% 
..\org.jruby.RubyHash$RubyHashEntry @ 0xe3ebc050
 40 40,894,600 10.92% 
...\org.jruby.RubyString @ 0xe3ebc078
 40 40,894,560 10.92% 
....\org.jruby.util.ByteList @ 0xe3f35810
 40 40,894,520 10.92% 
.....\byte[40894464] @ 0xf0b38630 e100b94f-86df-4611-bf6e-f4a35a453c60.web.2015-12-23 14:50:00.112.2015-12-15 18:01:01.000..page_view.d64452c8-8eff-4cd6-9b62-ca2fa2df97c4..Studio-Common-Http.Studio-0.9.5.2.clj-1.1.0-tom-0.2.0.hadoop-1.3.0-common-0.18.0.f718a4ed-5a48-4aaa-bfc0-6a05bb26df06....
 40,894,480 40,894,480 10.92% 


```

**Comment by alexanderdean** [comment]
Hi Eugene,

For a quick fix:

   1. Precede your StorageLoader run with an $ aws s3 cp command to pull
   down the files locally
   2. Run your StorageLoader with --skip download

In terms of the underlying problem: StorageLoader uses a library we wrote
called Sluice, which is a multi-threaded wrapper around the Fog library for
working with S3. The bug could be in either Sluice or Fog.

Note that the Postgres load architecture for Snowplow is pretty archaic at
this point: all enriched events are downloaded from S3 to the orchestration
box running StorageLoader, and then those event files are streamed into a
Postgres instance. It's the only place where there is actual dataflow
through the orchestration box (the Redshift load process is fully remote).

A much cleaner architecture would be to load the events straight from HDFS
into Postgres from the EMR cluster itself. We have a lot of refactoring
planned on our database load architectures for next year.

Cheers,

Alex

On Thu, Dec 24, 2015 at 2:31 PM, Eugene <notifications@github.com> wrote:

> I use Snowplow r73
> There are around 6Gb (462 part files max up to 75 Mb) of shredded events
> in shredded/good s3 folder
> I try to load them to PG database with storage loaded It failed with OOM
> Java heap space
> I skipped all steps except download and see problem persists, this means
> OOM happens in download phase
> I tried to tweak java heap opts to extend heap up to 15 GB which did not
> solve this problem, OOM still happens
>
> export java_args="-Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=memdumphprof"
> /snowplow-storage-loader -c configyml -s delete,load,shred,analyze,archive_enriched
>
> I see huge binary objects in java heap Feels like something gets into
> memory for no reason
> Any way to overcome this?
>
> Memory analyzer leak suspect output:
>
> One instance of "orgjrubyRubyHash" loaded by "javanetURLClassLoader @ 0xe06ce4e0" occupies 40,901,464 (1092%) bytes The memory is accumulated in one instance of "byte[]" loaded by "<system class loader>"
>
> Keywords
> javanetURLClassLoader @ 0xe06ce4e0
> orgjrubyRubyHash
> byte[]
>
>
> Class Name
>
> Shallow Heap
>
> Retained Heap
>
>
> byte[40894464] @ 0xf0b38630 e100b94f-86df-4611-bf6e-f4a35a453c60web2015-12-23 14:50:001122015-12-15 18:01:01000page_viewd64452c8-8eff-4cd6-9b62-ca2fa2df97c4Studio-Common-HttpStudio-0952clj-110-tom-020hadoop-130-common-0180f718a4ed-5a48-4aaa-bfc0-6a05bb26df06
>  40,894,480 40,894,480
> \bytes orgjrubyutilByteList @ 0xe3f35810
>  40 40,894,520
> \value orgjrubyRubyString @ 0xe3ebc078
>  40 40,894,560
> \value orgjrubyRubyHash$RubyHashEntry @ 0xe3ebc050
>  40 40,894,600
> \[5] orgjrubyRubyHash$RubyHashEntry[11] @ 0xe3ebac68
>  64 64
> \table orgjrubyRubyHash @ 0xe3ebac30
>  56 40,899,488
> \value orgjrubyRubyHash$RubyHashEntry @ 0xe3ebac08
>  40 40,899,528
> \[4] orgjrubyRubyHash$RubyHashEntry[11] @ 0xe3bff368
>  64 64
> \table orgjrubyRubyHash @ 0xe3bff330
>  56 40,901,464
> +<Java Local> javalangThread @ 0xe37db878 Ruby-0-Thread-3: /opt/snowplow-r73/snowplow-storage-loader!/gems/sluice-022/lib/sluice/storage/s3/s3rb:426 Busy Monitor, Thread
>  104 6,864
> +[0] javalangObject[7] @ 0xe3bf1498 »
>  48 127,104
> +variableValueZero orgjrubyruntimescopeOneVarDynamicScope @ 0xe3f11c80 »
>  32 32
>
>
>
>  Accumulated Objects in Dominator Tree
>
>
>
> Class Name
>
> Shallow Heap
>
> Retained Heap
>
> Percentage
>
>
> orgjrubyRubyHash @ 0xe3bff330
>  56 40,901,464 1092%
> \orgjrubyRubyHash$RubyHashEntry @ 0xe3ebac08
>  40 40,899,528 1092%
> \orgjrubyRubyHash @ 0xe3ebac30
>  56 40,899,488 1092%
> \orgjrubyRubyHash$RubyHashEntry @ 0xe3ebc050
>  40 40,894,600 1092%
> \orgjrubyRubyString @ 0xe3ebc078
>  40 40,894,560 1092%
> \orgjrubyutilByteList @ 0xe3f35810
>  40 40,894,520 1092%
> \byte[40894464] @ 0xf0b38630 e100b94f-86df-4611-bf6e-f4a35a453c60web2015-12-23 14:50:001122015-12-15 18:01:01000page_viewd64452c8-8eff-4cd6-9b62-ca2fa2df97c4Studio-Common-HttpStudio-0952clj-110-tom-020hadoop-130-common-0180f718a4ed-5a48-4aaa-bfc0-6a05bb26df06
>  40,894,480 40,894,480 1092%
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snowplow/snowplow/issues/2267>.
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 (0)203 589 6116
+44 7881 622 925
@alexcrdean <https://twitter.com/alexcrdean>

**Comment by chuwy** [comment]
Should be fixed in RDB Loader. Closing.
