### ISSUE TITLE
Scala Common Enrich: move JS enrichments below all other enrichments

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2268]
[This](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L439-L443) should be below all other enrichments, so JavaScript enrichment could access any field and context.

**Comment by chuwy** [comment]
@alexanderdean I think I changed my mind on this.
My original intention was to provide derived contexts to JS Enrichment, but now I think it will lead to tangled code in EnrichmentManager and JS enrichment still won't have access to custom contexts.
I think it would be better to change JS enrichment itself, so it can accept derived and custom contexts as second and third arguments (like API Request do).

**Comment by alexanderdean** [comment]
I agree - but let's push this back as it will take some time to design...

**Comment by yalisassoon** [comment]
I don't know that this is the desired behaviour. We're working with a user now where we want to do some tidying up of the data with the JS enrichment (consolidating data from a number of fields in a single field) *before* using it that field as a key with the API enrichment. So we'd want to make sure that the JS tracker enrichment runs *before* the API enrichment.

I think the ideal scenario would be for each user to specify the order in which they want enrichments run?

**Comment by yalisassoon** [comment]
cc @bogaert

**Comment by chuwy** [comment]
I also remember at least [one](http://discourse.snowplowanalytics.com/t/api-enrichment-nil-values/711) case on discourse where preceding JS enrichment could be desired and one opposite (cannot find a link). 

So, this is really should be up to user, we cannot decided for him upfront. Ideally user should have an ability to build a dependency graph of enrichments. See https://github.com/snowplow/snowplow/issues/2260

**Comment by alexanderdean** [comment]
Agree, let's close this and focus efforts on #2260. I've added a comment to that ticket about dependency graphs and closed #853
