### ISSUE TITLE
Elasticity S3DistCp Step: Shredded HDFS -> S3 fails if no data to process

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2315]
Currently the copy step to move shredded data to S3 fails if there's no data (or no shredded data) to copy.

This particularly effects new users who want to run Snowplow regularly (so they can debug the data in Redshift / Elasticsearch) but often have runs without any data

**Comment by alexanderdean** [comment]
This was fixed a while back - basically there is always something to copy now, because Hadoop Shred outputs the `/atomic-events/` folder too...
