### ISSUE TITLE
Snowplow CLI: add support for writing files to S3 with S3DistCp using server-side encryption

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2316]
This will be restricted to the steps that use S3DistCp, which supports the `--s3ServerSideEncryption` option:

http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_s3distcp.html

Background:

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by BenFradet** [comment]
this has been done, closing
