### ISSUE TITLE
Update Clojure collector setup documentation to show how to use lifecycle hooks so that collector can safely downscale

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2318]
Lifecycle hooks can be used to ensure that any instance that is terminated is kept alive for 2 hours after it has been disconnected from the ELB, during which any event logs that have not yet been flushed to S3 are.

**Comment by alexanderdean** [comment]
Edited to 2 hours to ensure all logs rotated

**Comment by alexanderdean** [comment]
Assigning into sprint, please liaise and decide who will do this.

**Comment by ihortom** [comment]
Updated wiki:

- https://github.com/snowplow/snowplow/wiki/Create-a-new-application-in-Elastic-Beanstalk-and-upload-the-WAR-file-into-it
- https://github.com/snowplow/snowplow/wiki/Troubleshooting-Clojure-Collector-instances-to-prevent-data-loss

**Comment by alexanderdean** [comment]
Thanks, @jbeemster can you review?

**Comment by jbeemster** [comment]
In the first one we still seem to be referencing the 1.1.0 release not the 2.0.0 that was recently published.

> https://github.com/snowplow/snowplow/wiki/Create-a-new-application-in-Elastic-Beanstalk-and-upload-the-WAR-file-into-it#alternative-approach-aws-cli

The second one has a few issues still - namely that the whole reason for adding Lifecycle hooks is to allow automated downscaling:

> https://github.com/snowplow/snowplow/wiki/Troubleshooting-Clojure-Collector-instances-to-prevent-data-loss#automatic-downscaling-should-be-disabled

@ihortom can you grab me this week and we can go through this together?

**Comment by BenFradet** [comment]
updated the wiki with Josh's review, closing
