### ISSUE TITLE
EmrEtlRunner: add bootstrap action to prepare AMI >= 3.8.0 for Snowplow

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2320]
This will download the correct version of the commons-codec jar.

**Comment by alexanderdean** [comment]
Think this is not just specific to AMI 4.1.0, but all AMI 4.x.x?

**Comment by fblundun** [comment]
It's AMI 3.8.0 and higher.

**Comment by alexanderdean** [comment]
Cool - can we refine the ticket name please...

**Comment by fblundun** [comment]
Done!
