### ISSUE TITLE
Scala Common Enrich: add SQL Query Enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2321]
The SQL Database Enrichment lets you perform dimension widening on a Snowplow event via a SQL query against a JDBC-capable relational database.

## Database support

Currently supported database types:

* MySQL, plus variants which speak MySQL (e.g. MariaDB, Amazon Aurora)
* PostgreSQL, plus variants which speak PostgreSQL

**Please do not attempt to use this enrichment with analytical databases which support minimal (50-100) concurrent queries (e.g. Redshift).**

## Configuration JSON

The configuration JSON for this enrichment contains five sub-objects:

1. `inputs` specifies the datapoint(s) from the Snowplow event to use as keys when performing your API lookup
2. `database` defines how the enrichment can access your relational database
3. `query` defines how the enrichment should query your relational database
4. `output` lets you tune how you convert the returned row(s) into one or more self-describing JSONs ready to be attached to your Snowplow event
5. `cache` improves the enrichment's performance by storing rows retrieved from your relational database

Here is an example configuration:

```json
{
  "enabled": true,
  "parameters": {
    "inputs": [
      {
        "placeholder": 1,
        "pojo": {
          "field": "user_id"
        }
      },
      {
        "placeholder": 1,
        "json": {
          "field": "contexts",
          "schemaCriterion": "iglu:com.snowplowanalytics.snowplow/client_session/jsonschema/1-*-*",
          "jsonPath": "$.userId"
        }
      },
      {
        "placeholder": 2,
        "pojo": {
          "field": "app_id"
        }
      }
    ],
    "database": {
      "postgresql": {
        "host": "cluster01.redshift.acme.com",
        "port": 5439,
        "sslMode": true,
        "username": "snowplow_enrich_ro",
        "password": "1asIkJed",
        "database": "crm"
      }
    },
    "query": {
      "sql": "SELECT username, email_address, date_of_birth FROM tbl_users WHERE user = ? AND client = ? LIMIT 1",
      "expectedRows": "AT_MOST_ONE"
    },
    "output": {
      "json": {
        "schema": "iglu:com.acme/user/jsonschema/1-0-0",
        "describes": "ALL_ROWS",
        "propertyNames": "CAMEL_CASE"
      }
    },
    "cache": {
      "size": 3000,
      "ttl": 60
    }
  }
}
```

To go through each of these sections in more detail:

### `inputs`

Specify an array of `inputs` to use as keys when performing your API lookup. Each input consists of a `placeholder` and a source: either `pojo` if the datapoint comes from the Snowplow enriched event POJO, or `json` if the datapoint comes from a self-describing JSON inside one of the three JSON fields.

The `placeholder` is the index of the `?` SQL placeholder which this input will be used to populate. It must be an integer greater than or equal to 1.

For the `pojo` source, the field name must be specified. A field name which is not recognized as part of the POJO will be ignored by the enrichment.

For the `json` source, you must specify the field name as either `unstruct_event`, `contexts` or `derived_contexts`. You must then provide two additional fields:

* `schemaCriterion` lets you specify the self-describing JSON you are looking for in the given JSON field. You can specify only the SchemaVer MODEL (e.g. 1-), MODEL plus REVISION (e.g. 1-1-) or a full MODEL-REVISION-ADDITION version (e.g. 1-1-1)
* `jsonPath` lets you provide the [JSON Path statement](https://github.com/gatling/jsonpath#jsonpath) to navigate to the field inside the JSON that you want to use as the input

The lookup algorithm is short-circuiting: the first match for a given key will be used.

### `database`

The `database` section lets you configure how the enrichment should access your relational database. At the moment `postgresql` and `mysql` are supported, with the same fields available for both. Please see the **Database support** section above for notes on compatibility.

Populate all properties in the `postgresql` or `mysql` configuration object, as follows:

* `host`, the hostname or IP address of the database server or cluster
* `port`, the port to connect to the database on
* `sslMode`, whether the database requires connections to use SSL
* `username`, the username to login to the database using
* `password`, the password for this username
* `database`, the name of the specific database to run the query against

**We strongly recommend that the username have minimal read-only permissions on just the entities required to execute the SQL query.**

If your database server has additional authentication in place, such as IP whitelisting, you will need to configure this security to permit access from all of your servers running the Snowplow Enrichment process.

### `query`

Specify the SQL query to run on your relational database to return row(s) to attach to this event. Each query consits of a `sql` and a `expectedRows` property.

The `sql` property contains the SQL statement to run against the database to return row(s). This SQL takes the form of a prepared statement, where each `?` is replaced by the `input` with the corresponding `placeholder` index.

Some notes on the behavior:

* If a placeholder index required in the `sql` prepared statement is not found in any of the `inputs`, then the lookup will not proceed, but this will **not** be flagged as a failure
* A final `;` is optional
* **This enrichment makes no attempt to sanitize the SQL statement, nor to verify that the SQL statement does not have harmful side effects (such as SQL injection)**

The `expectedRows` enum can take the following values:

* `EXACTLY_ONE` - exactly one row is expected. 0 or 2+ rows will throw an error, causing the entire event to fail processing
* `AT_MOST_ONE` - either one or zero rows is expected. 2+ rows will throw an error
* `AT_LEAST_ZERO` - between 0 and N rows are expected - in JSON terms we are dealing with an array of results
* `AT_LEAST_ONE` - between 1 and N rows are expected - i.e. an array of results. 0 rows will throw an error

### `output`

The enrichment adds the returned row(s) into the `derived_contexts` field within a Snowplow enriched event. Because all JSONs in the `derived_contexts` field must be self-describing JSONs, use the `schema` field to specify the Iglu schema URI that you want to attach to the event.

The `describes` property dictates whether the `schema` is the self-describing schema for all rows returned by the query, or whether the `schema` should be attached to each of the returned rows:

* `ALL_ROWS` means that the `schema` should box all returned rows - i.e. one context will always be added to `derived_contexts`, regardless of how many rows that schema contains
* `EVERY_ROW` means that the `schema` should be attached to each returned row - so e.g. if 3 rows are returned, 3 contexts with this same schema will be added to `derived_contexts`

The `propertyNames` property supports reformatting of the returned columns to fit the JSON Schema's conventions better. Supported options are:

* `AS_IS` - preserve the column names exactly as they are
* `CAMEL_CASE` - so `date_of_birth` becomes `dateOfBirth`
* `PASCAL_CASE` - so `date_of_birth` becomes `DateOfBirth`
* `SNAKE_CASE` - so `dateOfBirth` becomes `date_of_birth`
* `LOWER_CASE` - changes all characters to lowercase
* `UPPER_CASE` - changes all characters to uppercase

If these options aren't bespoke enough, remember that you can use column aliasing in your SQL statement to tweak individual column names.

### `cache`

A Snowplow enrichment can run many millions of time per hour, effectively launching a DoS attack on a data source if we are not careful. The `cache` configuration attempts to minimize the number of lookups performed.

The cache is an LRU (least-recently used) cache, where less frequently accessed values are evicted to make space for new values. The `uri` with all keys populated is used as the key in the cache. Configure the `cache` as follows:

* `size` is the maximum number of entries to hold in the cache at any one time
* `ttl` is the number of seconds that an entry can stay in the cache before it is forcibly evicted. This is useful to prevent stale values from being retrieved in the case that your API can return different values for the same key over time

### Single row

With this configuration:

```json
...
"query": {
    "sql": "SELECT username, date_of_birth FROM tbl_users WHERE user = ?",
    "expectedRows": "AT_MOST_ONE"
    },
  "output": {
    "json": {
      "schema": "iglu:com.acme/user/jsonschema/1-0-0",
      "describes": "ALL_ROWS",
      "propertyNames": "CAMEL_CASE"
    }
  },
...
```

And this query result:

```sql
SELECT username, date_of_birth FROM tbl_users WHERE user = 123;
| username | date_of_birth |
|----------|---------------|
|     karl |    1980-06-12 |
```

This would be added to the `derived_contexts` array:

```json
{
  "schema": "iglu:com.acme/user/jsonschema/1-0-0",
  "data": {
    "username": "karl",
    "dateOfBirth": "1980-06-12T00:00:00"
  }
}
```

With this query result:

```sql
SELECT username, date_of_birth FROM tbl_users WHERE user = 123;
| username | date_of_birth |
|----------|---------------|
```

No context would be added to the `derived_contexts` array, but the event would continue processing.

With this query result:

```sql
SELECT username, date_of_birth FROM tbl_users WHERE user = 123;
| username | date_of_birth |
|----------|---------------|
|     karl |    1980-06-12 |
|     mary |    1975-03-22 |
```

An error would be triggered, on account of the `AT_MOST_ONE` setting, and the event would be rejected.

### Multiple rows

With this configuration:

```json
...
"query": {
    "sql": "SELECT * FROM product WHERE category = ?",
    "expectedRows": "AT_LEAST_ZERO"
    },
  "output": {
    "json": {
      "schema": "iglu:com.acme/products/jsonschema/1-0-0",
      "describes": "ALL_ROWS",
      "propertyNames": "AS_IS"
    }
  },
...
```

And this query result:

```sql
SELECT * FROM product WHERE category = 'homeware';
| SKU | prod_name |
|-----|-----------|
| 123 |      iPad |
| 456 |  Ray-Bans |
```

This single context would be added to the `derived_contexts` array:

```json
{
  "schema": "iglu:com.acme/products/jsonschema/1-0-0",
  "data": [
    {
      "SKU": "123",
      "prod_name": "iPad"
    },
    {
      "SKU": "456",
      "prod_name": "Ray-Bans"
    }    
  ]
}
```

If we change the configuration to:
```json
...
  "output": {
    "json": {
      "schema": "iglu:com.acme/product/jsonschema/1-0-0",
      "describes": "EVERY_ROW",
      "propertyNames": "LOWER_CASE"
    }
  }
...
```

Then two contexts would be added to the `derived_contexts` array:

```json
{
  "schema": "iglu:com.acme/product/jsonschema/1-0-0",
  "data": {
    "sku": "123",
    "prod_name": "iPad"
  }
}
{
  "schema": "iglu:com.acme/product/jsonschema/1-0-0",
  "data": {
    "sku": "456",
    "prod_name": "Ray-Bans"
  }
}
```

**Comment by alexanderdean** [comment]
This isn't finished - but assigning to you prior to our 1:1...

**Comment by chuwy** [comment]
Got it.

**Comment by alexanderdean** [comment]
This is ready for review now - @yalisassoon, @bogaert, @chuwy let me know your thoughts!

**Comment by bogaert** [comment]
> A Snowplow enrichment can run many millions of time per hour, effectively launching a DoS attack on a data source if we are not careful. The cache configuration attempts to minimize the number of lookups performed.

That makes sense - but I'm still a bit worried about Redshift. It support at most 50 concurrent queries (but is configured by default to only 5), so even running 500 queries would be a heavy load.

**Comment by alexanderdean** [comment]
Yes - we can warn users not to use this with Redshift. I have removed the explicit reference to Redshift support from the ticket.

**Comment by alexanderdean** [comment]
Added warning

**Comment by alexanderdean** [comment]
Pushing back as API lookup is getting ready for the release runway

**Comment by alexanderdean** [comment]
Changed the `schemaCriterion` to:

    "schemaCriterion": "iglu:com.snowplowanalytics.snowplow/client_session/jsonschema/1-*-*"

**Comment by alexanderdean** [comment]
Renamed to "SQL Query Enrichment"

**Comment by chuwy** [comment]
I think we need to add to notes in query section that it is on user's behalf to surround placeholders with quotes. We cannot determine type of input in runtime.
Taking it in account, I don't think it really makes a lot of sense to use question marks as placeholders rather than template-keys (as in API Request enrichment). AFAIK it's common practice because of tools like Java's [`PreparedStatement`](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html), but it's useless in our case and template-keys much easier to implement correctly and safer to use.

**Comment by alexanderdean** [comment]
Hmm - prepared statements are best practice from an info-sec perspective. It's very easy for string manipulation of SQL queries to facilitate SQL injection. Why do you say that prepared statements are useless in our case?

**Comment by chuwy** [comment]
We need to provide types when building SQL query with prepared statement.
`PreparedStatement` works with method like:
```scala
statement.setBoolean(index: Int, x: Boolean): Unit
statement.setString(index: Int, x: String): Unit
...
```
One more option is to add expected `columnType` to inputs and try to cast everything. But this also will not work well with DB-specific features like Postgres JSON.

**Comment by alexanderdean** [comment]
Why can't we just take the type from either the relevant POJO property or the JSON Path property, then use that type to switch on `setBoolean` versus `setString` etc? So the whole thing is strongly typed versus just stringly typed...

**Comment by chuwy** [comment]
Hey @alexanderdean,

Here's a short list of proposals for configuration. Actually, only first one is really desirable for me, last two are just something we can think about.

+ I think `expectedRows` should really belong to output. I need to pass `Query#expectedRows` to methods in `Output` to get it work. Instead it could be just inner property of `Output` class. I think it could be easier to understand from user perspective as well.
+ If we remove `expectedRows` from `Query` it will be just `case class Query(sql: String)`, no more methods, no more properties, just a `sql` which I passing between functions. Not a problem, but looks not very elegant.  May be we can look at `db` object as at abstract Source of data with access-configuration and query (as we do for ApiRequestEnrichment's `api` object).  Or it could be a separate root-level string key.
+ I also think we can get rid of `propertyName`. SQL has `AS` keyword which allows us to set any column name we want (although user will need to embrace in double-quotes to preserve case)

**Comment by alexanderdean** [comment]
Hey @chuwy ! Thanks for these points, they all make sense as alternative approaches. Here are my thoughts:

* `expectedRows` - agree, let's move to `output`
* `query.sql` versus other approaches. Although it is tempting to move the SQL into a top-level `query` or into the `database`, I think keeping it separate is cleanest and most futureproof. We can always revisit this in the future
* `propertyNames` - I agree that this is not functionally necessary due to `AS alias`, but this functionality protects us in the case that column names are inconsistent and the user forgets to fix them with aliasing (e.g. user just writes `SELECT *`)
