### ISSUE TITLE
Scala Common Enrich: consolidate CljTomcatLoader to handle non url-encoded headers

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2322]
Example bad row:

``` json
{"line":"2016-01-06\t19:11:32\t-\t43\t170.185.92.17\tGET\t170.185.92.17\t/i\t200\thttp://www.valvoline.com/our-products/motor-oil-recommender?year=2012&make=Toyota&model=Camry&engine=SE, 4CYL 2.5L (2ARFE)\tMozilla%2F5.0+%28Windows+NT+6.1%3B+WOW64%3B+Trident%2F7.0%3B+rv%3A11.0%29+like+Gecko\te=pv&url=http%3A%2F%2Fwww.valvoline.com%2Four-products%2Fmotor-oil-recommender%3Fyear%3D2012%26make%3DToyota%26model%3DCamry%26engine%3DSE%2C%204CYL%202.5L%20(2ARFE)&page=Motor%20Oil%20Recommender%20-%20Valvoline%C2%AE&refr=http%3A%2F%2Fwww.valvoline.com%2F&tv=js-2.5.2&tna=co&aid=ValvDMC_valdotcom&p=web&tz=America%2FNew_York&lang=en-US&cs=utf-8&f_pdf=0&f_qt=0&f_realp=0&f_wma=0&f_dir=1&f_fla=1&f_java=0&f_gears=0&f_ag=1&res=1600x900&cd=24&cookie=1&eid=d8d09818-6fe5-4716-9599-3d091f4bcc07&dtm=1452107279593&vp=1600x806&ds=1600x806&vid=1&sid=7cd5d4b1-8f2a-4d14-9313-2852242af339&duid=2a20eac75ab006e9&fp=3019406417&cx=eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5dGljcy5zbm93cGxvdy9jb250ZXh0cy9qc29uc2NoZW1hLzEtMC0wIiwiZGF0YSI6W3sic2NoZW1hIjoiaWdsdTpjb20uc25vd3Bsb3dhbmFseXRpY3Muc25vd3Bsb3cvd2ViX3BhZ2UvanNvbnNjaGVtYS8xLTAtMCIsImRhdGEiOnsiaWQiOiI1NmViMDgwZC1jZDRhLTQ0ZmYtYWYxYS1kOWUzOGE1OGY4ZjEifX1dfQ&cv=clj-1.0.0-tom-0.2.0&nuid=a79cbea4-fbf9-4af3-aa54-0c5034ef897c\t-\t-\t-\t-\t-","errors":["Line does not match raw event format for Clojure Collector"]}
```

The issue appears to be that the URL contains spaces, so the line fails [this regex](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CljTomcatLoader.scala#L41-L63).

Either we need to update the regex (so it uses tabs rather than whitespace to delimit the different components of the Clojure logs) or update the Clojure collector to log the URL encoded URLs (so no whitespaces are shown and the regex passes.

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881

**Comment by alexanderdean** [comment]
We will probably fix this in the loader.

**Comment by BenFradet** [comment]
Looked into the log valve and there is no way to ensure proper url encoding of extracted headers (e.g. referer), renamed and descheduled

**Comment by alexanderdean** [comment]
Okay, understood

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/254
