### ISSUE TITLE
Placeholder for resurrecting tid as just a random nonce

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2324]
There are various environments (e.g. [AMP](https://www.ampproject.org/), ad servers) that won't make a UUID generator available when constructing a Snowplow tracker pixel, but will offer a random number/string. It is worth setting this to bust caches.

So we should tweak Snowplow Common Enrich and Redshift/Postgres to support `tid` as just a random string (let's say up to 256 bytes long for safety). I don't believe it requires any updates to the trackers.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/132
