### ISSUE TITLE
Scala Stream Collector: configure the ability to use IP address as partition key

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2331]
The SSC doesn't guarantee that records will be sent to Kinesis in the same order they arrive, which means sending events from the same IP to the same shard doesn't do anything.

So we should either stop using the IP address as a partition key or start guaranteeing preservation of record order.

**Comment by fblundun** [comment]
In the end we decided to make this a configurable setting.

**Comment by alexanderdean** [comment]
The default will be random sharding - but if you need events sharded by `ipAddress` (so that users are approximately tied to one shard), you can still switch that on.

**Comment by fblundun** [comment]
I'll add an optional boolean configuration setting called collector.sink.kinesis.useIpAddressAsPartitionKey defaulting to false.
