### ISSUE TITLE
Document Zapier integration

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2337]
We already integrate with Zapier via the Iglu webhook adapter.

**Comment by yalisassoon** [comment]
This should make it easy to fire Snowplow events in response to actions in all the different third party webhooks that Zapier supports: https://zapier.com/app/explore

**Comment by alexanderdean** [comment]
https://zapier.com/zapbook/webhook/

**Comment by alexanderdean** [comment]
Closing as an issue, could be written somewhere as a recipe
