### ISSUE TITLE
Quickstart does not execute warning free

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2342]
Various warnings give a rather bad first impression while following the quickstart. I didn't check whether or not these are actually catastrophic, but it's certainly inconvenient if the installation of the guest additions failed.  

```
stdin: is not a tty
```

```
Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 5.0.10. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
```

If the version of Virtualbox is important, fix the version of Virtualbox, if needed.

**Comment by alexanderdean** [comment]
Warnings in your VirtualBox boot are not in our control to fix, closing
