### ISSUE TITLE
Scala Common Enrich: add DynamoDB Read Enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2345]
The DynamoDB Read Enrichment lets you perform dimension widening on a Snowplow event by reading an item from a [DynamoDB](https://aws.amazon.com/dynamodb/) table.

Currently this read is performed using DynamoDB's `GetItem` API operation only.
## Configuration JSON

The configuration JSON for this enrichment contains five sub-objects:
1. `inputs` specifies the datapoint(s) from the Snowplow event to use as keys when getting your item from DynamoDB
2. `dynamodb` configures access to DynamoDB
3. `read` defines how the enrichment can retrieve an item from your DynamoDB table
4. `outputs` lets you tune how you convert the returned item(s) into one or more self-describing JSONs ready to be attached to your Snowplow event
5. `cache` improves the enrichment's performance by storing values retrieved from DynamoDB

Here is an example configuration:

``` json
{
  "enabled": true,
  "parameters": {
    "inputs": [
      {
        "key": "user",
        "pojo": {
          "field": "user_id"
        }
      },
      {
        "key": "user",
        "json": {
          "field": "contexts",
          "schemaCriterion": "iglu:com.snowplowanalytics.snowplow/client_session/jsonschema/1-*-*",
          "jsonPath": "$.userId"
        }
      },
      {
        "key": "client",
        "pojo": {
          "field": "app_id"
        }
      }
    ],
    "dynamodb": {
      "region": "us-east-1",
      "authentication": {
        "basic": {
          "accessKey": "xxx",
          "secretKey": "yyy"
        }
      }
    },
    "read": {
      "get": {
        "table": "Users",
        "primaryKey": {
          "hashKey": {
            "name": "UserId",
            "value": "{{client}}:{{user}}",
            "type": "STRING"
          },
          "rangeKey": null
        },
        "projectionExpression": "Username, EmailAddress, DateOfBirth",
        "consistentRead": false,
        "expectedItems": "AT_MOST_ONE"
      }
    },
    "outputs": [ {
      "json": {
        "jsonPath": "$.record",
        "schema": "iglu:com.acme/user/jsonschema/1-0-0",
        "propertyNames": "CAMEL_CASE"
      }
    } ],
    "cache": {
      "size": 3000,
      "ttl": 60
    }
  }
}
```

To go through each of these sections in more detail:
### `inputs`

Specify an array of `inputs` to use as keys when performing your API lookup. Each input consists of a `key` and a source: either `pojo` if the datapoint comes from the Snowplow enriched event POJO, or `json` if the datapoint comes from a self-describing JSON inside one of the three JSON fields. The `key` can be referred to later in the `read.get.primaryKey.hashKey.value` and `read.get.primaryKey.rangeKey.value` properties. 

For `pojo`, the field name must be specified. A field name which is not recognized as part of the POJO will be ignored by the enrichment.

For `json`, you must specify the field name as either `unstruct_event`, `contexts` or `derived_contexts`. You must then provide two additional fields:
- `schemaCriterion` lets you specify the self-describing JSON you are looking for in the given JSON field. You can specify only the SchemaVer MODEL (e.g. 1-), MODEL plus REVISION (e.g. 1-1-) or a full MODEL-REVISION-ADDITION version (e.g. 1-1-1)
- `jsonPath` lets you provide the [JSON Path statement](https://github.com/gatling/jsonpath#jsonpath) to navigate to the field inside the JSON that you want to use as the input

The lookup algorithm is short-circuiting: the first match for a given key will be used.
### `dynamodb`

The `api` section lets you configure how the enrichment should access DynamoDB. This section consists of a `region` string and a `authentication` sub-object.

DynamoDB tables are tied to a single region within a given AWS account, so you must specify the `region`.

For `authentication`, the following options are supported:
1. `basic`, where you specify the raw AWS access key and secret key
2. `instanceProfile`, where the credentials are fetched from the EC2 metadata service on the instance running the enrichment
3. `environmentVariables`, which will use the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
4. `classpathProperties`, where a properties file on the classpath is used
5. `defaultChain`, which will attempt to find AWS credentials using the default credential provider chain

For `basic` you must specify the access and secret keys in the sub-object:

``` json
"authentication": {
  "basic": {
    "accessKey": "xxx",
    "secretKey": "yyy"
  }
}
```

For all other authentication options, set the option to an empty object, like so:

``` json
"authentication": {
  "environmentVariables": {}
}
```
### `read`

The `read` section determines how you read data from your DynamoDB table. Currently, only one option is supported: `get`, which uses the DynamoDB `GetItem` API operation. In the future we may add support for the DynamoDB `Query` API operation too. 
#### `read`:`get`

For a `get`, you must specify a `table`, configure a `primaryKey`, provide an optional `projectionExpression` if required, choose `consistentRead` or not, and specify the `expectedItems`. Let's go through these in turn.

You need to specify the name of your DynamoDB table as `table`.

Your DynamoDB table will be configured with a [primary key](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataModel.html#DataModel.PrimaryKey) consisting of either **only** a hash key, or a hash key **plus** partition key. Thus you must specify the `hashKey`, providing the `name`, `value` and `type`:
- The `name` identifies the table attribute which is the hash key
- Within the `value`, you can template the `keys` named in your `inputs` section; the template syntax for a given key is `{{key}}`. If a specified `{{key}}` cannot be found in any of the `inputs`, no items can be retrieved; whether or not this causes an error depends on the `expectedItems` setting, below
- Supported values for `type` are `STRING`, `NUMBER` or `BINARY`. A mismatch between the `type` and the actual contents of the corresponding `value`, will throw an error, causing the entire event to fail processing

The fields for the `partitionKey` (if set) are the same.

DynamoDB returns all of the item attributes by default; to get just some of the attributes, set `projectionExpression` to the list of attributes you want to return. Find out more about [projection expressions](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html#Expressions.AccessingItemAttributes.ProjectionExpressions).

You can set `consistentRead` to ensure that the response reflects the results of any recently completed write operation (`PutItem`, `UpdateItem` or `DeleteItem`) - this is at the cost of availability.

Finally, the `expectedItems` enum can take the following values:
- `EXACTLY_ONE` - exactly one item is expected. 0 items will throw an error, causing the entire event to fail processing
- `AT_MOST_ONE` - either one or zero items is expected
### `outputs`

This enrichment lets you package the item attributes returned from DynamoDB as one or more derived contexts to add to your event. We use the Document API's `item.toJSONPretty()` to convert the returned item attributes into JSON.

Then, within the `outputs` array, each `json` entry contains a `jsonPath` configuration field that lets you specify which part of the returned JSON you want to add to your enriched event. `$` can be used if you want to attach returned JSON as is.

If the JSON Path specified cannot be not found within the returned JSON, then the lookup (and thus the overall event) will be flagged as a failure. 

The enrichment adds the selected JSON into the `derived_contexts` field within a Snowplow enriched event. Because all JSONs in the `derived_contexts` field must be self-describing JSONs, use the `schema` field to specify the Iglu schema URI that you want to attach to the event.

The `propertyNames` property supports reformatting of the returned DynamoDB attributes to fit the naming conventions for your JSON Schema better, if necessary. Supported options are:
- `AS_IS` - preserve the column names exactly as they are
- `CAMEL_CASE` - so `date_of_birth` becomes `dateOfBirth`
- `PASCAL_CASE` - so `date_of_birth` becomes `DateOfBirth`
- `SNAKE_CASE` - so `dateOfBirth` becomes `date_of_birth`
- `LOWER_CASE` - changes all characters to lowercase
- `UPPER_CASE` - changes all characters to uppercase

If these options aren't bespoke enough, remember that you can use column aliasing in your SQL statement to tweak individual column names.

The `outputs` array must have at least one entry in it.
### `cache`

A Snowplow enrichment can run many millions of time per hour, easily exceeding the provisioned read throughput you have configured for your DynamoDB table. The `cache` configuration attempts to minimize the number of reads performed.

The cache is an LRU (least-recently used) cache, where less frequently accessed values are evicted to make space for new values. The `uri` with all keys populated is used as the key in the cache. Configure the `cache` as follows:
- `size` is the maximum number of entries to hold in the cache at any one time
- `ttl` is the number of seconds that an entry can stay in the cache before it is forcibly evicted. This is useful to prevent stale values from being retrieved in the case that your API can return different values for the same key over time
### Source data

All examples are based on the [Creating Tables and Loading Sample Data](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SampleData.CreateTables.html) DynamoDB documentation.
### Hash key example

In the `ProductCatalog` table, data looks like this:

```
Id  | Title          | ISBN           | Authors   | Price | Dimensions       | PageCount | InPublication | ProductCategory
101 | Book 101 Title | 111-1111111111 | [Author1] | 2     | 8.5 x 11.0 x 0.5 | 500       | true          | Book
```

where `Id` is the hash key (a DynamoDB `Number`) and there is no range key.

With this configuration:

``` json
"read": {
  "get": {
    "table": "ProductCatalog",
    "primaryKey": {
      "hashKey": {
        "name": "UserId",
        "value": "{{bookId}}",
        "type": "NUMBER"
      },
      "rangeKey": null
    },
    "projectionExpression": "Id, ISBN, Authors, InPublication",
    "consistentRead": false,
    "expectedItems": "AT_MOST_ONE"
  }
},
"outputs": [ {
  "json": {
    "jsonPath": "$",
    "schema": "iglu:com.acme/product/jsonschema/1-0-0",
    "propertyNames": "CAMEL_CASE"
  }
} ],
```

If `{{bookId}}` evaluates to `101`, then this would be added to the `derived_contexts` array:

``` json
{
  "schema": "iglu:com.acme/product/jsonschema/1-0-0",
  "data": {
    "id": 101,
    "isbn": "111-1111111111",
    "authors": [ "Author1" ],
    "inPublication": true
  }
}
```

If `{{bookId}}` evaluates to a number not found in the table, then nothing will be added to the `derived_contexts` - but there will not be a failure, because `expectedItems` is set to `AT_MOST_ONE`.
### Hash and range key example

In the `Reply` table, data looks like this:

```
Id                                | ReplyDateTime            | Message                        | PostedBy
Amazon DynamoDB#DynamoDB Thread 1 | 2015-09-15T19:58:22.947Z | DynamoDB Thread 1 Reply 1 text | User A
```

where `Id` is the hash key (a DynamoDB `String`) and `ReplyDateTime` (another DynamoDB `String) is the range key.

With this configuration:

``` json
"read": {
  "get": {
    "table": "ProductCatalog",
    "primaryKey": {
      "hashKey": {
        "name": "Id",
        "value": "{{messageId}}",
        "type": "STRING"
      },
      "rangeKey": {
        "name": "ReplyDateTime",
        "value": "{{messageTimestamp}}",
        "type": "STRING"
      },
    },
    "projectionExpression": null,
    "consistentRead": true,
    "expectedItems": "EXACTLY_ONE"
  }
},
"outputs": [ {
  "json": {
    "jsonPath": "$",
    "schema": "iglu:com.acme/message/jsonschema/1-0-0",
    "propertyNames": "SNAKE_CASE"
  }
} ],
```

If `{{messageId}}` evaluates to `Amazon DynamoDB#DynamoDB Thread 1` and `{{messageTimestamp}}` evaluates to `2015-09-15T19:58:22.947Z`, then this would be added to the `derived_contexts` array:

``` json
{
  "schema": "iglu:com.acme/message/jsonschema/1-0-0",
  "data": {
    "id": "Amazon DynamoDB#DynamoDB Thread 1",
    "reply_date_time": "2015-09-15T19:58:22.947Z",
    "message": "DynamoDB Thread 1 Reply 1 text",
    "posted_by": "User A"
  }
}
```

If the `{{messageId}}` and `{{messageTimestamp}}` together do not match to any item in the table, then an error would be thrown and the event would be rejected, due to the `EXACTLY_ONE` setting for `expectedItems`.

**Comment by alexanderdean** [comment]
Renamed to DynamoDB Read Enrichment, as Query has a specific meaning in the DynamoDB API.

**Comment by alexanderdean** [comment]
Hi @chuwy - this is ready for your review now, please let me know any feedback!

**Comment by alexanderdean** [comment]
Hey @chuwy - can you review and feedback on this on Monday please?

**Comment by chuwy** [comment]
Everything makes sense for me.

**Comment by RyanCodes** [comment]
@chuwy @alexanderdean can this enrichment be used?

**Comment by chuwy** [comment]
Hi @RyanCodes. No, unfortunately it hasn't been implemented. But we just didn't have time for it, if anyone is willing to make a PR - it will be welcomed.

**Comment by RyanCodes** [comment]
@chuwy thanks for getting back to me! where would one start to construct a PR is there documentation somewhere that can help guide be to the proper repository?

**Comment by chuwy** [comment]
@RyanCodes you can look at our [contributing guide](https://github.com/snowplow/snowplow/blob/master/CONTRIBUTING.md) as a general recommendation. If you're looking something more technical then you can have a look at [SQL Query enrichment](https://github.com/snowplow/snowplow/issues/2321) and [API Request enrichment](https://github.com/snowplow/snowplow/issues/2051) implementations, which should be very similar to DynamoDB (although I believe DynamoDB should be more straightforward).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/135
