### ISSUE TITLE
wrong screenshot of "Troubleshooting jobs on Elastic MapReduce" wiki page

### ISSUE THREAD

**Issue by luochenhuan** [snowplow/snowplow#2346]
On [Diagnosing an ETL job failure wiki](https://github.com/snowplow/snowplow/wiki/Troubleshooting-jobs-on-Elastic-MapReduce#diagnosing-an-etl-job-failure), the screenshot for bootstraping failure and way-through failure are the same.

**Comment by alexanderdean** [comment]
Thanks for raising @luochenhuan !

**Comment by ihortom** [comment]
@alexanderdean, this was fixed earlier, please, close. When updating the link didn't realise that there was actually a ticket opened for it.

**Comment by alexanderdean** [comment]
Great, closing
