### ISSUE TITLE
Scala Hadoop Enrich: way of improving error trap with Thrift input?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2347]
Cascading's error trap for unexpected exceptions is great with textual input formats but useless with formats like Thrift. Example output:

```
[B@e3c15ea
[B@64af48e9
[B@68344ac0
[B@34891c4a
[B@47d2eae9
[B@1a71ec39
[B@4601ec11
[B@77496cbe
[B@484112ab
[B@2689338e
[B@10904e3a
[B@36db4683
```

Not sure if there is a solution here, but worth exploring.

**Comment by BenFradet** [comment]
There is no error trap since the move to Spark, closing

**Comment by alexanderdean** [comment]
Does that mean that all the `continue_on_unexpected_error` and `errors:` bucket paraphernalia is no longer used?

**Comment by BenFradet** [comment]
it's been kept for backwards-compatibility purposes

**Comment by alexanderdean** [comment]
Let's create a ticket to track removing this from the product, even if 90% of this will go "for free" when we move to Dataflow Runner...

**Comment by BenFradet** [comment]
>even if 90% of this will go "for free" when we move to Dataflow Runner...

It depends on how long we want to keep supporting the scalding-based pipeline for.

**Comment by alexanderdean** [comment]
Right - let's open up a ticket to discuss this.
