### ISSUE TITLE
Hadoop Event Recovery: update README instructions

### ISSUE THREAD

**Issue by iaingray** [snowplow/snowplow#2348]
The Ruby EMR client is now deprecated and I ran into trouble with the default roles requirement following the instructions.

I got it working using the AWS CLI EMR client with the following command:

````
aws emr create-cluster --name "Extract raw events from Snowplow bad row JSONs" --ami-version 3.11 \
--use-default-roles --ec2-attributes KeyName={{EC2_KEY_NAME}} \
--instance-type m3.xlarge --instance-count 3 \
--log-uri s3://{{PATH_TO_LOGGING_BUCKET}} \
--steps Type=CUSTOM_JAR,Name="Extract Bad Rows",ActionOnFailure=TERMINATE_CLUSTER,Jar=s3://snowplow-hosted-assets/3-enrich/scala-bad-rows/snowplow-bad-rows-0.1.0.jar,Args=["com.snowplowanalytics.hadoop.scalding.SnowplowBadRowsJob","--hdfs","--input","s3n://{{PATH_TO_YOUR_FIXABLE_BAD_ROWS}}","--output","s3n://{{PATH_WILL_BE_STAGING_FOR_EMRETLRUNNER}}"] \
--auto-terminate
````

Iain

**Comment by alexanderdean** [comment]
Thanks for raising @iaingray - assigning to @ihortom ...

**Comment by ihortom** [comment]
@alexanderdean - Updated locally.

**Comment by alexanderdean** [comment]
Hey @ihortom - thanks for this! If you change your commit message to:

     Update Scala Hadoop Bad Rows documentation to use AWS CLI EMR (close #2348)

then this ticket will automatically be merged when we merge this commit to master...

**Comment by ihortom** [comment]
@alexanderdean - Done.

**Comment by ihortom** [comment]
@alexanderdean - It was done [locally](https://github.com/ihortom/snowplow/tree/master/3-enrich/scala-hadoop-bad-rows) a while ago but still hasn't been pushed to [origin](https://github.com/snowplow/snowplow/tree/master/3-enrich/scala-hadoop-bad-rows).

**Comment by alexanderdean** [comment]
That's fine - it's in a PR now:

https://github.com/snowplow/snowplow/pull/2396

It takes time for PRs to be merged to master...
