### ISSUE TITLE
Instructions out of date

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2349]
The Amazon tool suite referred to here is deprecated. These instructions should be rewritten to use awscli. 

https://github.com/snowplow/snowplow/wiki/Enable-support-for-HTTPS#openssl-prep-keys

**Comment by alexanderdean** [comment]
Thanks for raising! Assigning...

**Comment by 0xABAB** [comment]
Wow, that's fast. Do you use some special tooling to respond that fast?

**Comment by alexanderdean** [comment]
We get all notifications into our internal chat!

**Comment by 0xABAB** [comment]
Very nice.

**Comment by ihortom** [comment]
@alexanderdean - Deprecated the info and provided the link to the instructions from Amazon docs. It might not be sufficient but it's not something I could verify myself. Our own instructions could be provided when we, say, renew our certificate.

**Comment by alexanderdean** [comment]
Thanks @ihortom - will leave this open till we re-write the section. We should probably also change these instructions to assume the user is working with an AWS-purchased certificate to simplify things.

**Comment by BenFradet** [comment]
moving to docs, closing
