### ISSUE TITLE
Update EmrEtlRunner installation: remove build instructions from 3. Installation

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2351]
* https://github.com/snowplow/snowplow/wiki/1-Installing-EmrEtlRunner#22-software
* https://github.com/snowplow/snowplow/wiki/1-Installing-EmrEtlRunner#3-installation

Steps:

* Update this to reflect the JRuby artifacts on Bintray
* Remove talk of building the CLI tool oneself - this setup guide is for devops, not developers

**Comment by alexanderdean** [comment]
@ihortom if you read through the Snowplow release blog posts you should get an idea of how we recommend installing EmrEtlRunner now. You can also talk to @chuwy and @ninjabear about this today...

**Comment by ihortom** [comment]
@alexanderdean this ticket is esentially the same as [#2371](https://github.com/snowplow/snowplow/issues/2371). Could be closed.

**Comment by alexanderdean** [comment]
It still needs some work - I have updated the title now!

**Comment by ihortom** [comment]
@alexanderdean you can review the the [forked version](https://github.com/ihortom/snowplow-wiki-temp/wiki/1-Installing-EmrEtlRunner) of the page. Also I noticed the same problem with [StorageLoader installation](https://github.com/snowplow/snowplow/wiki/1-installing-the-storageloader)

**Comment by alexanderdean** [comment]
Really nice @ihortom - I have pushed to master, closing
