### ISSUE TITLE
Ambiguous language in Google Tag Manager related documentation

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2353]
"In general, if the data point is directly related to the webpage being loaded, it makes sense to push that data point into the data layer at page load time. For example, if on the product pages on an online shop, it would make sense to push key product details (name, sku, price, category) with the page load, by inserting the following code in the page before the container tags:"

Do you mean that the server application process should inject that into the HTML sent to the browser? Pushing it at page load time could also mean that some piece of JavaScript collects the relevant information, and then subsequently puts it into dataLayer, which would be more fragile and slower for the consumer device, probably. 

It is also possible that you intended it to be ambiguous, but I'd prefer a short elaboration of the possibilities in that case, like I did above.

**Comment by alexanderdean** [comment]
@ihortom - worth talking to @yalisassoon about this one...

**Comment by ihortom** [comment]
@yalisassoon - Do you agree something needs to be rephrased? The excerpt refers to [this](https://github.com/snowplow/snowplow/wiki/Integrating%20javascript%20tags%20with%20Google%20Tag%20Manager#14-work-out-how-to-structure-the-data-passed-into-datalayer) section.

**Comment by BenFradet** [comment]
closing
