### ISSUE TITLE
Change example in-bucket name in wiki to s3://my-in-bucket

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2359]
https://github.com/snowplow/snowplow/wiki/Common-configuration

**Comment by ihortom** [comment]
Updated locally

**Comment by alexanderdean** [comment]
Done by @ihortom !

**Comment by alexanderdean** [comment]
Actually, this should be slightly different - I've changed the title and re-opened

**Comment by ihortom** [comment]
Done.

**Comment by alexanderdean** [comment]
Re-pushed, closing
