### ISSUE TITLE
Missing word in documentation

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2362]
2.5. Select the type of collector you're using and enter the relevant details. If you're using the Cloudfront collector you will need to enter the Cloudfront subdomain. If you're using the Clojure collector (or any other collector) you will need to enter the or the endpoint collector URL.

"enter the ???"

**Comment by ihortom** [comment]
For the sake of clarity, the page being referenced is [this](https://github.com/ihortom/snowplow-wiki-temp/wiki/Pixel-tracker-setup). @fblundun could you suggest what was meant here?

**Comment by yalisassoon** [comment]
I think it should just read "enter the endpoint collector URL" (i.e. that's the only thing you can enter).

**Comment by ihortom** [comment]
Updated locally

**Comment by alexanderdean** [comment]
Done by @ihortom !
