### ISSUE TITLE
Redshift: Patch Redshift DDL for the com.callrail/call_complete event

### ISSUE THREAD

**Issue by digitaltouch** [snowplow/snowplow#2363]

**Comment by alexanderdean** [comment]
Thanks! Putting this into the Blocked schemas milestone, as we cannot unfortunately merge this into master without breaking pipelines in the wild...

**Comment by digitaltouch** [comment]
I believe this should address everything. I can issue PR if you would like - or wait until the milestone completion gets closer.

**Comment by alexanderdean** [comment]
You are very welcome to open the PR @digitaltouch - thanks...

**Comment by alexanderdean** [comment]
Migrated to: https://github.com/snowplow/iglu-central/issues/534
