### ISSUE TITLE
Pixel Tracker: escape ampersands in querystring

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2366]
It's technically correct to have 

``` html
<img src=http://collector.com/i?e=pv&amp;p=web>
```

**Comment by fblundun** [comment]
To clarify: we already escape the whole tag once so that when the wizard appends it to the document, it is visible as a plain string. We need to escape the ampersands again so that when the wizard user copies and pastes the tag into their HTML, it is still correctly escaped.

**Comment by alexanderdean** [comment]
Let's do this - but for safety, let's always make sure we are quoting our attributes anyway, thusly:

```html
<img src="http://collector.com/i?e=pv&amp;p=web">
```
