### ISSUE TITLE
Create new version of pixel tracker based on JS tracker core

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2367]
There are three issues with the existing pixel tracker:
1. The hosting on snowplowanalytics.com is broken (this should be fixed separately)
2. The html escaping of characters on the querystring needs to be done twice: once for displaying the tag on screen, and a second time so that when the text is copied and pasted the escaped characters correctly copy paste (thanks for the spot @fblundun )
3. The wizard is very limited: it does not let you use unstructured events or custom contexts

It would be nice to put together a new version based on the JS tracker core. This would use the same functions that the JS tracker (and node.js tracker) use to generate the requests, but rather than execute them it would simply display them on the screen. 

This would also be easier to maintain as we evolve e.g. the tracker protocol going forwards.

**Comment by alexanderdean** [comment]
Closed, we will likely remove no-js wizard.
