### ISSUE TITLE
Documentation: Broken link for Ruby install docs

### ISSUE THREAD

**Issue by rbkn** [snowplow/snowplow#2371]
https://github.com/snowplow/snowplow/wiki/Ruby-and-RVM-setup
found on page 
https://github.com/snowplow/snowplow/wiki/1-Installing-EmrEtlRunner

**Comment by alexanderdean** [comment]
Thanks @rbkn !

**Comment by ihortom** [comment]
Removed the references to a non-existing (deleted) page.

**Comment by alexanderdean** [comment]
I have pushed your latest, you will need to grab a new copy of the master wiki
