### ISSUE TITLE
Explain shape of spikes that Beanstalk can handle

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2372]
`Elastic Beanstalk can scale up the number of webservers running the collector to handle spikes in traffic.`

Elastic Beanstalk is not designed to do this. It is designed for predictable growth, not a spike which has an advanced warning of 1 second for example (which already is a large warning for a spike as spikes usually come with no warning at all).

**Comment by alexanderdean** [comment]
Assigned to @jbeemster - can you take a look at this after the Avalanche release goes out?

**Comment by BenFradet** [comment]
closing
