### ISSUE TITLE
Add GraphQL API source to API Request Enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2375]
In API Lookup enrichment [spec](https://github.com/snowplow/snowplow/issues/2051) we have the `api` object which contain API sources with only single possible `http` for now. Another possible option is [GraphQL](https://blog.jacobwgillespie.com/from-rest-to-graphql-b4e95e94c26b#.cmekli1zu) API, which is transport-agnostic (could be non-http) and Schema-aware. All other configurations like `outputs` and `inputs` should fit it.

**Comment by alexanderdean** [comment]
Cool idea! See https://github.com/andimarek/graphql-java

**Comment by chuwy** [comment]
Or https://github.com/sangria-graphql/

**Comment by alexanderdean** [comment]
Nice @chuwy !

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/137
