### ISSUE TITLE
Remove broken link referencing piwik.js

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2376]
./technical-documentation/1a-trackers/javascript-tracker/Javascript-Tracker.md:[4. The relationship between Snowplow.js and Piwik.js](3-The-relationship-between-SnowPlow.js-and-Piwik.js)

This page has been removed; the link should be removed too.

**Comment by ihortom** [comment]
Done locally

**Comment by alexanderdean** [comment]
Pushed!
