### ISSUE TITLE
elastic-mapreduct-cli - uses deprecated API, DescribeJobFlows :  Error on --list.  

### ISSUE THREAD

**Issue by rbkn** [snowplow/snowplow#2379]
From page: https://github.com/snowplow/snowplow/wiki/Setting-up-EMR-command-line-tools#testing

$ ./elastic-mapreduce --list
Error: {"__type":"ValidationException","message":"DescribeJobFlows API is deprecated. Please refer to http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html for further information."}

**Comment by alexanderdean** [comment]
That elastic-mapreduce CLI tool is very out of date now. You can use the emr sub-command in the AWS CLI instead. Closing this ticket in favour of a new ticket: #2380

**Comment by rbkn** [comment]
Thanks Alex!
