### ISSUE TITLE
Remove pages on 5.4: get started analysing your data in EMR and Hive

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2380]
Remove these pages and associated links to these pages (sidebars etc):

* https://github.com/snowplow/snowplow/wiki/Setting-up-EMR-command-line-tools
* https://github.com/snowplow/snowplow/wiki/Running-Hive-using-the-command-line-tools

All that content is very out-of-date now... We should write a new Hive guide once we have moved the enriched event model over to Avro.

**Comment by ihortom** [comment]
@alexanderdean - done locally. The main page to observe the changes is [this one](https://github.com/ihortom/snowplow-wiki-temp/wiki/getting-started-with-EMR). I left the preambule as the new articles are to be written later on (as per your initial comment).

**Comment by alexanderdean** [comment]
Nice, closing
