### ISSUE TITLE
Document "local mode" with Snowplow Kinesis components

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2385]
This is a precursor to http://snowplowanalytics.com/blog/2014/02/04/snowplow-0.9.0-released-with-beta-kinesis-support/#local-mode

**Comment by ihortom** [comment]
@alexanderdean - done locally (preview [here](https://github.com/ihortom/snowplow-wiki-temp/wiki/Run-Scala-Kinesis-Enrich#running-in-local-mode))

**Comment by alexanderdean** [comment]
Really nice, merged, closing
