### ISSUE TITLE
Add glossary of terms to wiki

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2387]
Snowplow sorely needs a glossary or dictionary of terms which we use commonly but may a) be unheard of by new users (e.g. self-describing JSON) b) mean something totally different to other people (e.g. unstructured event).

Once we have this glossary, we **must** keep it updated as we evolve our language (e.g. "structured event" -> Google five-variable event, or contexts -> entities).

**Comment by ihortom** [comment]
@alexanderdean -  I "laid a foundation" for Glossary. Please, [review](https://github.com/ihortom/snowplow-wiki-temp/wiki/Glossary) and let me know if the format is OK.

**Comment by alexanderdean** [comment]
Really nice! Some suggested additional terms for the first batch:

* Tracker
* Collector
* Enrichment
* Storage
* Data modeling
* Analytics

**Comment by ihortom** [comment]
@alexanderdean - Done locally. I guess there's no need to keep this ticket open. We just have to keep populating the Glossary as needed.

**Comment by alexanderdean** [comment]
Looks awesome! Closing for now...
