### ISSUE TITLE
Documentation:  Link to Blogpost on Avro plans broken

### ISSUE THREAD

**Issue by rbkn** [snowplow/snowplow#2388]
Link in page:
https://github.com/snowplow/snowplow/wiki/canonical-event-model

Broken link (bottom of page):
http://snowplowanalytics.com/blog/2013/02/04/help-us-build-out-the-snowplow-event-model/

**Comment by alexanderdean** [comment]
Thanks - GitHub Pages recently upgraded to Jekyll 3. We are  working on a fi
