### ISSUE TITLE
Broken links in blog's sidebar

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2397]
Our [blog](http://snowplowanalytics.com/blog/)'s sidebar references categories by their _titles_ and not by the pages _names_ thus forming broken URLs. For example, the category [Inside the Plow](http://snowplowanalytics.com/blog/Inside%20the%20Plow) referes to the page in the URL's path as "Inside the Plow" instead of "inside-the-plow". Also bear in mind that URLs on GitHub are **case-sensitive**.

**Comment by bogaert** [comment]
It broke 3 days ago when GitHub upgraded to the latest version of Jekyll.

**Comment by alexanderdean** [comment]
Please re-open in the website repo...

**Comment by alexanderdean** [comment]
See https://github.com/snowplow/snowplow.github.com/issues/266
