### ISSUE TITLE
Scala Hadoop Shred: deduplicate event_ids with different event_fingerprints (synthetic duplicates)

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#24]
When you observe two events in your event stream with the same event_id, one of three things could be happening:

| category | cause | payload matches? | probable time between duplicates | fix |
| --- | --- | --- | --- | --- |
| ID collision | huge event volumes / algorithm flaws | no | far apart | give one event a new ID |
| synthetic copy | browser pre-cachers, anti-virus software, adult content screeners, web scrapers | partially (most or all client-sent fields) | close by logical time | either a) delete synthetic copy or b) give it a new ID & preserve relationship to "parent" event |
| natural copy | at least once processing | yes | close by ETL time | delete all but one event |

Thinking about this further, a simple de-duplication algorithm would be:
1. If the payload matches exactly, then delete all but one copy
2. If the payload differs in any way, then give one event a new ID and preserve its relationship to "parent" event

With this approach, distinguishing between ID collisions and synthetic copies can still be done (if needed) at analysis time.

Could this be done using bloom filters? (http://webdocs.cs.ualberta.ca/~drafiei/papers/DupDet06Sigmod.pdf) Not directly:

```
unless event_id **definitely not in set** of bloom[event_ids]:
    if hash(event) **definitely not in set** of bloom[event hashes]:
        assign new event_id and store old event_id in original_event_id field
    else:
        delete event # Deletes some false positives!
```

Rather than delete some false positives (causing data loss), it would be safer to err on the side of caution:

```
unless event_id **definitely not in set** of bloom[event_ids]:
    assign new event_id and store old event_id in original_event_id field
```

But this approach will still cause inflated counts with at least once processing systems. So a hybrid model, using a KV cache of N days of events and another KV cache of N days of event hashes:

```
if event_id in n_days_cache[event_ids]:
    if hash(event) in n_days_cache[event hashes]:
        delete event
    else:
         assign new event_id and store old event_id in original_event_id field
else:
    unless event_id **definitely not in set** of bloom[event_ids]:
        assign new event_id and store old event_id in original_event_id field
```

This prevents natural copies within an N day window and safely renames ID collisions and synthetic copies all the way back through time.

**Title was:** _Occasionally CloudFront registers an event twice_

**Content was:**

_Presumably because it hits two separate nodes at the same time._

_Update the ETL to dedupe this - algorithm would be to hash the querystring and check for duplicates within a X minute timeframe. (Hashing the full raw querystring would implicitly include `txn_id`, the random JavaScript-side identifier, in the uniqueness check.)_

**Comment by alexanderdean** [comment]
Renaming from Scala Common Enrich: to New module, because in a stream processing world, any stage can introduce duplicates. So we have to embed this module in each storage sink that cares about duplicates.

**Comment by alexanderdean** [comment]
We have done some further brainstorming on this today. First we drew out some different event scenarios:

![img_20150818_114840](https://cloud.githubusercontent.com/assets/200511/9329186/73536046-45a7-11e5-8392-3cb9861c482e.jpg)

**Comment by alexanderdean** [comment]
Then we came up with this taxonomy:

| event id  | ur event  | possible explanations                               | strategy                                                                                |
|-----------|-----------|-----------------------------------------------------|-----------------------------------------------------------------------------------------|
| same      | same      | At least once processing 2 trackers, 1 event Robots | Delete all but first                                                                    |
| same      | different | User reusing event ID Event ID algo collision Robot | Assign new event ID to all but first, preserving original event ID as 'parent event ID' |
| different | same      | 2 trackers, 1 event Behavioral collision            | Do nothing                                                                              |

**Comment by alexanderdean** [comment]
We quickly realized that it is essential to define the ur event (ur meaning most primitive) correctly. @yalisassoon to add his whiteboard photo...

**Comment by yalisassoon** [comment]
See below:

![img_20150818_120812](https://cloud.githubusercontent.com/assets/201147/9343302/025b2020-45f9-11e5-8233-bc7aa4a9bc91.jpg)

**Comment by alexanderdean** [comment]
Further reading:

* [Dealing with duplicate event IDs](http://snowplowanalytics.com/blog/2015/08/19/dealing-with-duplicate-event-ids/) 
* [New data model: deduplicate in R69](http://snowplowanalytics.com/blog/2015/07/24/snowplow-r69-blue-bellied-roller-released/#deduplication)
* [New deduplication queries in R72](http://snowplowanalytics.com/blog/2015/10/15/snowplow-r72-great-spotted-kiwi-released/#deduplication)
* [De-deduplicating events in Hadoop and Redshift [tutorial]](http://discourse.snowplowanalytics.com/t/de-deduplicating-events-in-hadoop-and-redshift-tutorial/248)
* [Event de-duplication in Hadoop Shred in R76](http://snowplowanalytics.com/blog/2016/01/26/snowplow-r76-changeable-hawk-eagle-released/#deduplication)

**Comment by alexanderdean** [comment]
For existing code: https://github.com/snowplow/snowplow/commit/8c09aded04d78eae51827b8baee8771b27b74da5
