### ISSUE TITLE
Documentation: Event fingerprint enrichment page has wrong schema in example

### ISSUE THREAD

**Issue by rbkn** [snowplow/snowplow#2401]
Page: 
https://github.com/snowplow/snowplow/wiki/Event-fingerprint-enrichment

In the example the schema given is:
iglu:com.snowplowanalytics.snowplow/referer_parser/jsonschema/1-0-0
when it should be:
iglu:com.snowplowanalytics.snowplow/event_fingerprint_config/jsonschema/1-0-0

**Comment by fblundun** [comment]
Thanks for spotting this @rbkn. It's fixed now.
