### ISSUE TITLE
vagrant provision is broken

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2408]
`vagrant provision` gives me error hell:

(This is not the only issue. )

As a solution, please deploy it automatically 20 times in your test infrastructure and collect all the errors from it, fix it, and then publish new scripts which do work. 

```
==> default: =======================================
==> default: CLONING ANSIBLE AND PLAYBOOKS WITH PERU
==> default: ---------------------------------------
==> default: Traceback (most recent call last):
==> default:   File "/usr/local/bin/peru", line 9, in <module>
==> default:     load_entry_point('peru==0.3.0', 'console_scripts', 'peru')()
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 345, in main
==> default:     async.run_task(command_fn(params))
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/async.py", line 25, in run_task
==> default:     return asyncio.get_event_loop().run_until_complete(coro)
==> default:   File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
==> default:     return future.result()
==> default:   File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
==> default:     raise self._exception
==> default:   File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
==> default:     result = coro.send(value)
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 91, in do_sync
==> default:     params.runtime, params.scope, params.imports, params.runtime.sync_dir)
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/imports.py", line 18, in checkout
==> default:     previous_index_file=index)
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 383, in export_tree
==> default:     _format_file_lines(modified))
==> default: peru.cache.DirtyWorkingCopyError: Imported files have been modified (use --force to overwrite):
==> default:
==> default: ansible/.gitignore
==> default: ansible/CHANGELOG.md
==> default: ansible/CODING_GUIDELINES.md
==> default: ansible/CONTRIBUTING.md
==> default: ansible/COPYING
==> default: ansible/MANIFEST.in
==> default: ansible/Makefile
==> default: ansible/README.md
==> default: ansible/RELEASES.txt
==> default: ...940 total
```

**Comment by jbeemster** [comment]
Hi @0xABAB, this error normally occurs if the ansible playbooks have been manually edited/modified after you have first attempted to provision.

A fix for this is to delete the `vagrant/.peru`, `vagrant/ansible` and `vagrant/oss-playbooks` directories and to then to run: `vagrant halt && vagrant up && vagrant provision` again.

Please let me know if this helps you get the environment running!

**Comment by 0xABAB** [comment]
This did work, but what I would like to do is run the Clojure collector in this Virtualbox VM. How can I do that?

**Comment by jbeemster** [comment]
You can run the servlet locally following the documentation found [here](https://github.com/snowplow/snowplow/wiki/Clojure-collector#event-logging). However we do not have any local infrastructure for running this collector locally inside tomcat.

For a local collector you can also look at the Scala Stream Collector which can be run locally and can be configured to output events to `stdout` rather than to a Kinesis Stream.

**Comment by Spycomb** [comment]
i still has the same exact problem after deleted vagrant/.peru, vagrant/ansible , vagrant/oss-playbooks then do the vagrant provision.

i'm currently using virtualbox 4.3 and ubuntu/trusty64     (virtualbox, 20160222.0.0) as the vagrant box
