### ISSUE TITLE
NoSuchMethod Exception

### ISSUE THREAD

**Issue by ranjithnaidu** [snowplow/snowplow#2411]
NoSuchMethod Exception while creating an emitter from an Activity.

**Comment by jbeemster** [comment]
Hi @ranjithnaidu, for debugging help with Trackers could you please post in the user forum: https://groups.google.com/forum/#!forum/snowplow-user

We will also need more information on the issue to help you out such as:

- Code sample of your implementation
- StackTrace of the exception

If you could post all of the above to the user group we will be able to help you get it working!

**Comment by ranjithnaidu** [comment]
From Activity's Constructor
public MyActivity(){
    SnowPlowAnalyticsManager.initTracker(context);
}

Anayltics manager
import android.content.Context;
import com.appleete.haat.FabricApplication;
import com.snowplowanalytics.snowplow.tracker.Emitter;
import com.snowplowanalytics.snowplow.tracker.Subject;
import com.snowplowanalytics.snowplow.tracker.Tracker;
import com.snowplowanalytics.snowplow.tracker.emitter.HttpMethod;
import com.snowplowanalytics.snowplow.tracker.emitter.RequestSecurity;
import com.snowplowanalytics.snowplow.tracker.events.Unstructured;
import com.snowplowanalytics.snowplow.tracker.payload.SelfDescribingJson;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by Ranjithnaidu on 03/02/16.
 */
public class SnowPlowAnalyticsManager {

    public static final String TRACKER_NAME_SPACE = "snowplowTracker";
    public static final String APP_ID = "__haat_snowplow__";
    private static final String SNOWPLOW_PRODUCT_REACH = "haat";
    private static final String SNOWPLOW_ACTION_LOAD = "load";
    private static final String SNOWPLOW_EVENT_CARD_VIEW = "card_view";
    public static Context appContext = null;
    public static final boolean useBase64 = true;
    public static final String USER_ID = "1009";
    public static final String TRACKER_URI = "<endpoint_uri>";

    private static final String SNOWPLOW_KEY_PRODUCT_NAME = "$1$product_name";
    private static final String SNOWPLOW_KEY_ACTION_NAME= "$1$action_name";
    private static final String SNOWPLOW_KEY_EVENT_NAME = "$1$event_name";
    private static final String SNOWPLOW_KEY_LOCALITY = "$1$locality";
    private static final String SNOWPLOW_KEY_PRODUCT_ID = "$1$doctor_id";
    private static final String SNOWPLOW_KEY_SUBSCRIPTION_ID = "$1$subscription_id";
    private static final String SNOWPLOW_DATE_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";
    private static final String SNOWPLOW_KEY_EVENT_DATE = "$1$event_date";

    public static Tracker mTracker;
    public static Emitter e1;

    public static void initTracker(Context context){
        appContext = HaatApplication.getContext();
//        try {
            e1 = new Emitter.EmitterBuilder(TRACKER_URI, context).build();
            e1.setHttpMethod(HttpMethod.GET);
            e1.setRequestSecurity(RequestSecurity.HTTP);

            mTracker = new Tracker
                    .TrackerBuilder(e1, TRACKER_NAME_SPACE, APP_ID, context)
                    .base64(useBase64)
                    .subject(new Subject.SubjectBuilder().build())
                    .build();
//        }catch (Exception e){
//            e.printStackTrace();
//        }
    }

    public static void sendReachEvent(){

        Map<String, Object> _event = new HashMap<>();
        _event.put(SNOWPLOW_KEY_PRODUCT_NAME, SNOWPLOW_PRODUCT_REACH);
        _event.put(SNOWPLOW_KEY_ACTION_NAME, SNOWPLOW_ACTION_LOAD);
        _event.put(SNOWPLOW_KEY_PRODUCT_ID, 265);
        _event.put(SNOWPLOW_KEY_SUBSCRIPTION_ID, 5999);

        Calendar c = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat(SNOWPLOW_DATE_TIME_FORMAT);

        _event.put(SNOWPLOW_KEY_EVENT_DATE, df.format(c.getTime()));

        SelfDescribingJson eventData = new SelfDescribingJson("null").setData(_event);
        Unstructured unstructuredEvent = Unstructured.builder().eventData(eventData).build();

        // Set user id
        mTracker.getSubject().setUserId(USER_ID);

        // Send data
        mTracker.track(unstructuredEvent);

    }

}

StackTrace of the exception
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime: FATAL EXCEPTION: main
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime: Process: com.practo.fabric, PID: 29350
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.practo.fabric/com.practo.fabric.result.SearchResultActivity}: java.lang.IllegalStateException: Can’t create emitter
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: Can’t create emitter
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.snowplowanalytics.snowplow.tracker.a$a.a(Emitter.java:237)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.misc.af.a(SnowplowAnalyticsManager.java:51)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.search.c$c.<init>(ProductSearch.java:769)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.search.c.<init>(ProductSearch.java:105)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.search.h.a(SearchFactory.java:18)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.result.c.onCreate(SearchResultFragment.java:170)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.o.a(FragmentManager.java:1029)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.o.a(FragmentManager.java:1248)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.f.run(BackStackRecord.java:738)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.o.i(FragmentManager.java:1613)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.l.p(FragmentController.java:330)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.j.onStart(FragmentActivity.java:547)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.result.SearchResultActivity.onStart(SearchResultActivity.java:113)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:6006)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:  Caused by: java.lang.NoSuchMethodException: <init> [class com.snowplowanalytics.snowplow.tracker.a$a]
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.Class.getConstructor(Class.java:531)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.Class.getDeclaredConstructor(Class.java:510)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.snowplowanalytics.snowplow.tracker.a$a.a(Emitter.java:234)
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.misc.af.a(SnowplowAnalyticsManager.java:51) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.search.c$c.<init>(ProductSearch.java:769) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.search.c.<init>(ProductSearch.java:105) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.search.h.a(SearchFactory.java:18) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.result.c.onCreate(SearchResultFragment.java:170) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreate(Fragment.java:1939) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.o.a(FragmentManager.java:1029) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.o.a(FragmentManager.java:1248) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.f.run(BackStackRecord.java:738) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.o.i(FragmentManager.java:1613) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.l.p(FragmentController.java:330) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.support.v4.app.j.onStart(FragmentActivity.java:547) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.practo.fabric.result.SearchResultActivity.onStart(SearchResultActivity.java:113) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:6006) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
02-11 05:13:34.577 29350-29350/com.practo.fabric E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jbeemster** [comment]
Please post this in the https://groups.google.com/forum/#!forum/snowplow-user group.

**Comment by ranjithnaidu** [comment]
thanks @jbeemster
