### ISSUE TITLE
Kinesis Elasticsearch Sink: add mixed output mode

### ISSUE THREAD

**Issue by ninjabear** [snowplow/snowplow#2412]
Elasticsearch-sink currently doesn't support writing to stdout and not stderr, or writing good to a kinesis stream and bad to stderr. It'd be nice if these were decoupled such that you can write good to one place and bad to another place - or even turn off the bad stream altogether.

**Comment by alexanderdean** [comment]
Makes sense, scheduling!

**Comment by alexanderdean** [comment]
Brought forwards to help Snowplow Mini

**Comment by fblundun** [comment]
This will require some changes to the config file. At the moment it's like this:

```
in: stdin | kinesis
out: stdouterr | elasticsearch-kinesis
```

How about changing that to:

```
in: stdin | kinesis
out: {
  good: elasticsearch | stdout
  bad: kinesis | stderr | none
}
```

**Comment by alexanderdean** [comment]
I like it! @ninjabear does that work for your use case (Snowplow Mini)?

**Comment by ninjabear** [comment]
Looks good to me! Is there ever a situation where you'd want to write to more than one place? For example bad rows go kinesis and get written to stderr too

**Comment by alexanderdean** [comment]
Hey @ninjabear - I can't think of any burning requirement for that right now; if it comes up in the future we can always extend the config I guess...
