### ISSUE TITLE
Scala Common Enrich: add support of OWM real-time API

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2415]
Could some subset of OWM calls be done via the real-time API, because the event timestamps are close enough to now() to work? Not sure if this is possible - it's probably a fair chunk of work - but if it was, it could be helpful, especially for real-time pipeline users.

**Comment by alexanderdean** [comment]
Some users may prefer the following algorithm to avoid paying for OWM's historical bolt-on:

* If the event is within the last X hours, use the real-time weather lookup
* If the event is more than X hours ago, don't add any weather

i.e. some users may prefer slightly stale weather or no weather instead of paying for accurate weather.

**Comment by chuwy** [comment]
Blocker for GCP: https://github.com/snowplow-incubator/schema-ddl/issues/45

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/139
