### ISSUE TITLE
Scala Kinesis Enrich: rename to Stream Enrich

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2418]
Because we will be using this from Kafka and from Snowplow Mini

**Comment by fblundun** [comment]
While we are at it, do you think we should drop the "Scala" too? Since we usually just refer to it as "Kinesis Enrich" anyway.

**Comment by alexanderdean** [comment]
Good question! I think at this point we are unlikely to reimplement the Enrichment process in another language, so there's no informational benefit to keeping the prefix (unlike with a collector, where we might easily write a Rust Stream Collector or Elixir Stream Collector one day).

So I think we could call the component "Stream Enrich" and artifacts would continue to be called "snowplow-stream-enrich" to avoid confusion...

**Comment by fblundun** [comment]
Are we going to reset the version to 0.1.0?

**Comment by jbeemster** [comment]
We didn't reset when we renamed kinesis-s3.

**Comment by alexanderdean** [comment]
Yep, we don't reset version numbers when components are renamed
