### ISSUE TITLE
Scala Hadoop Shred: add support for shredding [ {objectA}, {objectA}, ...]

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2451]
If the top-level of our JSON Schema is an array of objects of type `objectA`, then at the moment we will shred this into a JSON `[ {objectA}, {objectA}, ...]`, and the `COPY FROM JSON` code will fail to work with this in any meaningful way (because it's not a JSON object).

However, assuming we had support for this in Schema Guru (https://github.com/snowplow/schema-ddl/issues/49), it should be possible to flatten out a `[ {objectA}, {objectA}, ...]` into just multiple rows of an `{objectA}`.

**Comment by alexanderdean** [comment]
See also: #2095

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/122
