### ISSUE TITLE
Migrate some release info from blog to wiki

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2454]
> We have a pattern at Snowplow where the blog post documentation is much better than the wiki doco as an example, the [weather enrichment blog post](http://snowplowanalytics.com/blog/2015/12/22/snowplow-r74-european-honey-buzzard-with-weather-enrichment-released/) is far better than the [weather enrichment wiki page](https://github.com/snowplow/snowplow/wiki/Weather-Enrichment). I think it would be amazing if you could spend time pulling content from the release posts back into the wiki
> -- @alexanderdean

**Comment by BenFradet** [comment]
moved to docs, closing
