### ISSUE TITLE
Improve Snowplow version matrix

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2455]
A basic page has been connected here: https://github.com/snowplow/snowplow/wiki/Snowplow-version-matrix

@ihortom you should have write access to the underlying Google Spreadsheet. Tasks:

* [ ] Populate the yellow highlighted cells
* [ ] Flesh out the wiki page
* [ ] Wire the wiki page into other pages (e.g. upgrade guide)
* [ ] Email user group to let people know this exists now

**Comment by alexanderdean** [comment]
Note @ihortom that you can find the recommended AMI version from the sample config.yml file for that release

**Comment by ihortom** [comment]
@alexanderdean - completed the matrix and populated the page. Before flashing out and wiring, could you review the [page](https://github.com/ihortom/snowplow-wiki-temp/wiki/Snowplow-version-matrix), please?

**Comment by ihortom** [comment]
@alexanderdean - this could be closed.

**Comment by alexanderdean** [comment]
Agreed...
