### ISSUE TITLE
EmrEtlRunner: add warning about the array of in buckets in config.yml

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2462]
The users seem to ignore YAML style of an array item, "-" symbol in config.yml. That generate a significant amount of questions in Google group. I think we need to indicate the significance of the symbol even if only one item is to be added. That could be done both in config.yml as a comment as well as in corresponding [wiki page](https://github.com/snowplow/snowplow/wiki/Common-configuration).

**Comment by alexanderdean** [comment]
Improved title
