### ISSUE TITLE
Scala Stream Collector: add support for opt-out cookies

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2463]
http://www.allaboutcookies.org/manage-cookies/opt-out-cookies.html

Piwik supports this:
http://piwik.org/docs/privacy/#step-3-include-a-web-analytics-opt-out-feature-on-your-site-using-an-iframe

I'm not sure if opt-out cookies are a good way to give end users control over what is tracked per-se, but I like the idea of making it easier for Snowplow users to give their users the option to opt out of cookie tracking.

**Comment by alexanderdean** [comment]
Focused this on SSC given we are migrating away from Clojure Collector

**Comment by alexanderdean** [comment]
Interesting. As the collectors are stateless, this would have to be a new cookie that registers that the `nuid` must not be set.

**Comment by alexanderdean** [comment]
@BenFradet can you estimate the work involved here?

**Comment by BenFradet** [comment]
done as `doNotTrackCookie`, closing
