### ISSUE TITLE
Data model (web-recalculate): Set encoding on all tables

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow#2468]
The current web-recalculate data model uses `CREATE TABLE AS` extensively, resulting in huge tables with uncompressed columns, e.g. `snowplow_intermediary.events_enriched_final`

We should consider:
- Checking the table definitions [here](https://github.com/snowplow/snowplow/tree/master/5-data-modeling/sql-runner/redshift/setup/web-recalculate) to make sure they're updated
- Instead of dropping tables and using `CREATE TABLE AS`, delete all rows and use `INSERT INTO`

@bogaert does that make sense to you?

**Comment by bogaert** [comment]
Hi @bernardosrulzon. I agree that there is a lot of room for improvement. We will rethink some of these SQL data models in the near future, and, in the meantime, feel free to open a PR with these changes.

**Comment by alexanderdean** [comment]
Is this still the case @bogaert ?

**Comment by bogaert** [comment]
We can close this ticket @alexanderdean.

**Comment by alexanderdean** [comment]
Thanks, done
