### ISSUE TITLE
Create multi-page wiki guide to working with events and contexts in Snowplow

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2469]
Currently the documentation is spread over:

1. http://snowplowanalytics.com/documentation/concepts/events/
2. http://snowplowanalytics.com/documentation/concepts/event-dictionaries-and-schemas/
3. http://snowplowanalytics.com/documentation/concepts/contexts/
4. http://snowplowanalytics.com/documentation/concepts/iglu/
5. https://github.com/snowplow/example-event-dictionary/blob/master/README.md

We want a consolidated guide on the Snowplow wiki - a multi-page guide which walks the user through the above, and also adds in examples in JavaScript, iOS and Java for adding a custom context to an event.

Once this guide has been done, please request a detailed review from @bogaert.

**Comment by ihortom** [comment]
@alexanderdean - Please, review the [local copy](https://github.com/ihortom/snowplow-wiki-temp/wiki/Events-and-Contexts). Additional examples of code for different trackers are yet to be added.

**Comment by alexanderdean** [comment]
Hey @ihortom - this is great! I will have a detailed readthrough, but the first piece of feedback is that we decided yesterday to move from talking about "event dictionaries" to talking about "schema registries". So we are encouraging a company to set up a "schema registry". Reasons for the change:

1. "schema registry" is becoming a mainstream term
2. "schema registry" is a better fit for our work with Iglu
3. A "schema registry" can contain contexts as well as events

**Comment by bogaert** [comment]
Should we replace "unstructured events" with "self-describing events (also called unstructured events)"? We'll have to start somewhere and this seems like a good place.

cc @yalisassoon

**Comment by alexanderdean** [comment]
I'm happy with that, got to start somewhere...

**Comment by ihortom** [comment]
@alexanderdean / @bogaert / @yalisassoon  - I would keep the term "event dictionary" limiting its boundaries. When it comes to drawing screenshots and preparing JSON schemas it's building "event dictionary". When it comes to actual  (real world) implementation that would be called "schema registry". Thus "event dictionary" and "schema registry" are related but not mutually exclusive.

**Comment by alexanderdean** [comment]
I think the question is whether there really is a separate layer of screenshots etc (the "event dictionary") maintained ahead of / alongside uploading the schemas into the registry...

Separate point: @ihortom in your guide can you please replace any references to "... [schema] repository" (e.g. Iglu repository, schema repository) with "schema registry", so e.g. Iglu schema registry, schema registry.

**Comment by ihortom** [comment]
@alexanderdean - replaced the references to repository with registry. About event dictionaries: you do need to think ahead what you want to capture and draft the schemas accordingly (it cannot be called registry at this point). And that's an important phase. Users are free to skip it if the events are not complex.

**Comment by bogaert** [comment]
We should keep the concept of event dictionaries (it's something few users do, and it hurts when someone else needs to consume the data).

Whether we make it part of the registries or not is a separate discussion. I would let it live in the same place as the schemas.

**Comment by alexanderdean** [comment]
Sounds good to me!

**Comment by ihortom** [comment]
@alexanderdean - the wiki section has been live for quite a while now. Could you, please, close the issue?
