### ISSUE TITLE
Update the configurable enrichments wiki pages with extra sections

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2470]
### Data sources

So what data points does the enrichment use to perform its lookup.

### Algorithm

Or underlying library. May need to talk to the enrichment's author for this.

### Data generated

So e.g:

* For weather enrichment, make clear that a JSON `org.openweathermap/weather/...` is added to derived_contexts (and you could ask @chuwy for any detail on the individual properties)
* For IP lookups enrichment, add a table of all the fields in atomic.events which are populated by this enrichment

**Comment by ihortom** [comment]
@alexanderdean - Updated the following 3 wiki pages:

- IP lookups enrichment
- Campaign attribution enrichment
- Weather enrichment

**Comment by alexanderdean** [comment]
Great work! Pushed

**Comment by ihortom** [comment]
@alexanderdean - Updated the following wiki pages:
- Currency conversion enrichment
- ua-parser enrichment
- user-agent-utils enrichment
- IP anonymization enrichment
- referer parser enrichment

**Comment by alexanderdean** [comment]
These are great - pushed! Are there any left @ihortom ?

**Comment by ihortom** [comment]
@alexanderdean - Updated the remaining pages:

- Event fingerprint enrichment
- Cookie extractor enrichment
- JavaScript script enrichment

Please, review them carefully as they were harder to figure out the answers.

If all is OK, the ticket could be closed.

**Comment by alexanderdean** [comment]
Merged! Closing
