### ISSUE TITLE
Snowplow CLI: add debugging mode

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2471]
Open-source users most often experience difficulties related to either misconfigured `config.yml` or values entered conflicting with the current infrastructure like invalid path, wrong region etc. Answering/troubleshooting  this kind of issues takes up a considerable amount of time. It would be great if we could develop some kind of debugging utility. I don’t expect it to be neither complicated nor hard to implement. The same logic/algorithm could be utilized already implemented in EmrEtlRunner.

Currently we have ETL process implemented with a pair of apps launched like:

```
EmrEtlRunner <args to run job>
StorageLoader <args to do a load>
```

We could unify the app adding to it **lint** capability in the following manner
1. Hide StorageLoader
2. Rename EmrEtlRunner to, say, `snowplow` redesigning it to “mimic” _aws CLI program_

That is we would have snowplow CLI program with sub-commands, for example **EmrEtlRunner** becomes

```
$ snowplow emr run <<args>>
```

In debugging mode the users could run

```
$ snowplow lint <<config file>
```

**lint** could do 2 things:
1. Validate the configuration file (maybe against a JSON schema which gives better failure message than Ruby Contracts)
2. We could test common failures like:
   
   2.1 Can we access all buckets?
   2.2. Does the EC2 key exist?
   2.3. Does the region and placement or subnet exist/match?

From support point of view the following scenario could be common:
1. User reports failure "My config.yml isn't working"
2. Our response:  “Can you run `$ snowplow lint` and paste in the results?”

**Note**: we might need to mask the sensitive info in the output.

**Comment by alexanderdean** [comment]
Great idea @ihortom !

**Comment by fblundun** [comment]
Masking sensitive output shouldn't be too hard - we already do that when error messages might contain a user's AWS credentials.
