### ISSUE TITLE
EmrEtlRunner: update config/iglu_resolver.json version to 1-0-1

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2479]
https://github.com/snowplow/snowplow/blob/release/r78/3-enrich/stream-enrich/src/main/resources/resolver.json.sample#L2

**Comment by chuwy** [comment]
This can be pushed back and left as a reminder if we're not going to bump Iglu client in this version.

**Comment by alexanderdean** [comment]
Hey @chuwy - why hasn't this ticket been implemented?

**Comment by chuwy** [comment]
@alexanderdean I guess this should be pushed back as Iglu Client in Stream Enrich is still 0.3.1 therefore doesn't support resolver 1-0-1.

**Comment by alexanderdean** [comment]
Completely makes sense - good point @chuwy !

**Comment by chuwy** [comment]
@alexanderdean I just realized that [config/iglu_resolver.json](https://github.com/snowplow/snowplow/blob/release/r79/3-enrich/config/iglu_resolver.json) can be updated to 1-0-1 too. On the other hand, may be we should wait until Iglu Client in Stream Enrich will be updated to not confuse users with different SchemaVers.

**Comment by chuwy** [comment]
Oh. And also resolver in SE will be removed https://github.com/snowplow/snowplow/issues/1932

**Comment by alexanderdean** [comment]
I think let's make the change in R80 - @chuwy can you please do a commit directly into the release branch for R80 with the change?

**Comment by chuwy** [comment]
@alexanderdean I afraid I cannot, since it has been deleted (#1932). Or do you want me insert it **before** commit with delete?

**Comment by alexanderdean** [comment]
Fixed title
