### ISSUE TITLE
Common: change Vagrantfile to use NFS and extra CPU cores by default

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#2482]

**Comment by chuwy** [comment]
We need to warn users to check if they really have 4 CPUs. If we're setting up more CPUs than computer actually has performance degrades so much I nearly can feel CPU is switching contexts.

**Comment by fblundun** [comment]
It would be nice to actually calculate the number of processors in the Vagrantfile, but this seems to be quite awkward to do in Ruby.

**Comment by jbeemster** [comment]
Oddly according to this the extra CPU cores tends to degrade performance: https://ruin.io/2014/benchmarking-virtualbox-multiple-core-performance/

**Comment by 0xABAB** [comment]
Detecting the number of CPUs from Ruby is just a library call away: 
See: https://github.com/grosser/parallel

I don't really see any reason for hard-coded constants. In short, I don't see any problem here. Using the time to write a comment could also have been used to just fix the problem in the first place.
