### ISSUE TITLE
Evaluate changing Enhanced Ecommerce setup in GTM guide to use new Enhanced Ecommerce methods

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2487]
Relevant page: https://github.com/snowplow/snowplow/wiki/Integrating-javascript-tags-with-Google-Tag-Manager

**Comment by alexanderdean** [comment]
Current thinking is to leave the page as-is, as it attaches the data as contexts, whereas it is structured as `track...` events in the new JS Tracker API...

**Comment by alexanderdean** [comment]
If @yalisassoon is happy to leave this page as-is, I think this is a wrap for 2.6.0 release...

**Comment by paulboocock** [comment]
Closing in favour of, which uses enhanced ecommerce by default: https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/google-tag-manager-custom-template/
