### ISSUE TITLE
Update JS tracker contents page with links to enhanced ecommerce methods

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2489]
Update this page specifically: https://github.com/snowplow/snowplow/wiki/javascript-tracker

**Comment by jbeemster** [comment]
This page needs to be updated to point to these functions:

https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#enhanced-ecommerce

**Comment by jbeemster** [comment]
This has been updated, please review @yalisassoon

**Comment by yalisassoon** [comment]
Looks good - closing!
