### ISSUE TITLE
Remove references to snowplow-emr-etl-runner.sh from EmrEtlRunner documentation

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2495]
https://github.com/snowplow/snowplow/wiki/3-Scheduling-EmrEtlRunner links to the below URL:

https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/bin/snowplow-emr-etl-runner.sh

But the shell script URL is a 404.

**Comment by ihortom** [comment]
@alexanderdean - Updated all the EmrEtlRunner setup pages to reflect the end of support for Ruby based runner. Additionally, did the same on StorageLoader setup pages.
