### ISSUE TITLE
Add wiki page on Kinesis at-least-once processing

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2496]
https://groups.google.com/forum/#!topic/snowplow-user/QD5LeHKbIrQ

**Comment by ihortom** [comment]
@alexanderdean - Done. The local copy is [here](https://github.com/ihortom/snowplow-wiki-temp/wiki/Kinesis-at-least-once-processing). Once approved and pushed, I will add the ref to the article on Kinesis-S3 Sink page.

**Comment by alexanderdean** [comment]
@fblundun - can you review please?

**Comment by fblundun** [comment]
"at-least-once-processing" is usually hyphenated. Is it possible to have hyphens in the title of a wiki page?

Rather than starting at TRIM_HORIZON or LATEST the apps can also start from a specific sequence number. We have never documented this in the config file comments. But we should probably start.

Other than that it looks good!

**Comment by alexanderdean** [comment]
@fblundun - how does starting at a specific sequence number work? Wouldn't you have to specify the sequence number on a per-open-shard basis?

**Comment by fblundun** [comment]
You're right - it is for individual GetRecords calls, not configuring the whole KCL. My mistake!

**Comment by ihortom** [comment]
Here's what I found about it:

>You must specify the shard iterator type. For example, you can set the ShardIteratorType parameter to read exactly from the position denoted by a specific sequence number by using the AT_SEQUENCE_NUMBER shard iterator type, or right after the sequence number by using the AFTER_SEQUENCE_NUMBER shard iterator type, using sequence numbers returned by earlier calls to PutRecord, PutRecords, GetRecords, or DescribeStream. You can specify the shard iterator type TRIM_HORIZON in the request to cause ShardIterator to point to the last untrimmed record in the shard in the system, which is the oldest data record in the shard. Or you can point to just after the most recent record in the shard, by using the shard iterator type LATEST, so that you always read the most recent data in the shard.
-- [docs.aws.amazon.com](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kinesis/AmazonKinesisClient.html)

@fblundun - I've no control over the page's title. It's automatically generated.

**Comment by ihortom** [comment]
@alexanderdean - please, close (already live). Also added the ref to the page from Kinesis S3 sink page.
