### ISSUE TITLE
Scala Common Enrich: remove util.Tap

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2497]
Can also then remove the snowplow-utils dependency.

**Comment by alexanderdean** [comment]
Has this been done @chuwy @BenFradet ?

**Comment by chuwy** [comment]
I think yes https://github.com/snowplow/snowplow/commit/862ecc58ff743774c01a4bb4f79eed150920e07c

**Comment by alexanderdean** [comment]
Duplicate of #3054
