### ISSUE TITLE
Scala Common Enrich: bump CallRail's call_complete to 1-0-2

### ISSUE THREAD

**Issue by digitaltouch** [snowplow/snowplow#2501]
On 2015-02-05 the following fields were deprecated from the callrail webhooks 

`callernum` now `customer_phone_number`
`callername` now  `customer_name`
`callercity` now `customer_city`
`callerstate`now `customer_state`
`callerzip` now `customer_zip`
`callercountry` now `customer_country`

This will bump the schema version to 1-0-2

**Comment by BenFradet** [comment]
done in iglu-central: https://github.com/snowplow/iglu-central/tree/master/jsonpaths/com.callrail
