### ISSUE TITLE
StorageLoader: Patch JSON Path file for the com.callrail/call_complete event 1-0-2

### ISSUE THREAD

**Issue by digitaltouch** [snowplow/snowplow#2503]

**Comment by chuwy** [comment]
This shouldn't belong here anymore. Also assets look correct:

* [JSONPaths](https://github.com/snowplow/iglu-central/blob/master/jsonpaths/com.callrail/call_complete_1.json)
* [SQL](https://github.com/snowplow/iglu-central/blob/master/sql/com.callrail/call_complete_1.sql)
* [JSON Schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.callrail/call_complete/jsonschema/1-0-2)

**Comment by alexanderdean** [comment]
Okay @chuwy - closing... @digitaltouch please re-open if there's something specific missing.
