### ISSUE TITLE
Scala Hadoop Shred: support shredding self-describing ND-JSONs

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2506]
So we have a specific landing area for ND-JSONs, probably output by extra_steps, and Hadoop Shred will read these as well as the Snowplow enriched events.

Obviously it will validate them etc, then write them out to the common path.

TBC: what do we do on an entity clash: e.g. your enriched events contain `com.acme/sessions` and your extra_jobs' ND-JSON also writes out `com.acme/sessions`. Referring to `part-000` file clashes.

**Comment by alexanderdean** [comment]
Let's close this
