### ISSUE TITLE
Scala Stream Collector: use nuid query parameter value to set the 3rd party network id cookie

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2512]
In order to do some cookie syncing with other systems, i want to call the collector with a regular pageview event request. I want to pass an existing V4 UUID as value for nuid to the collector. I would have expected the collector to set the "sp" cookie using the value which was in the query parameter for the network_userid. But that was not the case.

> curl -IvsL "http://collector.url/i?e=pv&aid=cookie-sync-test&p=web&tv=no-js-0.1.1&nuid=$UUID" 
*   Trying xxx.xxx.xxx.xxx...
* Connected to collector.url (xxx.xxx.xxx.xxx) port 80 (#0)
> HEAD /i?e=pv&aid=cookie-sync-test&p=web&tv=no-js-0.1.1&nuid=89F0F89A-A949-41D8-85E2-458EE6FC161D HTTP/1.1
> Host: collector.url
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Content-Length: 43
< Content-Type: image/gif
< Date: Tue, 08 Mar 2016 15:20:41 GMT
< P3P: policyref="/w3c/p3p.xml", CP="NOI DSP COR NID PSA OUR IND COM NAV STA"
< Server: spray-can/1.2.0
< Set-Cookie: sp=27fdee53-4d57-4f30-ab55-3a20665bc1ca; Expires=Wed, 08 Mar 2017 15:20:41 GMT; Domain=collector.url

**Comment by alexanderdean** [comment]
This proposal seems sane - the `&nuid=` was invented to let a server-side tracker pass-through a client-side nuid to the collector, but you are right, the cookie value sent back is not influenced by the `&nuid=`. So in the case that you want to do a one-time sync and for that to dictate the nuid for all further behavior, yes you will need this ticket...

**Comment by fblundun** [comment]
Presumably this should happen even if the collector has previously set a different value for the cookie?

**Comment by christoph-buente** [comment]
I think so, yes. Any other behaviour doesn't make sense. But maybe this could be a config option.

**Comment by christoph-buente** [comment]
@fblundun is there any news on that?

**Comment by christoph-buente** [comment]
How was i able to unasign people from the issue? @alexanderdean ??

**Comment by alexanderdean** [comment]
Ah! @fblundun no longer works at Snowplow, so first action on a ticket will unassign him!

**Comment by christoph-buente** [comment]
That's a bummer. Now what?

**Comment by alexanderdean** [comment]
I'll bring this forwards...
