### ISSUE TITLE
Scala Common Enrich: bump user-agent-utils version to latest

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2516]
@bogaert is seeing some suspicious values for br_name.

**Comment by bogaert** [comment]
The particular example is Firefox 4X being parsed at Firefox 4.

**Comment by alexanderdean** [comment]
Bringing forwards...

**Comment by christoph-buente** [comment]
:+1: I know it is a pain to keep this library up to date. But i think it is quite essential for proper event processing.
