### ISSUE TITLE
Scala Stream Collector: configurable cookie path

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2524]
The snowplow collector does not set an explicit cookie path when dropping the 3rd party network_id cookie. According to wikipedia (https://en.wikipedia.org/wiki/HTTP_cookie) it does not have an effect, as the tracking endpoint is at /i, which will lead implicitly to an path set to "/" in the browser. But the track link endpoint is a nested resource at "/r/tp2" which would lead to set the cookie path to "/r" which is probably not desirable.

So i think the collector should either statically set the cookie path to "/" to make sure it is valid for all collector endpoints or let it be set in the config page. What do you think?

**Comment by alexanderdean** [comment]
Good catch, I think we should set to "/"

**Comment by gyurist** [comment]
It seems like the same issue affects the clojure collector as well. 
Since no explicit path is set the default browser behavior is used which sets the `sp` cookie path to `/com.snowplowanalytics.snowplow`.

**Comment by alexanderdean** [comment]
Bringing forwards (R82 is in test already)

**Comment by alexanderdean** [comment]
Thanks for flagging @gyurist - created #2739 to explore this...

**Comment by jbeemster** [comment]
Closing this ticket in favour of PR
