### ISSUE TITLE
Kinesis Elasticsearch Sink: add support for Elasticsearch 2.x

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2525]

**Comment by fblundun** [comment]
See https://groups.google.com/forum/#!topic/snowplow-user/L8ZteHGwtWg

**Comment by alexanderdean** [comment]
Blocked by https://github.com/awslabs/amazon-kinesis-connectors/pull/63

**Comment by alexanderdean** [comment]
Correction: not blocked, bringing forwards

**Comment by jbeemster** [comment]
Hey @alexanderdean, this ticket could be solved quite quickly by either:

1. Doing robust testing of the 0.7.0 release and checking whether the current HTTP client works for 2.x

2. Building a second binary with an updated dependency on the Jest Elasticsearch client. (This is preferable as their 2.x library does not work necessarily work backwards)
