### ISSUE TITLE
Enrichments: City by coordinates

### ISSUE THREAD

**Issue by dannyeuu** [snowplow/snowplow#2526]
We could have some way to enrich city, state, country by coordinates? IP lockup with GeoCity it's too bad, even with premium account in large cities!

**Comment by alexanderdean** [comment]
MaxMind is famously pretty inaccurate in Brazil... Maybe take a look at https://geocoder.opencagedata.com/ ?

**Comment by dannyeuu** [comment]
Cool!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/141
