### ISSUE TITLE
Documentation: rename Scala Kinesis Enrich to Stream Enrich

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2529]
I don't know whether we want to also change it on documentation for earlier versions of SKE.

To avoid broken links, maybe we could keep have each old page (e.g. Scala-Kinesis-Enrich.md) contain only a link to the corresponding new page.

**Comment by alexanderdean** [comment]
I think @ihortom will have a view on this - suspect he will want to "grandfather" the old page somewhere...

**Comment by ihortom** [comment]
@alexanderdean / @fblundun - I think that if there's a necessity to rename a (old) page, we should rather:

1. Create a new one with the required name (and moved/amended content). 
2. The old page should remain with the note the page has been moved and provide the link to the new page.

**Comment by fblundun** [comment]
I have just made this change everywhere except the upgrade guide and the version matrix.

I have left pages for earlier versions of SKE (like [this one](https://github.com/snowplow/snowplow/wiki/Install-Scala-Kinesis-Enrich-v0.1)) as they were, since the project was still called Scala Kinesis Enrich at the time of those versions.

I have tried to avoid creating outdated or broken links but I won't be surprised if I missed some - please let me know if you find any.

**Comment by alexanderdean** [comment]
Thanks @fblundun!

**Comment by fblundun** [comment]
I just noticed the large comment in the markdown for the version matrix page [here](https://github.com/snowplow/snowplow/wiki/Snowplow-version-matrix). Should I change it there too? Does that comment need to continue to exist?

**Comment by alexanderdean** [comment]
That comment can be deleted...

**Comment by fblundun** [comment]
I have removed it, and this ticket is finished.
