### ISSUE TITLE
Update Configure shredding page

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2531]
It's quite out-of-date: https://github.com/snowplow/snowplow/wiki/6-Configuring-shredding

**Comment by ihortom** [comment]
That page and subject triggers the need to update the following pages too:
https://github.com/snowplow/snowplow/wiki/setting-up-EmrEtlRunner
https://github.com/snowplow/snowplow/wiki/Shredding
https://github.com/snowplow/snowplow/wiki/4-Loading-shredded-types
Will take care of them.

**Comment by alexanderdean** [comment]
Awesome - thanks @ihortom!

**Comment by ihortom** [comment]
@alexanderdean - Updated all the pages.

**Comment by alexanderdean** [comment]
Thanks! Pushed, closing
