### ISSUE TITLE
Encoding `refr` vs `url`

### ISSUE THREAD

**Issue by mariussoutier** [snowplow/snowplow#2539]
Hi,

I'm using the JS collector 2.5.3 and a modified version of the Scala Stream collector (only added a Kafka sink).

I want to generate a page flow diagram, however there's an issue with URL encoding of the `page_referrer` (`refr` attribute) in comparison with `page_url` (`url` attribute). 

Example:
`url` contains correctly encoded value: `https://www.example.org/D%C3%BCfte/index16.html`
`refr` contains additional chars: `https://www.example.org/D%25C3%25BCfte/index16.html`, as if the % signs were encoded again.

Now this sometimes happens in the page_url, sometimes in page_referrer. Any idea what the cause might be?

**Comment by alexanderdean** [comment]
Hi @mariussoutier - it's awesome that you are working on Kafka support for Snowplow! It sounds like you are having trouble with your enrichment process - presumably you've taken Stream Enrich and added Kafka support. Open a PR containing the problematic code and we'll be happy to take a look!

**Comment by mariussoutier** [comment]
I've checked the two parameters before the enrichment process - they are already problematic when extracting from the raw parameters (e.g. `rawEvent.parameters.get("url")`). Is this something you've already seen?

**Comment by alexanderdean** [comment]
There's a lot of logic in Common Enrich to deal with all sorts of edge cases in the incoming event stream - your best bet is to use that component... It shouldn't be too difficult to integrate Kafka support into Stream Enrich, which embeds Common Enrich.

**Comment by mariussoutier** [comment]
I'm already using common enrich. I also haven't found a lot code that handles these kind of problems.

**Comment by alexanderdean** [comment]
Can you share an example of the problem? Ideally something like:

* Visiting this page URI from this referer URI
* The page URI/referer URI is incorrect in the `rawEvent`: xxx
* The page URI/referer URI is incorrect in the enriched event: xxx

**Comment by mariussoutier** [comment]
Nevermind, Snowplow is working fine. It's the system that produces the URLs that is inconsistent with encodings.

**Comment by alexanderdean** [comment]
Ah - thanks for clarifying!

**Comment by mariussoutier** [comment]
Sure, thanks for your support.
