### ISSUE TITLE
Make page URL parsing an independent enrichment

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2542]
We have some users (e.g. that are doing ad tracking) that lose a % of data owing to events being recorded on URLs that are invalid, but that they do not control.

The proposal here is to have a setting in the pipeline so that if a URL is invalid, rather than failing the whole event just the different page_url related fields.

This might be easier to deliver if the page URL parsing was broken out into an independent enrichment with it's own json config?

**Comment by alexanderdean** [comment]
Yep I think page URL parsing needs to become an independent enrichment - as a first draft it can obviously still populate the legacy columns (so it will be a "configurable enrichment populating legacy fields" in @ihortom's parlance).

Having a standalone URL enrichment is similar to how Keen do it: https://keen.io/docs/api/#url-parser

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/142
