### ISSUE TITLE
Automated documentation 

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/snowplow#2543]
You are referring to 2.5.3 (see below string), but you already released 2.6.0. 

```
http://d1fc8wv8zag5ca.cloudfront.net/2.5.3/sp.js
```

It should be a build failure in your release engineering process to refer to such old symbols.

**Comment by alexanderdean** [comment]
Hey @ihortom - can you update the specific references? We will leave this ticket open afterwards as it refers to a wider point (automatic generation of new docs)...

**Comment by ihortom** [comment]
@alexanderdean - Updated the following pages:

- https://github.com/snowplow/snowplow/wiki/integrating-javascript-tags-onto-your-website
- https://github.com/snowplow/snowplow/wiki/hosted-assets

Also added a comment how to ensure the latest version is loaded (if the page is behind).

Will do the same to https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker once get local copy synced with the master (have some changes in progress).

**Comment by alexanderdean** [comment]
Pushed!

**Comment by ihortom** [comment]
@alexanderdean - Updated the last page. The ticket could be reassigned once pushed.

**Comment by alexanderdean** [comment]
Pushed and re-assigned

**Comment by paulboocock** [comment]
This is no longer relevant. The whole build and docs process has changed for the JS Tracker. Theres now a mix of manual docs - https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/ and automated stuff - https://github.com/snowplow/snowplow-javascript-tracker/blob/master/trackers/browser-tracker/docs/markdown/browser-tracker.md
