### ISSUE TITLE
EmrEtlRunner: add step to delete raw events from HDFS before shredding

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2545]
How fast would this file op be? It would presumably free up a lot of space ready for the shredding output...

**Comment by ihortom** [comment]
@alexanderdean - Is it to reclaim some space back (to be available for shredding)?

**Comment by alexanderdean** [comment]
Yes, hopefully it would reclaim some space mid-run...

**Comment by alexanderdean** [comment]
Moving forwards as this would really help a couple of clients... /cc @yalisassoon

**Comment by alexanderdean** [comment]
Bringing forwards given this help avoid some shred failures.
