### ISSUE TITLE
Rename EMR "Loading bad rows into Elasticsearch" step

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2549]
Currently when querying snowbot with the command `last emr status` the steps related to loading bad rows (errors) into Elasticsearch show up as below

```
Elasticity Scalding Step: Errors in s3n://goeuro-logs-out/clojure/shredded/bad/run=2016-03-18-19-05-24/ -> Elasticsearch: com.goeuro ES for bad rows | ...
Elasticity Scalding Step: Errors in s3n://goeuro-logs-out/clojure/enriched/bad/run=2016-03-18-19-05-24/ -> Elasticsearch: com.goeuro ES for bad rows | ...
```

which have the misleading wording `Errors in {{SHREDDED/ENRICHED_BAD_BUCKET_LOCATION}}`.

**Comment by alexanderdean** [comment]
Thanks, assigning

**Comment by BenFradet** [comment]
EMR steps have been renamed in #3945 , closing
