### ISSUE TITLE
Documentation: update wiki to include section for Analytics SDKs

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2555]
The first one is Scala but there will be others.

Start the documentation with the contents of:

http://snowplowanalytics.com/blog/2016/03/23/snowplow-scala-analytics-sdk-0.1.0-released/

**Comment by ihortom** [comment]
@alexanderdean - Done. Local copy is [here](https://github.com/ihortom/snowplow-wiki-temp/wiki/Snowplow-Analytics-SDK).

**Comment by alexanderdean** [comment]
Awesome - I will push once the GTM page has been reviewed...

**Comment by ihortom** [comment]
@alexanderdean - please, close (already live).
