### ISSUE TITLE
Scala Stream Kinesis Enrich binary + Embedded Iglu Repository question

### ISSUE THREAD

**Issue by Hamitamaru** [snowplow/snowplow#2558]
So based on this:
https://github.com/snowplow/iglu/wiki/Iglu-client-configuration

I can have a resolver that that will read from disk, shown in "Example 2: just one embedded repository":
`
"connection": {
    "embedded": {
        "path": "/iglu-embed-path"
    }
}
`

When I run the Scala Stream Kinesis Enrich (the binary that is shared from hosted assets page ) as shown here:
https://github.com/snowplow/snowplow/wiki/Run-Scala-Kinesis-Enrich

e.g.
$ ./path_a/scala-kinesis-enrich-0.3.0 --config /path_b/my.conf --resolver file:/path_c/resolver.json

Where does my "iglu-embed-path" folder need to be?

Is it:
/path_a/iglu-embed-path
/path_b/iglu-embed-path
/path_c/iglu-embed-path
or somewhere else?

( Sorry I know I should probably mark this as a question but I don't know how...)

**Comment by alexanderdean** [comment]
Hi @Hamitamaru - support questions to the Snowplow user group please.
