### ISSUE TITLE
Documentation: provide an example for JS Enrichment with context validation

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2573]
We can provide an example which generates some more useful (than current [one](https://github.com/snowplow/snowplow/wiki/JavaScript-script-enrichment#javascript-function)) derived context, along with its validation using Iglu Client right inside a function.

This can serve as a reminder about strengths and cautions of JS Enrichment as well as fact that we can call any method available in Scala Common Enrich.

Any suggestions about context?

/cc @ihortom

**Comment by alexanderdean** [comment]
Good idea @chuwy

**Comment by paulboocock** [comment]
This page now includes more complex examples on working with the event data in the JS Enrichment: https://docs.snowplowanalytics.com/docs/enriching-your-data/available-enrichments/custom-javascript-enrichment/
