### ISSUE TITLE
Scala Common Enrich: add functionality to load files from DynamoDB or the local filesystem

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2578]

**Comment by fblundun** [comment]
Actually this should probably be in a new library, separate from Common Enrich. Any suggestions on what to call it?

**Comment by alexanderdean** [comment]
Here are some ideas:

* `scala-kv-conf`
* `scala-confhaus` (inspired by [storehaus](https://github.com/twitter/storehaus))
* `scala-config-kv`

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/None

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/255
