### ISSUE TITLE
EmrEtlRunner: add automatic deletion of Tomcat logs for Clojure Collector that do not contain Snowplow data

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2582]
To save S3 storage space

**Comment by alexanderdean** [comment]
There are a few options:

1. Run the delete as part of the initial move to processing step (optionally with a new `config.yml` option to enable/disable these deletes)
2. Add the delete as a new (Clojure Collector only) step immediately after move to processing
3. Include the delete as a housekeeping step in EmrEtlRunner which can be invoked from the command-line but isn't part of the regular flow

They all have pros and cons - the difficulty with 3. is it's another separate process to schedule. The trouble with 1. and 2. is that they slow down the run time for non-essential housekeeping.

There is a further risk with 1. and 2., namely that we upgrade a long-term Snowplow user and then Sluice (which is not fast) gets stuck deleting thousands of files before EMR can even start. So it feels like we need the option of switching this functionality off and also the option to run just this functionality - for these reasons I am leaning towards option 2...

**Comment by justingourley** [comment]
Guys, thanks for digging in to this. I like option 3 the most as it feels the most flexible. We're scheduling the emr and storage loader tasks synchronously anyway so adding a 3rd step (if desired and maybe some users do not) would seem to be an easy option. Also, it can be tested/used independently of running emr runner which is great when we're running in dev and breaking things/clearing out s3 etc.

**Comment by alexanderdean** [comment]
I think you're right - option 3 is the least disruptive one and it can always be added to the regular DAG if somebody wants to delete events as they go along...

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the SSC:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881
