### ISSUE TITLE
Quick Start fails during first vagrant up

### ISSUE THREAD

**Issue by pj-moviestarplanet** [snowplow/snowplow#2594]
When I try the Quick Start the first vagrant up fails with the below error messages.

When I then ssh into the box and try to run sbt it says sbt does not exists. I guess thats because the vagrant provision failed.

Here is the output from vagrant
`
==> default: Checking connectivity... done.
==> default: git fetch https://github.com/snowplow/ansible-playbooks.git
==> default: ===
==> default: Traceback (most recent call last):
==> default:   File "/usr/local/bin/peru", line 9, in <module>
==> default:     load_entry_point('peru==0.4.0', 'console_scripts', 'peru')()
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 345, in main
==> default:     async.run_task(command_fn(params))
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/async.py", line 25, in run_task
==> default:     return asyncio.get_event_loop().run_until_complete(coro)
==> default:   File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
==> default:     return future.result()
==> default:   File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
==> default:     raise self._exception
==> default:   File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
==> default:     result = coro.send(value)
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/main.py", line 91, in do_sync
==> default:     params.runtime, params.scope, params.imports, params.runtime.sync_dir)
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/imports.py", line 18, in checkout
==> default:     previous_index_file=index)
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 414, in export_tree
==> default:     yield from session.checkout_files_from_index()
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 189, in checkout_files_from_index
==> default:     yield from self.git('checkout-index', '--all')
==> default:   File "/usr/local/lib/python3.4/dist-packages/peru/cache.py", line 77, in git
==> default:     raise GitError(command, process.returncode, stdout, stderr)
==> default: peru.cache.GitError: git command "['git', '--git-dir=/vagrant/vagrant/.peru/cache/trees', '--work-tree=/vagrant/vagrant', 'checkout-index', '--all']" returned error code 128.
==> default: stdout:
==> default: stderr: ansible/lib/ansible/module_utils/redhat.py already exists, no checkout
==> default: ansible/library/cloud/ec2_scaling_policy already exists, no checkout
==> default: ansible/library/source_control/hg already exists, no checkout
==> default: oss-playbooks/leiningen.yml already exists, no checkout
==> default: oss-playbooks/roles/packer/meta/main.yml already exists, no checkout
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
`

**Comment by alexanderdean** [comment]
Hi @pj-moviestarplanet , I've added a recovery guide here: http://discourse.snowplowanalytics.com/t/problems-with-vagrant-and-our-github-repositories/122
