### ISSUE TITLE
Scala Hadoop Enrich: add test for API Request Enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2603]

**Comment by alexanderdean** [comment]
Hi @chuwy - can you look at this one and let me know what has happened?

**Comment by alexanderdean** [comment]
My current theory is that something was overwritten in the force push which caused something to change so that this commit did not close, although I believe that the commit is now in master. I am nervous about closing this ticket and tagging the release until I head back from @chuwy however.

**Comment by chuwy** [comment]
I tend to think it caused by force-push as well. When I added this commit, I mistakenly referenced wrong issue #2604. But last time I ovverrode it right one (we can see reference above). But I cannot see why in commit log we have wrong reference now.

**Comment by alexanderdean** [comment]
Okay - so it sounds like:

* The feature was code complete 24 days ago
* 3 days ago you made a single change: fix the commit message to reference the correct ticket
* My force push undid the commit message fix

The solution: I rebase and reword the commit message, then force push again. Agree?

**Comment by chuwy** [comment]
But why my yesterday force-push didnt corrected it back?

**Comment by alexanderdean** [comment]
Not sure - but if the feature was code complete 24 days ago, I'm happy to fix per the above...
