### ISSUE TITLE
Scala Common Enrich: add adapter to pre-process Unbounce webhooks

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2615]
http://documentation.unbounce.com/hc/en-us/articles/203510044-Using-a-Webhook

The way this would work is as follows:
1. We ask users to add a hidden "schema" element into their forms
2. We use the schema element to make the `data.json` self-describing - this becomes the event (this is quite similar to the Iglu Adapter)
3. We add a context containing the other parameters (`page_id`, `page_name`, `page_url`, `variant`)

**Comment by alexanderdean** [comment]
Moving this into R85. This would be a good one for @ronnyml to do next

**Comment by jbeemster** [comment]
@alexanderdean we can define our own query-string parameters on the webhook.  Rather than hiding the schema in the form could we not just keep it with the webhooks?

**Comment by alexanderdean** [comment]
Ah, much better idea, let's do that! I was overthunking it. Thanks Josh.

**Comment by jbeemster** [comment]
No worries!  We have sample Unbounce data now and we will assume that schema={{ schema_uri }} is in the querystring.

**Comment by alexanderdean** [comment]
Nice
