### ISSUE TITLE
Discrepancy in `addTrans` documentation

### ISSUE THREAD

**Issue by adamlwgriffiths** [snowplow/snowplow#2620]
https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#addTrans

The description states it takes 7 parameters, the table provides 8 values, and the example provides 9.

The difference between the table and example code, is the example adds a tax field as the 4th parameter.

Looking at the [javascript](https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/src/js/tracker.js#L1792) it seems that it should have 9 values. Ie the documentation is missing the tax field.

**Comment by alexanderdean** [comment]
Thanks @adamlwgriffiths, assigning to @ihortom

**Comment by ihortom** [comment]
@alexanderdean - [Updated](https://github.com/ihortom/snowplow-wiki-temp/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#addTrans). Also modified the table as it was confusing *Parameter* with its *Description*

**Comment by alexanderdean** [comment]
Thanks pushed!
