### ISSUE TITLE
Wiki documentation: move Troubleshooting jobs on Elastic MapReduce page to Discourse

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2623]
https://github.com/snowplow/snowplow/wiki/Troubleshooting-jobs-on-Elastic-MapReduce

Refresh the page and screenshots and move the guide over.

Because this page is referenced in help messages from the EmrEtlRunner, rather than delete this page we should replace it with a link to the knowledgebase article

**Comment by paulboocock** [comment]
Closing, this page no longer exists and we're in the process of deprecating EMR usage.
