### ISSUE TITLE
Wiki documentation: move Troubleshooting Clojure Collector instances to prevent data loss page to Discourse

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2625]
https://github.com/snowplow/snowplow/wiki/Troubleshooting-Clojure-Collector-instances-to-prevent-data-loss

**Comment by ihortom** [comment]
@alexanderdean - Done: http://discourse.snowplowanalytics.com/t/troubleshooting-clojure-collector-instances-to-prevent-data-loss/184

**Comment by alexanderdean** [comment]
Awesome - closing!
