### ISSUE TITLE
TrackerPayload logger is verbose on INFO level

### ISSUE THREAD

**Issue by rgabo** [snowplow/snowplow#2630]
We are seeing each key-value pair logged by `com.snowplowanalytics.snowplow.tracker.payload.TrackerPayload` on INFO level. As a result a single API request generates 192 log entries with JSON serialization overhead.

I would suggest that `TrackerPayload` logs on `DEBUG` or `TRACE` :smile:

**Comment by jbeemster** [comment]
Hi @rgabo, is this referring to the Java Tracker?

**Comment by rgabo** [comment]
Hey @jbeemster, yes, we are using the latest Java Tracker with BatchEmitter.

**Comment by jbeemster** [comment]
Okay @rgabo no worries, I will move this ticket to the appropriate repo then!  Agreed that it should be moved to trace as it really doesn't need to be that low.

**Comment by rgabo** [comment]
Ouch, forgot that trackers now have their own repos. Thanks Josh!
