### ISSUE TITLE
Scala Hadoop Bad Rows: add range of etl_tstamps to process

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2636]
This would be two arguments to Bad Rows to specify the range of etl_tstamps to include in the reprocessing.

**Comment by fblundun** [comment]
Moving back - for now we are letting users manually define which input buckets to reprocess using s3distcp regular expressions.

**Comment by BenFradet** [comment]
can be done through snowplow-event-recovery through partitioning
