### ISSUE TITLE
Placeholder for tracking the mutation applied in Hadoop Bad Rows

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2637]
Potentially a new context added to audit the mutation required to get this through the Snowplow pipeline

**Comment by fblundun** [comment]
It would be possible for users to do this in the custom JavaScript.

**Comment by alexanderdean** [comment]
Good way of prototyping it!

**Comment by BenFradet** [comment]
migrated to snowplow-incubator/snowplow-event-recovery#21
