### ISSUE TITLE
Scala Common Enrich: placeholder for validating the derived contexts

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2639]
As we make the enrichments more and more powerful, the likelihood of introducing invalid derived contexts (i.e. contexts that don't validate against their claimed schemas) increases. At the moment we will catch this downstream in Scala Hadoop Shred, but there's no equivalent safety net for other consumers of the enriched events. And in any case, a Snowplow enriched event should be considerable as fully validated.

**Comment by chuwy** [comment]
Fully agree. I was tempted to validate contexts in API Request enrichment (this is actually really easy), but decided that doing so per-enrichment basis is wrong.

**Comment by alexanderdean** [comment]
You made the right call @chuwy! Will be great to do this ticket in due course...

**Comment by benjben** [comment]
Handled by #3795
