### ISSUE TITLE
404 in documentation

### ISSUE THREAD

**Issue by timgriffin** [snowplow/snowplow#2640]
See https://github.com/snowplow/snowplow/wiki/SendGrid-webhook-setup#setup-redshift

The following URLs linked are 404s:

- https://github.com/snowplow/snowplow/tree/master/4-storage/redshift-storage/sql/com.sendgrid/delivered.sql
- https://github.com/snowplow/snowplow/tree/master/4-storage/redshift-storage/sql/com.sendgrid/spam_report_1.sql

**Comment by alexanderdean** [comment]
Thanks! Assigning

**Comment by ihortom** [comment]
@alexanderdean - Fixed the broken links (locally).

**Comment by alexanderdean** [comment]
Pushed to main, closing
