### ISSUE TITLE
EmrEtlRunner: add "no logs to process" message on exit with return code 3

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2644]

**Comment by BenFradet** [comment]
@alexanderdean Is this regarding the staging Sluice operations?
If so, they should be converted to S3DistCps as per #276 and we won't have control over whether or not the directory was empty.

What do you think?

**Comment by alexanderdean** [comment]
Hey @BenFradet - you raise a good point, which is that it will be hard to perform the various data checks in a world where all the file move code has moved to the cluster. I'm talking here both about the "no data to process" no-op state and the "data already found in {processing|enriched|shredded}, a previous run is ongoing" no-op state.

I think we need a new ticket in your release to brainstorm approaches here...

**Comment by alexanderdean** [comment]
See https://github.com/snowplow/snowplow/issues/3112

**Comment by BenFradet** [comment]
Since this is back on the menu per #3112, do you think putting the error message is enough?

Also, shouldn't we do the same in case of a `DirNotEmptyError`?

**Comment by alexanderdean** [comment]
I think for return code 3 we need the info (or warn? not error) message, as well as the return code.

I think a companion ticket for an info message in the case of a `DirNotEmptyError` would be great - please add!

**Comment by BenFradet** [comment]
By the way did you mean a log message or a tracker message?

**Comment by alexanderdean** [comment]
stdout
