### ISSUE TITLE
Add some more examples of sending custom contexts with events using the Python tracker

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2645]
In the Python technical documentation.

Just gone through this with a client and the examples are pretty sparse - would be nice to see a complete example of e.g. a `track_page_view` and one / two other event types sent with a contexts array containing more than one context.

**Comment by paulboocock** [comment]
https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/python-tracker/tracking-specific-events/#1-custom-context
