### ISSUE TITLE
Documentation capitalisation change for Python tracker

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#2664]
I think the code snippet on the Python tracker page should have `subject` capitalised.
https://github.com/snowplow/snowplow/wiki/Python-Tracker

```
from snowplow_tracker import Subject
s = Subject()
```

**Comment by alexanderdean** [comment]
Agreed - thanks @miike!

**Comment by ihortom** [comment]
@alexanderdean - modified locally.

**Comment by alexanderdean** [comment]
Pushed, thanks, closing!
