### ISSUE TITLE
Documentation: Code example change for Python tracker (setting timezone)

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#2665]
The code snippet for settings timezone under section 3.6 https://github.com/snowplow/snowplow/wiki/Python-Tracker

should read
`s.set_timezone("Europe/London")`
it currently reads
`s.set_color_depth("Europe/London)`

**Comment by alexanderdean** [comment]
Whoops - thanks

**Comment by ihortom** [comment]
@alexanderdean - modified locally.

**Comment by alexanderdean** [comment]
Pushed, thanks, closing!
