### ISSUE TITLE
Add Python Analytics SDK to Snowplow Analytics SDK wiki

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2680]
Blog: http://snowplowanalytics.com/blog/2016/05/17/snowplow-python-analytics-sdk-0.1.0-released/
Wiki: https://github.com/snowplow/snowplow/wiki/Snowplow-Analytics-SDK

**Comment by ihortom** [comment]
Actually it's already added but not referenced in the homepage for Snowplow Analytics SDK. Updating it now...

**Comment by ihortom** [comment]
@alexanderdean - updated (locally). Please, push.

**Comment by alexanderdean** [comment]
Done, closing
