### ISSUE TITLE
Hadoop Event Recovery: support raw collector files as input

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2681]
Currently we assume that Event Recovery should work on the bad rows output by Scala Hadoop Enrich, but in fact there are situations where it is known that all of the raw collector files are bad, and need fixing.

A good example of this: http://discourse.snowplowanalytics.com/t/cant-enrich-custom-events-with-custom-schemas-repository/237/4

We should extend Hadoop Event Recovery to work on raw collector files as well as bad rows output.

A workaround till this is implemented would be to run Snowplow Hadoop Enrich and then Event Recovery, but this would be pretty wasteful.

**Comment by fblundun** [comment]
We could do this with a mandatory --input-format argument which would initially support two values, `raw` and `bad`.

**Comment by fblundun** [comment]
When using raw collector files as input, I assume we would just pass an empty array as the "errors" argument of the user-defined function. That way, users could write a single function which would work in both cases.

**Comment by alexanderdean** [comment]
I wonder if it should be `raw` or the specific formats (`clj-tomcat`, `cloudfront` etc)...

**Comment by alexanderdean** [comment]
> When using raw collector files as input, I assume we would just pass an empty array as the "errors" argument of the user-defined function

I think that sounds good...

**Comment by fblundun** [comment]
I think there are two configurable things here:

* What created the raw lines (cloudfront vs clj-tomcat)
* Whether the raw lines are wrapped in a bad row JSONs

At the moment, only the second of these would change the logic that the job actually runs - I don't know how we would treat cloudfront vs clojure raw lines differently?

**Comment by alexanderdean** [comment]
CloudFront versus Clojure is perhaps a bad example as the Clojure row is a superset of the CloudFront row - I suppose `clj-tomcat` versus `thrift` is a more challenging example...

**Comment by fblundun** [comment]
It does seem unfair to force users to decode Thrift using JS.

In a discussion we came to the conclusion that for the first Hadoop Event Recovery release we will make it possible to configure the input type as either raw lines or bad rows, and won't support Thrift. A future release will orthogonally make it possible to configure whether to expect Thrift, Cloudfront, or clj-tomcat log lines.

**Comment by BenFradet** [comment]
migrated to snowplow-incubator/snowplow-event-recovery#19
