### ISSUE TITLE
Question about Stream collector

### ISSUE THREAD

**Issue by bcharp** [snowplow/snowplow#2682]
I'm starting to look at the scala stream collector, as it's out of beta, and I have some questions. 
We use the clojure collector+emr right now, with quite a high volume.

If I [understand correctly](http://discourse.snowplowanalytics.com/t/need-help-getting-events-from-kinesis-to-s3-to-redshift/39), Snowplow follow the [Lambda architecture](http://lambda-architecture.net/) meaning that there should be two pipelines, one for maintaining a dataset, and one for real time data.

So, if I understood correctly, my architecture with the stream collector should look like : 

```
scala-collector -> Raw Events Stream 
```

then two parts

```
[real time case] -> scala-enrich-sink -> ElasticSearch -> Kibana.

[dataset case] -> scala-kinesis-s3-sink  -> S3 (raw events) -> EmrEtlRunner -> S3 (enriched & shredded) -> StorageLoader -> Redshift.
```

Am I right ?

So... questions : 

* In the AWS case study there is a schema with a redshift drip-feed. [https://aws.amazon.com/solutions/case-studies/snowplow/](https://aws.amazon.com/solutions/case-studies/snowplow/) 
I found some third party code on that, but what's the status, do you plan to integrate it as a part of snowplow ? 	
Does it follow the Lambda Architecture pattern / the snowplow philosophy ?

* Following the lambda architecture, I don't need all my data to be real-time, only a subset. What's the best way to do that ? 
(separate iglu repository ? Keep both the clojure and strean collector ? )

* Seamlessly, where can I put my data at the end of the scala-enrich-sink, in snowplow mini it use elasticsearch, but can I use whatever I want ?

* If I want to use elasticsearch, how can I manage that ? Is there a scala-kinesis-es-sink that would work with the result of the scala enrichment process ?

**Comment by alexanderdean** [comment]
Hey @bcharp - these are great questions, and we'd love to answer them! The best place for discussion questions is on our Discourse forums: http://discourse.snowplowanalytics.com/
