### ISSUE TITLE
Spark Shred: consider refactoring the folder structure for shredded JSONs

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2687]
With a customer with a very high cardinality of event types, when running on a large number of Hadoop workers (20+), we have seen issues where their S3DisCp step fails due to [S3 partition hotspotting](http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html).

From talking to the AWS team, we have learnt that slashes are significant in the S3 partitioning system - which means that:

```
mybucket/A_B_C_D/RAND/part-00001
```

will be less likely to suffer from S3 partition hotspotting than:

```
mybucket/A/B/C/D/RAND/part-00001
```

(where `A`, `B`, `C`, `D` represent the four logical sections of an Iglu schema URI, and `RAND` is the hex hash key to prevent hotspotting).

We should therefore consider refactoring the folder structure to reduce the risk of S3 partition hotspotting.

**Comment by alexanderdean** [comment]
See also: https://github.com/snowplow/snowplow/issues/2678

**Comment by BenFradet** [comment]
we're now running consolidation to avoid the issue, closing
