### ISSUE TITLE
Add EmrEtlRunner option to filecrush to hour precision not just day

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#269]
The filecrush code rolls up all CloudFront files to the day currently:

```
"--groupBy"           , ".*\\.([0-9]+-[0-9]+-[0-9]+)-[0-9]+\\..*",
```

For most users, this will be fine - if they run nightly, they will end up with 1 or a handful of LZO-compressed files of 128Mb each.

**But** for absolutely huge sites and content/ad networks, it may be more efficient to compress at the level of each hour:

```
"--groupBy"           , ".*\\.([0-9]+-[0-9]+-[0-9]+-[0-9]+)\\..*",
```

Note the moved ")" in the above. Add a configuration argument to config.yml to support this option.

Low priority - +1 this ticket if you fall into this bucket (sorry).

**Comment by BenFradet** [comment]
consolidation is done when moving data from hdfs to s3, closing
