### ISSUE TITLE
EmrEtlRunner: handle run= sub-folders if resuming from shred

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2693]
If EmrEtlRunner sees --skip enrich (but implied, please do shred), then it will first copy the enriched events back from S3 enriched:good into HDFS ready for shredding.

Unfortunately this doesn't work out of the box, because the logic copies up the /run=xxx sub-folders, and these cause the Hadoop job to break (Hadoop hates sub-folders). So the quick fix in config.yml is to temporarily specify the actual /run=xxx sub-folder against enriched:good (has to be reverted afterwards).

A better approach would be to use S3 pattern expressions to flatten the /run=xxx sub-folders.

**Comment by alexanderdean** [comment]
Pushing back...

**Comment by BenFradet** [comment]
@alexanderdean Is this assuming an enrich run already occurred?

**Comment by alexanderdean** [comment]
Hey @BenFradet - yes, this is to handle the situation where the Hadoop Enrich step has already occurred, the user is resuming from the Hadoop Shred step (`--skip enrich`). It's worth trying this yourself in the Dev account, you'll then see what the problem is first hand (basically: the run= folder gets copied to HDFS and Hadoop Shred dies when it encounters a folder).

**Comment by alexanderdean** [comment]
I know this may go away with the move to Spark, but I think it makes sense to tackle it sooner...

**Comment by BenFradet** [comment]
ahah I was about to post this lol
