### ISSUE TITLE
Scala Stream Collector: add support for cookie bounce

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2697]
## Context

More and more web clients do not support or block 3rd party cookies. The result is, that one user browsing the website results in a series of events, that have the same domain_userid but a lot of different network_userids. For later processing the network_userid is completely useless and could be set to a fixed value like `00000000-0000-4000-A000-000000000000` to adhere to the UUID rules.
## Why

It saves a lot of computation later in the process, because it cuts down the flood of useless network_userids, which will never be seen again.
## How is it done?

Ususally the cookie bounce works like this: The collector takes the request, checks for the presence of the defined cookie name.
- If it is there: use it and process the request.
- If the cookie is missing, the collector issues a redirect to itself with an magic/uniq/special query parameter and the Set-Cookie header. Once the client follows the redirect, the collector checks for the presence of the cookie.
- If it is not presented by the client, it is obvious that 3rd party cookies do not work.
- In this case the network_userid can be set to the defined value and the request could be processed. 
## Implications

This behaviour results in a bit more traffic due to this additional redirect. We observed roughly 30%.

Ideally the value of the network_userid could be specified in the config. If nothing was specified, the collector would work, like it used to be. 

Any suggestions?

**Comment by alexanderdean** [comment]
Discussion is here: http://discourse.snowplowanalytics.com/t/scala-stream-collector-add-support-for-cookie-bounce/306

**Comment by christoph-buente** [comment]
Thx @alexanderdean, but it does not seem to resound with the needs of the rest of the community :)

**Comment by alexanderdean** [comment]
Give it time!

**Comment by christoph-buente** [comment]
⌚ waiting

**Comment by christoph-buente** [comment]
@alexanderdean Can you check our internal pull request?

https://github.com/liveintent-berlin/snowplow/pull/1/files and provide some feedback on it?
