### ISSUE TITLE
Explore options to archive the HDFS compacted files alongside the raw Cf logs

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#270]
References:
1. https://github.com/snowplow/snowplow/issues/82
2. https://groups.google.com/forum/#!topic/snowplow-user/xdhegsztJlA
3. http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_s3distcp.html

It looks like S3DistCp may be a bit of a gamechanger in terms of being able to archive the compacted files.

**Comment by alexanderdean** [comment]
Should we rename to be more clearly focused on an out-of-band compaction process for Very Big users?

**Comment by BenFradet** [comment]
consolidation is now done when moving data from hdfs to s3 closing
