### ISSUE TITLE
Placeholder for deciding overall CI/CD approach

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2704]
We have already implemented some CI/CD - see https://github.com/snowplow/snowplow/issues/2621 This ticket is about defining the overall approach across the whole repo.

Options:
1. **Tag-driven build** - Component-version tags drive releases, and also version numbers of components (i.e. e.g. `BuildSettings.scala` is dynamically populated with version number)
2. **Double-entry build** - Component-version tags drive releases, and the versions they dictate are validated against the versions in `BuildSettings.scala` etc
3. **Semi-smart build** - Component tags drive releases, but the versions are pulled from `BuildSettings.scala`
4. **Smart build** - Generic tags drive releases, but the component-versions to include are detected automatically by a smart build script

Currently the Kinesis CI/CD is a hybrid of approaches 1 and 2 - the Kinesis zipfile is driven from the tag; the constituent app versions are driven from the `BuildSettings.scala` files.

**Comment by alexanderdean** [comment]
R81 is going to update:

* Scala Common Enrich
* Stream Enrich
* Hadoop Event Recovery

**Comment by alexanderdean** [comment]
Proposal:

1. We define a set of aliases for each unit of deployment (e.g. Scala Common Enrich, Stream Enrich, Hadoop Event Recovery)
2. We come up with a syntax to support Double-entry build with multiple components, like:

```
sce-0.24.0;se-0.9.0;her-0.2.0
```

where:

1. Components are published sequentially in left-to-right order
2. Component versions are validated against `BuildSettings.scala` etc

**Comment by fblundun** [comment]
A big advantage of tag-driven builds: you can be selective about what you build. A given subproject may be changed in the development branch, but that doesn't necessarily mean that you want to spend time building and deploying it with every commit in that branch.

**Comment by ninjabear** [comment]
Proposal:

We have a self describing json in the root that tells the build what to run and what to release. This would change over time and would be updated manually by the person editing a specific component.

This would allow the person to select different items freehand and allow some complexity while enforcing a standard format.

**Comment by alexanderdean** [comment]
What about the JSON-based approach, but then allow the tag to whitelist or blacklist specific components, so e.g.

```
+sce;+her
```

will only push SCE and HER.

or

```
-sce
```

will push all but SCE.

**Comment by alexanderdean** [comment]
@BenFradet @chuwy - it feels like we have consensus on how CI/CD works/should work for this repo. Can I close?

**Comment by chuwy** [comment]
Fine by me.
