### ISSUE TITLE
Stream Enrich: disable EC2 metadata context on non-EC2 boxes

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2707]
Scala Tracker tries to reach 169.254.169.254:80 which is reserved on AWS EC2 to get [instance identity document](https://github.com/snowplow/iglu-central/blob/master/schemas/com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0). However, on non-EC2 boxes it crashes tracker: http://discourse.snowplowanalytics.com/t/scala-stream-enrich-connection-attempt-to-169-254-169-254-80-failed/326

**Comment by alexanderdean** [comment]
Should this logic be inside the Scala Tracker? Otherwise we have to solve for this problem in every application using the tracker...

**Comment by chuwy** [comment]
To get instance identity we need to either explicitly call [`getInstanceContextBlocking`](https://github.com/snowplow/snowplow-scala-tracker/blob/master/src/main/scala/com.snowplowanalytics.snowplow/scalatracker/Ec2Metadata.scala#L73) which waits for context and if it is unavailable just return `None` or explicitly call [`getInstanceContextFuture`](https://github.com/snowplow/snowplow-scala-tracker/blob/master/src/main/scala/com.snowplowanalytics.snowplow/scalatracker/Ec2Metadata.scala#L87) which switches on automatic context attaching and if `Future` is faling it crashes tracker.
So, in both cases user of tracker needs to explicitly fetch context.

**Comment by chuwy** [comment]
So, what I suggest is to switch to first option with `Option[Context]` which will not return a context if it is not an EC2.

**Comment by alexanderdean** [comment]
Hmm - why does the second option crash the tracker if the EC2 metadata is not available? That feels unnecessarily risky.

**Comment by chuwy** [comment]
Hm, sorry, I was a bit wrong (it was a long time since I worked on that context). In Stream Enrich we're using [enableEc2Context](https://github.com/snowplow/snowplow-scala-tracker/blob/master/src/main/scala/com.snowplowanalytics.snowplow/scalatracker/Tracker.scala#L250) which should switch on automatic context attaching and it shouldn't crash app.

**Comment by alexanderdean** [comment]
Got it - so maybe the problem in that Discourse ticket is slightly different?

**Comment by chuwy** [comment]
The only thing I can suggest is that what was posted there is just a warning and not a critical error.

**Comment by jbeemster** [comment]
It doesn't look like it is crashing his application just adding logs.

**Comment by chuwy** [comment]
We need clarify it and if it's just a warning - this ticket appears to be invalid.

**Comment by jbeemster** [comment]
Easiest way to check would be to run that application locally yourself potentially?

**Comment by alexanderdean** [comment]
Is this a verified issue?

**Comment by chuwy** [comment]
No, I think it is not. Scala Tracker didn't crash my application (so it is safe to try enableEc2Context on non-EC2) and Spycomb's problem also lays not in the tracker.
