### ISSUE TITLE
EmrEtlRunner: update snowplow-ami4-bootstrap.sh to take optional commons-codec version argument

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#2713]
See #2691

We may have to create a new bootstrap script - I don't know whether changing the old one will cause problems when running the version of Hadoop Enrich which uses commons codec version 0.5.0.

**Comment by chuwy** [comment]
Probably typo. I see commons-codec-1.5.

**Comment by alexanderdean** [comment]
Hey @fblundun, @chuwy - do we think doing an in-place mutation is safe here? I wonder if we should be moving to a more robust approach where the Scala Hadoop Enrich version is provided to the bootstrap script which then decides what specific versions of things to deploy/delete...

**Comment by alexanderdean** [comment]
When I ask if it's safe, I mean are we happy for existing clusters using older versions of SHE to have this change applied to them too...

**Comment by fblundun** [comment]
Before doing it in place, we should at least check whether it will actually works without giving us some sort of binary incompatibility error.

We could also just put the bootstrap script's S3 location in the configuration YAML.

**Comment by fblundun** [comment]
@chuwy you are right, it was a typo. Should have said 1.5 instead of 0.5.0.

**Comment by alexanderdean** [comment]
Sure, I just renamed it (feel free to teak title further)
