### ISSUE TITLE
Scala Hadoop Enrich: add test for SQL Query Enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2718]
Test is disabled for now and needs to be [enabled](https://github.com/snowplow/snowplow/commit/a463b12748be28a71b64c51d3d71ecd778a28b69#diff-7077fdbbbf41283a403f6d3d49f1a3ebR184) after https://github.com/snowplow/iglu-central/pull/349 merged.

**Comment by chuwy** [comment]
Hey @alexanderdean! Just heads up that we need to release Iglu Central to make this test work.

**Comment by alexanderdean** [comment]
That's fine - that's next on my list to do!
