### ISSUE TITLE
Scala Hadoop Enrich: bump to 1.9.0

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#2725]

**Comment by chuwy** [comment]
@jbeemster https://github.com/snowplow/snowplow/issues/2716 https://github.com/snowplow/snowplow/issues/2717 these are scheduled for 82.

**Comment by alexanderdean** [comment]
Add one to these numbers Josh...

**Comment by jbeemster** [comment]
So 1.8.1?

**Comment by alexanderdean** [comment]
No this is new functionality so 1.9.0

**Comment by alexanderdean** [comment]
@jbeemster can you cherry-pick this into your CloudFront branch as the latter will be put into test first...

**Comment by BenFradet** [comment]
superseded by #3533, closing
