### ISSUE TITLE
StorageLoader: fix integer columns in com.optimizely schemas

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2731]
There was a bug in Schema Guru 0.6.0/Schema DDL 0.3.0 which transformed type `integer,null` into `VARCHAR(4096)`. Currently I can see only [com.optimizely](https://github.com/snowplow/snowplow/tree/661c6a60c84b3a8af113118d162f0a29680d6904/4-storage/redshift-storage/sql/com.optimizely) DDLs were produced with Schema DDL 0.3.0 and seems only [state_1.sql](https://github.com/snowplow/snowplow/blob/661c6a60c84b3a8af113118d162f0a29680d6904/4-storage/redshift-storage/sql/com.optimizely/state_1.sql#L20) was [affected](https://github.com/snowplow/iglu-central/blob/master/schemas/com.optimizely/state/jsonschema/1-0-0#L19-L22).

**Comment by alexanderdean** [comment]
Thanks for digging into this @chuwy . We may be able to make this fix without breaking existing Snowplow pipelines - I am going to schedule this for R83 and we'll take a look...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/iglu-central/issues/631.
