### ISSUE TITLE
Add Snowplow BigQuery Loader

### ISSUE THREAD

**Issue by kala725** [snowplow/snowplow#2732]
@alexanderdean @fblundun Can you please guide me for the same. Is there any lib available for snowplow bigquery integration ?

**Comment by alexanderdean** [comment]
Hi @kala725 ! This is a cool idea but not something we are actively developing yet.

**Comment by alexanderdean** [comment]
This is being worked on here: https://github.com/snowplow-incubator/snowplow-bigquery-loader
