### ISSUE TITLE
EmrEtlRunner: add version recognition of currently installed commons-codec

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2735]
See https://github.com/snowplow/snowplow/issues/2713

We need to recognize installed version of commons-codec and pass it as argument to bootrstap shell-script which can delete it and substitute with appropriate version.

**Comment by alexanderdean** [comment]
We can achieve this with a simple (static) lookup table of Scala Hadoop Enrich versions...

**Comment by chuwy** [comment]
@alexanderdean can I rephrase #2713 about deletion of file? Or do I need to create new ticket and close that one?

**Comment by chuwy** [comment]
@alexanderdean could you please elaborate on lookup table? As I can see we need to delete codec that already installed, not codec shipped with Scala Hadoop Enrich. How can we find version information from SHE?

**Comment by chuwy** [comment]
Oh, that should be same version. Sorry, nevermind.

**Comment by alexanderdean** [comment]
The lookup table is about which version of commons-codec to install, not which ones to delete...

If SHE is >= 0.24.0, then install 0.10.0, otherwise 0.5.0

Just be careful about doing semantically correct version number comparisons
