### ISSUE TITLE
Can Snowplow be used with a Publisher/Subscriber pattern

### ISSUE THREAD

**Issue by guevaraf** [snowplow/snowplow#2736]
I'm extremely new to snowplow but I was wondering if there is an easy way to implement this pattern where not only the Snowplow's collectors received the tracked event.

Any ides?

**Comment by alexanderdean** [comment]
Hey @guevaraf ! Great question - please raise on our forums (GitHub is for bugs and new features): http://discourse.snowplowanalytics.com/
