### ISSUE TITLE
Clojure Collector: make cookie path configurable

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2739]
Sister ticket to #2528.

The cookie path should default to "/", but we should allow a configurable override to help users with existing cookies on e.g. "/com.snowplowanalytics.snowplow/"

**Comment by danielmohacsi** [comment]
Any status update on this?

**Comment by alexanderdean** [comment]
Please use the reaction icons if you are interested in seeing a feature being prioritised. Any progress on a ticket will be visible on the ticket with an associated git commit.

**Comment by alexanderdean** [comment]
Won't fix, we are doubling down on the Scala Stream Collector per:

http://discourse.snowplowanalytics.com/t/replacing-the-clojure-collector/881

This is fixed in the SSC.

**Comment by alexanderdean** [comment]
Re-opening as I think wontfixes are confusing. A bug is a bug!
