### ISSUE TITLE
Ad Impressions support on Mobile

### ISSUE THREAD

**Issue by jpotts18** [snowplow/snowplow#2741]
One of the examples in the javascript tracker [ads.html](https://github.com/snowplow/snowplow-javascript-tracker/blob/15cecb7bf398aa02d251ea6fc7f0a6a0eff5940e/examples/ads/async.html) shows the use of ad impressions. 

```javascript
window.adTracker('trackAdImpression:' + rnd, 
  '67965967893',            // impressionId
  'cpa',                    // costModel - 'cpa', 'cpc', or 'cpm'            
  10,                       // cost - requires costModel
  'http://www.example.com', // targetUrl
  '23',                     // bannerId
  '7',                      // zoneId
  '201',                    // advertiserId
  '12'                      // campaignId
);
```

I have tried to search through the Android repository to see if this is supported yet. If you could please let me know if it is / where it is in the roadmap? It looks like the Collect and Storage phases have some code written for this based on this [search](https://github.com/snowplow/snowplow/search?utf8=%E2%9C%93&q=impression)

**Comment by alexanderdean** [comment]
Hi @jpotts18 - ah, good timing - we are working on a new Android Tracker release now. `trackAdImpression` is a very thin wrapper around the underlying self-describing JSON:

https://github.com/snowplow/snowplow-javascript-tracker/blob/4e52a258dba248d824c360941caadd338f9e4490/core/lib/core.js#L449

So it should be an easy add for the Android Tracker if you want to open a PR!
