### ISSUE TITLE
Scala Common Enrich: tolerate content type for GET requests sent to Clojure Collector

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2743]
Migrated from https://github.com/snowplow/snowplow-javascript-tracker/issues/489

**Comment by jbeemster** [comment]
Hey @alexanderdean this only seems to affect the Clojure Collector Loader - should I rename the ticket to make this a bit more explicit?

**Comment by alexanderdean** [comment]
Sounds good @jbeemster !
