### ISSUE TITLE
Stream Enrich: tolerate trailing slashes for paths in IP Lookups Enrichment configuration

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2744]
Hadoop Enrich tolerates trailing slashes, but Stream Enrich cannot yet

**Comment by alexanderdean** [comment]
@jbeemster - if you put a trailing slash in the configuration for one of the MaxMind database URLs, you should get a crash...

**Comment by jbeemster** [comment]
But a trailing slash in the url would denote an invalid path to a file wouldn't it?  Or is this to allow the downloading of a folder rather than an individual file?

**Comment by alexanderdean** [comment]
The [documentation page](https://github.com/snowplow/snowplow/wiki/IP-lookups-enrichment) says: *Must not end with a trailing slash.*

I agree - I can't figure out what this means.

**Comment by alexanderdean** [comment]
Actually before I de-schedule, can you just try it and tell me what happens?

**Comment by jbeemster** [comment]
Ahh this makes sense.  When you have a trailing slash this happens:

http://snowplow-hosted-assets.s3.amazonaws.com/third-party/maxmind//GeoLiteCity.dat

Which is an invalid url.
