### ISSUE TITLE
Scala Common Enrich: placeholder for application crash enrichments

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2752]
Two ideas so far:
### Better code context

Use the source fields in the application_context to lookup the file with the exception line, and attach say the preceding N and following M lines of code around the line causing the exception.
### Who broke the app

Use the source fields in the application_context to git blame the offending line and attach the committer's details

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/96
