### ISSUE TITLE
Scala Hadoop Shred: bump Iglu Scala Client to 0.4.1

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2754]
See: https://github.com/snowplow/iglu-scala-client/issues/57

**Comment by jbeemster** [comment]
@alexanderdean this Iglu Scala Client has not been updated yet, which milestone would you like me to move this into?  Or should we wait for it to be released?

**Comment by alexanderdean** [comment]
Moving into @chuwy's release. @chuwy - can we get this Iglu Scala Client release scheduled? It's been pending kick-off for a long time...

**Comment by chuwy** [comment]
Will do!

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/snowplow/issues/3090
