### ISSUE TITLE
Kinesis Elasticsearch Sink: hocon example broken?

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2760]
I'm trying to upgrade kinesis-elasticsearch-sink frim 0.4.0 to 0.6.0. But there seems to be a problem with the new config file. (https://github.com/snowplow/snowplow/blob/r80-southern-cassowary/4-storage/kinesis-elasticsearch-sink/examples/config.hocon.sample) Essentially it has two sink objects nested into each other

```
sink {
  source = 'kinesis'
  sink {
    "good": 'elasticsearch'
  }
}
```

I get the following stack trace when starting the service: 

> 2016-07-01_09:34:14.61991       at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
> 2016-07-01_09:34:14.61997       at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> 2016-07-01_09:34:14.62002       at scala.App$$anonfun$main$1.apply(App.scala:71)
> 2016-07-01_09:34:14.62008       at scala.App$$anonfun$main$1.apply(App.scala:71)
> 2016-07-01_09:34:14.62014       at scala.collection.immutable.List.foreach(List.scala:318)
> 2016-07-01_09:34:14.62020       at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
> 2016-07-01_09:34:14.62026       at scala.App$class.main(App.scala:71)
> 2016-07-01_09:34:14.62032       at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.ElasticsearchSinkApp$.main(ElasticsearchSinkApp.scala:67)
> 2016-07-01_09:34:14.62038       at com.snowplowanalytics.snowplow.storage.kinesis.elasticsearch.ElasticsearchSinkApp.main(ElasticsearchSinkApp.scala)

I'm i doing it wrong?

**Comment by alexanderdean** [comment]
Assigning to R82...

**Comment by alexanderdean** [comment]
I don't know if this is a bug, but let's investigate...

**Comment by christoph-buente** [comment]
Thx, would be cool. Love to upgrade the es sink too.

**Comment by alexanderdean** [comment]
This is a dedicated milestone now, R83 >>

**Comment by jbeemster** [comment]
Hey @christoph-buente the example hocon is correct as far as I can tell.  My strategy would be to grab a fresh copy of the example hocon and move your old values across.  If that still does not get it working please feel free to create a discourse topic on it so we can help you debug this!

The first issue that pops out though is that:

```json
sink {
  source = 'kinesis'
  sink {
    "good": 'elasticsearch'
  }
}
```

This portion is missing a __bad__ sink, this should look like:

```json
sink {
  source = 'kinesis'
  sink {
    "good": 'elasticsearch'
    "bad" 'kinesis' (or stderr)
  }
}
```

**Comment by alexanderdean** [comment]
In that case - closing... Feel free to continue discussion on Discourse!
