### ISSUE TITLE
Add support for MaxMind geo IP accuracy radius

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#2788]
http://discourse.snowplowanalytics.com/t/maxmind-ip-lookup-defaults-on-a-single-location-in-kansas/78/2

> Some of the Maxmind libraries provide the accuracy radius field which can give you can idea of how close (very approximate) the IP is to the geographical location. It may be worth considering adding an extra field to the schema for geoip_accuracy_radius. Here's what the current distribution looks like using the IPv4 GeoIP2 city database (free).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/105
