### ISSUE TITLE
Document how to load Redshift via SSL 

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2800]
Currently this is missing from the documentation.

We should update [this page](https://github.com/snowplow/snowplow/wiki/Common-configuration) with the different valid configuration options for `ssl_mode`. The legal values are:

* `disabled` (default)
* `require`
* `verify-ca` or 
* `verify-full`

We should similarly update https://github.com/snowplow/snowplow/wiki/Setting-up-Redshift#ssl

**Comment by ihortom** [comment]
@yalisassoon - I updated the [Common Configuration](https://github.com/snowplow/snowplow/wiki/Common-configuration) article. However, to update the [Setting up Redshift](https://github.com/snowplow/snowplow/wiki/Setting-up-Redshift#ssl), I need a real example of (access to) SSL enabled cluster.

**Comment by yalisassoon** [comment]
Thanks Ihor!

On Mon, Jul 11, 2016 at 7:59 PM, Ihor Tomilenko <notifications@github.com>
wrote:

> @yalisassoon <https://github.com/yalisassoon> - I updated the Common
> Configuration
> <https://github.com/snowplow/snowplow/wiki/Common-configuration> article.
> However, to update the Setting up Redshift
> <https://github.com/snowplow/snowplow/wiki/Setting-up-Redshift#ssl>, I
> need a real example of (access to) SSL enabled cluster.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/snowplow/snowplow/issues/2800#issuecomment-231796597>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMRu5V16etBErAv7VYFqr8t_Jnw5p3Kks5qUnZvgaJpZM4JIyCq>
> .
>



-- 
Co-founder
Snowplow Analytics <http://snowplowanalytics.com/>
The Roma Building, 32-38 Scrutton Street, London EC2A 4RQ, United Kingdom
+44 7841 954 117
@yalisassoon <https://twitter.com/yalisassoon>
<https://twitter.com/yalisassoon>
Sign up to our mailing list! <http://eepurl.com/b0yEgz>

**Comment by alexanderdean** [comment]
Not sure I understand what you need @ihortom for the second part?

**Comment by ihortom** [comment]
@alexanderdean - that article is all about screenshots. If that is what expected, I need to produce a screenshot of some client. If that is not required and a few sentences will do then I will completed the task.

**Comment by alexanderdean** [comment]
A few sentences is fine...

**Comment by ihortom** [comment]
done

**Comment by alexanderdean** [comment]
Great, closing!
