### ISSUE TITLE
Missing `iglu:` in nodejs documentation

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2809]
In the node-js tracker documentation the example unstructured event appears to be missing the `iglu:` in the schema name:

```
t.trackUnstructEvent({
  "schema": "com.example_company/save-game/jsonschema/1.0.2",
  "data": {
    "save_id": "4321",
    "level": 23,
    "difficultyLevel": "HARD",
    "dl_content": true 
  }
})
```

Shouldn't that be:

```
t.trackUnstructEvent({
  "schema": "iglu:com.example_company/save-game/jsonschema/1.0.2",
  "data": {
    "save_id": "4321",
    "level": 23,
    "difficultyLevel": "HARD",
    "dl_content": true 
  }
})
```

The documentation is here: https://github.com/snowplow/snowplow/wiki/Node.js-Tracker#46-track-unstructured-events-with-trackunstructevent

**Comment by ihortom** [comment]
I think it works without `iglu:` as well. Nonetheless, amended to avoid confusion.

**Comment by alexanderdean** [comment]
Thanks @ihortom - I can't see how it could work without the `iglu:` (it might "work" in that it gets passed to the collector okay, but it would fail validat
