### ISSUE TITLE
Kinesis Elasticsearch Sink: add support for Elasticsearch 1.5.3

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2811]

**Comment by jbeemster** [comment]
The transport client already has support for this and the http client will.  There is nothing extra to be done for support for this particular version.  Can this ticket be closed @alexanderdean ?

**Comment by alexanderdean** [comment]
Yes, let's de-schedule too...

**Comment by jbeemster** [comment]
Closing as support is already included for this version...
