### ISSUE TITLE
CloudFront Collector: test if Iglu webhook works

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2812]
https://github.com/snowplow/snowplow/wiki/Iglu-webhook-setup

If we create a literal pixel at `/com.snowplowanalytics.iglu/v1` (alongside the regular `i` pixel), does everything in the pipeline work?

I think it should per:

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CloudfrontLoader.scala

But good to check...

If it does work, given advisories like http://discourse.snowplowanalytics.com/t/tracking-email-events-sends-opens-and-clicks-with-snowplow-tutorial/436, we may want to add this additional pixel to the CloudFront Collector setup guide...

**Comment by Germanaz0** [comment]
I'm using the cloujure collector and I am not sure if the pipeline works too, I am following those tutorials, creating schemas, uploading jsponpaths, and the data for the custom schema is not added.

I'm also using all strings for the schema to avoid errors, and still, cannot see the iglu webhook working.

Thanks

**Comment by alexanderdean** [comment]
Hi @Germanaz0 - if you are having troubles using this webhook adapter with the Clojure Collector, the best place to raise this is on our forums: http://discourse.snowplowanalytics.com/

This GitHub ticket is about something different.

**Comment by alexanderdean** [comment]
Update: it works. Closing this ticket in favor of #2996

**Comment by alexanderdean** [comment]
See thread here for this working: http://discourse.snowplowanalytics.com/t/iglu-webhook-response-code/837/3
