### ISSUE TITLE
EmrEtlRunner: scrub credentials from stderr

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2815]
Sluice in particular can leak AWS access keys:

```
F, [2016-07-20T07:38:49.964000 #27217] FATAL -- : Excon::Errors::Forbidden (Expected(200) <=> Actual(403 Forbidden) excon.error.response :body => "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>NEEDS REDACTING</AWSAccessKeyId><StringToSign>GET
```

/cc @jbeemster

**Comment by alexanderdean** [comment]
Are we going to get to this before we replace EmrEtlRunner with Dataflow Runner per our RFC?

**Comment by alexanderdean** [comment]
This may go away when we ditch Sluice. Keeping it in, we'll wait and see.

**Comment by BenFradet** [comment]
Didn't have time to fully investigate, but we're now using the official aws sdk so it shouldn't leak credentials.
The example above is definitely taken care of now.

**Comment by alexanderdean** [comment]
Shall we de-schedule?
