### ISSUE TITLE
Common: massive ecosystem bump

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2824]
This ticket intended to be a journal for what we need to bump/refactor/upgrade/remove to stay up to date with actual Scala ecosystem (2.11.8 and upcoming 2.12). 

Our current plan is following:
- Implement CI/CD for all not-outdated JVM projects inside snowplow organization
- Figure out if any of third-party dependencies aren't published for 2.11
- Start to bump `scalaVersion` in our dependencies. For a while cross-compilation for 2.10 and 2.11 should be required.

It would be great if all tickets from this and another projects related to scala/dependencies bump could refer this this ticket.

/cc @ninjabear @jbeemster @alexanderdean

**Comment by alexanderdean** [comment]
Love the ticket name!

**Comment by chuwy** [comment]
On a side note, our commonly used approach to SBT configuration needs to be refactored a bit. SBT `Build` trait has been deprecated in 0.13.12 and likely will be removed in 1.0.

It doesn't mean we need to remove all `project/Dependencies.scala` and `project/BuildSettings.scala`. It just mean we need to refactor `project/ProjectBuild.scala` to `build.sbt`. I think it's good idea also to start to add this `build.sbt`-tickets to projects.

**Comment by alexanderdean** [comment]
I agree @chuwy, thanks for flagging

**Comment by alexanderdean** [comment]
https://github.com/snowplow/snowplow/issues/2050

**Comment by ninjabear** [comment]
+1! It would also be nice to use jdk8 as java 7 is no longer being patched

**Comment by alexanderdean** [comment]
Great point @ninjabear !

**Comment by BenFradet** [comment]
Somewhat related, the 5.x amis support Spark 2.0+ but only built against Scala 2.11.
As a result, we're currently stuck with Spark 1.6.1.

**Comment by alexanderdean** [comment]
Thanks for flagging this @BenFradet - another great reason to press on with this upgrade...

**Comment by chuwy** [comment]
Last round happened in https://github.com/snowplow/snowplow/pull/4254
