### ISSUE TITLE
Spark Enrich: remove test cases' dependency on absent schemas

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2827]
Following test cases use obsolete Schemas (`iglu:com.snowplowanalytics.snowplow-website/signup_form_submitted/jsonschema/1-0-0` or  `iglu:com.snowplowanalytics.snowplow-website/trial_form_submitted/jsonschema/1-0-0`):
- com.snowplowanalytics.snowplow.enrich.hadoop.MasterCljTomcatSpec
- com.snowplowanalytics.snowplow.enrich.hadoop.good.UnstructEventBase64CfLineSpec
- com.snowplowanalytics.snowplow.enrich.hadoop.good.CljTomcatTp1TnuidSpec
- com.snowplowanalytics.snowplow.enrich.hadoop.good.CljTomcatTp1SingleEventSpec
- com.snowplowanalytics.snowplow.enrich.hadoop.MasterCfLinesSpec
- com.snowplowanalytics.snowplow.enrich.hadoop.good.UnstructEventCfLineSpec

Tests are passing successfully because these Schemas are still (accidentally) available on igluctenral.com.

**Comment by alexanderdean** [comment]
Tweaked the title - as these tests should be revised to use real schemas.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/108
