### ISSUE TITLE
EmrEtlRunner: --debug flag does not work with eu-central-1

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#2829]
The error "Ensure step 1 jar file s3://elasticmapreduce/libs/script-runner/script-runner.jar"

**Comment by alexanderdean** [comment]
Quick notes:

* I believe that adding the debugger step is handled under the hood by the AWS API
* Unfortunately that built-in support doesn't seem to work with `eu-central-1`

I could be wrong on this...

**Comment by kazgurs** [comment]
Running EMR on `eu-central-1` seems to not work at all. I get no errors and it fails on `Elasticity Setup Hadoop Debugging`. Is this region supported?

**Comment by alexanderdean** [comment]
Yes it works fine without the `--debug` flag, the ticket is correct though - the debug flag doesn't work.

**Comment by BenFradet** [comment]
created rslifka/elasticity#135

**Comment by BenFradet** [comment]
done in elasticity, closing
