### ISSUE TITLE
Typo in the trackSiteSearch sample code

### ISSUE THREAD

**Issue by leonmaas** [snowplow/snowplow#2831]
@ihortom 

The sample code on this page: https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#siteSearch has a typo; there is an extra comma at the end:

window.snowplow_name_here('trackSiteSearch',
    ['unified', 'log'], // search terms
    ['books'],          // filters
    14,                 // results found
    8,                  // results displayed on first page (this comma needs to be removed)
);

**Comment by ihortom** [comment]
@leonmaas - done. Also corrected similar typo in section https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#315-custom-contexts
