### ISSUE TITLE
Archived logs are not necessarily CloudFront logs anymore

### ISSUE THREAD

**Issue by rgabo** [snowplow/snowplow#2832]
EmrEtlRunner output:

```
D, [2016-08-02T11:45:24.989000 #49] DEBUG -- : Archiving CloudFront logs...
```

(source: https://github.com/snowplow/snowplow/blob/b772f6e089bb9e0b3bdbed93a4ab18902c4f1a4a/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3_tasks.rb#L180)

The same messaging is used for any log that needs to be archived (saw it while archiving Clojure logs). Miniscule issue, sending single commit PR from GitHub in a sec.

**Comment by alexanderdean** [comment]
Superseded by #1977 (archiving raw moving to EMR)...

**Comment by rgabo** [comment]
Great stuff as always @alexanderdean, looking forward to it. Do you think the process will move towards being more idempotent in the future? We've found that when orchestrating EmrEtlRunner as a single task in our workflow (using Luigi), if only shred fails we have to manually intervene with `--process-shred` and rerunning the task will not suffice, unless we add more complex logic to detect what output is already available and what isn't. Any thoughts?

**Comment by alexanderdean** [comment]
Hey @rgabo - yes we'd like it to move to being more idempotent - that's one of the easiest ways of making it more stable. We'll most likely get rid of the copies to HDFS as part of the move to Spark...
