### ISSUE TITLE
listen_address should be listen_addresses

### ISSUE THREAD

**Issue by rbalicki2** [snowplow/snowplow#2835]
On the https://github.com/snowplow/snowplow/wiki/Setting-up-PostgreSQL, the instructions are to set the postgresql.conf file to read `listen_address='*'`, whereas it should be `listen_addresses='*'`

Thank you! The guide is amazing, otherwise.

**Comment by alexanderdean** [comment]
Thanks! Assigning

**Comment by ihortom** [comment]
Done
