### ISSUE TITLE
Wiki typo: `3.9 Setting the useragent with set_ip_address`

### ISSUE THREAD

**Issue by adamlwgriffiths** [snowplow/snowplow#2838]
The Python Tracker wiki has a copy-paste error.
The title for the `set-useragent` section lists `set_ip_address` as it's function:

    3.9 Setting the useragent with set_ip_address

It should read:

    3.9 Setting the useragent with set_useragent

https://github.com/snowplow/snowplow/wiki/Python-Tracker#set-useragent

**Comment by alexanderdean** [comment]
Thanks Adam! Assigning for fix

**Comment by ihortom** [comment]
Done
