### ISSUE TITLE
Wiki typo: Golang listed as Goland

### ISSUE THREAD

**Issue by adamlwgriffiths** [snowplow/snowplow#2839]
The Go tracker in section 1A is spelt `Goland`, instead of `Golang`.

> 1A. Trackers
> 
> Trackers overview
> ActionScript3 Tracker
> Android Tracker
> Arduino Tracker
> Goland Tracker
> ....

https://github.com/snowplow/snowplow/wiki/Snowplow-technical-documentation

**Comment by alexanderdean** [comment]
Thanks @adamlwgriffiths - assigning for fix...

**Comment by ihortom** [comment]
Done. Also corrected the same typo in Sidebar
