### ISSUE TITLE
Scala Stream Collector: option to disable the cookie

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2845]
We have more and more users who want to use these collectors (for POST or real-time processing) but don't want to set a third party cookie at all. It would be nice if there was a straightforward way to disable the setting of third party cookies in both collectors.

**Comment by jbeemster** [comment]
Don't we already have this by setting the cookie age to 0 days?  Or do we want a more explicit setting?

**Comment by alexanderdean** [comment]
Good point! Is this documented?

**Comment by BenFradet** [comment]
`collector.cookie.enabled = true`, closing

**Comment by alexanderdean** [comment]
Re-opened and turned into doco ticket.

**Comment by ihortom** [comment]
@alexanderdean / @yalisassoon - I can see this in wiki: https://github.com/snowplow/snowplow/wiki/Configure-the-Scala-Stream-Collector#5-setting-the-cookie-duration. Is it not what you were looking for? Any other places to consider?

**Comment by alexanderdean** [comment]
Read Ben's comment above - please add and stress the ability to disable the cookie with this line:

https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/examples/config.hocon.sample#L40

Rather than just having to set the duration to 0.

**Comment by ihortom** [comment]
Done
