### ISSUE TITLE
Documentation: tracker feature matrix

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#2849]
We don't have feature parity between trackers.

Users often don't know what features a tracker does or does not support, or if they are aware of the features, sometimes they're surprised a certain tracker doesn't support it.

Proposal: create a page with a table (or a spreadsheet) with one column per tracker & one row per important feature, and in each cell either "no support" or "versions x.x.x or later". Potential features to include:

- asynchronous sending
- client-side sessionization
- local storage
- device sent timestamp

**Comment by alexanderdean** [comment]
Great idea! We should also track which event types we support first-class, and which contexts

**Comment by alexanderdean** [comment]
Assigning to Josh and Ihor - hopefully Ihor can work on the template. Added here: https://docs.google.com/spreadsheets/d/1rN2nkBet53rFlv00ByYRGpo9Ou_6ZxGqfDpsVWDtIlY/edit#gid=0

**Comment by bogaert** [comment]
This came up again this week - users that have more than one tracker struggle to understand what tracker supports what (so this would be a direct win for users).

**Comment by alexanderdean** [comment]
Moved to Trello
