### ISSUE TITLE
RDB Loader: add support for loading via SSH tunnel

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2858]
When we move StorageLoader to run on the EMR cluster, we will need a new solution to loading a Redshift database via SSH tunnel.

Updating our Redshift configuration to hold the additional information is not too difficult. The challenge will be getting the private SSH key onto the master node in a safe way. What is best practice here?

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/5
