### ISSUE TITLE
Scala Common Enrich: add POST support for /i as well as com.snowplowanalytics.snowplow/tp2

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2860]
In case there are ad blockers blocking POSTs to URIs with the word analytics in them.

Are there any ad blockers like this?

There would also need to be a flag in the Snowplow JS Tracker (or new default?) to use this.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/110
