### ISSUE TITLE
question 4-storage Postgresql inheritance for event types

### ISSUE THREAD

**Issue by agentgt** [snowplow/snowplow#2866]
I know the current support for Postgresql is just plain event storage (ie unstruct is not supported).

I am adding unstruct event support to our ETL pipeline which uses Postgresql for intermediate storage. I do what I guess you guys call "shredding" in our own pipeline (ie use Java + Jackson to do this).

My idea is to use Postgresql inheritance for each one of the event types (page_view, unstruct, struct, etc). This is to make updating the atomic event schema less messy as our unstruct table will probably be pretty custom as well as faster filtering on event types (apparently postgres does smart things with inheritance and check constraints).

I have written some of the SQL migration scripts for this and could put a pull request or a simple gist. Or I could be completely wrong in my approach 😨  hence the question. The other option of course is joining tables but this complicates things for us. 

I'm curious on how (or if) you guys plan on accomplishing supporting other events with Postgresql.

**Comment by alexanderdean** [comment]
Hey @agentgt - we definitely plan on adding full nested entity support to Postgres once we've done a full refactoring of our Redshift load code.

Our working assumption is that our Postgres approach will very closely mirror our Redshift approach - but this isn't something we've devoted any R&D time to, so it's all still to explore.

Postgres table inheritance sounds interesting - not something we'd really had on our radar, I'd love to see a PR and then continue the conversation  :coffee:

**Comment by agentgt** [comment]
I will see if I can do a PR next week. This is roughly what our stuff does (we have different names for some stuff events -> event).


```sql
ALTER TABLE event RENAME TO event_v04;

-- Copy schema
CREATE TABLE event AS (SELECT * from event_v04 limit 0);

-- FORCE programmatic dispatch to table (v9.2).
-- A trigger could be used to route but this forces correct
-- handling of struct and unstruct
ALTER TABLE event ADD CONSTRAINT event_no_insert CHECK (false) no inherit;


-- CREATE sub tables
CREATE table event_page_view (
       CHECK ( event = 'page_view' )
) INHERITS (event);

CREATE table event_page_ping (
       CHECK ( event = 'page_ping' )
) INHERITS (event);

CREATE table event_unstruct (
       CHECK ( event = 'unstruct' )
) INHERITS (event);

CREATE table event_struct (
       CHECK ( event = 'struct' )
) INHERITS (event);


INSERT INTO event_page_view (SELECT * from event_v04 where event='page_view');
INSERT INTO event_page_ping (SELECT * from event_v04 where event='page_ping');
INSERT INTO event_unstruct (SELECT * from event_v04 where event='unstruct');
INSERT INTO event_struct (SELECT * from event_v04 where event='struct');
```

Now when you do something like:

```sql
SELECT * from event where event.event = 'page_view'
```

Postgresql will only look at the `event_page_view` table. 

We may not use the check constraint on the `event` field but rather the `event_name` and `event_vendor` in the future now that the schema 4-tuple info is now in the events (vendor,name,format,version).

If you did that approach you would create a table per schema for unstructs and have them inherit. 

The table name would be something like:

```scala
tableName = event.eventVendor.replaceAll("\\.", "_") + "_" event.eventName
```
But that might get you some unwieldy table names :)

**Comment by alexanderdean** [comment]
Thanks for sharing @agentgt! Super interesting. In this approach, where do the event-specific columns get created and live?

**Comment by agentgt** [comment]
All the basic columns still live **logically** in `atomic.events` (ie the structured ones). **Physically** though I think postgresql duplicates them but I don't know the internals well enough.

The `event_unstruct` could contain additional columns perhaps flattened from schemas. For example we do something like this for the link_click schema:

```sql
ALTER TABLE event_unstruct
ADD COLUMN link_click_element_id character varying(256);

ALTER TABLE event_unstruct
ADD COLUMN link_click_element_target character varying(128);

ALTER TABLE event_unstruct
ADD COLUMN link_click_target_url character varying(2048);

ALTER TABLE event_unstruct
ADD COLUMN link_click_element_content character varying(1024);
```

You won't see these fields though unless you directly query `event_unstruct` (I think) but event_unstruct would contain all the `atomic.events` columns. You can think of this as partitioning by event type (in fact I think Postgresql calls it partitioning).

Now the advantage to this approach besides the aforementioned performance is you guys can continuously make updates to the events table and all the inheriting schemas will pick up the updates. Obviously they are some caveats that are in the postgresql documentation so it would be wise to check those out.

You can of course partition out later on and migrate. The only fairly tricky thing is that because we are adding columns you must insert into the tables directly (Many examples don't do this because they are partitioning by time for cube analysis. The sub tables are only for performance.). Thus the ETL storage process would have to know how to dispatch to the correct table (we do this on our own but I believe you guys have a mechanism for this with jsonpath and what not).

**Comment by BenFradet** [comment]
closing
