### ISSUE TITLE
Scala Common Enrich: add Project Honey Pot enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2876]
Using the Scala library: https://github.com/osinka/httpbl

Users will need to apply to join the Project Honey Pot project and get an access key:
- http://www.projecthoneypot.org/httpbl_api.php
- http://www.projecthoneypot.org/terms_of_service_use.php

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/111
