### ISSUE TITLE
Can't find Postgres atomic sql for version 0.8.0

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2883]
Right now the latest is 0.7.0, whereas Redshift has support for 0.8.0. We'd need the update SQL for atomic_event and a migration file.

**Comment by chuwy** [comment]
Hello @simplesteph,

Could you please readdress your question to our [Discourse forum](http://discourse.snowplowanalytics.com/) so other users could find an answer? (Github is only for bugs and features)

Thanks
