### ISSUE TITLE
Can't get 'ua'(user agent) and 'ctype'(connection type) in pv/pp/...

### ISSUE THREAD

**Issue by YuxinChou** [snowplow/snowplow#2884]
Use version: sp.js 2.6.2.
I don't know why I can't get 'ua' and 'ctype' from pageview. 
Who can tell me how to get them? Thank you.

I can get:

> stm=1473816452246
> e=pv
> url=******
> refr=*******
> tv=js-2.6.2
> tna=cf
> aid=CFe23a
> p=mob
> tz=Asia/Shanghai
> lang=zh-cn
> cs=UTF-8
> res=320x568
> cd=32
> cookie=1
> eid=3d4bdf51-4a77-465f-9685-cd908badf03d
> dtm=1473816452240
> vp=980x1409
> ds=1210x1409
> vid=1
> sid=a313546f-d8f3-4ed1-9ecb-6563581e28b0
> duid=dbbdc496-521e-4b53-a655-466c0663167c
> fp=943216764
> uid=alex+123

**Comment by chuwy** [comment]
Hello @YuxinChou ,

Could you please readdress your question to our [Discourse forum](http://discourse.snowplowanalytics.com/) so other users could find an answer? (Github is only for bugs and features)

Thanks
