### ISSUE TITLE
Add page on Hadoop Shred deduplication to wiki

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2890]
With contents from: http://snowplowanalytics.com/blog/2016/01/26/snowplow-r76-changeable-hawk-eagle-released/#deduplication

**Comment by ihortom** [comment]
Info added to the page https://github.com/snowplow/snowplow/wiki/Shredding (rather than a separate page)

**Comment by alexanderdean** [comment]
Looks great! Closing. Please add to Trello as done so we can track all this...
