### ISSUE TITLE
Installing EMRETL Runner

### ISSUE THREAD

**Issue by bhattdeepak90** [snowplow/snowplow#2891]
Hi Folks,

    I am a beginner and just started with Snowplow. Can anyone please tell me the steps to build the EmrEtlRunner jar with the source code. How can i build the above jar in my local Linux machine. There is no documentation available by the snowplow.

   Thanks in advanced.

**Comment by alexanderdean** [comment]
Closing, has been asked on Discourse: http://discourse.snowplowanalytics.com/t/installing-emretl-runner/608

**Comment by bhattdeepak90** [comment]
I have asked the same on Discourse. Please help..

Thanks
