### ISSUE TITLE
Bug in "Get User ID" code snippet

### ISSUE THREAD

**Issue by adamlwgriffiths** [snowplow/snowplow#2892]
The documentation provides a snippet to retrieve the user id from the snowplow cookie.
https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#get-id

The code in question is below

```
function getSnowplowDuid(cookieName) {
  cookieName = cookieName || '_sp_';
  var matcher = new RegExp(cookieName + 'id\\.[a-f0-9]+=([^;]+);');
  var match = document.cookie.match(matcher);
  if (match && match[1]) {
    return match[1].split('.')[0];
  } else {
    return false;
  }
}
```

This code fails when the `_sp_id` is the last value in the cookie, and therefore doesn't have a terminating `;`.

```
>>> document.cookie.match(new RegExp('_sp_id\\.[a-f0-9]+=([^;]+);'));
null
>>> document.cookie
"_sp_id.cf85=e1f8f430f15983d2.1474516277.1.1474518652.1474516277.fdfd18bb-449d-4eb8-b77d-dccbdb5e3415"
```

The fix is to make the `;` optional by appending a `?` at the end (Ie. `'id\\.[a-f0-9]+=([^;]+);?'`)

```
>>> document.cookie.match(new RegExp('_sp_id\\.[a-f0-9]+=([^;]+);?'));
["_sp_id.cf85=e1f8f430f15983d2.1474516277.1.1474518652.1474516277.fdfd18bb-449d-4eb8-b77d-dccbdb5e3415", "e1f8f430f15983d2.1474516277.1.1474518652.1474516277.fdfd18bb-449d-4eb8-b77d-dccbdb5e3415"]

```

**Comment by alexanderdean** [comment]
Many thanks for raising @adamlwgriffiths, I've updated the wiki page with your fix.
