### ISSUE TITLE
Scala Common Enrich: bump scala-uri to 0.5.0

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#2893]
We see decent amount of requests ending up in the bad bucket, because of page_url contains more than one # character. Like this one:

> `Provided URI string [http://www.example.com/path/index.ssf/2016/09/taco_charlton_jourdan_lewis_tr.html#incart_river_index#incart_m-rpt-2] could not be parsed by Netaporter: [Illegal character in fragment at index 104: http://www.example.com/path/index.ssf/2016/09/taco_charlton_jourdan_lewis_tr.html#incart_river_index#incart_m-rpt-2]
> `

Essentially all browsers i tried could handle that URL, even though regarding to the spec it might not be valid. Is there a way to let those type of event through?

**Comment by christoph-buente** [comment]
Are we the only ones seeing this behaviour? @alexanderdean?

**Comment by alexanderdean** [comment]
The Netaporter library we use is the most permissive URI parser available for the JVM - it would be worth raising an issue there and seeing if they are up for tolerating URIs with 2 fragments attached? If not, we're really back looking at #351...

**Comment by christoph-buente** [comment]
Thx @alexanderdean,

and you know what, there is an issue already, regarding double fragment separators:
https://github.com/NET-A-PORTER/scala-uri/issues/114

I left a comment and asked for the changes.

**Comment by alexanderdean** [comment]
Cool, sounds like a plan @christoph-buente !

**Comment by christoph-buente** [comment]
@alexanderdean: I've never seen a faster fix!
https://github.com/NET-A-PORTER/scala-uri/commit/22dd7672c9c3af68facbf949069fbfa4e67df468

**Comment by alexanderdean** [comment]
Wow! Thanks so much @theon.

**Comment by theon** [comment]
No problem!

**Comment by christoph-buente** [comment]
@alexanderdean Has this dependency bump released ever since?

**Comment by alexanderdean** [comment]
Not yet!

**Comment by matogertel** [comment]
Any update on this ?

**Comment by alexanderdean** [comment]
Given this issue causes data quality issues, we will prioritise...

**Comment by christoph-buente** [comment]
Thanks @alexanderdean, would be wonderful to see this being released. We're still losing out on 200k events every day.

**Comment by DrGomi** [comment]
Cheers, just wanted to tell you guys that christoph is not the only one waiting for this fix.
We are also having this issue in our ionic v1 based hybrid app.

**Comment by matogertel** [comment]
If you're using the JavaScript tracker, I've added some code to our tracker initialization script to fix the "invalid" urls. Essentially, it url-escapes all # characters after the first one.
This is the general idea:
```
var url = window.location.href;
var matches = url.match(/#/g);
if (matches && matches.length>1) {
    var fixed = url.split('#').slice(0,1).join('') + '#' + url.split('#').slice(1).join('%23');
    snowplow('setCustomUrl',fixed);
}
```

**Comment by alexanderdean** [comment]
Adding to R92

**Comment by theon** [comment]
FYI: I have moved the scala-uri project over to https://github.com/lemonlabsuk/scala-uri and the latest version is 0.5.0 now.

**Comment by christoph-buente** [comment]
@alexanderdean and @BenFradet from what collector version was this Scala Common Enrich version being used? Is it R92?

**Comment by alexanderdean** [comment]
R93 I believe:

https://github.com/snowplow/snowplow/blob/master/CHANGELOG#L126
