### ISSUE TITLE
Kinesis Elasticsearch Sink: ensure field names do not contain any dots

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#2894]
As of Elasticsearch 2.x field names can no longer contain dots.  They all need to be replaced by underscores.

**Comment by alexanderdean** [comment]
Really! That's a pretty big change...

**Comment by jbeemster** [comment]
Hey @alexanderdean yes it is a pretty big change.  I imagine this has something to do with more performant parsing of nested JSONs in ES 2.x.  As this error was picked up for a fieldName in a deeply nested JSON Value for a key.

In any case the blog post will contain a big angry warning about this change!

**Comment by alexanderdean** [comment]
Sounds good!
