### ISSUE TITLE
Kinesis Elasticsearch Sink: does not take into account buffer configurations

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2895]
Hi,

the following parameters:
```

  # Events are accumulated in a buffer before being sent to Elasticsearch.
  # The buffer is emptied whenever:
  # - the combined size of the stored records exceeds byte-limit or
  # - the number of stored records exceeds record-limit or
  # - the time in milliseconds since it was last emptied exceeds time-limit
  buffer {
    byte-limit: {{sinkElasticsearchBufferByteThreshold}}
    record-limit: {{sinkElasticsearchBufferRecordThreshold}}
    time-limit: {{sinkElasticsearchBufferTimeThreshold}}
  }
```

Are not taken into account in the ElasticsearchSenderHTTP.scala code, and therefore the record being sent to ElasticSearch are not throttled by time and bytes.

**Comment by jbeemster** [comment]
Hi @simplesteph I will have a look into this.  My understanding was that these limits were applied above the actual emitter within the Kinesis Connectors Library which supplies the records to the emitter.

Will do some investigation!
