### ISSUE TITLE
Kinesis Elasticsearch Sink: error messages are not helpful

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2896]
Hi,

When an error is caught, the error message is not display or is very unclear. I had to modify the code and do e.printStackTrace() to get a clear idea of what was wrong.
It'd be great if you fix that bug (should be quite easy to fix). In my opinion any unexpected exception should be logged with a full stacktrace

Regards,
Stephane

**Comment by jbeemster** [comment]
Hi @simplesteph that does sound like an easy fix.  Could you provide the point where you had to add this stackTrace printing?

**Comment by simplesteph** [comment]
Kinesis sink around line 98, I added the following:

```
    } catch {
      case rnfe: ResourceNotFoundException => false
      case e: Exception => e.printStackTrace(); false
    }
```

ElasticSearchSenderHTTP.scala around line 181
```
case e: Exception => {
          e.printStackTrace()
          Log.error("ElasticsearchEmitter threw an unexpected exception ", e)
          
```

Overall anytime you try catch I believe you should somehow display a clear idea of the error.

**Comment by jbeemster** [comment]
Well I still think the idea of the error is there but I do agree that without the stacktrace it could make it quite difficult to debug!  I will schedule this into the next milestone.

**Comment by simplesteph** [comment]
Yeah the idea of the error is here but somehow the error never got displayed, i.e. in my logs I would get 

` "ElasticsearchEmitter threw an unexpected exception <blank>`
