### ISSUE TITLE
Kinesis Elasticsearch Sink: allow parametrized timeouts for jest client

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2897]
I have implemented this on my end and it could be useful for other people, but I think it could be beneficial to configure the jest client directly from the hocon config file. Especially the connection and read timeout values (5 seconds was too small for my cluster in case of big load). 

ElasticSenderHttp:
```
  private val factory: JestClientFactory = new JestClientFactory()
  factory.setHttpClientConfig(new HttpClientConfig
    .Builder("http://" + configuration.ELASTICSEARCH_ENDPOINT + ":" + configuration.ELASTICSEARCH_PORT)
    .multiThreaded(true)
    .discoveryEnabled(false)
    .maxConnectionIdleTime(30L, TimeUnit.SECONDS)
    .connTimeout(300000) # this line
    .readTimeout(300000) # this line
    .build()
  )
```

**Comment by jbeemster** [comment]
Agreed!  All of those should be available from the HOCON.
