### ISSUE TITLE
form tracking ... beware of the security impacts...

### ISSUE THREAD

**Issue by mdespriee** [snowplow/snowplow#2902]
Hi Snowplow folks.

The js tracker is great, thanks for this.
I just discovered that this little thing : `snowplow('enableFormTracking');` is just an enormous security hole.
I know about the black-list option, but by default it's empty, and I think that SP should never ever transmit password fields in any case.

Suggestion : any password type field should not be transmitted, and ideally any form containing such a sensitive info should automatically disable the form-tracking on it. 
My 2 ct

Cheers

**Comment by alexanderdean** [comment]
Hi @mdespriee - I like the idea of excluding password type fields by default - that seems like a no-brainer...

**Comment by alexanderdean** [comment]
Migrated as this is tracker-specific
