### ISSUE TITLE
Placeholder to investigate buffer adherence within KCL applications

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#2907]
PR: https://github.com/awslabs/amazon-kinesis-connectors/pull/75

Essentially the idea is that at the moment the Buffer is not adhered too if `GetRecords` returns a chunk of events greater than the buffer settings.  Solutions to this are to either:
1. Write buffer splitters to ensure that what we send correlates to the buffer settings, however we then cannot checkpoint until we send each slice which adds a risk of double sending data if some slices succeed but others do not or if the application crashes midway through processing a Buffer.
2. Greatly reduce the GetRecords amount so that it is closer to the Buffer settings we want to use.  This is not an efficient solution however and does not have any reasoning around Byte or Time limits.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/114
