### ISSUE TITLE
Kinesis Elasticsearch Sink: add better detection of failed storage target

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#2918]
Currently the Kinesis Elasticsearch Sink is far to quick to decide that the data is at fault and will then simply pass it of to the bad path.  We need two tiers of detection:
1. On entering the emitter ascertain whether the storage target is available for bulk event indexing.
2. On any failure to bulk index we need to ascertain exactly what caused that failure.

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#13
