### ISSUE TITLE
Common: update script to sync us-east-2 (Ohio) Snowplow Hosted Assets bucket

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2919]
See #2903 for a similar implementation

**Comment by jbeemster** [comment]
This has already been done:

https://github.com/snowplow/snowplow/commit/e43b4d30dee99db999dc49815322e10ad4768d88

**Comment by jbeemster** [comment]
Is there anything to be done with this ticket @alexanderdean as it looks like the region has already been added?

**Comment by alexanderdean** [comment]
Duplicate of #2986
