### ISSUE TITLE
Scala Common Enrich: add webhook adapter for AppsFlyer

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2920]
The structure is pretty simple (flat) as seen here and can hold multiple event types: https://support.appsflyer.com/hc/en-us/articles/207034396-Push-API-Data-Structure-Android

For iOS it has almost identical fields except some extra specific iOS-related fields like idfa:
https://support.appsflyer.com/hc/en-us/articles/207034386-Push-API-Data-Structure-iOS

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/58
