### ISSUE TITLE
Stream Enrich: fix incorrect parsing of S3 urls

### ISSUE THREAD

**Issue by juanstiza** [snowplow/snowplow#2921]
Hi guys,

I'm setting up the Scala Stream Enrich process, I set the enrichment config using a directory with the jsons, my ip_lookups.json looks like this (I'm using paid maxmind data):

``` json
{
    "schema": "iglu:com.snowplowanalytics.snowplow/ip_lookups/jsonschema/1-0-0",
    "data": {
        "name": "ip_lookups",
        "vendor": "com.snowplowanalytics.snowplow",
        "enabled": true,
        "parameters": {
            "geo": {
                "database": "GeoIPCity.dat",
                "uri": "s3://my-private-bucket.s3.amazonaws.com"
            },
            "isp": {
                "database": "GeoIPISP.dat",
                "uri": "s3://my-private-bucket.s3.amazonaws.com"
            },
            "organization": {
                "database": "GeoIPOrg.dat",
                "uri": "s3://my-private-bucket.s3.amazonaws.com"
            }
        }
    }
}
```

I'm getting this error:

```
[main] ERROR com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$ - Error downloading s3:/my-private-bucket.s3.amazonaws.com/GeoIPCity.dat: java.lang.IllegalArgumentException: The bucket name parameter must be specified when requesting an object
Exception in thread "main" java.lang.RuntimeException: Attempt to download s3:/my-private-bucket.s3.amazonaws.com/GeoIPCity.dat to ./ip_geo failed
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$$anonfun$12.apply(KinesisEnrichApp.scala:172)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$$anonfun$12.apply(KinesisEnrichApp.scala:154)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$delayedInit$body.apply(KinesisEnrichApp.scala:154)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp$.main(KinesisEnrichApp.scala:71)
    at com.snowplowanalytics.snowplow.enrich.kinesis.KinesisEnrichApp.main(KinesisEnrichApp.scala)
```

Let me know what might be the problem and if you need any more info.
Thanks!

**Comment by jbeemster** [comment]
Hi @juanstiza which version of Stream Enrich are you using which is causing this error?

**Comment by alexanderdean** [comment]
Hi @juanstiza - your URIs should look like this:

```json
            "geo": {
                "database": "GeoIPCity.dat",
                "uri": "s3://my-private-bucket"
            },
            "isp": {
                "database": "GeoIPISP.dat",
                "uri": "s3://my-private-bucket"
            },
            "organization": {
                "database": "GeoIPOrg.dat",
                "uri": "s3://my-private-bucket"
            }
```

Can you direct future support questions to our [Discourse forums](http://discourse.snowplowanalytics.com/)?

**Comment by juanstiza** [comment]
I downloaded this file: `https://dl.bintray.com/snowplow/snowplow-generic/snowplow_kinesis_r84_stellers_sea_eagle.zip` and ran the `snowplow-stream-enrich-0.9.0` binary.

**Comment by juanstiza** [comment]
@alexanderdean ah! great, I'll check! Thanks!!

**Comment by juanstiza** [comment]
Hi, I tested that change and it throws the same `The bucket name parameter must be specified when requesting an object` error. I'll forward this to Discourse.

**Comment by jbeemster** [comment]
This is a regression error in the latest release.  We attempted to dynamically fix URIs with accidental double slashes but have inadvertantly broken the s3 support here.

A hack around this is to change your URL to look like the following:

```
         "geo": {
                "database": "GeoIPCity.dat",
                "uri": "s3:///my-private-bucket"
            },
            "isp": {
                "database": "GeoIPISP.dat",
                "uri": "s3:///my-private-bucket"
            },
            "organization": {
                "database": "GeoIPOrg.dat",
                "uri": "s3:///my-private-bucket"
            }
```

The triple slash will be reduced to double slashes and it will then parse correctly.

**Comment by alexanderdean** [comment]
Please share a link to the regression commit?

**Comment by jbeemster** [comment]
https://github.com/snowplow/snowplow/issues/2744

**Comment by jbeemster** [comment]
This [line](https://github.com/snowplow/snowplow/blob/master/3-enrich/stream-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/KinesisEnrichApp.scala#L158) needs to become:

val cleanUri = new java.net.URI(uriFilePair._1.toString.replaceAll("(?<!(http:|https:|s3:))//", "/"))

**Comment by juanstiza** [comment]
@jbeemster thanks. I tested the fix and now I'm getting a `Unable to calculate a request signature: Unable to calculate a request signature: Empty key`, but I believe that might be related to authentication... somehow.

**Comment by jbeemster** [comment]
That does sound like authentication!  If you cannot get that issue resolved please post to the Discourse thread so we can help you debug it.
