### ISSUE TITLE
br feature flash?

### ISSUE THREAD

**Issue by StaymanHou** [snowplow/snowplow#2922]
There's a br feature flash field in the atomic.events table. However, looks like there's no data in that field. Am I missing something when I implement the tracking tag? Or maybe the flash feature detection has not been implemented? If so, is it in the roadmap?

Thanks

**Comment by alexanderdean** [comment]
Hi @StaymanHou - can you direct support questions to our [Discourse forums](http://discourse.snowplowanalytics.com/) please?
