### ISSUE TITLE
Scala Collector Jar not found

### ISSUE THREAD

**Issue by redsquare** [snowplow/snowplow#2923]
The scala jar file is currently not available for download http://dl.bintray.com/snowplow/snowplow-generic/snowplow_stream_collector_0.8.0.zip

**Comment by jbeemster** [comment]
Hi @redsquare the binary has been moved to: http://dl.bintray.com/snowplow/snowplow-generic/snowplow_scala_stream_collector_0.8.0.zip

Could you please advise where you got this link from so I can update the corresponding documentation?

**Comment by redsquare** [comment]
Hi @jbeemster - from your hosted assets page https://github.com/snowplow/snowplow/wiki/Hosted-assets. Thanks for the revised link.

**Comment by jbeemster** [comment]
Fixed!  Thanks for pointing that.
