### ISSUE TITLE
Kinesis Elasticsearch Sink: allow empty custom contexts

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2927]
We published javascript-tracker-core 0.4.0 two years ago. Until now it wasn't used in mainstream tracker because included one significant change: it allowed [empty custom contexts](https://github.com/snowplow/snowplow-javascript-tracker/issues/292) which would break compatibility with Scala Hadoop Shred < 0.9.14.

But turns out Kinesis Elasticsearch Sink bears this [chunk of code](https://github.com/snowplow/snowplow/blame/master/4-storage/kinesis-elasticsearch-sink/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/elasticsearch/Shredder.scala#L175) and prohibits empty context (and also [Scala Analytics SDK](https://github.com/snowplow/snowplow-scala-analytics-sdk/blob/master/src/main/scala/com.snowplowanalytics.snowplow.analytics.scalasdk/json/JsonShredder.scala#L175).

This all means we should either:
1) Allow empty contexts here and in Analytics SDK and wait two years more when these versions will be obsolete.
2) Abandon `com.snowplowanalytics.snowplow/contexts/jsonschema/1-0-1` Schema and use old `1-0-0`, which makes more sense to me.

**Comment by alexanderdean** [comment]
I am happy with option 2. Can you remind me why we allowed empty custom contexts in 1-0-1?

**Comment by alexanderdean** [comment]
Actually we should do both - if we believe empty custom contexts is A Good Thing, we should create tickets to add support for this to KES and the Scala Analytics SDK.

**Comment by chuwy** [comment]
> Can you remind me why we allowed empty custom contexts in 1-0-1

No, I'm wondering about it as well. It was long before I joined Snowplow.

Real question is whether we really thing empty contexts is good thing. For me empty contexts make not much sense.

**Comment by alexanderdean** [comment]
Thanks @chuwy - can you add an equivalent of https://github.com/snowplow/snowplow-scala-analytics-sdk/issues/21 for Kinesis Elasticsearch Sink and link it back to this ticket?

**Comment by chuwy** [comment]
Sorry @alexanderdean, I'm not following - what do I need to add?

**Comment by alexanderdean** [comment]
Oh sorry! I didn't scroll up and read the name of this ticket 👍 Please ignore!

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#14
