### ISSUE TITLE
Scala Common Enrich: bump ua-parser to latest version

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2931]
This library is in a bit of a mess:

* There is no version available on Maven Central
* The Java version has not been updated for a long time

**Comment by jbeemster** [comment]
Looks like we are already using 1.3.0 which is the latest I can find from here (what we are currently using): https://clojars.org/org.clojars.timewarrior/ua-parser

Also found here:
https://mvnrepository.com/artifact/ua_parser/ua-parser/1.3.0

The library appears to have been split into many new repositories and the new one to watch is:
https://github.com/ua-parser/uap-java

However looks like we are using the latest and greatest of this library so should we push this back?

cc/ @alexanderdean

**Comment by alexanderdean** [comment]
Okay - thanks for checking - let's push back!

**Comment by userkci** [comment]
FYI, they have finally started publishing to Maven Central with version 1.4.0: ua-parser/uap-java#1

This would be extremely useful, as the UA parsing ruleset currently embedded in the enrichment jar is from 2013.

**Comment by BenFradet** [comment]
Thanks for the update, PRs are most welcome :+1:

**Comment by BenFradet** [comment]
superseded by #3811
