### ISSUE TITLE
Update the wiki with Apache Kafka support

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2949]

**Comment by joshuacox** [comment]
I was just wondering if I could replace Amazon Kinesis with Kafka.   Is everything working but undocumented?

**Comment by alexanderdean** [comment]
Hi @joshuacox - you are right, we really need to update the documentation to cover the Kafka support. The current functionality is per the blog post:

https://snowplowanalytics.com/blog/2016/11/15/snowplow-r85-metamorphosis-released-with-beta-apache-kafka-support/

**Comment by simplesteph** [comment]
@alexanderdean would love to get a chance to discuss https://github.com/snowplow/snowplow/pull/3189 before documentation is written. My PR has a few breaking changes but streamlines the whole kafka piece, while providing integration with secure kafka setups

**Comment by alexanderdean** [comment]
Of course! Thanks @simplesteph

**Comment by BenFradet** [comment]
done, closing
