### ISSUE TITLE
sp.js include in example doesn't exist

### ISSUE THREAD

**Issue by shermozle** [snowplow/snowplow#2953]
This page on the wiki: 
https://github.com/snowplow/snowplow/wiki/integrating-javascript-tags-onto-your-website

References:
http://d1fc8wv8zag5ca.cloudfront.net/2.7.0/sp.js

Which doesn't exist. It also talks about a different version directly below.

**Comment by chuwy** [comment]
Thanks @shermozle. I rolled back that page until 2.7.0 released (which should be very soon).
