### ISSUE TITLE
Marketing campaign keyed by arbitrary input properties

### ISSUE THREAD

**Issue by german-bortoli** [snowplow/snowplow#2958]
In discussion to this forum thread http://discourse.snowplowanalytics.com/t/marketing-campaigns-and-iglu-webhook/790

I think that would be a nice idea to enrich any utm* variables that travel like everywhere for example an iglu webhook

It could be included into Campaign attribution enrichment.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/60
