### ISSUE TITLE
How to check if snowplow tracker has been initialised?

### ISSUE THREAD

**Issue by amolbarewar** [snowplow/snowplow#2965]
I am using JS snowplow tracking events. If we do not initialise tracker and executing tracking then we get warning message 'Snowplow: Warning: No tracker configured'. Is there any way to check if tracker has been initialised ( like snowplow_name_here.hasInitialised() )

**Comment by jbeemster** [comment]
Hi @amolbarewar - support questions to our forum please: http://discourse.snowplowanalytics.com/
