### ISSUE TITLE
Add WURFL powered useragent parsing enrichment

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#2966]
http://wurfl.sourceforge.net/
https://web.wurfl.io/

**Comment by christoph-buente** [comment]
@yalisassoon is that still in planning?

**Comment by alexanderdean** [comment]
wurfl microservice java client api is available on maven central : https://search.maven.org/search?q=g:com.scientiamobile.wurflmicroservice

and on a public repo here : https://github.com/WURFL/wurfl-microservice-client-java with some example code.

**Comment by alexanderdean** [comment]
This is where the Docker service is:

https://docs.scientiamobile.com/documentation/wurfl-microservice/docker-getting-started

As far as the list of properties go, here is the reference page:

https://www.scientiamobile.com/capabilities/

**Comment by alexanderdean** [comment]
Here are the AWS AMIs. These let an AWS customer interact with the WURFL microservice by spinning up an AMI:

https://aws.amazon.com/marketplace/pp/B076MJ3JQG?qid=1553179169272&sr=0-2&ref_=srh_res_product_title#pdp-pricing

**Comment by alexanderdean** [comment]
Here is a draft schema:

https://github.com/snowplow/iglu-central/pull/578/files

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/61
