### ISSUE TITLE
Iglu webhook, create an alias

### ISSUE THREAD

**Issue by german-bortoli** [snowplow/snowplow#2971]
Hello, I am trying to make a pixel tracker for emails, following the tutorial http://discourse.snowplowanalytics.com/t/tracking-email-events-sends-opens-and-clicks-with-snowplow-tutorial/436

But it seems that my.collector.url/**com.snowplowanalytics.iglu** is a large string...

is it possible to do an alias, like the "i" but using another word, or something shorter ... ?

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/62
