### ISSUE TITLE
Scala Hadoop Shred: bump SBT to 0.13.13

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#2972]
#2824 

@alexanderdean I created corresponding milestone, assuming cross-batch dedupe release will contain next SHS release.

**Comment by alexanderdean** [comment]
LGTM!

**Comment by alexanderdean** [comment]
Ping @BenFradet

**Comment by BenFradet** [comment]
Can I take care of this since I'm in the middle of a pretty big refactor?

**Comment by alexanderdean** [comment]
Pushing back into @BenFradet's milestone...

**Comment by chuwy** [comment]
Sorry @BenFradet, I need to bring it forward to R88 Milestone, since I need sbt-assembly 0.14.4 to shade dependencies.
