### ISSUE TITLE
Stream Enrich: make Kafka sink more fault tolerant by allowing retries

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2973]
See here:
https://github.com/snowplow/snowplow/blob/e977c976151a36894ed7b83e9461c2fea7eec252/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/sinks/KafkaSink.scala#L60

Would be great to have an optional param in config to set the number of retries. 

That might bring up duplicates, as the docs says though (https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html):
```
If the request fails, the producer can automatically retry, though since we have specified retries as 0 it won't. Enabling retries also opens up the possibility of duplicates (see the documentation on message delivery semantics for details).
```

**Comment by alexanderdean** [comment]
Good idea! Scheduling
