### ISSUE TITLE
Stream Enrich: implement source/sink-agnostic at-least once processing via checkpointing

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2975]
**Was:** *Enricher: Kafka messages are not received at least once*

So in Kafka, you need to choose between at most once, at least once, exactly once. Exactly once is quite tricky to achieve. 

Right now, the implementation snowplow has is at most once. Meaning if the enricher fails while processing data, it won't try to process it again, because there is a chance the offsets have already been committed in Kafka: https://github.com/snowplow/snowplow/blob/r85-metamorphosis/3-enrich/stream-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sources/KafkaSource.scala#L91

See doc at 

https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

I recommend you do manual commits of offsets, to prevent any kind of data loss (at the expense of sometimes having duplicates when rebooting the app - that's the at least once strategy). 

See "Manual Offset Control" in the kafka consumer doc

**Comment by alexanderdean** [comment]
Good plan, scheduling

**Comment by simplesteph** [comment]
So I looked at this and it is going to be more complicated than expected. 

We are losing information along the way, because we do Kafka Consumer -> Processing -> Kafka Producer
The producer doesn't know the offsets of the original records, and therefore we can't commit there. 

I'm not sure if any offsets are committed in Kinesis or how it's achieved today, but I guess you would have the exact same issues. The behaviour is therefore somewhat consistent (although there is the risk of losing data)

This sounds like a perfect use case to use Akka Streams though: http://doc.akka.io/docs/akka/2.4.14/scala/stream/index.html

It has a reactive Kafka adapter: https://github.com/akka/reactive-kafka
Someone put together a reactive stream for Kinesis too: https://github.com/timeoutdigital/akka-streams-kinesis

That will make the framework way more robust in my opinion.

**Comment by alexanderdean** [comment]
Migrating over content from #2946

**Comment by alexanderdean** [comment]
Given that Stream Enrich is flexible around which source you connect to which sink, we have some interesting questions around how we successfully achieve at-least once processing. Here are some examples:

* Kinesis to Kinesis: we should only checkpoint the read when the write has been successful
* Google Cloud Pub/Sub to stdout: we should only ack the read messages when the print to stdout has been successful 
* Kafka to Google Cloud Pub/Sub: we should only checkpoint the read when the write has been successful

We could actually build a whole matrix of the source-sink options and capture the required behaviors for at-least once processing.

I believe that currently Stream Enrich performs optimistic checkpoints on the source, and this is a result of the design decision to have very loosely coupled:

    source -> sink

I think we need to re-architect Stream Enrich and introduce some kind of first-class Checkpoint entity, which we will use to deliver pessimistic checkpointing on the source:

    source -> sink -> checkpoint 
       ^                    /
        \------------------/

**Comment by simplesteph** [comment]
If you use Akka Streams framework, I believe you can easily achieve that :) Just need to create a Source interface that has a `checkpoint` call which can get called when the job is done. 
An example to look at (at least for inspiration) can be found here: http://doc.akka.io/docs/akka-stream-kafka/current/consumer.html#offset-storage-in-kafka

**Comment by alexanderdean** [comment]
Sounds great, thanks @simplesteph!

**Comment by BenFradet** [comment]
Delaying until we get stream enrich onto beam (and an appropriate runner) where we'll get checkpointing for free

**Comment by BenFradet** [comment]
this is done for beam enrich, descheduling

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/63
