### ISSUE TITLE
Kafka, Discussion: app-name is used as group ID, is that risky?

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#2976]
I don't know how often and if snowplow users ever change their app name, but if they do, because kafka uses app-name as the group-id, the streams will be read from start (earliest). https://github.com/snowplow/snowplow/blob/master/3-enrich/stream-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/sources/KafkaSource.scala#L90

I would personally feel more confident if a group-id was a parameter within the kafka config, and I could change that independently of my app-name. This would allow me to change a few things and then replay it all just by changing group-id.

Any thoughts on that?

**Comment by alexanderdean** [comment]
Interesting question. The Kafka behavior is exactly the same as the Kinesis behavior - the app name is used *primarily* to identify the consuming group from a checkpointing perspective. We haven't had any concerns about this from the Kinesis users so I think this is a non-issue, unless there is something specific about Kafka I am missing...

**Comment by simplesteph** [comment]
I think it's just the naming, on my end. I feel more confident when seeing this param with the kafka config, otherwise I'd have to dig up the code and see if it was app-name. 
Maybe the documentation will clear that up?

**Comment by alexanderdean** [comment]
I hear you - if you're very familiar with Kafka and understand consumer groups, you're probably going to hunt for a variable with that name. If you're not "Kafka/Kinesis native", then the idea that the app name identifies the app from a behavioral perspective is pretty intuitive.
