### ISSUE TITLE
EmrEtlRunner: no longer use sources property when loading Elasticsearch

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2993]
`sources` is an array of all the buckets containing bad rows which user want to send to Elasticsearch. If the `sources` field isn't given, it defaults to the two bad rows buckets for the current run (enrich failures and shred failures).

This should be always default to `enriched/bad` and `shredded/bad`.

**Comment by alexanderdean** [comment]
Can you add a description to this ticket please @chuwy ?

**Comment by chuwy** [comment]
Done.
