### ISSUE TITLE
Update CloudFront Collector documentation to mention second pixel

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2996]
See http://discourse.snowplowanalytics.com/t/iglu-webhook-response-code/837/7

**Comment by ihortom** [comment]
@alexanderdean - Done: https://github.com/snowplow/snowplow/wiki/Setting-up-the-Cloudfront-collector#using-webhook-adapter

**Comment by alexanderdean** [comment]
Great - closing.
