### ISSUE TITLE
Update Installing EmrEtlRunner wiki page to not reference a version explicitly

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2997]
* https://github.com/snowplow/snowplow/wiki/1-Installing-EmrEtlRunner
* http://discourse.snowplowanalytics.com/t/emretlrunner-argumenterror-aws-emr-api-error-validationexception/844/6

**Comment by ihortom** [comment]
@alexanderdean - The wiki page does provide the link to other versions and explains how to get them:

>**Note**: Please, follow [this link](http://dl.bintray.com/snowplow/snowplow-generic/) if you wish to get a different version of the runner. The distribution name follows the pattern `snowplow_emr_{{RELEASE_VERSION}}.zip`.

Do you think something else needs to be done?

**Comment by alexanderdean** [comment]
I removed the stale content, closing
