### ISSUE TITLE
Kinesis Elasticsearch Sink: allow AWS request signing for outbound events

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3001]
http://stackoverflow.com/questions/33760144/signing-aws-http-requests-with-apache-httpcomponents-client/33762950#comment68073867_33762950

https://github.com/inreachventures/aws-signing-request-interceptor

**Comment by mrwacky42** [comment]
This would be very nice, since so far, the rest of the Snowplow stack supports IAM role profiles.

**Comment by nitin02** [comment]
Hello, Is there any milestone or progress on this request?

Signing is definitely a necessary component as it allows for the sink to scale to any number of machines based on input load (with aws).

**Comment by alexanderdean** [comment]
Fair point! Scheduled into the next Kinesis milestone.

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#12
