### ISSUE TITLE
EmrEtlRunner: update spark_enrich version in config.yml.sample to 1.11.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3002]

**Comment by knservis** [comment]
@alexanderdean this seems ready, it just needs to be tested correct?

**Comment by alexanderdean** [comment]
Yes. This ticket exists really just to track the bump in the underlying Spark Enrich, which will bump because of the other tickets in the release. I'll update the ticket name now

**Comment by alexanderdean** [comment]
Changed to 1.x.0 as not sure what the version will be on release.

**Comment by knservis** [comment]
Is this still relevant given #3068 ?

**Comment by alexanderdean** [comment]
The title of the ticket was updated yesterday (it's still relevant)
