### ISSUE TITLE
[EMR]Tag EMR generated VPC with Snowplow-EMR-temporary

### ISSUE THREAD

**Issue by spy-tech** [snowplow/snowplow#3011]
In 
`https://github.com/snowplow/snowplow/blob/6c62b205fcd60e286dbca76e829a2eab8e8e621f/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb` I would like to see the autogenerated VPC to be tagged in such a way that a listing of all the VPCs in the Amazon Console displays something like Snowplow-EMR-temporary in the left most column. Currently, there is an empty description visible. 

While it is possible to look into the details and see security groups related to EMR, this shouldn't be needed.

We would like to also have feedback whether you would be interested in having such a feature in the first place.

For generality, there should be two mechanisms supported; one using an existing VPC and another where one can configure the name of the temporary VPC to be created.

**Comment by alexanderdean** [comment]
Under what circumstances does EmrEtlRunner auto-generate a VPC?

**Comment by spy-tech** [comment]
@alexanderdean I was wrong. I will check how we exactly do things. Not a Snowplow issue.
