### ISSUE TITLE
storageloader compiled with jruby-9.0.5.0 doesn't seem to work

### ISSUE THREAD

**Issue by chocopowwwa** [snowplow/snowplow#3017]
Hi, 
first of all, why don't you specify the version of jruby on 
https://github.com/snowplow/snowplow/blob/release/r87-chichen-itza/4-storage/storage-loader/build.sh

Branch: master
Command that i use to build ( on snowplow/4-storage/storage-loader )
```
bash build.sh
```
Command that i use to run
```
./deploy/snowplow-storage-loader -c ./deploy/config.yml
```

Output:
```
Downloading Snowplow events...
Unexpected error: no implicit conversion of Symbol into Integer
org/jruby/RubyArray.java:1457:in `[]'
uri:classloader:/storage-loader/lib/snowplow-storage-loader/s3_tasks.rb:41:in `download_events'
uri:classloader:/storage-loader/bin/snowplow-storage-loader:42:in `<main>'
org/jruby/RubyKernel.java:973:in `load'
uri:classloader:/META-INF/main.rb:1:in `<main>'
org/jruby/RubyKernel.java:955:in `require'
uri:classloader:/META-INF/main.rb:1:in `(root)'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `<main>'

```

Gemfile.lock https://gist.github.com/chocopowwwa/1137b05036d18b52754090bec20786fe

and i saw the commit https://github.com/snowplow/snowplow/commit/6bdd3fbb724464dc00ebcf43146721c0c40bd2cf
and i try to build and run it again
and it give me output
```
Downloading Snowplow events...
Unexpected error: undefined method `host=' for #<Fog::Storage::AWS::Real:0x47f5ab58>
uri:classloader:/storage-loader/lib/snowplow-storage-loader/s3_tasks.rb:41:in `download_events'
uri:classloader:/storage-loader/bin/snowplow-storage-loader:42:in `<main>'
org/jruby/RubyKernel.java:973:in `load'
uri:classloader:/META-INF/main.rb:1:in `<main>'
org/jruby/RubyKernel.java:955:in `require'
uri:classloader:/META-INF/main.rb:1:in `(root)'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `<main>'

```

but after i remove the line 41 ( ```s3.host = region_to_safe_host(config[:aws][:s3][:region])``` )
and build it again it works fine, looks like the fog remove host attribute
what am i missing here?
is it going to have further problem ?
thx

**Comment by alexanderdean** [comment]
Scheduling into R67...

**Comment by alexanderdean** [comment]
Pushing back

**Comment by alexanderdean** [comment]
Closing in favor of #3051
