### ISSUE TITLE
SnowPlow installing via CocoaPods

### ISSUE THREAD

**Issue by ksingh65** [snowplow/snowplow#3018]
Hi,

I am trying to install Snowplow using cocoa pods, while building its giving me error:
" include of non-modular header inside framework module 'FMDB.FMDatabase' [-Werror,-Wnon-modular-include-in-framework-module]
#import "sqlite3.h""

My project is in Swift.

Thanks,

**Comment by alexanderdean** [comment]
Please use our Discourse for support: http://discourse.snowplowanalytics.com/
