### ISSUE TITLE
RDB Loader: replace StorageLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3026]
Do this first @chuwy and then update all the other ticket names

**Comment by chuwy** [comment]
Renamed ticket, as code-wise it's just remove of `4-storage/storage-loader`.

**Comment by alexanderdean** [comment]
Do you mean "RDB Loader: remove StorageLoader Ruby files"? Replace doesn't seem correct as I just see deletions in this commit.

**Comment by chuwy** [comment]
Yes, "remove" sounds more acceptable.
