### ISSUE TITLE
EmrEtlRunner: replace hadoop_shred in config.yml.sample with rdb_shredder

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3035]

**Comment by BenFradet** [comment]
Should we move the config to the storage part as well, instead of enrich?

**Comment by alexanderdean** [comment]
Hmm, good question - I think we should...

**Comment by alexanderdean** [comment]
We're calling the component RDB Shredder, so the config file property should be `rdb_shredder` - updated the ticket title...

**Comment by BenFradet** [comment]
Should we rename the tags as well: https://github.com/snowplow/snowplow/pull/3203/files#diff-354f30a63fb0907d4ad57269548329e3R75 ?

**Comment by BenFradet** [comment]
same goes for https://github.com/snowplow/snowplow/blob/78676a1e2497f0169260986f606b89535a08dff5/.travis/release_relational_database_shredder.yml

**Comment by alexanderdean** [comment]
Let's do it, please rename the tags, commits, tickets etc...
