### ISSUE TITLE
StorageLoader: add support for Spark-based Shredder's directory structure

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3044]
Due to the changes introduced by #3034, the directory structure will now look like:

```
shredded/
    good/
        run=2016-11-26-21-48-42/
            atomic-events/
                part-00000
                part-00001
                ...
            shredded-types/
                vendor=com.acme/
                    name=event/
                        format=jsonschema/
                            version=1-0-0/
                                part-00001-00010
                    name=context/
                        format=jsonschema/
                            version=1-0-0/
                                part-00001-00010
```

as opposed to what was before

```
shredded/
    good/
        run=2016-11-26-21-48-42/
            atomic-events/
                part-00000
                part-00001
                ...
            com.acme/
                event/
                    jsonschema/
                        1-0-0/
                            part-00001-00010
                context/
                    jsonschema/
                        1-0-0/
                            part-00001-00010
```

There are effectively two changes:

- The field names of `SchemaKey` (vendor, name, format, version) are part of the path, what was `com.acme/event/jsonschema/1-0-0` is now `vendor=com.acme/name=event/format=jsonschema/version=1-0-0`
- A `shredded-types` layer has been added

**Comment by alexanderdean** [comment]
Renamed ticket to make it a command rather than a description

**Comment by chuwy** [comment]
I think this should be for "StorageLoader"?

**Comment by BenFradet** [comment]
It depends on the timeline of the releases: if RDB Loader is released before the Spark port, I'll need to port the commit over to the RDB Loader, otherwise it belongs to StorageLoader yes.

**Comment by alexanderdean** [comment]
Yes, sequencing is everything here!

**Comment by alexanderdean** [comment]
Updated title, please update commit!

**Comment by alexanderdean** [comment]
StorageLoader no space
