### ISSUE TITLE
Placeholder for one-time script to backload DynamoDB manifest with event IDs and fingerprints

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#3045]
As title, needed for launch

**Comment by alexanderdean** [comment]
Descheduling as per @yalisassoon and @bogaert:

> The requirement to populate the DynDB table before starting isn't a strong requirement at all. Anyone upgrading to this release will need to do a one-off process to remove historical dupes and that process, if run a few weeks after upgrade, remove the handful of new dupes that might be generated post upgrade because the DynDB table starts off empty. So we can probably drop this altogether.

**Comment by alexanderdean** [comment]
Closing!
