### ISSUE TITLE
What's the latest stable of EmrEtlRunner?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [snowplow/snowplow#3046]
In [changelog](https://github.com/snowplow/snowplow/blob/master/CHANGELOG) it looks like: `Release 86 Petra (2016-12-20)` is the one. But in http://dl.bintray.com/snowplow/snowplow-generic/ it looks like the latest is: `snowplow_emr_r77_great_auk.zip`

???

**Comment by jbeemster** [comment]
Hi @NielsKSchjoedt as the repo is comprised of many different projects we do not necessarily work on every project per release cycle.  If you look in the changelog you will see that the last EmrEtlRunner release was R83 (https://github.com/snowplow/snowplow/blob/master/CHANGELOG#L75).

In Bintray you will then find a zip file called `snowplow_emr_r83_bald_eagle.zip`.  

Link: http://dl.bintray.com/snowplow/snowplow-generic/:snowplow_emr_r83_bald_eagle.zip

In future please use our  Discourse forum for support: http://discourse.snowplowanalytics.com/
