### ISSUE TITLE
Why aren't tables referenceing atomic.events using ON DELETE CASCADE?

### ISSUE THREAD

**Issue by radubogdan** [snowplow/snowplow#3075]
We are using the [deduplication queries](https://github.com/snowplow/snowplow/tree/master/5-data-modeling/deduplication-queries) to get rid of duplicates in the `atomic.events` table, they work great. However we are wondering, why all the tables referencing `atomic.events` (e.g. `atomic.com_snowplowanalytics_snowplow_ua_parser_context_1`) are not having `ON DELETE CASCADE` on the FK? 
If an event is begin detected as a duplicate in the events table, then the following delete action will fail due to the current FK constraint setting (no cascade). 
How is this suppose to work and what's the thinking behind it?

**Comment by bogaert** [comment]
Hi @radubogdan. I don't think `ON DELETE CASCADE` is available in Redshift?

**Comment by alexanderdean** [comment]
Closing given @bogaert's comment
