### ISSUE TITLE
Placeholder for updating the AWS SDK version

### ISSUE THREAD

**Issue by acgray** [snowplow/snowplow#3079]
The current AWS SDK dependencies don't support IAM roles for ECS container tasks which makes it difficult to run Snowplow in ECS with a correct IAM setup.

Simply bumping the dep version to 1.11.16 pushes the jarfile pushes some components over the file limit however, so resolving that problem is the main intent for this issue.

**Comment by alexanderdean** [comment]
Makes sense!

**Comment by acgray** [comment]
Limiting the AWS deps to only the necessary components (i.e. Kinesis) solves this for me - will submit a PR shortly...

**Comment by BenFradet** [comment]
this has been done, closing
