### ISSUE TITLE
Stream Enrich: replace ArrayIndexOutOfBoundsException in IP Lookups with initialization failure

### ISSUE THREAD

**Issue by NirSivan** [snowplow/snowplow#3083]
I am running snowplow-stream-enrich-0.10.0 
I have setup ip_lookups enrichment, setup looks good but I am receiving this error.

{
    "schema": "iglu:com.snowplowanalytics.snowplow/ip_lookups/jsonschema/1-0-0",

    "data": {

        "name": "ip_lookups",
        "vendor": "com.snowplowanalytics.snowplow",
        "enabled": true,
        "parameters": {
            "geo": {
                "database": "GeoLiteCity.dat",
                "uri": "s3://xxxxxxxxx-snow-plow-assets/third-party/maxmind"
            }
        }
    }
}
However when running the stream enrich the enrichment results in an error 

"Could not extract geo-location from IP address [xx.xx.xx.xx]: [java.lang.ArrayIndexOutOfBoundsException: 15796200 

I have tried a lot of trouble shooting and finally what helped is downloading the db via

yum install GeoIP GeoIP-data

Then putting the ip_geo file in the enrichment folder, that made the stream enrich to start downloading the file, after that the process ran correctly  and successfully finish the job.

I would assume some sort of cache is causing this

**Comment by alexanderdean** [comment]
For just using the GeoLiteCity.dat, this works fine:

```json
{
    "schema": "iglu:com.snowplowanalytics.snowplow/ip_lookups/jsonschema/1-0-0",

    "data": {

        "name": "ip_lookups",
        "vendor": "com.snowplowanalytics.snowplow",
        "enabled": true,
        "parameters": {
            "geo": {
                "database": "GeoLiteCity.dat",
                "uri": "http://snowplow-hosted-assets.s3.amazonaws.com/third-party/maxmind"
            }
        }
    }
}
```

There may be an issue with the `s3://` protocol and Stream Enrich - I'll update the ticket name...

**Comment by alexanderdean** [comment]
See this thread for others having a similar problem:

http://discourse.snowplowanalytics.com/t/ip-lookup-arrayindexoutofboundsexception/870/20

My question would be how authentication currently works in Stream Enrich for the s3: protocol with the IP Lookups enrichment.

**Comment by NirSivan** [comment]
I have tried this configuration multiple times and that did not fix the issue, 

I have also tried with S3:// and with http: on my local buckets after verifying that the server have access to them and that the resources on them are available.

Like I said my best assumption is that something did not load up properly on my first configuration, then it got stuck in this situation where no matter if the setup is correct or not, the result is the error.

Putting the file in the enrichments folder was sort of a last resort,but it did the work

Hope this helps anyone.

**Comment by dashirov-ga** [comment]
I've noticed the enrichment downloads ( or attempts to download) the ip database into the current working directory of the running stream enrichment process. It silently fails to download,  if your start the process from a path that lacks sufficient permissions to download the database.
Changing directory to a location writable by the running enrich process should fix your situation. Fixing the enrichment to download database files into a known and configurable location obviously is a better thing to do.

**Comment by alexanderdean** [comment]
Thanks @dashirov-ga - I have modified the ticket title again...

**Comment by alexanderdean** [comment]
See also: #3084

**Comment by thiagogsr** [comment]
It is working for me after it:

http://discourse.snowplowanalytics.com/t/ip-lookup-arrayindexoutofboundsexception/870/21?u=thiagogsr

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/64
