### ISSUE TITLE
Scala Common Enrich: bump scala-iglu-client to 0.5.0

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3092]

**Comment by chuwy** [comment]
@BenFradet just a heads-up. This should be done in same release with https://github.com/snowplow/snowplow/issues/3098 and https://github.com/snowplow/snowplow/issues/3090, as Iglu Client 0.5.0 contains changes that are probably not binary compatible (but source-compatible) with previous versions.

**Comment by BenFradet** [comment]
@chuwy Ok thanks, I think the plan was to combine the bumps with the spark port milestone anyway.
