### ISSUE TITLE
Common: add CI/CD for EmrEtlRunner and StorageLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3102]
Currently they are deployed manually using this script:

https://github.com/snowplow/snowplow/blob/master/vagrant/push/publish-emr-release.bash

Let's port to CI/CD and delete the above script.

This is important to make sure we have repeatable builds for EmrEtlRunner and StorageLoader, which are probably our most build-environment-sensitive apps.

**Comment by alexanderdean** [comment]
Hey @chuwy - where is the code for this?

**Comment by chuwy** [comment]
Pushed now ^^
