### ISSUE TITLE
EmrEtlRunner: add backend for a `generate` command

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3105]
Two sub-command options:

* `generate emr-cluster`, which produces a Dataflow Runner-compatible EMR cluster config in Avro format
* `generate playbook`, which products a Dataflow Runner-compatible playbook for running the job

Let's take these in turn:

### `generate emr-cluster`

This command will use the cluster specification in the `config.yml` to generate a Dataflow Runner-compatible EMR cluster config.

### `generate playbook`

This command will use the `config.yml` plus the contents of the `--enrichments` folder, plus any relevant command line arguments (such as `--skip staging`) to generate a Dataflow Runner-compatible playbook for running the identical job via Dataflow Runner.

**Comment by alexanderdean** [comment]
If this is blocked by any missing features in Dataflow Runner, these should go into a priority 0.2.0 for Dataflow Runner.

**Comment by alexanderdean** [comment]
This functionality must be written in Java so that it can survive an EmrEtlRunner port into Scala...

**Comment by BenFradet** [comment]
@alexanderdean Are we sure, we want to write this part in Java?

It seems that, to be able to interact with your own java code, you need to deal with unmanaged dependencies (`require 'lib/mylib.jar'`).
Plus, if it's destined to be rewritten in Scala we might as well rewrite this part as well because I don't think it'll be portable as it might be written anyway (the Java code will be peppered with JRuby stuff from what I understand).

Please, correct me if I'm wrong as it's my first time even remotely approaching some JRuby (and Ruby for that matter).

**Comment by alexanderdean** [comment]
Hi @BenFradet - you raise good points. I think it's okay then to write this in Ruby, same as the rest of the codebase...

**Comment by BenFradet** [comment]
> If this is blocked by any missing features in Dataflow Runner, these should go into a priority 0.2.0 for Dataflow Runner.

It's not a blocker since I don't really know the order of things but the Spark stuff relies on snowplow/dataflow-runner#6

**Comment by alexanderdean** [comment]
Okay cool - assigned you to the 0.2.0 milestone per our convo a little earlier...

**Comment by BenFradet** [comment]
@alexanderdean 

By the way, dataflow-runner only allows `CANCEL_AND_WAIT` and `CONTINUE` as `actionOnFailure` and not `TERMINATE_JOB_FLOW`, I defaulted to `CANCEL_AND_WAIT` as a result in the making of the playbook.

Do you think it's reasonable?

**Comment by alexanderdean** [comment]
Hey @BenFradet - I think that's reasonable - Dataflow Runner will happily kill the cluster on a step moving into WAIT, if it is `--run-transient`...

**Comment by jbeemster** [comment]
Thats exactly right @alexanderdean - we have the ability to manually kill the cluster as the last step irrespective of the steps.

**Comment by alexanderdean** [comment]
This is nice but we will push back so we can get this release out faster.

**Comment by alexanderdean** [comment]
@BenFradet to schedule this back in and clarify name and add follow-up tickets

**Comment by alexanderdean** [comment]
Nice ticket name
