### ISSUE TITLE
Kinesis Elasticsearch Sink: add support for Elasticsearch 5.x

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3111]
https://aws.amazon.com/about-aws/whats-new/2017/01/elasticsearch-5-now-available-on-amazon-elasticsearch-service/

We need a third build target to support this to be sure that there will be no complications.

**Comment by jbeemster** [comment]
At this point the 2.x sinks do work with a 5.x sink but it would be good to get this properly tested and to use the latests libs supporting this.

**Comment by gincor** [comment]
@jbeemster are you saying I can give the 2.x sink a shot with an elasticsearch 5.x cluster? Not for production, but it should sort of work? Clarifying because either you mistyped ('2.x sinks do work with a 5.x **sink**') or I don't get what you mean.

**Comment by jbeemster** [comment]
Ahh yes I meant a 5.x cluster.  We do actually are using this in production now without any issues.

**Comment by gincor** [comment]
Just FYI - couldn't make the 0.8 2.x sink work with an es 5.2.2 cluster - don't have the exact error at hand now, but it failed to find an es node at the given endpoint. It worked when I downgraded that exact endpoint to 2.4.4 and ran it with the exact same configuration file.

**Comment by jbeemster** [comment]
Using the `transport` or `http` client @gincor ?

**Comment by gincor** [comment]
transport. I'm almost sure I tried it once or twice with http as well, but not 100%.

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#10
