### ISSUE TITLE
EmrEtlRunner: placeholder for deciding what to do with file-related no-ops

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3112]
One of the powerful features of EmrEtlRunner is that it is very good at detecting no-op scenarios that should lead to a graceful termination of the run.

In particular:

* If no data is found in raw for moving to staging, then do not proceed (nothing to do)
* If data is found in staging, enriched or shredded, then do not proceed (previous run is ongoing or has failed pending manual fix)

In a world where all S3 file manipulation has moved to EMR, and in a world where EmrEtlRunner is having the dataflow logic extracted from it (ready for the move to Dataflow Runner), then we need to decide:

* Do we still need these no-op detections, or is there a better way of accomplishing the same thing?
* Where should these no-op detections live / how should they be implemented?

**Comment by alexanderdean** [comment]
One idea is to move these checks into individual jobflow steps (run on master), and make them terminate the cluster if they don't pass. Then it's on EmrEtlRunner (and later Dataflow Runner) to realize that these steps terminating the cluster means a benevolent no-op, not a job failure per se... Thoughts @BenFradet, @chuwy ?

**Comment by BenFradet** [comment]
The added value from the current checks I see is the short-circuiting of the launch of the EMR cluster.

Once the EMR cluster is up, I don't think those checks matter, it has virtually no impact whether to run the no-ops steps or not, unless I'm mistaken?

And since we want to move everything to EMR, the cluster would be up no matter what.

**Comment by alexanderdean** [comment]
You are right - we are losing the ability to short-circuit the launch of the cluster; that's never coming back.

However:

* We have to terminate the cluster if the previous run has failed/is ongoing - the pipeline is not currently setup to successfully work through a subsequent load if the previous one failed
* (Less important) there may be an advantage in shortcutting a no-data run early (vs just letting the pipeline run its course with no data). It may even be that a downstream component will break if there's no data to process - needs testing.

**Comment by BenFradet** [comment]
From what I gathered/experimented with today, we could:

- implement the different checks (empty dirs and even number of lzo files) through simple bash scripts submitted as emr steps as you said earlier
- use s3distcp for staging and archiving. However, the cleaning up of the filenames performed in [s3_tasks](https://github.com/snowplow/snowplow/blob/master/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3_tasks.rb#L57-L100) seems a bit too involved for an s3distcp step. As a result do you think we can do without or that we should rely on something else entirely to do the staging step?

**Comment by alexanderdean** [comment]
Thanks @BenFradet -

* _Implement the empty dirs checks through simple bash scripts submitted as emr steps_ sounds good - the challenge is we need to figure out how to capture return codes from those bash scripts
* Note that the LZO files check will be gone soon (#2740)
* S3DistCp for archiving raw is coming soon (#1977)
* S3Distcp for archiving enriched/shredded will be tackled by @chuwy (#1777)
* _the cleaning up of the filenames performed in s3_tasks seems a bit too involved for an s3distcp step_ - agree; if we consider that we have four collector formats to handle (cloudfront, clojure, lzo sink, Urban Airship), my hunch is that 2 or 3 of these can be handled by S3DistCp with a bit of hacking; 1 or 2 of these will need a dedicated script/binary which runs on the EMR cluster

**Comment by BenFradet** [comment]
> the challenge is we need to figure out how to capture return codes from those bash scripts
Isn't a fail/succeed step enough?

I'll keep on investigating the last point

**Comment by alexanderdean** [comment]
> Isn't a failed/succeeded step enough?

Yes, I think you will end up with:

* Succeeding/failing the step
* Writing custom code in EmrEtlRunner to interpret certain jobflow steps failing as a no-op with specific return code from EmrEtlRunner, versus currently where any jobflow step failing means that EmrEtlRunner failed.

**Comment by BenFradet** [comment]
I guess I don't really see the difference between:

- now:
  - a no-op which results in the termination of both the cluster (or avoid starting it but this goes away no matter what as we said earlier) and eer (through a `DirNotEmptyError` or a `NoDataToProcessError`), for me this does seem like a kind of failure
  - the failure of a step like enrich which results in the same thing (through `EmrExecutionError`)

- and what would be (as I imagine it):
  - no-ops and failures both result in the termination of both the cluster and eer (through `EmrExecutionError`)

Since `EmrExecutionError` invites the user of eer to check the console, she/he will see why things failed (no-op or "real" failure).

I think this simplify things quite a bit actually regarding the transition to dataflow runner compared to having to inspect the status of a particular set of steps.

Would love to hear your thoughts.

**Comment by alexanderdean** [comment]
The difference is that any `DirNotEmptyError` or a `NoDataToProcessError` should not be escalated to a engineer for investigation - they should not generate an incident waking up a team member in the middle of the night to verify that they are dealing with a no-op versus a failure requiring manual intervention.

**Comment by BenFradet** [comment]
So here is how I've managed to mimic the current behavior of eer without relying on Sluice based on two scripts that check whether a directory is empty:

- script step checking that the processing is empty, if not failure of the step which is then picked up by eer and results in a `DirNotEmptyError`
- staging s3distcp step (still has to be coded)
- script step checking that the processing has been filled, if not -> failure of the step -> `NotDataToProcessError`
- script steps checking that shred and enrich are empty, if not -> failure of the steps -> `DirNotEmptyError`

**Comment by alexanderdean** [comment]
I think this sounds good @BenFradet. Maybe split this into two tickets:

1. One covering (both) `DirNotEmptyError` scenarios
2. One covering the `NoDataToProcessError` scenario

**Comment by BenFradet** [comment]
@alexanderdean Ok, I'll try to split the commit in two.

**Comment by BenFradet** [comment]
created #3130 and #3131 :+1:

**Comment by alexanderdean** [comment]
Closing and de-scheduling this given we have specific tickets now...
