### ISSUE TITLE
RDB Loader: fix eventual consistency problem

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3113]
We have a problem with users who a) have large volumes and b) have high event/context cardinalities where:

* The StorageLoader code for discovering folders in S3 of shredded entities detects already-deleted "ghost" folders (this is due to S3's notorious eventual consistency problems), *but*
* The Redshift `COPY` statement (correctly) does not find this ghost folder (nor any contents of it), *and thus*
* The overall `COPY` statement (correctly) fails

We need to fix this - we can hope that just porting the StorageLoader S3 folder discovery code *might* make the problem go away, but it would be better to actively guard against this issue in this release.

/cc @leonmaas

**Comment by gregbonnette** [comment]
Good talk on this issue and some potential solutions...  https://spark-summit.org/east-2017/events/spark-and-object-stores-what-you-need-to-know/
