### ISSUE TITLE
Common: add AWS staging credentials to .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3114]
* `AWS_STAGING_ACCESS_KEY_ID`
* `AWS_STAGING_SECRET_ACCESS_KEY`

Unlike credentials from #2963 these are for continuous integration, not for hosted assets deployment.

@alexanderdean should we also rename #2963 credentials to make explicit that they're for deploying?

**Comment by alexanderdean** [comment]
Thanks @chuwy - yes we should rename the existing, but that doesn't have to go in this release (please create a new ticket!)

**Comment by alexanderdean** [comment]
The table the permissions should be on should be: `table/snowplow-integration-test-crossbatch-deduplication`

**Comment by chuwy** [comment]
Thanks. Cherry-picked.
