### ISSUE TITLE
Common: rename AWS deployment credentials in .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3115]
* `AWS_ACCESS_KEY` to `AWS_DEPLOY_ACCESS_KEY_ID`
* `AWS_SECRET_KEY` to `AWS_DEPLOY_SECRET_ACCESS_KEY`

See #3114.

Put in the webhooks milestone, assuming it'll be R89.

**Comment by alexanderdean** [comment]
Ticket where the variables we need to rename were added:

https://github.com/snowplow/snowplow/issues/2963

**Comment by alexanderdean** [comment]
Okay, I've added the commits. Still to do:

* Tidy-up into one commit (or maybe add another ticket/commit for adding all the nice comments back in)
* Update the call sites for these renamed variables

**Comment by alexanderdean** [comment]
FYI the updated secrets were added like this:

```
travis encrypt AWS_DEPLOY_ACCESS_KEY="xxx" --add

travis encrypt AWS_DEPLOY_SECRET_KEY="yyy" --add
```

**Comment by knservis** [comment]
@alexanderdean I suggest we keep the environment variables as: 
```
AWS_DEPLOY_ACCESS_KEY_ID
```
and
``` 
AWS_DEPLOY_SECRET_ACCESS_KEY
```
instead of:
```
AWS_DEPLOY_ACCESS_KEY
```
and
``` 
AWS_DEPLOY_SECRET_KEY
```
but either way will work (I cannot add these keys as I don't have them).

**Comment by alexanderdean** [comment]
Oh welp, I misread the ticket sorry. Will update

**Comment by knservis** [comment]
- [ ] @alexanderdean to update the secrets
- [ ] @knservis to compact the commits through rebase and submit PR

**Comment by alexanderdean** [comment]
Done, ran:

```
travis encrypt AWS_DEPLOY_ACCESS_KEY_ID="..." --add

travis encrypt AWS_DEPLOY_SECRET_ACCESS_KEY="..." --add
```

**Comment by knservis** [comment]
@alexanderdean Did you push your changes?

**Comment by alexanderdean** [comment]
Yes, check the branch https://github.com/snowplow/snowplow/commits/issue-3115

**Comment by knservis** [comment]
Submitted https://github.com/snowplow/snowplow/pull/3479
