### ISSUE TITLE
Hadoop Elasticsearch Sink: add support for Elasticsearch 5.x

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3122]
At the moment it looks like we are using the Elasticsearch Hadoop 2.2 library - however with the recent release of Elasticsearch 5.x it would be great if we can get this upgraded!

https://github.com/snowplow/snowplow/blob/master/4-storage/hadoop-elasticsearch-sink/project/Dependencies.scala#L35
https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-hadoop

We have also noticed quite a few failures with very large volumes of data - if possible it would be great to perform some load tests to see how we can stabilise this.

**Comment by alexanderdean** [comment]
Component is no longer supported.
