### ISSUE TITLE
EmrEtlRunner: turn the no data to process detection through Sluice into an EMR step

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3131]

**Comment by alexanderdean** [comment]
This is a nice feature, because it prevents an EMR cluster from spinning up unnecessarily if there is nothing to process, but:

1. It adds a lot of complexity
2. It would be infrequently used (most pipelines have some data to process each run)

**Comment by alexanderdean** [comment]
Descheduling

**Comment by alexanderdean** [comment]
I don't understand this idea any more - spinning up an EMR cluster to run a jobstep to see if there is data to process defeats the purpose of the check in the first place...
