### ISSUE TITLE
EmrEtlRunner: use S3DistCp to move raw files from S3 to HDFS for all collector formats

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3136]

**Comment by alexanderdean** [comment]
Made ticket name less cryptic

**Comment by alexanderdean** [comment]
@BenFradet why does the commit message not match the ticket name? This is super confusing

**Comment by alexanderdean** [comment]
We always want a 1:1 match

**Comment by BenFradet** [comment]
I must have missed your renaming
