### ISSUE TITLE
StorageLoader: handle return code of 4 for EmrEtlRunner in snowplow-runner-and-loader.sh

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3139]
See https://github.com/snowplow/snowplow/issues/2546

**Comment by chuwy** [comment]
For what I understand from [this comment](https://github.com/snowplow/snowplow/issues/3112#issuecomment-281663380), it should output error-specific message and exit with **0**?

**Comment by alexanderdean** [comment]
Correct
