### ISSUE TITLE
Scala Hadoop Shred: make ttl of event in duplicates storage configurable

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3141]
So far `ttl` is fixed value (`etl_tstmp` + 1 month), which may be not sufficient to clean up enough duplicates. We can provide users ability to tweak this timespan via duplicates storage target configuration JSON.

See #2999 

/cc @bogaert

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/124 closing
