### ISSUE TITLE
event_vendor value is always com.google.analytics for non-custom structured events

### ISSUE THREAD

**Issue by LBirk** [snowplow/snowplow#3142]
In snowplow-master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/SchemaEnrichment.scala:
the meta-data enrichment defines a schema for events of type "struct" (line 48):
    ``case "struct"           => Schemas.structSchema``
where structSchema is defined on line 42 to be:
    ``val structSchema          = SchemaKey("com.google.analytics", "event", "jsonschema", "1-0-0").success``
It looks like non-custom structured events being sent without a tracker are causing this line to map the event_vendor to com.google.analytics (I'm sending the events directly to the collector). If an event gets sent without the tracker but it's an unstructured event, the event_vendor field is populated correctly.

Seems like the ``com.google.analytics`` should be replaced with something like ``com.snowplow.analytics``.

**Comment by chuwy** [comment]
Hello @LBirk,

Sorry, but it's not entirely clear what expectations do you have about structured events. It looks like you confuse structured and self-describing events. [Structured events](https://github.com/snowplow/snowplow/wiki/Custom-events#custom-structured-event) are modeled after a Google Analytics event, therefore they have `com.google.analytics` vendor. These should be not confused with [Unstructured (self-describing) events](https://github.com/snowplow/snowplow/wiki/Custom-events#self-describing-event).

If my suggestion is right and you need more information about these - you can ask questions on [discourse forums](http://discourse.snowplowanalytics.com/) and this issue can be closed (Github is for issues only). Please, reopen if I'm wrong.
