### ISSUE TITLE
StorageLoader: remove Northern Virginia endpoint for Postgres load

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3143]
Issue: http://discourse.snowplowanalytics.com/t/storage-loader-issues-runtime-errors/1039/6

This effectively reverts https://github.com/snowplow/snowplow/issues/2748

`.host = ` is not supported by Sluice/Fog. I cannot see at what point this API worked and since when it stopped to work, but it makes Postgres load non-working. Moreover, from expired status in [this document](https://forums.aws.amazon.com/ann.jspa?annID=3112) and from [this post](https://forums.aws.amazon.com/thread.jspa?messageID=766896) I understand that `s3-external-1` is no more useful anyway.

**Comment by alexanderdean** [comment]
Thanks

**Comment by alexanderdean** [comment]
Fixed capitalization, please update commit

**Comment by chuwy** [comment]
Done.
