### ISSUE TITLE
Kinesis Elasticsearch Sink: update hocon example with valid app-name

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3147]
This line does not work: https://github.com/snowplow/snowplow/blob/master/4-storage/kinesis-elasticsearch-sink/examples/config.hocon.sample#L81

As `connector` is not a valid key in the hocon!

**Comment by jbeemster** [comment]
This does not seem to work at all anymore ... it appears variable substitution is not working as expected anymore.

**Comment by BenFradet** [comment]
migrated to: snowplow/snowplow-elasticsearch-loader#7
