### ISSUE TITLE
Scala Common Enrich: fix failing WeatherEnrichmentSpec expectation

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3154]
In integration test we were relying on closest timestamp output from OpenWeatherMap. It looks like they optimized historical timestamp from precise `2015-08-29T23:16:14.000Z` to round `2015-08-30T00:00:00.000Z`. We need to fix expectation to conform this change.

This is in some sense critical for R88, because Travis run SCE tests even if SCE itself isn't releasing.

@alexanderdean should it be SCE 0.24.1?

**Comment by alexanderdean** [comment]
Hey @chuwy - can we get away with just a SCE 0.24.1, or do we have to release a SHE too?

**Comment by chuwy** [comment]
Luckily, just SCE.

**Comment by alexanderdean** [comment]
Cool, let's schedule into R88, update CHANGELOG etc. Thanks!
