### ISSUE TITLE
Scala Common Enrich: bump to 0.24.1

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3155]
This is ad-hoc release for #3154. Could be not included in client apps (SHE or SHS).

**Comment by alexanderdean** [comment]
> Could be not included anywhere

Can't parse this statement - it's going into R88?

**Comment by chuwy** [comment]
@alexanderdean I meant apps such as Scala Hadoop Enrich and Scala Hadoop Shred.

**Comment by alexanderdean** [comment]
Ah right - so yes you mean "Snowplow apps are not yet including this version"

**Comment by chuwy** [comment]
Right. And actually they could never include it.

**Comment by alexanderdean** [comment]
> And actually they could never include it.

How come?

**Comment by alexanderdean** [comment]
Of course, thanks

**Comment by chuwy** [comment]
Sorry for confusion.
