### ISSUE TITLE
Update Javascript tracker documentation for trackSelfDescribingEvent

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3156]
On the [General parameters for the Javascript](https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker) wiki page there are a few instances that refer to `trackSelfdescribingEvent` rather than `trackSelfDescribingEvent`.

**Comment by chuwy** [comment]
Thanks @miike. Fixed.
