### ISSUE TITLE
Event Manifest Populator: add Spark job to backpopulate DynamoDB duplicate storage

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3158]
@alexanderdean could you remind me how we decided to call it? Duplicate manifest populator or ...?

**Comment by alexanderdean** [comment]
I think it was event-manifest-populator ?

**Comment by alexanderdean** [comment]
Updated the ticket name, please update the commit!

**Comment by vceron** [comment]
I have a question for you @alexanderdean & @chuwy . Why a lifespan of 6 months has been set?  Is it possible to modify this parameter in a recent release ? 
It's been 4 days since my DynamoDB table has been created in order to enable cross-batch de-duplication and these are my numbers : 
- Storage size (in bytes) | 2.00 
- Item count | 18,495,836

**Comment by chuwy** [comment]
Hey @vceron, we did analysis during QA on few our pipelines which showed us that most of natural duplicates are grouped within 3-6 months - increasing span wouldn't give us much better de-duplication results, at the same time it looked like reducing it doesn't save us much at AWS costs (if your item count doesn't imply manifest populator's count then we were probably wrong). Anyway - we cannot confgiure it right now and I'm 100% agree this is a good idea to make it configurable, please feel free to create an issue in [RDB Loader repo](https://github.com/snowplow/snowplow-rdb-loader/) (which is a new home for Redshift-specific part of pipeline).

**Comment by chuwy** [comment]
I afraid that if you're really concerned about manifest's size then only one possible solution is to tweak the value in [source code](https://github.com/snowplow/snowplow-rdb-loader/blob/master/shredder/src/main/scala/com.snowplowanalytics.snowplow.storage/spark/DuplicateStorage.scala#L187) and use your own asset.

**Comment by vceron** [comment]
Manifest ? Do you mean, in Redshift ? 
Not, this number comes from the table details in DynamoDB.

**Comment by chuwy** [comment]
No, I meant DynamoDB table. We call it "Event Manifest". Sorry for confusion.

**Comment by vceron** [comment]
No, I didn't use the [Event Manifest Populator](https://github.com/snowplow/snowplow/tree/master/5-data-modeling/event-manifest-populator), all these items are from a fresh table (today I already have 33M items for ~3.5GB).

Here is the relate issue : https://github.com/snowplow/snowplow-rdb-loader/issues/84

**Comment by vceron** [comment]
Is there a wiki page which explains how to build our own hadoop_shred  @chuwy ? 
And I guess that all asset are taken from the same bucket (s3.bucket.assets), isn't it ?

**Comment by chuwy** [comment]
@vceron yes, you should be able to use vagrant as per our short [quickstart guide](https://github.com/snowplow/snowplow#quickstart). 

```shell
 host$ git clone https://github.com/snowplow/snowplow.git
 host$ cd snowplow
 host$ git checkout r88-angkor-wat
 host$ vagrant up && vagrant ssh
guest$ cd /vagrant/3-enrich/scala-hadoop-shred
guest$ sbt assmebly
```

Last command will provide you an asset in `scala-hadoop-shred/target/scala-2.10/`. You'll have to upload this asset to your own `s3.bucket.assets`. This bucket should also contain `scala-hadoop-enrich` and mimic our own hosted assets structure (`aws s3 ls s3://snowplow-hosted-assets/`).
