### ISSUE TITLE
Stream Enrich: add ability to force re-download IP lookup databases on reboot

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3159]
At the moment simply replacing Maxmind files in S3 does not result in an update to the local files as they are aggressively cached.  It could be a nice idea to add a CLI argument that would force a refresh of the files - or that would at least check remote against local to see if an update has occurred.

https://github.com/snowplow/snowplow/blob/master/3-enrich/stream-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/kinesis/KinesisEnrichApp.scala#L149-L175

cc/ @alexanderdean

**Comment by alexanderdean** [comment]
Ouch, scheduling

**Comment by alexanderdean** [comment]
Can you define what you mean by "aggressively cached" Josh?

**Comment by jbeemster** [comment]
Meaning that even after rebooting it is still cached.  It is cached to disk rather than in-memory.

**Comment by christoph-buente** [comment]
Maybe it's a good idea to make a config option available, that would invalidate the cached files based on time. For example a TTL in seconds. We are subscribed to the professional Maxmind service, which allow us to download a fresh file every other day. Right now we are forced to overwrite the cached files and restart the service. Would love to have something more convenient.

**Comment by ludwigm** [comment]
We also have a professional subscription and figured now that it caches and basically ignores updated files in S3. It was not totally obvious and would be great if this is added to the docs or even better a periodic check to S3 is added. We are for now cleaning the local files and restart the service to always have up to date data

**Comment by BenFradet** [comment]
Logged #3407 as a spin-off since enforcing a time to live on a file being used in an always on application is not trivial.
