### ISSUE TITLE
Scala Common Enrich: update CallRail Adapter to emit call_complete event version 1-0-3

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3164]
Depends on https://github.com/snowplow/iglu-central/issues/516

Although technically this should be treated as part of the [Blocked schemas](https://github.com/snowplow/snowplow/milestone/79) milestone, we should make an exception because the Callrail webhook is emitting events which fail validation currently...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/68
