### ISSUE TITLE
Scala Common Enrich: enrichment to expunge sensitive data using the Data Loss Prevention API

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3167]
We are seeing more frequent examples in the forums of users needing to expunge sensitive data that has been accidentally captured by Snowplow, for example by un-restricted use of the automatic form capture capabilities in the JavaScript Tracker.

It would be nice to add an enrichment which uses GCP's [Data Loss Prevention API](https://cloud.google.com/dlp/docs/) to check either all JSONs or properties within JSONs which have been flagged as potentially sensitive, and automatically expunge them if they pass a certain sensitive data threshold...

**Comment by alexanderdean** [comment]
An alternative idea here could be to write a dedicated Flink/Dataflow job which uses the API to inspect a sample of events and fire an alert if PII spotted. So it becomes more of an out-of-band detection process, rather than jumping to automatic expunging (which is difficult to get right).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/69
