### ISSUE TITLE
Declaring window.snowplow before script load

### ISSUE THREAD

**Issue by liamtarpey** [snowplow/snowplow#3169]
Hi there, 

We are integrating Snowplow with our JS app by waiting for the page load before initialising the asynchronous script - to ensure all of our content is loaded before loading any third party scripts - this is something we've done with other trackers successfully. 
We would use something like the below:

```
const loadSnowplow = () => { 
   //snowplow init script here
}

window.addEventListener('load', loadSnowplow);
```

Unfortunately with this approach, occasionally we try to send custom events before the script has finished loading which obviously throw errors. We would like to queue up the events in an empty array until Snowplow gets loaded which then sends all the queued events.

The way we have solved this with other trackers and their recommendations was to declare the namespace before the event listener even fires to ensure it's always attached to the window.

The below code creates problems as the `if(!p[i])` conditional statement in your code gets ignored as the scripts already assumes that the snowplow method is already loaded on the window - which is currently just an empty array rather than a function. 

```
const loadSnowplow = () => {
     ;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
     p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
     };p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
     n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d1fc8wv8zag5ca.cloudfront.net/2.7.2/sp.js",'snowplow'));

    window.snowplow('trackPageView');
};

window['snowplow'] = window['snowplow'] || [];
window.addEventListener('load', loadSnowplow);
```

Do you have any solutions for this that don't require modifying your script?

**Comment by alexanderdean** [comment]
Hi @liamtarpey - I'm assigning this to Anton for his thoughts.

**Comment by liamtarpey** [comment]
Hi @alexanderdean & @chuwy 

I've been deconstructing your snippet to try to understand it better.

From what I understand the script is doing two main things:

1. Creating a function `q` on `window.snowplow` which stores queued events until the script is loaded
2. Creating a script tag which injects the snowplow script

Without having to rewrite much of your script, the below solution would work for us:

```
const loadSnowplow = () => {
        ;(function(p,l,o,w,i,n,g){n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
        n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d1fc8wv8zag5ca.cloudfront.net/2.7.2/sp.js","snowplow"));
};

const attachSnowplow = () => {
  if(!window['snowplow']) {
    window.GlobalSnowplowNamespace = window.GlobalSnowplowNamespace || [];
    window.GlobalSnowplowNamespace.push('snowplow');
    window['snowplow'] = function() {
    ( window['snowplow'].q = window['snowplow'].q || []).push(arguments)
  };
  window['snowplow'].q = window['snowplow'].q || [];
}

attachSnowplow();
window.addEventListener('load', loadSnowplow);
```

Can you foresee any issues with us using this method?

**Comment by chuwy** [comment]
Hello @liamtarpey. This indeed an interesting approach and I don't foresee any issues with splitting init script. In the end it repeats all same actions as far as I can see. You can even shorten `loadSnowplow` further. If you have more questions about what is in init tag - [here's prettified version](https://github.com/snowplow/snowplow-javascript-tracker/blob/master/tags/tag.js).

I'm closing this as it's not an issue. If you have any questions - please post on https://discourse.snowplowanalytics.com or file an issue on dedicated JS tracker repository: https://github.com/snowplow/snowplow-javascript-tracker/issues

**Comment by liamtarpey** [comment]
Thanks @chuwy much appreciated :)
