### ISSUE TITLE
Using EmrEtlRunner to process the archive bucket works for S3DistCp but fails on the subsequent ETL step

### ISSUE THREAD

**Issue by rgabo** [snowplow/snowplow#317]
We have 500k+ logfiles in our archive bucket so `--process-bucket s3n://snowplow-archive/logs/` sounds like a great idea and S3DistCp seems to do its job nicely, picking up the files from the datestamped folders, but subsequently the Hadoop ETL job fails:

> 2013-08-09 21:22:37,017 ERROR org.apache.hadoop.security.UserGroupInformation (pool-1-thread-2): PriviledgedActionException as:hadoop cause:java.io.IOException: Not a file: hdfs://10.159.55.19:9000/local/snowplow-logs/2013-05-09

Even though there were logs rolled up for that day. Quite hard to troubleshoot this at this point, but being able to process my archive bucket would save us about a million S3 requests and an enormous amount of time.

`--process-bucket s3n://snowplow-archive/logs/2013-05-09/` works as expected.

**Comment by alexanderdean** [comment]
Closing, this ticket has been superceded by events
