### ISSUE TITLE
Redshift, canonical event schema and documentation issue

### ISSUE THREAD

**Issue by faltad** [snowplow/snowplow#3171]
Hello,

We are currently planning to use the canonical event model as described [in the documentation](https://github.com/snowplow/snowplow/wiki/canonical-event-model).
However, there is this line that is a bit confusing:

> The field joined on is the distribution and sort key for both tables, so queries are as fast as if the data were in a single table

Which conflicts a bit with the schema proposed [here](https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/atomic-def.sql) which gives a SORTKEY on the collector_tstamp (and which does make sense) and not the event_id.
So is a SORTKEY better on the collector_tstamp or on the event_id (in the atomic.events table)?

**Comment by alexanderdean** [comment]
Thanks, updated the documentation, closing!
