### ISSUE TITLE
Stream Collector: fix incorrect property used for kafkaProducer.batch.size

### ISSUE THREAD

**Issue by jatinder85** [snowplow/snowplow#3173]
## KafkaSink: Incorrect config property being set for producer
Incorrect config key "buffer.byte-limit" is used to set kafkaProducer.batch.size instead it should be "buffer.record-limit" config key

 See here: https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/sinks/KafkaSink.scala#L60

## Separate kinesis and Kafka buffer object
Also it would be better to separate config property keys for kinesis and kafka instead of shared "buffer" object as it is confusing.  And would be great to have an option to set dynamic kafka properties through the config. Thoughts?

**Comment by alexanderdean** [comment]
Hi @jatinder85 - I've renamed the ticket to report on your first issue.

Why is it confusing using the same buffer object for Kinesis and Kafka? The semantics of Kinesis and Kafka are near identical.

**Comment by jatinder85** [comment]
Hi @alexanderdean ok sounds good. I can submit PR, is there any dev docs on submitting PRs?

Yeah nvm the buffer semantics are identical.

**Comment by alexanderdean** [comment]
Thanks - a PR would be great! (No special magic to contributing a PR to Snowplow)

**Comment by jatinder85** [comment]
Ok cool. Here u go: #3177
