### ISSUE TITLE
Kinesis Elasticsearch Sink: Invalid app-name causes strange errors

### ISSUE THREAD

**Issue by mrwacky42** [snowplow/snowplow#3174]
While attempting to set up the Elastic sink, I was getting errors when it attempted to create the DynamoDB table.

```
[main] DEBUG com.amazonaws.request - Received error response: com.amazonaws.AmazonServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/
[SNIP]
```

After much hand-wringing, and hair pulling, I noticed my configuration specified the `app-name` with a leading space.
The app-name should be validated before passing to AWS.

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow/snowplow-elasticsearch-loader#5
