### ISSUE TITLE
EMR shred step failed with exitCode -1

### ISSUE THREAD

**Issue by tyomo4ka** [snowplow/snowplow#3175]
My EMR job failed this morning (was successfully run since last week).
This is what I found in controller log:

```
2017-03-29T19:48:32.155Z WARN Step failed with exitCode -1 and took 2586 seconds
```

stderr and stdout logs are empty and syslog has nothing interesting.
Could you please help to understand the meaning of exitCode -1?

**Comment by alexanderdean** [comment]
Hey @tyomo4ka - please can you direct support requests to our community forums:

http://discourse.snowplowanalytics.com/

**Comment by tyomo4ka** [comment]
@alexanderdean

Ok. Thanks!

Asked there http://discourse.snowplowanalytics.com/t/emr-shred-step-failed-with-exitcode-1/1090
