### ISSUE TITLE
RDB Loader: remove compupdate step

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3178]
Was added in https://github.com/snowplow/snowplow/issues/344 and never worked.

* It has a [typo](https://github.com/snowplow/snowplow/commit/2fd264a1f13f34b7335dc59dcc9fb258dff35fea#diff-2e84d58a69028d91fd9fbddea1abaec5R33) in CLI parameter - compudate instead of compu**p**date (and CLI parser rejects `compudate`)
* It expects `comprows` to be a CLI option, but we insert it as target configuration parameter

**Comment by chuwy** [comment]
@alexanderdean do we want to put it into R88?

**Comment by alexanderdean** [comment]
No, R88 is locked for release now. We should consider what to do with compupdate going forwards (a discretionary CLI argument doesn't make much sense once StorageLoader moves to EMR).

**Comment by chuwy** [comment]
Renamed ticket as we didn't ever use compupdate.
