### ISSUE TITLE
Documentation: Update JS instructions to reflect latest version of tracker

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3180]
The setup here https://github.com/snowplow/snowplow/wiki/Self-hosting-snowplow-js refers to using version 2.5.1. Could we update this to point to the 2.7.2 on Cloudfront?

**Comment by alexanderdean** [comment]
Thanks @miike , assigning to Ihor

**Comment by ihortom** [comment]
Done

**Comment by alexanderdean** [comment]
Thanks @ihortom
