### ISSUE TITLE
Fix example of how snowplow_name_here works

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplow#3181]
In the [wiki](https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#21-loading-snowplowjs) it says:

> For example, the method trackStructEvent has this signature:

> `function trackStructEvent(category, action, label, property, value, context)`

> where only the first two arguments are required. You would use it like this:

> `snowplow_name_here('trackStructEvent', 'Mixes', 'Play', '', '', 20);`

> Empty strings are provided for the **label** and **value** arguments to pad them out. (Null would also work.) They won't be added to the event. Neither will the context argument, which isn't provided at all.

Shouldn't that be: "(...) the **label** and **property** arguments (...)"?

**Comment by alexanderdean** [comment]
Thanks @dilyand , assigning

**Comment by ihortom** [comment]
Fixed
