### ISSUE TITLE
Stream Enrich can not read Scala Collector Thrift data / Parsing error

### ISSUE THREAD

**Issue by halilduygulu** [snowplow/snowplow#3183]
Hello, 
Thanks for Snowplow, it is a good product.
I installed js tracker and scala collector and that part works fine. Then i tried to process collector kinesis stream with scala stream enrich application, i tried both 0.9.0 and 0.10.0 versions of enrich. But it can not parse incoming data and gives the error below. I only passed this error once and the data went to enrich-bad-stream of kinesis then i continued with this error again. I looked for the exception online but could not find a solution.

My environment is aws linux, t2.small. And i run both enrich and collector on same instance, i tried seperate instances but it did not changed anything. Also data is streamed on kinesis.

I run the enrich with this command, even without an enrichment to be sure that doesn't cause error. Resolver is same as the one in repository.
`./snowplow-stream-enrich-0.9.0 --config snowplow.scala.enrich.conf --resolver file:iglu_resolver.json`
`./snowplow-stream-collector-0.9.0 --config snowplow.scala.collector.config`

```
[pool-2-thread-1] INFO com.snowplowanalytics.snowplow.enrich.kinesis.sources.KinesisSource - Processing 1 records from shardId-000000000000
{
   "line": "MY_DATA_AS_BASE64_ENCODED_HERE",
   "errors": [{
      "level": "error",
      "message": "error: object has missing required properties ([\"schema\"])\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"/items\"}\n    instance: {\"pointer\":\"/1\"}\n    domain: \"validation\"\n    keyword: \"required\"\n    required: [\"data\",\"schema\"]\n    missing: [\"schema\"]\n"
   }],
   "failure_tstamp": "2017-03-31T12:15:52.986Z"
}
```

So i changed my usage and converted collector output thrift data to json and currenly using it that way but as i read enrichment options are great, ready to use solutions for common requirements, i really want to use enrichment.
Thank you.

**Comment by alexanderdean** [comment]
Hi @halilduygulu - can you use the forum for support questions like this:

http://discourse.snowplowanalytics.com/
