### ISSUE TITLE
Scala Common Enrich: IPv6 support

### ISSUE THREAD

**Issue by dominikschulz** [snowplow/snowplow#3185]
Since AWS CloudFront supports IPv6 for some time we'd like to turn on IPv6 on our CloudFront collector.

Unfortunately the Snowplow wiki doesn't clearly state if this is supported or not. It still says that IPv6 is not support on CF which is not true anymore.

Furthermore we're using the GeoIP Enrichtment. Looking at Code I get the impression that it doesn't support IPv6, yet.

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/IpLookupsEnrichment.scala#L143

Since Scala is not my home turf I may be wrong, AFAIK MaxMind offers seperate databases for IPv4 and IPv6 and the IpLookup enrichment does only seem to support on database at a time.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/72
