### ISSUE TITLE
Missing build.sbt?

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#3186]
Is that intended that there are no `build.sbt`?... for the folders

- scala-stream-collector
- scala-common-enrich
- scala-hadoop-enrich
- scala-hadoop-shred
- stream-enrich 

That would make it way easier to use IntelliJ to edit project, in order to resolve dependencies and build indexes.

**Comment by chuwy** [comment]
Hi @simplesteph,

Yes we used old so called [Build.scala](https://www.safaribooksonline.com/library/view/scala-cookbook/9781449340292/ch18s17.html) SBT syntax. You can find definitions in [project](https://github.com/snowplow/snowplow/tree/master/3-enrich/scala-common-enrich/project) directories. And Intellij IDEA should handle these without problems (at least it does for me).

Anyway, Build.scala has been deprecated some time ago and we're switching to build.sbt: https://github.com/snowplow/snowplow/issues/3056, https://github.com/snowplow/snowplow/issues/2972

**Comment by simplesteph** [comment]
Hi @chuwy . Yup it works when I open the subfolder with intellij, but not if I open the top level, so I guess that's an IntelliJ limitation.

**Comment by chuwy** [comment]
@simplesteph by top level do you `snowplow` repository itself? In that case, yes it doesn't work and I suppose it wouldn't even with `build.sbt`. And that's for purpose. `snowplow/snowplow` is a monorepo with different projects, many of them are not even Scala, so it wouldn't make much sense to provide single build definition.
