### ISSUE TITLE
Kafka: Optionally Support Avro Schema schema

### ISSUE THREAD

**Issue by simplesteph** [snowplow/snowplow#3187]
Currently, the data written to Kafka is in the Thrift format, which is not the accepted standard in Kafka. We should provide the option to leverage the Schema Registry https://github.com/confluentinc/schema-registry and write the data in Avro format. 

This will make Snowplow Kafka options AWESOME

**Comment by alexanderdean** [comment]
Great discussion topic! Please migrate to our Discourse:

http://discourse.snowplowanalytics.com/

**Comment by simplesteph** [comment]
done
