### ISSUE TITLE
Documentation: add warning about changing the cookie domain in the Javascript tracker

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplow#3190]
Changing the cookie domain in the Javascript tracker can be a disruptive change. Our users should be aware that this will reset the `domain_userid` and session information.

**Comment by alexanderdean** [comment]
Assigned to @ihortom

**Comment by ihortom** [comment]
Done.

https://github.com/snowplow/snowplow/wiki/1-General-parameters-for-the-Javascript-tracker#223-configuring-the-cookie-domain
