### ISSUE TITLE
Stream Enrich: customize useragent for GCP API calls

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3193]
```
Suggested format

"<prod_name>/ver (GPN:<company name>; <other comments>) <other prod>/ver "*

Example

"Product_A/1.1 (GPN:Partner_ABC; staging) Product_B/1.3

Google­HTTP­Java­Client/1.20.0"

*User Agent compliance with RFC

(http://tools.ietf.org/html/rfc7231#section­5.5.3)
```

**Comment by BenFradet** [comment]
@alexanderdean what's the story behind this?

**Comment by alexanderdean** [comment]
Oh hey @BenFradet. This is an interesting one. There's some kind of mechanism in the GCP SDKs to customize the useragent making the API calls. Presumably the purpose of this is so that GCP can understand who are the biggest consumers of the APIs. I don't know what value we should use - but if you can store that as a constant somewhere, we should be able to nail down the value before launch...

**Comment by BenFradet** [comment]
ok :+1:
