### ISSUE TITLE
Hadoop Shred not hosted on S3 (us-east-1)

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow#3202]
@alexanderdean @chuwy I think this is a critical bug. The Shred step on R88 is failing because the path `s3://snowplow-hosted-assets-us-east-1/3-enrich/scala-hadoop-shred/snowplow-hadoop-shred-0.11.0.jar` does not exist. The correct path is `s3://snowplow-hosted-assets/3-enrich/scala-hadoop-shred/snowplow-hadoop-shred-0.11.0.jar`, but this seems to be generated dynamically in the Shred code.

**Comment by alexanderdean** [comment]
Ah thanks for flagging, I am running the manual sync process to copy all of the final assets into each of the region-specific buckets. Should be up within the next 60 mins. Closing...

**Comment by bernardosrulzon** [comment]
Cool, thanks! :)
