### ISSUE TITLE
Postgres support for shredded events

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3204]
Sorry, couldn't find any existing tickets regarding this (except #2475), but pretty sure they exist.

Just wanted to clarify what we need to do to make this happen, since we now considering removing Postgres support from StorageLoader/RDB Loader.

From my point of view, main missing components are:

1. Spark job that takes events and JSON paths and produces TSV. Rough scalaish pseudo-code:

```scala
def convertJsonToTsv(jsonPaths: JsonPath, json: Hierarchy): TSV = ???

def produceTsv(igluResolver: Resolver, json: Hierarchy): TSV = {
  val jsonPaths = igluResolver.fetchJsonPaths(json.schema)
  convertJsonToTsv(jsonPaths, json)
} 
```

2. Notion of JSON Paths in Iglu.
3. Actual RDB Postgres loading code.

@alexanderdean did I miss something?

**Comment by alexanderdean** [comment]
No that's great @chuwy - thanks for capturing this here!

**Comment by chuwy** [comment]
Was raised before in https://github.com/snowplow/snowplow/issues/657 and https://github.com/snowplow/snowplow/issues/658. 

Closing old ones, leaving this one as umbrella-ticket.

**Comment by claudiomartins** [comment]
+1 for Postgres shredding - we extensively use Postgres for all our needs and would help to not have to run another ETL to export data out of Redshift into Postgres.

**Comment by alexanderdean** [comment]
Can we migrate this ticket into the RDB Loader repo @chuwy ?

**Comment by chuwy** [comment]
Moved to https://github.com/snowplow/snowplow-rdb-loader/issues/47, closing this one.
