### ISSUE TITLE
Scala Common Enrich: fix failing WeatherEnrichmentSpec expectation

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3205]

**Comment by chuwy** [comment]
Follow-up for https://github.com/snowplow/snowplow/issues/3154

Hey @BenFradet, can we maybe make date as close to today as possible? Like `2017-05-01T23:56:01.003+00:00`, as current expectation will start to fail within 4 next months.

**Comment by BenFradet** [comment]
true, will do
