### ISSUE TITLE
RDB Shredder: remove AWS Java SDK shading

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3206]
As part of cross-batch deduplication I had to [shade](https://github.com/snowplow/snowplow/commit/48d17a319b982b7052819cedc820efe737ad0451#diff-746e73b85aa50e048fd8cfa0ec596febR38) AWS Java SDK and few associated libraries as they conflicted with AMI 4.5.0 and threw runtime exception.

When we [bump](https://github.com/snowplow/snowplow/commit/5a8edc671140fa0d4676d706e2735cf237790a52#diff-1341b6a17c4adf7a954e2932f4d9b353R28) (https://github.com/snowplow/snowplow/issues/3068) AMI to latest version it could be removed.

**Comment by BenFradet** [comment]
I'll take care of it :+1:

**Comment by chuwy** [comment]
This is invalid. EMR 5.5.0 still provides 1.10.75. Descheduling.

**Comment by BenFradet** [comment]
moved to snowplow/snowplow-rdb-loader#54, closing
