### ISSUE TITLE
EmrEtlRunner: bump AMI version in example config to 5.5.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3207]
If we have to do all this testing, let's bump to the latest AMI at the same time...

**Comment by BenFradet** [comment]
Do you mean in the wiki? because it's already [the case in eer](https://github.com/snowplow/snowplow/pull/3203/files#diff-1341b6a17c4adf7a954e2932f4d9b353R28).

**Comment by alexanderdean** [comment]
Ah great, please split out into a dedicated commit to map onto this ticket...
