### ISSUE TITLE
Remove broken links from wiki

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3208]
@stdfalse is tracking pages that have broken links where the linked content no longer exists:

* [ ] xxx
* [ ] xxx

**Comment by stdfalse** [comment]
- [ ] [Getting started with data modeling](https://github.com/snowplow/snowplow/wiki/getting-started-with-data-modeling)

  - [ ] http://snowplowanalytics.com/analytics/index.html
  - [ ] http://snowplowanalytics.com/analytics/event-dictionaries-and-data-models/data-modeling.html
  - [ ] https://github.com/snowplow/snowplow/tree/master/5-data-modeling/sql-runner/redshift/ **may be this:** https://github.com/snowplow/snowplow/tree/master/5-data-modeling/web-model/redshift
  - [ ] https://github.com/snowplow/snowplow/tree/master/5-data-modeling/sql-runner/redshift/playbooks/full.yml **may be this:** https://github.com/snowplow/snowplow/blob/master/5-data-modeling/web-model/sql-runner/playbook/web-model.yml.tmpl

**Comment by stdfalse** [comment]
- [ ] [Getting started analyzing Snowplow data](https://github.com/snowplow/snowplow/wiki/getting-started-analyzing-snowplow-data)
  - [ ] http://snowplowanalytics.com/analytics/index.html
  - [ ] https://github.com/snowplow/snowplow/tree/master/5-analytics
  - [ ] https://github.com/snowplow/snowplow/tree/master/5-analytics/redshift
  - [ ] https://github.com/snowplow/snowplow/tree/master/5-analytics/postgresql/recipes

- [ ] [Setting up Looker](Getting-started-with-Looker)
  - [ ] https://github.com/snowplow/snowplow/tree/master/5-analytics/looker-analytics

- [ ] [Setting up ChartIO](Setting-up-ChartIO-to-visualize-your-data)
  - [ ] http://snowplowanalytics.com/analytics/index.html

- [ ] [Setting up Excel to analyze Snowplow data](Setting-up-Excel-to-analyze-Snowplow-data)
  - [ ] http://snowplowanalytics.com/analytics/index.html
  - [ ] http://snowplowanalytics.com/analytics/tools-and-techniques/converting-snowplow-data-into-a-format-suitable-for-olap.html

- [ ] [Setting up Tableau to analyze your Snowplow data](Setting-up-Tableau-to-analyze-your-Snowplow-data)
  - [ ] http://snowplowanalytics.com/analytics/tools-and-techniques/converting-snowplow-data-into-a-format-suitable-for-olap.html#what
  - [ ] http://snowplowanalytics.com/analytics/catalog-analytics/measuring-and-comparing-product-page-performance.html#visualising
  - [ ] http://snowplowanalytics.com/analytics/catalog-analytics/measuring-and-comparing-content-page-performance.html#single-user-journey
  - [ ] http://snowplowanalytics.com/analytics/

- [ ] [Setting up R to perform more sophisticated analysis on your Snowplow data](Setting-up-R-to-perform-more-sophisticated-analysis-on-your-Snowplow-data)
  - [ ] http://snowplowanalytics.com/analytics/index.html
  - [ ] http://snowplowanalytics.com/analytics/tools-and-techniques/get-started-analysing-snowplow-data-with-r.html

- [ ] [Setting up Qubole to analyze Snowplow data using Apache Hive](Setting-up-Qubole-to-analyze-Snowplow-data-using-Apache-Hive)
  - [ ] http://snowplowanalytics.com/analytics/index.html

**Comment by ihortom** [comment]
@alexanderdean - I actually can find some of the old posts on snowplow.github.com in my local repo. Maybe I could place those on wiki and update the references rather than delete them?

**Comment by alexanderdean** [comment]
Chat to @yalisassoon about this @ihortom - Yali is managing the re-housing of old docs off the Snowplow website to new homes...

**Comment by BenFradet** [comment]
moved to docs, closing
