### ISSUE TITLE
Scala Stream Collector: Query params are not passed through with a POST request

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3211]
When a POST request is made url parameters in the query string are not passed through into the CollectorPayload (see [here](https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/CollectorService.scala#L90)).

Some downstream functionality relies on this for example POSTing a payload to the Iglu webhook endpoint while specifying the schema as part of the query string.

To replicate locally run SSC and issue the following request:

```
curl -XPOST -H "Content-Type: application/json" "http://127.0.0.1:8080/com.snowplowanalytics.iglu/v1?schema=test" -d '{
     "x": 1
}'
```

Expected Collector Payload (querystring present)

```
CollectorPayload(networkUserId='xxxx-xxxx-xxxx-xxxx', schema='iglu:com.snowplowanalytics.snowplow/CollectorPayload/thrift/1-0-0', contentType='application/json', encoding='UTF-8', refererUri=None, body='{\n    "x": 1\n}', hostname='127.0.0.1', ipAddress='127.0.0.1', timestamp=1494232796667, collector='ssc-0.9.0-stdout', headers=['Host: 127.0.0.1:8080', 'User-Agent: curl/7.49.0', 'Accept: */*', 'Content-Type: application/json', 'Content-Length: 14'], **querystring='schema=test'**, path='/com.snowplowanalytics.iglu/v1', userAgent='curl/7.49.0')
```

Actual Collector Payload (querystring absent)

```
CollectorPayload(networkUserId='xxxx-xxxx-xxxx-xxxx', schema='iglu:com.snowplowanalytics.snowplow/CollectorPayload/thrift/1-0-0', contentType='application/json', encoding='UTF-8', refererUri=None, body='{\n    "x": 1\n}', hostname='127.0.0.1', ipAddress='127.0.0.1', timestamp=1494232796667, collector='ssc-0.9.0-stdout', headers=['Host: 127.0.0.1:8080', 'User-Agent: curl/7.49.0', 'Accept: */*', 'Content-Type: application/json', 'Content-Length: 14'], querystring=None, path='/com.snowplowanalytics.iglu/v1', userAgent='curl/7.49.0')
```

**Comment by alexanderdean** [comment]
Ouch - that's a nasty bug, scheduling

**Comment by jramos** [comment]
I knew this bug looked familiar... https://github.com/snowplow/snowplow/pull/2685

😄

**Comment by miike** [comment]
@jramos I must have missed that previous issue when searching through the Github issues!

@BenFradet The change to the code here is trivial but I'm struggling to write a test case for it. The tests in `PostSpec` only seem to test for setting cookie values back on the `HttpRequest` object and the actual creation of the payload only seems to be tested by manually constructing a `responseHandler.cookie` object rather than making a POST request. Any thoughts on the best/idiomatic way to do this?

**Comment by BenFradet** [comment]
@miike

The tests seem a bit convoluted I agree.
As is, I don't think there is way to test the created payload since only the http response is sent back in the route.

**Comment by miike** [comment]
In that case it looks like #2685 should solve the issue @jramos

**Comment by BenFradet** [comment]
Closing this one since the commit will close #2685 :+1:
