### ISSUE TITLE
Scala Common Enrich: remove deviceIsMobile column from user-agent-utils enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3215]
It is deprecated and derived from `deviceType == "MOBILE"`, so effectively useless.

This probably is far-away ticket that depends on https://github.com/snowplow/snowplow/issues/1899, https://github.com/snowplow/snowplow/issues/1900, https://github.com/snowplow/snowplow/issues/1901 or maybe we'll want to exclude this enrichment at all as library is no [longer maintained](http://www.bitwalker.eu/blog/user-agent-utils-1-20-final-release).

**Comment by BenFradet** [comment]
closing, enrichment is to be removed.
