### ISSUE TITLE
Publish scala-common-enrich and scala-hadoop-shred

### ISSUE THREAD

**Issue by jramos** [snowplow/snowplow#3231]
Can you publish `scala-common-enrich` and `scala-hadoop-shred` to Maven? We use both in our custom Redshift sink, and it would be nice to not have to compile them locally.

**Comment by alexanderdean** [comment]
No plans to extract a library from Scala Hadoop/Spark Shred, but yes Common Enrich is coming to Maven Central soon, assigning to @BenFradet to clarify...

**Comment by jramos** [comment]
👍

**Comment by BenFradet** [comment]
As Alex said, the next version of scala-common-enrich (0.25.0) will be on maven central.

However, I don't think it makes sense to have the final applications (spark enrich or scala-hadoop-shred for example) in maven central.

However, if you don't want to have to compile those locally you can download them from s3:

```bash
aws s3 cp \
  s3://snowplow-hosted-assets/3-enrich/scala-hadoop-shred/snowplow-hadoop-shred-0.10.0.jar \
  .
```
