### ISSUE TITLE
StorageLoader: fix always skipped download in Postgres load

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3237]
See http://discourse.snowplowanalytics.com/t/postgres-storage-download-skips-variable-name-issue/1197/2

There's a typo in config accessor. Should be `config[:download_required]` instead of `config[:storage][:download_required]`.

**Comment by alexanderdean** [comment]
This is StorageLoader, not EER no?

**Comment by chuwy** [comment]
You're right.

**Comment by chuwy** [comment]
Closing, was fixed in RDB Loader.
