### ISSUE TITLE
[Spark?] Shred: events being silently dropped during shredding

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3244]
See http://discourse.snowplowanalytics.com/t/how-to-debug-shredding-process/1218/3

**Comment by mrosack** [comment]
Attaching example enriched events here since I couldn't on the forum and I'm probably going to delete that bucket: [part-00001.gz](https://github.com/snowplow/snowplow/files/1064241/part-00001.gz)

**Comment by alexanderdean** [comment]
De-scheduling
