### ISSUE TITLE
Scala Common Enrich: support per-request IP anonymization

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3248]
Similar to Google Analytics:

https://support.google.com/analytics/answer/2763052?hl=en

Depends on an update to the Snowplow Tracker Protocol, and tracker support such as https://github.com/snowplow/snowplow-javascript-tracker/issues/586

**Comment by alexanderdean** [comment]
We would be effectively extending the IP anonymization enrichment.

**Comment by alexanderdean** [comment]
We need to push this back as it is dependent on a change to the Tracker Protocol, which will need further thought.

**Comment by alexanderdean** [comment]
We don't need to update the Tracker Protocol - we can just add a self-describing context to each event flagging the IP anonymization.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/73
