### ISSUE TITLE
Scala Stream Collector: certain reserved characters result in a 400 response

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3272]
At the moment certain reserved characters (such as `=`) when passed in a URL param result in a 400 currently from the collector. Other reserved characters such as `&`, `$` and `@` do not.

Ideally these characters should be urlencoded however in some limited environments where there may be restricted variable substitution (e.g., email platforms) it may be required to pass this data through. Snowplow should accept this data in raw form.

Example:
where user_id is the product of ```base64("test")```
```curl -XGET http://localhos:8080/i?e=pv&uid=dGVzdA==```
should return a 200 rather than a 400.

In addition the current setting for `uri-parsing-mode` in [config.hocon](https://raw.githubusercontent.com/snowplow/snowplow/master/2-collectors/scala-stream-collector/examples/config.hocon.sample) sits under spray.can.server whereas it should sit under spray.can.server.parsing according to [reference.conf](https://github.com/spray/spray/blob/master/spray-can/src/main/resources/reference.conf). I'm not certain on the behaviour of Spray but if it isn't currently picking up the setting in `config.hocon` due to the path then it may use the default value of strict.

**Comment by BenFradet** [comment]
closing this one since the commit in the PR is part of #3274 :+1:
