### ISSUE TITLE
Storage: replace example Redshift storage target configuration with 2-0-0

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3281]
With new `roleArn` property.

https://github.com/snowplow/iglu-central/issues/616

**Comment by alexanderdean** [comment]
1-1-0 or 2-0-0 @chuwy ?

**Comment by chuwy** [comment]
2-0-0!

**Comment by alexanderdean** [comment]
Cool, is this the last ticket in the release?

**Comment by chuwy** [comment]
Yes, but I want to fix https://github.com/snowplow/snowplow/issues/3322 as part of https://github.com/snowplow/snowplow/issues/3242. I'm double-checking everything right now.
