### ISSUE TITLE
104 expectations, 0 failure, 0 error

### ISSUE THREAD

**Issue by shashi4414** [snowplow/snowplow#3284]
hello 

   >sbt test
when I try to run this command I got  exception .
[info] 5 examples, 104 expectations, 0 failure, 0 error
[error] Failed: Total 285, Failed 1, Errors 0, Passed 270, Skipped 14
[error] Failed tests:
[error]         com.snowplowanalytics.snowplow.enrich.common.enrichments.ExtractEventTypeSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 32 s, completed 7 Jul, 2017 5:01:55 PM

**Comment by alexanderdean** [comment]
Please raise support questions on the forum:

http://discourse.snowplowanalytics.com/
