### ISSUE TITLE
Wiki outdated on views recipes

### ISSUE THREAD

**Issue by joshuacox** [snowplow/snowplow#3286]
This [page](https://github.com/snowplow/snowplow/tree/master/5-analytics/postgresql/recipes) has this block:
```
Now that you've created your atomic.events table, you're in a position to the different views. This can also be done at the command line:

$ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f recipes/recipes-basic.sql
$ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f recipes/recipes-catalog.sql
$ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f recipes/recipes-customers.sql
```

which is in reference to [this](https://github.com/snowplow/snowplow/tree/master/5-analytics/postgresql/recipes), but it no longer exists.

What is the current method of creating those views?  Should I begin with by hunting down those sql files in the git history, or has this morphed into some equivalent [here?](https://github.com/snowplow/snowplow/tree/master/5-data-modeling/web-model/redshift/sql)

**Comment by bogaert** [comment]
Hi @joshuacox,

I get a 404 when I go to this [page](https://github.com/snowplow/snowplow/tree/master/5-analytics/postgresql/recipes). Is it possible you meant to post a different link?

In any case, those views were removed in an earlier version of Snowplow. The recipes themselves were quite basic and no longer in line we how we think about event analytics. Instead, we have put our effort into developing much more powerful and useful event data models (like the one you linked to).

You can still find the original SQL queries in this post on Discourse: http://discourse.snowplowanalytics.com/t/basic-sql-recipes-for-web-data/25

For more information on event data modeling, check out this post: http://discourse.snowplowanalytics.com/t/what-is-event-data-modeling/56

Hope this helps!

**Comment by joshuacox** [comment]
sorry I must've pasted the wrong link

@bogaert I think this section of the wiki needs to be changed which still references the `recipes`:

```
282 [[/images/warning.png]] | Note we are working on new data models and recipes that are more specific than we currently have. They will make use of all our latest features and enhancements.
283 ---|:---
284 
285 First, let's create the `atomic.events` table, where the actual Snowplow data will live. The SQL for creating the atomic schema and table can be found [here][postgres-table-def]. Either copy and paste that SQL into PSQL / Navicat, or      you can run that file into PSQL at the command line. To do this, navigate to your Snowplow repo, then:
286 
287   $ cd 4-storage/postgres-storage/sql
288   $ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f atomic-def.sql
289 
290 You'll need to substitute in your credentials for `<HOSTNAME>` and `<PORT>`. Make sure you use the `power_user` credentials to create new tables etc.
291 
292 Now that you've created your `atomic.events` table, you're in a position to the different views. This can also be done at the command line:
293 
294   $ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f recipes/recipes-basic.sql
295   $ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f recipes/recipes-catalog.sql
296   $ psql -h <HOSTNAME> -U power_user -d snowplow -p <PORT> -f recipes/recipes-customers.sql
297 
298 Finally, you need to grant access relevant access permissions to your different users to the different tables and views.
```
--- snowplow.wiki/setup-guide/4-setup-alternative-data-stores/postgres/Setting-up-PostgreSQL.md

**Comment by joshuacox** [comment]
@bogaert of note I do not  believe the links you posted answer this question. 
 
The links you posted show how to query an existing database, whereas that section of the wiki is about creating the different views, and those sql files are not there.

**Comment by bogaert** [comment]
Thanks! I have updated that section of the wiki to remove all references to the old recipes.

If you prefer, the views can be recreated the views by simply wrapping the queries in a `CREATE VIEW` statement. If you have any other questions about the views themselves or data models, please post them on our [Discourse](http://discourse.snowplowanalytics.com/). Thanks :)

**Comment by alexanderdean** [comment]
Can this be closed now?
