### ISSUE TITLE
Placeholder for improving Spark-S3 interactions

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3287]
Reading:

* https://www.slideshare.net/SparkSummit/spark-and-object-stores-what-you-need-to-know-spark-summit-east-talk-by-steve-loughran
* https://medium.com/@subhojit20_27731/apache-spark-and-amazon-s3-gotchas-and-best-practices-a767242f3d98
* http://arnon.me/2015/08/spark-parquet-s3/

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/75
