### ISSUE TITLE
Add git submodule for web data model

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3289]
Title was "Move data modeling "bundles" out into separate repos?"

This would be consistent with what we are doing with storage loaders currently.

The advantages:

* It lets the Analytics team wholly own the data modeling process
* It makes data models more prominent within Snowplow
* It lets the data models evolve at their own pace versus Snowplow core

**Comment by bogaert** [comment]
Sounds good. I'll schedule this in.

**Comment by bogaert** [comment]
How would we go about this?

- Do we need a "release" to take data modeling out of Snowplow core?
- Do we want a single "data modeling" repo or one per model? I'd start with one repo.

**Comment by alexanderdean** [comment]
> Do we need a "release" to take data modeling out of Snowplow core?

Yes, when we move things out we try to move out, announce the new release in its own repo, then the next snowplow/snowplow release removes the legacy content.

> Do we want a single "data modeling" repo or one per model? I'd start with one repo.

I would go one repo per data modeling bundle (SQL, metadata, Looker bindings etc). Just because that is the unit of release...

**Comment by bogaert** [comment]
Sounds good. Will get this process started.

**Comment by paulboocock** [comment]
Ah good spot, I didn't realise we hadn't included the new repo here 👍
