### ISSUE TITLE
Explore ways to manifest pipeline steps

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3290]
Lack of this feature becomes prevalent while we're adding new custom storage targets and data-modeling using Analytics SDKs. Also, this can be a solution for [recovering complex pipelines](http://discourse.snowplowanalytics.com/t/recover-from-emr-failures-with-deduplication/1225/6) and more general solution than Run Manifests presented in Analytics SDKs.

We need a reliable and general way to claim that some step of DAG has particular state and exchange this knowledge between parts of pipeline that require this knowledge.

I think this feature can be part not only Snowplow (EER, snowplowctl), but also more general tools such as dataflow-runner or factotum.

Here's roughly estimated amount of information that we need in RDB Shredder deduplication to understand that it re-processes folder.

```
[{
  "step": "staging",
  "id": "08838EDD-F734-431E-9421-7CCD7AAD61AB"
  "state": {
    "name": "started",
    "timestamp": "1499838451"
  },
  "options": {     // Content is based on step
    "src": "s3://acme-snowplow-eu-west-2/processing/",
    "dest": "s3://acme-snowplow-eu-west-2/archive/raw/run=2017-07-11-12-42-40/"
  }
},
...
{
  "step": "shred",
  "id": "0737AD20-A9AD-4375-AA72-26C4818F59B3",
  "state": {
    "name": "failed”",
    "timestamp": "1499838451"
  }
}]
```

It is up to deduplication process to parse this, fetch DAGs where shred step was started and failed, extract `etl_tstamp` from staging step and understand that this `etl_tstamp` should be treated differently.

I really think this data should be unstructured and it is up to consumer to understand it as all our steps have very different contents and semantics. For example, some steps such as RDB Loader can add their own specific (specific to target!) sub-steps: `Discover`, `Load`, `Analyze`.

**Comment by alexanderdean** [comment]
Thanks @chuwy - I think you are thinking about the underlying problem in exactly the right way. I am thinking on this issue a lot this week - look forward to brainstorming some different approaches next week.

**Comment by alexanderdean** [comment]
I think this is neat but general DAG concepts are out of scope of Snowplow (tho see e.g. OpenLineage), and likely less relevant as we moved to full-real time.
