### ISSUE TITLE
Event Manifest Populator: support pre-R83 enriched events

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3293]
According to https://github.com/snowplow/snowplow/issues/2679 until R83 we dumped enriched files with `.gzip` extension, which is not recognized by Spark and therefore EMP, it fails with cryptic exception and effectively cannot load dupe-storage with pre-R83 events.

**Comment by alexanderdean** [comment]
Ah yes - this is why we changed the file extension (for Spark support).

What are our options here?

**Comment by chuwy** [comment]
Don't know yet, I just discovered this problem.

I'll try to search for workarounds inside Spark. Otherwise I see just batch-rename for dedupe.

**Comment by chuwy** [comment]
I think this can be used as solution inside Spark https://medium.com/@samuelboyd/spark-reading-gzipped-files-from-s3-without-the-gz-extension-58cc78e6a09d

Will test it now.

**Comment by chuwy** [comment]
Ok. Fix worked. 

@alexanderdean do you agree this should go into upcoming R90 release as 0.1.1?

**Comment by alexanderdean** [comment]
Yes agree
