### ISSUE TITLE
Spark Shred: explore auto scaling for duplicate storage

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3296]
AWS recently introduced [auto scaling](https://aws.amazon.com/ru/blogs/aws/new-auto-scaling-for-amazon-dynamodb/) for DynamoDB. 

> DynamoDB Auto Scaling is designed to accommodate request rates that vary in a somewhat predictable, generally periodic fashion.

> You can decrease capacity up to nine times per day for each table 

I believe above fully conforms our usage-pattern.

**Comment by alexanderdean** [comment]
I saw this in the UI recently too - definitely worth exploring...

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/125, closing
