### ISSUE TITLE
Communication not happening between scala stream collector and javascript tracker.

### ISSUE THREAD

**Issue by sandeshputtaraju** [snowplow/snowplow#3301]
I am using slowplow, basic setup and configuration of snowplow done in the local server(ubuntu),
 collector(i am using scala Stream collector) installation and configuration completed,
1.In the tracker section(i am using javaScript tracker), i am confused that what should be their "MY-COLLECTOR-URI"?
2.How the communication will happen between scala Stream collector and javaScript tracker?
3. Where the response of tracker will be stored in the scala Stream collector?
  
  Please help us..

**Comment by alexanderdean** [comment]
Hi, please direct support requests to our forums:

http://discourse.snowplowanalytics.com/
