### ISSUE TITLE
getting 502 status response from javascript tracker.

### ISSUE THREAD

**Issue by sandeshputtaraju** [snowplow/snowplow#3303]
i added this script in my webpage. .

	
		<script type="text/javascript">
		;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];
		p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)
		};p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;
		n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d1fc8wv8zag5ca.cloudfront.net/2.6.2/sp.js","snowplow"));

		window.snowplow('newTracker', 'cf', 'http://x.x.x.x:8080', { // Initialise a tracker
		  appId: '1',
		  cookieDomain: 'com.x.analytics'
		});

		window.snowplow('trackPageView');
		</script>
		

where "http://x.x.x.x:8080" is public url in the above script.
but i am getting 502 status response in fiddler and Firefox.
In my configuration file collector is sink with stdout. but i cant able to find in my local server(ubuntu). 
please help me out.

**Comment by chuwy** [comment]
Hello @sandeshputtaraju,

1. Your collector address should not include `http://` protocol. Just `x.x.x.x:8080`
2. If you're getting 502 error - this is likely collector, not tracker issue
3. Latest JS Tracker version is 2.8.0
4. `cookeDomain` should be valid domain

Also, please send support questions to our [forums](http://discourse.snowplowanalytics.com/), github is for bugs and feature requests only.
