### ISSUE TITLE
not able to run stream enrich in local server(ubuntu)?

### ISSUE THREAD

**Issue by sandeshputtaraju** [snowplow/snowplow#3315]
installation is completed and in the configuration we used source=stdin and sink=stdouterr, but finally in running stream enrich
using the below command
./snowplow-stream-enrich-0.10.0 --config enrich.conf --resolver file:/home/hadoop/snowplow/3-enrich/config/iglu_resolver.json --enrichments file:/home/hadoop/snowplow/3-enrich/config/enrichments/ >> stream_enrich_log_file.txt 2>&1

i am getting below error.
{"line":"","errors":[{"level":"error","message":"Error deserializing raw event: Cannot read. Remote side has closed. 
Tried to read 1 bytes, but only got 0 bytes. (This is often indicative of an internal error on the server side. Please check your server logs.)"}]
,"failure_tstamp":"2017-07-19T14:41:16.575Z"}

please help me out to resolve this error.

**Comment by alexanderdean** [comment]
Hey! Please raise on our forums:

http://discourse.snowplowanalytics.com/
