### ISSUE TITLE
how to use aws apigateway and lambda as collector

### ISSUE THREAD

**Issue by Tiny-wlx** [snowplow/snowplow#3316]
i want use aws apigateway and lambda to replace Scala Stream Collector to get near-real time events,  what i want to do is when call lambda, lambda will put the records to "good stream" which config at collector.conf, other steps will follow snowplow's document description.
AS i know, the "good stream" is serializes to a Thrift record format, and i got "structs.thrift" from https://github.com/WesleyBatista/snowplow-kafka/blob/master/decode.py, how could i organize data and serializes the data?

**Comment by alexanderdean** [comment]
Hey @Tiny-wlx - it's not an architecture we are looking at supporting any time soon:

* The Scala Stream Collector has certain features (with more on the roadmap) which an API Gateway cannot support
* An API Gateway-based solution will only work on AWS, and we are moving Snowplow to having first-class support for multiple clouds, plus on-prem
