### ISSUE TITLE
Invalid dvce_sent_tstamp causes fail in Redshift load

### ISSUE THREAD

**Issue by esquire900** [snowplow/snowplow#3332]
We encountered a problem when a user sent events with dvce_sent_tstamp being set to "9999-05-28 13:13:23.260" (that is how it comes out of the stream enricher). This causes the derived_tstamp to be set to "-5965-09-20 15:44:22.721", which is not a valid timestamp for redshift, which fails to load the event.

It's a quite an edge case and doesn't lead to any significant problems, but hopefully worth mentioning.

**Comment by alexanderdean** [comment]
Thanks for flagging @esquire900 !

**Comment by alexanderdean** [comment]
Adding data-loss label.

**Comment by alexanderdean** [comment]
No reccurence since 2017, closing
