### ISSUE TITLE
Error while running snowplow-storage-loader

### ISSUE THREAD

**Issue by nishanth6** [snowplow/snowplow#3351]
**Step 4: setting up alternative data stores » Setup PostgreSQL.
In my localhost I had successfully installed PostgreSQL and successfully created & configured 
"atomic"."events" table and configured resolver.json.**

I tried to run in \4-storage\storage-loader\deploy directory with unzipping two files 
ie., snowplow-storage-loader & snowplow-emr-etl-runner from snowplow_emr_r88_angkor_wat.zip
with config.yml configured?. Even though I am not having Amazon Awz Account.

When I tried to run the below command:

`./snowplow-storage-loader --config config/config.yml --resolver config/resolver.json --targets config/targets/ --skip analyze`

I'am getting the following error:	

LoadError: no such file to load -- jruby_pageant
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agen                                                                                                                t/java_pageant.rb:1
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agen                                                                                                                t.rb:1
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/agen                                                                                                                t.rb:20
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/key_                                                                                                                manager.rb:1
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/key_                                                                                                                manager.rb:4
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:133
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/sess                                                                                                                ion.rb:1
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh/authentication/sess                                                                                                                ion.rb:4
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:55
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh.rb:1
	  require at org/jruby/RubyKernel.java:959
	  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_                                                                                                                ext/kernel_require.rb:133
	   <main> at uri:classloader:/gems/net-ssh-2.9.4/lib/net/ssh.rb:11
	  require at org/jruby/RubyKernel.java:959
	   (root) at uri:classloader:/gems/fog-1.25.0/lib/fog/joyent/compute.rb:1
	   <main> at uri:classloader:/gems/fog-1.25.0/lib/fog/joyent/compute.rb:3
	  require at org/jruby/RubyKernel.java:959
	   (root) at uri:classloader:/gems/fog-1.25.0/lib/fog/joyent.rb:1
	   <main> at uri:classloader:/gems/fog-1.25.0/lib/fog/joyent.rb:1
		 load at org/jruby/RubyKernel.java:977
	   <main> at uri:classloader:/gems/fog-1.25.0/lib/fog.rb:1
	  require at org/jruby/RubyKernel.java:959
	   (root) at uri:classloader:/gems/fog-1.25.0/lib/fog.rb:39
	   <main> at uri:classloader:/storage-loader/lib/snowplow-storage-loader/contrac                                                                                                                ts.rb:1
	ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load --                                                                                                                 jruby_pageant

How should I need to configure config.yml file with postgreSQL installed.

**Even after installing Ruby and updating Gem file & adding ruby_pageant still the issue has not been solved.**

**Comment by nishanth6** [comment]
Does any one knows how should I have to run in GitBash command shell.

**Comment by chuwy** [comment]
Hi @nishanth6,

Please put support requests to our [forums](https://discourse.snowplowanalytics.com/). Github is for issues and bugs only.

**Comment by nishanth6** [comment]
Hello @chuwy ,
I have already posted it in

- [Unexpected error while running the Storage Loader](https://discourse.snowplowanalytics.com/t/unexpected-error-while-running-the-storage-loader/1311)

- [How to run Storage Loader in PostgreSQL database](https://discourse.snowplowanalytics.com/t/how-to-run-storage-loader-in-postgresql-database/1303?source_topic_id=1311)

But no replied for the LoadError: no such file to load -- jruby_pageant. 
I need a solution for running storage loader even without configuring .yml & .json files.
