### ISSUE TITLE
EmrEtlRunner: add file- and Consul-based locking mechanism

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3352]
This is to replace #3130 

This is a temporary measure until we can migrate off EmrEtlRunner to Dataflow Runner. I would recommend lifting the public API and internal behavior verbatim from Dataflow Runner, to minimize the impedance mismatch when we finally do the move.

**Comment by BenFradet** [comment]
@alexanderdean do we need a softlock too?

**Comment by alexanderdean** [comment]
No, just hardlock, there's no safe softlock scenario I can think of...
