### ISSUE TITLE
Event Manifest Populator: explore potentially missed records in event manifest

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3353]
According to docs, AWS SDK can throw exceptions when writer stays above provisioned throughput volume for long period of time. However, I've seen EMP working with 3000 capacity on 1000 provisioned throughput for several hours and didn't interrupt. It can have two explanations: records have been throttled and postponed (current assumption) or thrown away (in that case deduplication isn't working with full force).

To check it we just need to run EMP with very low provisioned throughput and compare results with usual run.

**Comment by alexanderdean** [comment]
Given explanation two:

> thrown away (in that case deduplication isn't working with full force).

I'm treating this as a data quality issue.

**Comment by alexanderdean** [comment]
De-scheduling.

**Comment by chuwy** [comment]
Actually, let's close this. I performed a test that didn't reveal any suspicious results back then.
