### ISSUE TITLE
Scala Stream Collector: multiple IP addresses stored in IP address field

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3356]
Rare, but this can happen if multiple IP addresses are passed in as one of the request headers.

Multiple IP addresses in the IP address field causes some strange behaviours downstream, see https://snowplow.zendesk.com/agent/tickets/5456 for details.

If the offending header is of the form `ipAddressA, ipAddressB, ipAddressC`, then we should take just the first IP address, `ipAddressA`.

**Comment by BenFradet** [comment]
This is already the case?

**Comment by BenFradet** [comment]
superseded by #3771, closing
