### ISSUE TITLE
Spark Enrich: enrichment secrets passed in to jobstep

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3357]
Sensitive facts such as API keys are passed in as command line args to the jobstep as part of enrichment configurations. We should fix this.

**Comment by alexanderdean** [comment]
Two ways of fixing this:

1. We switch from config files on CLI to some kind of Control Plane, which we secure
2. We use the EC2 Secret Store, as we do for Redshift Loader configuration

**Comment by knservis** [comment]
Could we use environment variables?

**Comment by alexanderdean** [comment]
No, that's not how the EMR API works

**Comment by chuwy** [comment]
Spark Enrich is deprecated.
