### ISSUE TITLE
EmrEtlRunner: ensure appropriate log level for RDB logs

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow#3369]
In the release prior to R90, we have the *full commit* in `stderr` which is quite handy to determine what needs to be fixed (in addition to the actual error reported).

In R90, there's nothing in `stderr` on failure and the `stdout` only presents the actual error which might not be sufficient.

Here's an [incident example](https://snowplow.pagerduty.com/incidents/PAJM316). For visibility, the output relevant to RDB follows (truncated for brevity and data sensitivity):

```
D, [2017-08-10T18:41:17.722000 #29070] DEBUG -- : Downloading . . .
I, [2017-08-10T18:41:19.778000 #29070] INFO -- : {{ Redshift NAME }}
I, [2017-08-10T18:41:19.779000 #29070] INFO -- : ERROR: Data loading error [Amazon](500310) Invalid operation: Cannot COPY into nonexistent table com_snowplowanalytics_snowplow_desktop_context_1;
Following steps completed: [Discover]
F, [2017-08-10T18:41:20.390000 #29070] FATAL -- : 

Snowplow::EmrEtlRunner::EmrExecutionError (EMR jobflow j-YQR7ML4XD6SO failed, check Amazon EMR console and Hadoop logs for details (help: https://github.com/snowplow/snowplow/wiki/Troubleshooting-jobs-on-Elastic-MapReduce). Data files not archived.
Snowplow {{ job }} enrichment: TERMINATING [STEP_FAILURE] ~ elapsed time n/a [2017-08-10 18:25:54 +0000 - ]
 . . .
- 8. Elasticity Custom Jar Step: Load {{ Redshift NAME}} Storage Target: FAILED ~ 00:01:00 [2017-08-10 18:38:34 +0000 - 2017-08-10 18:39:34 +0000]
 . . .
```

Moreover, the error is prefixed with `INFO`

```
. . .  INFO -- : ERROR: Data loading error . . .
```

Not sure if that is the reason even that (shorten) message doesn't go to `stderr`.

With respect to RDB logs, I can see the following issues still open which seems to be somehow related: https://github.com/snowplow/snowplow/issues/3361 and https://github.com/snowplow/snowplow/issues/3363

**Comment by chuwy** [comment]
Just to clarify what the fix should include:

* RDB Logs output go to `stderr`
* RDB Logs prefixed with correct log level

Is there anything we can improve in message `Invalid operation: Cannot COPY into nonexistent table com_snowplowanalytics_snowplow_desktop_context_1`?

**Comment by alexanderdean** [comment]
> Is there anything we can improve in message

The problem is that the old error messages used to print out the whole COMMIT that failed, which was quite helpful context around the specific command that failed...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/23

**Comment by chuwy** [comment]
Re-opening, this is mostly EmrEtlRunner.

**Comment by BenFradet** [comment]
Given that, R91 outputs the logs on failure (#3361), is it just a matter of:

- RDB Logs output go to stderr
- RDB Logs prefixed with correct log level

?

I'm not sure how we would go about the second point given that we don't know what's in the logs.

A first step would be to error if the step failed, warn if cancelled and info otherwise, what do people think?

**Comment by alexanderdean** [comment]
I like it!
