### ISSUE TITLE
Part of corrupted page/referer querystring can end up in fragment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#337]
If a URL querystring is corrupted (read: contains unescaped URLs itself), then part of this can end up in the `_urlfragment` field of the output.

Not a big issue, but a little messy.

See Alex's email to himself, "Snowplow issue 337" for an example row from a client.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/233
