### ISSUE TITLE
RDB Loader: jsonpath resolution caching not caching

### ISSUE THREAD

**Issue by acgray** [snowplow/snowplow#3384]
When running some local tests with the RDB loader jar I was surprised at what seemed to be very slow execution for a small data set.

On stepping through the code it seems that the caching mechanism for jsonpath resolution isn't working as expected.  I added some `println` statements to demonstrate what I see:

https://gist.github.com/acgray/4be9f38610d8d0a321bce4deb9a4a72e#file-shreddedtype-scala-L119-L131

The result is as follows:

https://gist.github.com/acgray/6d2d5a4ffdd0c77396e38799781708c4

I'm happy to write a fix if you guys can confirm this is indeed the wrong behaviour or whether I have got the wrong end of the stick!

**Comment by BenFradet** [comment]
@acgray the 2nd gist 404s

**Comment by BenFradet** [comment]
Initially suspected tagged types but they seem to behave fine at as far as the cache is concerned.

**Comment by chuwy** [comment]
Thanks for report @acgray! We will look into it.

Btw, we now have a dedicated repository for RDB Loader: https://github.com/snowplow/snowplow-rdb-loader, all code and issues will migrate there soon.

Moving ticket into new repository, closing this one.

**Comment by acgray** [comment]
@BenFradet I replaced the 2nd gist to censor our bucket names, perhaps you caught the old version

The correct link is https://gist.github.com/acgray/6d2d5a4ffdd0c77396e38799781708c4

**Comment by BenFradet** [comment]
@acgray yup, got it :+1:
