### ISSUE TITLE
Fix wiki links in README for storage/postgres

### ISSUE THREAD

**Issue by premjg** [snowplow/snowplow#3389]
Both the links - `Technical Docs` and `Setup Guide` are currently pointing to non-existent pages.

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by BenFradet** [comment]
moved to docs, closing
