### ISSUE TITLE
Typo in the documentation in the Link tracking section

### ISSUE THREAD

**Issue by mahmoudfelfel** [snowplow/snowplow#3397]
Hi,
There is a typo in the TrackLinkClick example in the documentation here:
https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#393-tracklinkclick
```
snowplow_name_here('trackLinkCLick', 'http://www.example.com', 'first-link', ['class-1', 'class-2'], '', 'this page');
```
the `L` in `CLick` should be lowercase otherwise snowplow will raise an error becasue this method is not there.
This cost me an hour of debugging :)

**Comment by ihortom** [comment]
Fixed.
