### ISSUE TITLE
Unstructured event documentation of Snowplow Tracker Protocol uses wrong iglu schema in examples

### ISSUE THREAD

**Issue by rgabo** [snowplow/snowplow#3406]
Examples in https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol#unstructevent should use the JSON schema `iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0` for the outermost JSON envelope instead of `iglu:com.my_company/unstruct_event/jsonschema/1-0-0`.

**Comment by alexanderdean** [comment]
Thanks @rgabo !
