### ISSUE TITLE
Scala Stream Collector: query params ignored for post requests

### ISSUE THREAD

**Issue by acgray** [snowplow/snowplow#3414]
https://github.com/snowplow/snowplow/blob/5d2ffc5cec5bb00876acc778b72ae8937e1bde24/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors/scalastream/CollectorService.scala#L89-L100

This line appears to ignore query string parameters for collector POST requests, instead always passing `null` (L90).  This prevents specifying tracker protocol parameters for webhooks, e.g. app id, as described in the documentation here (with `aid=mandrill`):

https://github.com/snowplow/snowplow/wiki/Mandrill-webhook-setup#21-mandrill

**Comment by BenFradet** [comment]
This has been taken care of as part of #3274 : https://github.com/snowplow/snowplow/blob/3dd91edfadf1b3bd6145bbc95a1052dcc4ed6ac1/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorRoute.scala

**Comment by acgray** [comment]
Ah great.  I'll keep an eye out for the release.
