### ISSUE TITLE
Update documentation to point to debug tool

### ISSUE THREAD

**Issue by shermozle** [snowplow/snowplow#3422]
Please put a link to Snowplow Inspector, our Chrome extension:
https://chrome.google.com/webstore/detail/snowplow-inspector/maplkdomeamdlngconidoefjpogkmljm

Into the following places:
https://github.com/snowplow/snowplow/wiki/Testing-the-Javascript-tracker-is-firing
https://github.com/snowplow/snowplow/wiki/javascript-tracker-setup

Sample copy to use:
Test that the JavaScript tracker is working correctly, including decoding embedded JSON, using [Snowpow Inspector](https://chrome.google.com/webstore/detail/snowplow-inspector/maplkdomeamdlngconidoefjpogkmljm), a Chrome extension that exposes a new tab for Snowplow beacons inside the developer tools.

**Comment by alexanderdean** [comment]
Sure - Ihor can you do this one...

**Comment by ihortom** [comment]
Added to "Testing-the-Javascript-tracker-is-firing" page only. Don't want to duplicate it on "Javascript-tracker-setup" as it links to "Testing-the-Javascript-tracker-is-firing" which is the most appropriate location for the reference to Snowplow Inspector.
