### ISSUE TITLE
SP.js error 

### ISSUE THREAD

**Issue by waspesi** [snowplow/snowplow#3423]
Hi,
The link click tracking is an automatic feature of the Snowplow library. I'm not sure why it is not tracking the target url as it should be according to the documentation. I've tried using the "manual" link click tracking to see if we manually pass our own targetURL, but there is an error thrown.
See attached.
![image](https://user-images.githubusercontent.com/29575504/30438882-5a321d02-9940-11e7-8b40-ec4c46eb70ea.png)

I even tried this hardcoding this on a local test page without using Tealium and it still gives me the same error.
See attached.
![image](https://user-images.githubusercontent.com/29575504/30438927-7aac8900-9940-11e7-8122-c5fccce9920c.png)

I am seeing the tag fire however there are no values being passed.
I will have to defer to support from Snowplow at this point.

Regards,
 @waspesi waspesi changed the title from Unable to get the event tracking to work (with or without Telaium to Unable to get the event tracking to work (with or without Telaium) on Jun 20
 @waspesi waspesi changed the title from Unable to get the event tracking to work (with or without Telaium) to Unable to get the event tracking to work (with or without Tealium) on Jun 20

**Comment by BenFradet** [comment]
Hello, could you create the issue in the repository dedicated to the javscript tracker: https://github.com/snowplow/snowplow-javascript-tracker? Thanks.

**Comment by waspesi** [comment]
Sorry, new to this. Thanks!

Wayne Aspesi
Marketing Analytics Consultant | Data Analytics
T: (413) 744-3262
MassMutual
1295 State Street  | MIP F205  |  Springfield, MA 01111
MassMutual.com | RetireSmart |  Facebook | Twitter | LinkedIn
Please use below link to submit requests:
Data Analytics Requests<http://mminfo.private.massmutual.com/RequestCenter/myservices/navigate.do?query=serviceid&sid=1481&layout=&userid_for_service_search=12167&>

Massachusetts Mutual Life Insurance Company (MassMutual), Springfield, MA 01111-0001,
and its affiliated US insurance companies.
