### ISSUE TITLE
Collector: invalid request cookie value resulting random network_userid 

### ISSUE THREAD

**Issue by youngboy** [snowplow/snowplow#3431]
I'm getting different set network_userid from every js-tracker request
It took me few hours find that it is caused by my existed cookies, which have special characters like comma, backslash...

possible relate issue ? https://github.com/spray/spray/issues/702

maybe there is another workaround by add 'nuid' parameter from js-tracker, but couldn't find any document.

**Comment by BenFradet** [comment]
R93, which is the next release, will migrate the collector to akka-http (cf #3299).

In akka-http cookie parsing is just a matter of configuration, see `cookie-parsing-mode` in the [akka-http default configuration](http://doc.akka.io/docs/akka-http/current/java/http/configuration.html)

**Comment by BenFradet** [comment]
Closing since R93 has been released :+1:
