### ISSUE TITLE
EmrEtlRuner: add S3 bootstrap action removing empty $folder$ files

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3439]
This jobstep will be responsible for maintaining a clean state within S3.  Namely the empty `*$folder$` files that get left around as part of the `S3DistCp` routine.

**Comment by alexanderdean** [comment]
Agree - the problem comes from S3DistCp, so we should fix it in EMR...

**Comment by BenFradet** [comment]
Will investigate whether s3distcp is even capable of removing those files.

**Comment by BenFradet** [comment]
Apparently there is no way to do this with s3distcp, are we okay introducing a new bootstrap action removing the existing $folder$ files?

It would go through the configured buckets and remove the $folder$ files.

**Comment by alexanderdean** [comment]
Yep that's fine with me...

**Comment by alexanderdean** [comment]
Taking a step back on this one: why was it implemented as a bootstrap action, not as a jobflow step? It's got nothing to do with preparing the EMR cluster for the job...

**Comment by knservis** [comment]
As an alternative, instead of relying on s3distcp to delete the s3 objects it may be possible to delete them as a separate step after the job is successful (s3distcp provides a manifest that can be used for that)

**Comment by BenFradet** [comment]
I don't believe those are included in the manifest since they are created as a byproduct of the s3distcp job, i.e. they weren't in hdfs to begin with.

**Comment by BenFradet** [comment]
Descheduling.

**Comment by frankcash** [comment]
is there any progress or acceptable way of doing this that is endorsed by the snowplow team right now 💯

**Comment by BenFradet** [comment]
hey @frankcash we have an internal process that removes those files which is launched on demand, it's unlikely it will make its way into the off-the-shelf job given its impact on job time.

**Comment by sebastianvillarroel** [comment]
could we have this as some job utility like a lambda? which are the folders which should be empty?

**Comment by chuwy** [comment]
Hi @sebastianvillarroel. EmrEtlRunner is at the end of life - we recommend everyone to upgrade to Stream Enrich and [RDB Loader R35](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/loaders-storage-targets/snowplow-rdb-loader/r35-upgrade-guide/) that don't have dependency on EER anymore.

**Comment by sebastianvillarroel** [comment]
@arndkorn FYI
