### ISSUE TITLE
Common: decorrelate CI/CD for Scala Stream Collector and Stream Enrich

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3441]
At the moment [release_kinesis](https://github.com/snowplow/snowplow/blob/7e5da44d4b8fa08e0cf90f1aaa327e0a8aad937a/.travis/release_kinesis.yml) handles both the release of ssc and se, that shouldn't be the case.

**Comment by alexanderdean** [comment]
What will be the new approach?

**Comment by BenFradet** [comment]
same as spark enrich: a `release_ssc` and a `release_se` with separate tags
