### ISSUE TITLE
Spark Enrich: overwrite output datasets

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3443]
If one is to lose a container during a task writing the bad rows / good events, the task will be retried on a new container but will fail with `FileAlreadyExistsException`. We should overwrite those output datasets in order to avoid this issue.

**Comment by alexanderdean** [comment]
There is no risk of accidental duplication of data across retries here?

**Comment by BenFradet** [comment]
no, this is idempotent
