### ISSUE TITLE
Scala Common Enrich: make event_fingerprint mandatory field

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3445]
I think `event_fingerprint` is core property of enriched event and should not be a part of pluggable enrichment. Worst thing is that it give user a [false assurance](https://discourse.snowplowanalytics.com/t/unwanted-deduplicated-events-are-getting-through/1492/8) that events getting though deduplication processes, while they're not.

This is probably should be a part of bigger enriched format refactoring, but I couldn't find any tickets related to it.

**Comment by chuwy** [comment]
Also, in shred job, we're generating random strings for `event_fingerprint` which confuses me even more.

**Comment by alexanderdean** [comment]
@chuwy can you share a link on the random string point? Maybe I can provide some context...

**Comment by chuwy** [comment]
@alexanderdean here in RDB Shredder: https://github.com/snowplow/snowplow-rdb-loader/blob/master/shredder/src/main/scala/com.snowplowanalytics.snowplow.storage/spark/ShredJob.scala#L107-L114

**Comment by chuwy** [comment]
Here's a commit adding it: https://github.com/snowplow/snowplow-rdb-loader/commit/788144d1c099c4a3f65165a6b8d4c3cde229f58b#diff-f2fb0e331ce18870d9066074e3a52733

**Comment by alexanderdean** [comment]
So I think we are generating a random fingerprint to avoid accidentally deduplicating. But I agree that shouldn't be surfaced.

I don't know if I agree that event fingerprinting should be mandatory and not configurable, but happy to hear the arguments. But I do agree that it's very confusing to say that deduplication = event fingerprinting + DynamoDB storage target. There's nowhere where we say `deduplication = ON`.

**Comment by chuwy** [comment]
Well, I would like to put in other way round. What's the purpose of having it as an enrichment?

I mean, do we know any cases where users tried to actually configure it? We're not saving disk space - it's not that big and always present anyway. Having it as mandatory field means it's easier to port deduplication to stream environment. For me it's a field of same important as `true_tstamp`.

**Comment by alexanderdean** [comment]
> Well, I would like to put in other way round. What's the purpose of having it as an enrichment?

I'd say the purpose of it being an enrichment is that *everything should be an enrichment* - in other words, there should be less hard-coded magic in the core enrichment process, not more. You could argue that Snowplow is not Snowplow without e.g. event fingerprinting or calculating the derived timestamp, but the more prescriptive we are, the more we limit the use cases / future audience of Snowplow...

**Comment by chuwy** [comment]
That makes sense. Though fingerprinting logic still exists independently of enrichment (and it is not always satisfactory). 

What about leaving fingerprint enrichment as it is now, allowing users to configure it, but change a shredder code substituting random UUID with "default" algorithm?

**Comment by alexanderdean** [comment]
> What about leaving fingerprint enrichment as it is now, allowing users to configure it, but change a shredder code substituting random UUID with "default" algorithm?

What about throwing an exception / failing the process if an event_fingerprint is missing? Clearly the user wants to dedupe, but they can't because the fingerprint enrichment is switched off, so why proceed?

**Comment by chuwy** [comment]
I like it as well! Moving ticket into RDB Loader repo.

**Comment by chuwy** [comment]
Done https://github.com/snowplow/snowplow-rdb-loader/issues/45
