### ISSUE TITLE
Iglu Webhook Adapter: support TJSON for GET

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3446]
Currently GETs are stringly typed - we assume that all properties should be strings.

We could use TJSON (Typed JSON) annotations to indicate the actual data type:

https://www.tjson.org/

So sending in a float might look like:

http://collector.com/.../?cost:f=34.4

**Comment by alexanderdean** [comment]
Useful for environments where a `POST` is not an option (e.g. ad-tech).

/cc @ihortom

**Comment by miike** [comment]
I'd never heard of TJSON before - the spec looks quite interesting.

**Comment by alexanderdean** [comment]
Reminder that we need to update this tutorial following release as the cost-sending example is broken:

https://discourse.snowplowanalytics.com/t/how-to-track-ad-impressions-and-clicks-tutorial/29

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/77
