### ISSUE TITLE
EmrEtlRunner: add support for passing tunnel configuration to RDB Loader

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3448]
See https://github.com/snowplow/snowplow-rdb-loader/issues/22

This should contain:

* SSH username
* SSH passphrase (optional)
* SSH server
* Local port (which also must be in target configuration) 

We have three options here:
1. Create new  self-describing configuration, like `iglu:com.snowplowanalytics.snowplow/ssh-tunnel/jsonschema/1-0-0` 
2. Add section `config.yml`
3. Add new `sshTunnel` section to RDB storage targets

I prefer third option - in that case this ticket can be closed (assuming EER will pass any valid config to RDB Loader).

**Comment by alexanderdean** [comment]
I vote for 3

**Comment by jbeemster** [comment]
Agreed number 3 is cleanest

**Comment by chuwy** [comment]
Ok. Closing then. 

Third options also means SSH tunnels can be used with any version of EmrEtlRunner as long as RDB Loader is >= 0.14.
