### ISSUE TITLE
Scala Common Enrich: use tnuid to add a network_userid in adapters

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3450]
Clojure Collector always [adds](https://github.com/snowplow/snowplow/blob/e2e0a1000f91baa7efacc295b246782aab20d77c/2-collectors/clojure-collector/java-servlet/war-resources/.ebextensions/server.xml#L138) `nuid` with cookie content to log, therefore it's advised to use `tnuid` to override `network_userid` via tracker - SCE [overrides](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L204) `network_userid` with `tnuid` value if it is present.

At the same time all adapters [accept](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/Adapter.scala#L66) only `nuid` parameter, throwing an exception on `tnuid`. Example from Iglu Adapter:

```
        "level": "error",
        "message": "error: object instance has properties which are not allowed by the schema: [\"tnuid\"]\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"\"}\n    instance: {\"pointer\":\"\"}\n    domain: \"validation\"\n    keyword: \"additionalProperties\"\n    unwanted: [\"tnuid\"]\n"
```

It happens because `tnuid` should be extracted from Iglu Adapter's payload, but instead it's part of self-describing JSON, which should not be a case. 

In the end we have non-working `tnuid` in adapters+clj-collector.

Docs for webhooks also should be updated: [1](https://github.com/snowplow/snowplow/wiki/Iglu-webhook-adapter), [2](https://github.com/snowplow/snowplow/wiki/SendGrid-webhook-setup), etc. (and many webhook docs miissing fact that some properties can be customized, btw)

**Comment by alexanderdean** [comment]
Agreed, the webhook adapters should respect `tnuid`...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/78
