### ISSUE TITLE
EmrEtlRunner: handle SSE-S3 encrypted S3 buckets

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3456]
The command line option for S3DistCp is `--s3ServerSideEncryption`:

http://docs.aws.amazon.com/emr/latest/ReleaseGuide/UsingEMR_s3distcp.html

We need to understand:

* Can we switch this on for all S3DistCp operations, or just for ones with S3 destinations
* The implications for reading data from S3 (e.g. with our Analytics SDKs)
* The implications for loading data into Redshift

**Comment by miike** [comment]
I've been having a look at S3 encryption recently.

There's three types of S3 encryption supported: customer provided (SSE-C), Key Management based (SSE-KMS) and S3 managed (SSE-S3).

SSE-C isn't supported by EMR or Redshift COPY so we can eliminate having to deal with that at the moment [1], [2].

Neither SSE-KMS or SSE-S3 required modifying the COPY command to include an ENCRYPTED argument so this doesn't require any changes to the way Redshift is loaded [3].

The `--s3ServerSideEncryption` flag may work with no changes to the EMR cluster for SSE-S3 but we may need to add an extra `Encryption` parameter for EMRFS to support SSE-KMS [4] - it looks like there's at least 1 additional step to support SSE-KMS [5]

[1] https://docs.aws.amazon.com/emr/latest/DeveloperGuide/emr-emrfs-encryption.html
[2] https://docs.aws.amazon.com/redshift/latest/dg/c_loading-encrypted-files.html
[3] https://docs.aws.amazon.com/redshift/latest/dg/c_loading-encrypted-files.html
[4] https://docs.aws.amazon.com/emr/latest/DeveloperGuide/emr-emrfs-encryption.html
[5] https://docs.aws.amazon.com/emr/latest/DeveloperGuide/emr-create-security-configuration.html#emr-security-configuration-encryption

**Comment by alexanderdean** [comment]
Thanks for sharing this @miike !

**Comment by BenFradet** [comment]
Thanks a lot for the investigation @miike :+1: 

It seems there are 3 work streams:

- encryption at rest on S3 which @miike describes thoroughly above (I tend to lean towards SSE-S3 which seems to have the less hassle)
- encryption at rest on HDFS in EMR which seems to be a matter of configuration:
  - https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html#Data_Encryption_on_RPC
  - https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html#Data_Encryption_on_Block_data_transfer.
- encryption in transit on Spark in EMR:
  - RPC (e.g. for shuffle) is encrypted by default with EMR > 5.9.0
  - HTTP (e.g. to the web interace) is another matter of configuration https://spark.apache.org/docs/latest/security.html#ssl-configuration

https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-data-encryption-options.html
