### ISSUE TITLE
Placeholder for implementing Kinesis stream encryption

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3457]

**Comment by BenFradet** [comment]
@alexanderdean was this regarding server-side encryption?

**Comment by alexanderdean** [comment]
Yes, http://docs.aws.amazon.com/streams/latest/dev/server-side-encryption.html

**Comment by BenFradet** [comment]
Ok this will be more a matter of QA than code since it's advertised as being transparent for the consumers and producers.

**Comment by alexanderdean** [comment]
Sounds good!

**Comment by BenFradet** [comment]
works as expected and doesn't need anything from our side, closing

**Comment by alexanderdean** [comment]
Thanks Ben!
