### ISSUE TITLE
EmrEtlRunner: bump AMI version in example config to 5.9.0

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3465]
Since 5.8.0 Amazon at last started to bundle EMR AMI with AWS SDK 1.11.*. Older versions introduced lots of problems with API incompatibility, [shading](https://github.com/snowplow/snowplow/issues/3206) etc. Also it now provides [Application History](http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-cluster-application-history.html), which should make debugging a lot easier.

Though, there's more notable changes, like Spark 2.2 and it would likely take more effort than just bumping AMI, but still would be great to move forward and not let Snowplow ecosystem stale.

**Comment by alexanderdean** [comment]
Can we fit this into R95 @BenFradet?

**Comment by BenFradet** [comment]
we could the changes should be lightweight
