### ISSUE TITLE
Placeholder for re-adding an updated sync-hosted-assets.bash

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3480]
Referring to 045789b371a89e580564284166ed574bb493cae6

```
commit 045789b371a89e580564284166ed574bb493cae6
Author: Anton Parkhomenko <mailbox@chuwy.me>
Date:   Fri Jun 30 20:04:06 2017 +0700

    Common: update CI/CD to push S3 artifacts to all regional Hosted Assets buckets (close #3242)

 delete mode 100755 vagrant/push/sync-hosted-assets.bash
```

I see why this file was deleted, but there are two unresolved issues:

1. When AWS creates new regions, we still need a way of backfilling all the old bucket contents into the new bucket
2. We still need a way of pushing and synchronizing all the JSON Paths files for Iglu Central. Though actually it would be better to handle this from the Iglu Central repo, I'll add a ticket there...

**Comment by chuwy** [comment]
Our CI/CD has significantly changed.
