### ISSUE TITLE
Scala Common Enrich: default port to 443 if scheme is https

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3483]
The current behaviour of `explodeUri` sets port to 80 if there is no explicit port number in the URL. To correct this if no port number is present and the scheme is https the port returned should be 443.

[Related discourse post](https://discourse.snowplowanalytics.com/t/bug-js-tracker-is-logging-port-numbers-incorrectly/1573)

**Comment by alexanderdean** [comment]
"Default" -> "default"
