### ISSUE TITLE
Scala Common Enrich: add preference for successful skip to API Request Enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3485]
See: https://discourse.snowplowanalytics.com/t/api-enrichment-response-error-handling-question/1570

Idea is to specify cases, where service returned non-success/not-valid, but instead of sending to bad-bucket we just don't add derived context and effectively skip enrichment.

I see two possible (complementary) preferences. 

1. Using HTTP-statuses (`skip`). If service returns one of specified status codes - don't add anything to derived context and don't send to event bad-bucket, effectively skip enrichment. Though taking in account that it will be used mostly for own web-services - I think only 404 should be useful.

```json
"api": {
  "http": {
    "method": "GET",
    "uri": "http://api.acme.com/users/{{client}}/{{user}}?format=json",
    "timeout": 5000,
    "authentication": { },
    "skip": [404, 500]
  }
}
```

2. Using JSONPaths (`optional`). If output isn't found by JSONPath - don't add to derived contexts

```json
"outputs": [ {
  "schema": "iglu:com.acme/user/jsonschema/1-0-0", 
  "json": {
    "jsonPath": "$.record",
    "optional": true
  }
} ],
```

**Comment by bogaert** [comment]
FYI, one of our customers asked for this exact feature last week. Running the risk that events fail validation when the API is unavailable makes the enrichment less attractive.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/240
