### ISSUE TITLE
EmrEtlRunner: add support to the spot market for core instances

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow#3487]
This one is quite straightforward: supporting the spot market for core instances can reduce EMR costs significantly (~60% in our case), which is especially important now that the long de-duplication and RDB Loader steps were moved to EMR. The open question is whether data would be lost in case of an instance termination.

PS: Task nodes are not effective as rbolkey [pointed out on the forums](https://discourse.snowplowanalytics.com/t/learnings-from-using-the-new-spark-emr-jobs/1260).

**Comment by alexanderdean** [comment]
Thanks @bernardosrulzon . We will keep this ticket open to track the requirement, but it's very unlikely to be implemented before the move to Dataflow Runner (at which point we will migrate this ticket).

**Comment by bernardosrulzon** [comment]
That makes a lot of sense @alexanderdean.

I guess the key issue is whether Snowplow is ready for spot instances or there's additional development involved in making it resistant to instance termination/rebooting - which would be especially troublesome on the Shred Step as data would already be inserted into DynamoDB.

Any thoughts on that? /cc @BenFradet

**Comment by BenFradet** [comment]
Unfortunately cross-batch deduplication through DynamoDB is not idempotent. As a result, we'd need to make the two exclusive.

This kind of makes sense since the two are going in different directions, cross-batch deduplication is a sizable added cost whereas when using spot instances you're trying to save money.

**Comment by chuwy** [comment]
As we re-discovered recently - cross-batch deduplication is idempotent. When you're shredding even that is already in manifest **and has same etl timestamp** it will not be marked as duplicate. It means that we can safely re-deduplicate events on spot instances without loosing them.

**Comment by bernardosrulzon** [comment]
That's the point @chuwy - when a job fails in Shred and we re-process data using EmrEtlRunner, a new job is created with an updated `etl_tstamp`, which causes the previous events to be discarded as duplicates
