### ISSUE TITLE
EmrEtlRunner: add DynamoDB auto-scale mechanism

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3488]
Idea is to upscale event manifest table some time (10 minutes minimum) before starting shred job and downscale immediately afterwards.

Technically, DynamoDB since recently has their own auto-scaling, but it's very unresponsive and intended for different kind of loads - while we have just two modes (full load and zero load) people usually have much more smooth load profile. It means that:

1. Quite often we have table upscaled to maximum for 90% of day, while proper value should be 10-15%. This adds huge costs.
2. We need to maintain "safe" lower bound 100% of time, while can have 0 throughput when pipeline is not running.
3. DynamoDB can fail to upscale quick enough when load started
4. Maximum value is pre-defined and need to be bumped manually for catch-up jobs, while could be derived from EMR cluster configuration.

My proposal is to add following to EmrEtlRunner:

0. Add `aws.dynamodb.autoscale` boolean setting to `config.yml`
1. Calculate throughput based on EMR cluster size (very roughly, each "small" instance adds 800 units)
2. Wait until Enrich job started
3. Send [UpdateTable](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTable.html) with calculated throughput

Problems:

1. It should not be used for pipelines with more than 4 runs per day - DynamoDB table cannot scale more
2. Table can remain with high throughput in some failure-scenarios (still works better than native autoscaling)
3. Mixes-in some DevOps magic into conifg. Still EMR settings is same DevOps' responsibility.

**Comment by chuwy** [comment]
This can implemented as:

1. EMR Custom Jar, blocking on `UpdateTable`. Adds some idle to EMR cluster, ~5-8 minutes, but very safe in terms on unexpected peaks.
2. API call from EmrEtlRunner. Here we cannot predict good timings for update. It will always have a lot of idle, or risk of another throughput exception.

**Comment by alexanderdean** [comment]
I like option 1 as migratability to Dataflow Runner is a must...

**Comment by chuwy** [comment]
Some real-world examples to calculate throughput.

* `m3.xlarge` master and 2x `m3.xlarge` - up to 1.100 writes
* `m4.xlarge` master and 6x `c4.8xlarge` - up to 20.000 writes

**Comment by alexanderdean** [comment]
I like the idea but I don't this is urgent.

**Comment by chuwy** [comment]
Awesome. Closing.
