### ISSUE TITLE
Handle double-encoded cs(Referer) as per CloudFront post-14-September

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#349]
As per https://forums.aws.amazon.com/thread.jspa?threadID=135086&tstart=0

Not scheduling (yet), as it's not obvious how to do this:
- If you just decode twice, you may "break" out reserved characters e.g. `|` which then cause referer URI creation to fail
- You cannot determine if a string is uncoded simply by inspection

Luckily this is lower priority than fixing useragent. (Lower priority because the cs(Referer) is very very rarely used to determine the page URL.)

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/234
