### ISSUE TITLE
Scala Common Enrich: use automated code formatting

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3496]
I believe that we should nail down formatting and use an automated tool to format code and not talk about it any more (as it is not a useful discussion). 

This issue is about following the existing style in snowplow but using a tool (such as scalafmt) to test the format and format all new scala code. 

Changed the scope to SCE only to begin with.

**Comment by knservis** [comment]
@BenFradet @chuwy @alexanderdean 
After the initial commit, there one way to ensure that this style continues to apply is making the scalafmt task a dependancy of the compile task in sbt. How do you feel about that?

**Comment by chuwy** [comment]
Wouldn't it be a problem if people start to apply `sbt compile` only on `HEAD` and thus `HEAD` will contain changes (only styling) that should be part of different commits? To solve this we will have to run `sbt compile` each time before `git commit` and on each rebase, which also can be quite problematic.

**Comment by chuwy** [comment]
`alias gitc="scalafmt && git commit`?

**Comment by BenFradet** [comment]
I'd be for leaving it to the default `scalafmt` task, and run this as part of the ci so if anyone forgot to run it the ci will just fail. Because I don't want to delay `compile`.

**Comment by knservis** [comment]
@BenFradet In my experience compile is not noticeably affected

**Comment by BenFradet** [comment]
really? I've always heard that scalafmt is terribly slow for medium to large projects.

**Comment by knservis** [comment]
@BenFradet 
It adds 3 sec on average to the SCE compile from pristine which on average takes 58.3 sec:

```
repeat 3 { gpristine && time sbt compile >> /dev/null }

From pristine:
HEAD is now at 3ce332e3 Merge branch 'release/r96-zeugma'
Removing .scalafmt.conf
Removing project/project/
Removing project/target/
Removing target/

1. sbt compile >> /dev/null  212.17s user 6.64s system 385% cpu 56.754 total
2. sbt compile >> /dev/null  225.30s user 7.03s system 389% cpu 59.717 total
3. sbt compile >> /dev/null  216.93s user 7.48s system 388% cpu 57.688 total

With Scalafmt as compile task dep (sbt-scalafmt 1.13):

1. sbt compile >> /dev/null  237.59s user 7.49s system 383% cpu 1:03.91 total
2. sbt compile >> /dev/null  228.52s user 7.00s system 392% cpu 1:00.03 total
3. sbt compile >> /dev/null  235.57s user 7.14s system 394% cpu 1:01.47 total
```
I think that is tolerable

**Comment by alexanderdean** [comment]
U in Use should be lowercase (use)
