### ISSUE TITLE
EmrEtlRunner Download link points to outdated asset

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3501]
In 
https://github.com/snowplow/snowplow/wiki/Hosted-assets

the documentation mentions http://dl.bintray.com/snowplow/snowplow-generic/snowplow_emr_r92_maiden_castle.zip 

but the link points to:

http://dl.bintray.com/snowplow/snowplow-generic/snowplow_emr_r88_angkor_wat.zip

**Comment by alexanderdean** [comment]
Ouch good catch - @BenFradet make sure to always keep that page of links up to date!

**Comment by BenFradet** [comment]
this has been fixed in the upcoming r95
