### ISSUE TITLE
Stream Collector: Cookie bounce and load balancer SSL termination can result in an insecure web page

### ISSUE THREAD

**Issue by rbolkey** [snowplow/snowplow#3505]
A combination of (1) enabling the cookie bounce feature and (2) an environment terminating SSL connections at the load balancer can result in the SSC returning an insecure (http) link in the `Location` header.

This isn't an issue in environments where SSL is being terminated at the SSC, but it becomes an issue if the SSC is behind a load balancer that has SSL connections being terminated there (common in AWS).

I'm pretty sure the use of `request.uri` below is the culprit.

https://github.com/snowplow/snowplow/blob/a98ac7188db1a70b5af2ac29cbbe52c6dcb8c909/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorService.scala#L111

At this point, the connections with the SSC are insecure, and `request.uri` reflects that, and results in an insecure uri being used to generate the `Location` header.

I could try putting together a PR to resolve, but would need guidance as to what to use to generate the proper value for the `Location` header.

**Comment by BenFradet** [comment]
If I understand correctly you would like the location header to contain the https url of the original load balancer?

**Comment by rbolkey** [comment]
Yes, but to be more specific, the protocol of the URL used to connect to
the original load balancer is the crucial bit.

Digging into the ELB docs, they do provide a custom header that contains
this information: X-Forwarded-Proto.

Using this header to help construct the URL would be sufficient. Would this
be a satisfying solution on your end?

http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-proto

On Nov 17, 2017 4:15 AM, "Ben Fradet" <notifications@github.com> wrote:

If I understand correctly you would like the location header to contain the
https url of the original load balancer?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/snowplow/snowplow/issues/3505#issuecomment-345202243>,
or mute the thread

**Comment by BenFradet** [comment]
yup I was thinking about leveraging this header as well 👍

**Comment by rbolkey** [comment]
Fantastic! Is there a time frame for this? Would it speed things up if I tried to put together a pull request?

**Comment by BenFradet** [comment]
No timeframe yet, feel free to open a PR 👍

**Comment by rbolkey** [comment]
Hi Ben, I created a Pull Request. Can someone review for the next release?

**Comment by BenFradet** [comment]
Closing since #3512 will be closed when the release happens.
