### ISSUE TITLE
pass VM paratmeters for Kinesis S3 Sink Apps while running the application does it have any effect?

### ISSUE THREAD

**Issue by ps185130** [snowplow/snowplow#3506]
we have a configuration setup in for Kinesis S3 Sink (snowplow-kinesis-s3-0.4.1) app in such a way that it takes buffer size of around 150 MB or count of 900K recorrds or time-limit of 1 hr  ,which is a requirement based on our internal PERF test . But we see that the Kinesis Application hungs and throws OOM Error .

Trying to add JVM parameters as below and not sure if this has any impact on the application .

java -jar -Xms1024m -Xmx6144m -XX:+UseConcMarkSweepGC -XX:+UseStringCache -XX:+UseCompressedStrings -XX:+HeapDumpOnOutOfMemoryError -XX:ErrorFile=/home/ec2-user/snowplow/s3_sync/hs_err_pid.log -XX:HeapDumpPath=/home/ec2-user/snowplow/s3_sync/java_pid.hprof -XX:OnOutOfMemoryError='kill -9 %p' /home/ec2-user/snowplow/s3_sync/snowplow-kinesis-s3-0.4.1 --config /home/ec2-user/snowplow/s3_sync/my.config > spjmxtest.log 2>&1 &

**Comment by BenFradet** [comment]
`-jar` needs to be the last argument e.g. https://github.com/snowplow/snowplow-docker/blob/master/s3-loader/0.6.0/docker-entrypoint.sh#L10-L12

Also you should update your s3 loader version 0.4.1 is quite old.

In the future, please raise your support requests in [our discourse](https://discourse.snowplowanalytics.com).
