### ISSUE TITLE
Add finegrained validation to Snowplow Common Enrich

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#351]
Including:
- Adding support for new warning bucket configuration option passed from EmrEtlRunner
- Writing a new Etl monad (like the Validation monad but richer)
- Switching URI parse failures to warnings
- Add a warning if the IP address is incomplete or incorrectly formatted

Depends on #350

Validation monad ideas:

Good
Good with Warnings
Bad with Errors and Warnings

/cc @yalisassoon

**Comment by alexanderdean** [comment]
Talking to @chuwy about this. This becomes more important as we layer on more enrichments with external dependencies (e.g. weather, APIs, DBs), which could fail in some way, but don't necessarily mean that the whole event should fail.

**Comment by alexanderdean** [comment]
One approach which I quite like is to attach the warnings ("API enrichment faied") as contexts to the event. Then you always have the partial failure of an enrichment joined to the event affected. Better than creating a whole new set of buckets/streams to manage just for warnings...

**Comment by BenFradet** [comment]
It has become true as well for the ip lookup enrichment 2-0-0 for which the api (scala-maxmind-iplookups) doesn't suppress errors anymore.

Maybe handling could be set at the enrichment level: suppress / warn / fail

**Comment by chuwy** [comment]
Related: https://github.com/snowplow/snowplow/issues/3485

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/235
