### ISSUE TITLE
Event Manifest Populator: add option to specify AWS role or use one from EMR instead of credentails 

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3511]
Right now we're using AWS credentials from config, which is:

1. Security issue - base64-encoded credentials are visible in console
2. Might not have enough permissions

**Comment by chuwy** [comment]
If no credentials nor role is specified we can use default credentials provider chain which will pick up EMR-role.

**Comment by alexanderdean** [comment]
@chuwy is this still live for one of our projects?

**Comment by chuwy** [comment]
Yup, we have a separate lib used in RDB and Snowflake loaders and I think the job should be a part of that project: https://github.com/snowplow-incubator/snowplow-events-manifest/issues/18. Moving it over there.

**Comment by chuwy** [comment]
Cannot transfer into another org. Created a sister ticket there https://github.com/snowplow-incubator/snowplow-events-manifest/issues/19
