### ISSUE TITLE
Scala Stream Collector: document the stdout sink better

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3515]
It's not clear what should be commented out to make the stdout sink work in 0.11 (the [documentation](https://github.com/snowplow/snowplow/wiki/Configure-the-Scala-Stream-Collector) refers to setting "stdout" for enabled).

https://github.com/snowplow/snowplow/blob/3ce332e37596b964831ca4dd32bb1054cfce5c2e/2-collectors/scala-stream-collector/examples/config.hocon.sample#L71

@aldemirenes

**Comment by BenFradet** [comment]
@miike what do you think about:

>To use stdout, comment or remove everything in the "collector.streams.sink" except "enabled" which should be set to "stdout"

?
