### ISSUE TITLE
Common: reenable publishLocal in travis for spark enrich tests to pass

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3516]

**Comment by BenFradet** [comment]
@knservis pls rename according to our naming convention: it should state what is being fixed and how and not what the problem is e.g. `Spark Enrich: enable dropwizard metrics sink` and not `Spark Enrich: dropwizard metrics sink is missing`

**Comment by alexanderdean** [comment]
This ticket needs renaming

**Comment by alexanderdean** [comment]
This ticket didn't make it into the R97 PR, so presumably it's either no longer required or should be pushed back?
