### ISSUE TITLE
Spark Enrich: add Snowplow Wire

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3518]
Includes:

* `enrich_started`
* `enrich_finished`

I also can see this as an independent project because it includes a lot of specific (spark-independent) logic:

* Schema keys for all events and contexts
* Getting performance-metrics from CloudWatch
* Listing S3 (though it might be better to list HDFS)
* Tracking-code

For recap what we decided to use (and I'm going to use this issue as master-ticket):

### Spark enrich started:
* version
* configuration: enrichments ...
* raw input sizes (array of longs)
* cluster ID
* run ID

### Spark enrich ends:
* version
* event count
* good count
* bad count
* good output sizes (array of longs)
* bad output sizes (array of longs)
* performance context (cloudwatch?)
* cluster ID
* run ID

### Shred start:
* version
* configuration: deduplication enabled …
* input sizes

### Shred ends:
* version
* [vendor + name + version + schema tech + count + event/context]
* number of events deduplication [per type]
* output sizes
* performance context (cloudwatch?)

### RDB loader starts:
* version
* configuration
* cluster ID

### RBD step events

Each step can have specific metrics: Load, Discover, Analyze

### Others

* Success event
* Failure event

### Discover good (Post RDB loader)
* Successful events per minute
* Number of successful events by minute
* Tracker version

### Discover bad
* Count by failure type
* Bad event analysis

/cc @dmpacheco @bogaert @stdfalse @jbeemster

**Comment by alexanderdean** [comment]
Looks great! I think you're missing shred cardinality under `Shred ends`...

**Comment by miike** [comment]
This would be amazing!

**Comment by bogaert** [comment]
Super excited about this!

**Comment by chuwy** [comment]
Replaced by Snowplow Observability approach https://discourse.snowplowanalytics.com/t/observability-for-the-snowplow-streaming-pipeline/1955
