### ISSUE TITLE
Placeholder for kinesis-tee: filters/routes events using JavaScript

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#352]
Examples of filtering/routing might include:

* A company's own IP addresses
* Specific useragents
* Specific geo-locations
* Specific event types

These can all be filtered by building SQL views on the data *today*, but some users might want to discard those events earlier, i.e. in the ETL.

Potential implementations:

1. Blacklists for specific IP addresses/useragents/geo-locations/event types
2. GA-style regexp support
3. A scripting language? Could be cool to write custom scripts to filter out events

/cc @yalisassoon

**Comment by alexanderdean** [comment]
Updated title as this would be much better done as a new job in the flow than as a set of filters in Common Enrich. If done in Common Enrich, we will be in the situation where rows are being silently filtered with no audit trail...

**Comment by alexanderdean** [comment]
We will implement this as a new Kinesis app, kinesis-tee...

**Comment by fblundun** [comment]
Closing in favour of https://github.com/snowplow/kinesis-tee
