### ISSUE TITLE
Redshift: widen sensitive columns in atomic.events to support pseudonymization

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3528]
Although we are only initially supporting SHA256 for hashing (see #3472), we will bump these columns to 512 width as this is a relatively painful process (and we will likely want to support SHA512 hashing and also encryption options later on).

**Comment by alexanderdean** [comment]
@yalisassoon can you please review:

https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/atomic-def.sql

and add to this ticket the full list of the sensitive columns which need to be widened?

**Comment by knservis** [comment]
We need to think about this in context of this comment: https://github.com/snowplow/iglu-central/pull/664#issuecomment-351312945

**Comment by alexanderdean** [comment]
Nudge @yalisassoon

**Comment by yalisassoon** [comment]
Sorry for the delay - adding below:

* user_id
* user_ipaddress
* user_fingerprint
* domain_userid
* network_userid
* ip_organization
* ip_domain
* tr_orderid
* ti_orderid
* mkt_clickid
* refr_domain_userid
* domain_sessionid

**Comment by alexanderdean** [comment]
That's your list @knservis - let's widen to 256 if they are currently <256, so we can support SHA_512. I believe they are all strings, so there shouldn't any other issues with this.

**Comment by knservis** [comment]
@alexanderdean sha-512 is 128 characters long as a hex string.

**Comment by alexanderdean** [comment]
Edited!

**Comment by alexanderdean** [comment]
What about se_label @yalisassoon ?

**Comment by yalisassoon** [comment]
Any of the se_ fields could require anonymization but I think they're all long enough already?

**Comment by alexanderdean** [comment]
Yep they are - good point!
