### ISSUE TITLE
EmrEtlRunner: add --ignore-lock-on-start option

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3537]
This is because we can create a race condition by deleting the lock and then creating a new one after EmrEtlRunner boots.

This just means ignore-lock-on-start, it will still delete the lock at the end.

**Comment by jbeemster** [comment]
Or possibly --ignore-lock - so that it can continue in circumstances that you control?

**Comment by alexanderdean** [comment]
Welp yes, typo, fixed
