### ISSUE TITLE
EmrEtlRunner: recover from RestClient::ServiceUnavailable when making status checks

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3539]
At the moment, eer makes recurrent status checks to see where the pipeline is at.

However, somewhat frequently, emr responds with:

```
RestClient::ServiceUnavailable (503 Service Unavailable)
```

which causes eer to fail but the job to succeed.

**Comment by alexanderdean** [comment]
See also #3468 (let's harmonize the names or tickets)
