### ISSUE TITLE
EmrEtlRunner: add retry logic for EMR bootstrap timeouts

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#354]
We have around a 1% failure rate where EMR "fails to launch". Failure to launch looks like this:

* Elapsed time 0 minutes
* All steps `CANCELLED`
* "Last State Change: On the master instance (i-3f33d270), bootstrap action 1 timed out executing"

Potentially we could update EmrEtlRunner to check for failure to launch if the job fails. EmrEtlRunner could back off for first 5 minutes and then 15 minutes to reduce the chances of repeated failure to launches.

@yalisassoon  could you take a look at these failure to launches:

* j-2EVSD2FM0RL6X
* j-18Z91SJL8WNYH

And let me know if "All steps `CANCELLED` is a safe way of detecting failure to launch?

**Comment by alexanderdean** [comment]
It looks like this:

```
SHUTTING_DOWN [On the master instance (i-xxx), bootstrap action 1 timed out executing] ~ elapsed time n/a [ - ] - 1. Elasticity Scalding Step: Enrich Raw Events: CANCELLED ~ elapsed time n/a [ - ] - 2. Elasticity S3DistCp Step: Enriched HDFS -> S3: CANCELLED ~ elapsed time n/a [ - ] - 3. Elasticity Scalding Step: Shred Enriched Events: CANCELLED ~ elapsed time n/a [ - ] - 4. Elasticity S3DistCp Step: Shredded HDFS -> S3: CANCELLED ~ elapsed time n/a [ - ])
```

**Comment by alexanderdean** [comment]
Here's another:

```
On the master instance (i-xxx), after bootstrap actions were run Hadoop failed to launch] ~ elapsed time n/a [ - 2015-04-10 10:16:22 UTC]
 - 1. Elasticity S3DistCp Step: Raw S3 -> HDFS: CANCELLED ~ elapsed time n/a [ - ]
 - 2. Elasticity Scalding Step: Enrich Raw Events: CANCELLED ~ elapsed time n/a [ - ]
 - 3. Elasticity S3DistCp Step: Enriched HDFS -> S3: CANCELLED ~ elapsed time n/a [ - ]
 - 4. Elasticity Scalding Step: Shred Enriched Events: CANCELLED ~ elapsed time n/a [ - ]
 - 5. Elasticity S3DistCp Step: Shredded HDFS -> S3: CANCELLED ~ elapsed time n/a [ - ]):
```

**Comment by fblundun** [comment]
There is something else that sets all statuses to CANCELLED: manually terminating the cluster before any step has completed. (I found this out by accident - I terminated a job without killing the EmrEtlRunner and the retry logic got called.)

So I guess we should implement the regex for LastStateChangeReason, maybe just searching for the string "bootstrap action"?

**Comment by alexanderdean** [comment]
Oh good catch Fred! Agree, let's check for bootstrap string...

**Comment by alexanderdean** [comment]
Hey @fblundun - there is another valid failure string for a bootstrap failure:

    Snowplow data pipeline: SHUTTING_DOWN [Master instance startup failed due to an internal error] ~ elapsed time n/a [ - ]

It would be great to support retry for this one too...

**Comment by fblundun** [comment]
In that case I'll try checking LastStateChangeReason for both "bootstrap action" or "Master instance startup failed" - that probably won't give any false positives.

**Comment by alexanderdean** [comment]
Thanks Fred!
