### ISSUE TITLE
Add explicit field requirements for ad impression and ad click tracking via pixel tracker

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3543]
Example: https://github.com/snowplow/snowplow/wiki/pixel-tracker#4-click-tracking

Have had issues with clients sending data without required fields - the process would be much easier if we explicitly specify that `targetUrl` must be a string with min length 1, for example.

**Comment by alexanderdean** [comment]
Is this something we should be fixing in the open-source documentation, and/or in the Snowplow Insights UI?

**Comment by colmsnowplow** [comment]
Actually this is a prime candidate for the insights UI, now that you mention it. I think most open source users would likely look at the schema before sending events/infer that this is required themselves.

**Comment by alexanderdean** [comment]
Closing this one then, please chat to Mike about this...
