### ISSUE TITLE
snowplow configuration

### ISSUE THREAD

**Issue by pawanpatil08** [snowplow/snowplow#3547]
I am new in snowplow and I want to configure javascript tracker in my web page i have some events on which i want to capture some information and sen it to backend for analysis.
some events like 
1. button click 
2. when hi search something in site.
please help me how should i do it with a  short example.

**Comment by chuwy** [comment]
Hello @pawanpatil08. As I mentioned [before](https://github.com/snowplow/snowplow-nodejs-tracker/issues/38) - we use Github issues for bug-reports and feature-requests only. Please, direct support questions to [our forums](https://discourse.snowplowanalytics.com/) - this is the right place for asking for help.

[Setup guide](https://github.com/snowplow/snowplow/wiki/Setting-up-Snowplow) is available on our wiki with examples for each particular tracker.

Closing this.

**Comment by pawanpatil08** [comment]
Sure thanks ..
I have not seen this  last notification
