### ISSUE TITLE
Scala Stream Collector: fix stdout sink configuration

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3550]
At the moment, one needs to specify `sink.enabled = stdoutconfig` instead of `sink.enabled = stdout`, relates to #3515

**Comment by alexanderdean** [comment]
Weird bug, what happened there?

**Comment by BenFradet** [comment]
the configuration value is based on the case object name which happens to be [StdoutConfig](https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/model.scala#L97).

**Comment by alexanderdean** [comment]
Got it
