### ISSUE TITLE
Scala Stream Collector: move cross domain configuration to enabled-style

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3556]
At the moment, there are configurations which are defined as:

```hocon
x {
  enabled = true/false
  restOfTheConfig = ...
}
```

and others defined as:

```hocon
x {
  restOfTheConfig = ...
}
```

and its presence or absence determines if the feature is used.

We should pick one and stick to it.

I tend to prefer the second one as less stuff you don't care about gets in your way.

wdyt @chuwy @alexanderdean ?

**Comment by alexanderdean** [comment]
Hmm good point. I think I prefer the first one because it's more templating friendly.  @chuwy what do you prefer?

**Comment by chuwy** [comment]
At least in JSON configurations we prefer first approach (even have linter for that). I also think that first approach is more explicit.

**Comment by BenFradet** [comment]
from @rbolkey :

>I looked at the thread there. I didn't see anyone propose using both Option at the top level along with an enabled field? You can kind of have both pieces of cake there. Missing block implies disabled (less pain for user's configuring). Present block has enabled defaulting to true, but you can template it to false if desired? Thoughts?

My personal view is that it might be kinda confusing, wdyt @chuwy @alexanderdean ?

**Comment by alexanderdean** [comment]
Not sure I quite understand @rbolkey's suggestion?

**Comment by BenFradet** [comment]
both

```conf
a {
  x {
    enabled = true/false
    restOfTheConfig = ...
  }
}
```

```conf
a {
}
```

are valid

**Comment by alexanderdean** [comment]
Not sure. Your call.
