### ISSUE TITLE
Scala Common Enrich: use iglu client for schema criterion matching

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3572]
The code here: https://github.com/snowplow/snowplow/blob/33b11191b42a9d7840e566ca8a6bd1073d74e9ce/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/apirequest/Input.scala#L200
and here:
https://github.com/snowplow/snowplow/blob/33b11191b42a9d7840e566ca8a6bd1073d74e9ce/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/Input.scala#L230

Is exactly the same. We should probably be using iglu-scala-client for this

**Comment by chuwy** [comment]
We should be using Iglu Scala Core for this https://github.com/snowplow/iglu-scala-client/issues/20

**Comment by chuwy** [comment]
Done in https://github.com/snowplow/snowplow/pull/4254
