### ISSUE TITLE
Documentation: Configuring storage targets mistakes

### ISSUE THREAD

**Issue by jethron** [snowplow/snowplow#3576]
A few mistakes on [Step 4: Configuring storage targets](https://github.com/snowplow/snowplow/wiki/Configuring-storage-targets)

- PostgreSQL `purpose` property suggests the value `ENRICHED_DATA`, schema requires `ENRICHED_EVENTS`
- Redshift `purpose` property suggests the value `ENRICHED_DATA`, schema requires `ENRICHED_EVENTS`
- DynamoDB schema links to version 2-0-0, which doesn't exist; the latest is 1-0-1
- Redshift schema links to version 2-0-0; the latest is 2-1-0

**Comment by chuwy** [comment]
Thank you @jethron! We've fixed these oversights now.
