### ISSUE TITLE
Stream Enrich: update config.hocon.sample to include a PII output stream

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3579]
Update to https://github.com/snowplow/snowplow/blob/master/3-enrich/stream-enrich/examples/config.hocon.sample#L48-L52

**Comment by knservis** [comment]
@BenFradet Should we just include a PII section with an output stream name in the hocon?

**Comment by BenFradet** [comment]
which configuration parameters will you need apart from the output stream name?

**Comment by knservis** [comment]
@BenFradet I don't think there is something else. Is/should the user be able to select a different type of stream for the different outputs (e.g. good to kinesis, pii to kafka)?

**Comment by BenFradet** [comment]
no, we've been trying to limit the size of the matrix of supported configurations :+1:

**Comment by knservis** [comment]
@BenFradet can we come up with a better title? Or I could simply merge this to the corresponding issue: https://github.com/snowplow/snowplow/issues/3580

**Comment by BenFradet** [comment]
done
