### ISSUE TITLE
Scala Common Enrich: extend PII Enrichment to include identification events in EnrichedEvent

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3580]

**Comment by alexanderdean** [comment]
The name of this ticket needs a bit of work, or we might split it into two tickets.

**Comment by knservis** [comment]
@alexanderdean Does that name capture the work?

**Comment by alexanderdean** [comment]
Yep I think that's good for now. We'll probably want to rename EnrichedEvent in due course, as that envelope will technically contain multiple enriched events now.

**Comment by knservis** [comment]
Depends on https://github.com/snowplow/iglu-central/pull/708

**Comment by knservis** [comment]
@alexanderdean @yalisassoon Before releasing part 2 we may want to consider emitting a salt if it is finally added (We will need to modify iglu-central schemas for config and the event). See discussion here https://github.com/snowplow/snowplow/issues/3648 
Should we hold off till we have made a decision?

**Comment by alexanderdean** [comment]
Hey @knservis - what do you mean by

> emitting a salt

Surely the salt should be very closely held?

**Comment by alexanderdean** [comment]
BTW I've scheduled https://github.com/snowplow/snowplow/issues/3648

**Comment by knservis** [comment]
@alexanderdean Yes the salt should not be emitted. It should only be in config.
