### ISSUE TITLE
Stream Enrich: extend PII Enrichment to output a stream of PII identification events

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3581]

**Comment by knservis** [comment]
Depends on https://github.com/snowplow/iglu-central/pull/708

**Comment by knservis** [comment]
@BenFradet This is commit is not yet properly tested. I would like to add some test to stream enrich that will run the complete pipeline, including sending and receiving events based on something like https://github.com/mhart/kinesalite . Does that sound like a good idea to you?

**Comment by BenFradet** [comment]
I've been thinking about this lately and, given that the migration to beam is not a long way off (where, ideally, we'll be able to run some end to end tests independently of the targeted storage), I wonder if it's wise to spend time on testing kinesis-only things.

Basically, it boils down to how big of a time investment this is going to be.

wdyt?

**Comment by knservis** [comment]
@BenFradet I do not believe it will be a bid time investment. From experience, I have set up similar tests before in 1-2 days. I am not partial to kinesis. It could be anything (now that I think about it maybe mock kafka is a better idea), but I think end to end testing is important to add soon.

**Comment by alexanderdean** [comment]
SGTM, I think it's worth adding...

**Comment by BenFradet** [comment]
@knservis kafka would indeed be easier as you can do everything programmatically without resorting to another project.

**Comment by knservis** [comment]
Added https://github.com/snowplow/snowplow/issues/3639 (Not sure about title)
