### ISSUE TITLE
Placeholder for coming up with a 1-1-0 of the pii_enrichment_config

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3583]
This needs to be able to indicate that we want the output stream written.

**Comment by knservis** [comment]
@alexanderdean Does this belong to iglu-central?

**Comment by alexanderdean** [comment]
Yep, you can migrate!

**Comment by knservis** [comment]
@alexanderdean Done. Created https://github.com/snowplow/iglu-central/issues/702

**Comment by alexanderdean** [comment]
Removed milestone
