### ISSUE TITLE
Documentation: Setting up Redshift with RDBLoader SSH tunnel should mention passphrase requirement

### ISSUE THREAD

**Issue by jethron** [snowplow/snowplow#3584]
In the documentation for [Setting up Redshift](https://github.com/snowplow/snowplow/wiki/Setting-up-Redshift#load), it should be noted that the RDB Loader SSH key you store in EC2 Parameter Store _must_ have a passphrase, otherwise, the underlying JSch library considers the private key invalid and aborts the load for that target.

This may also be a bug against the [Iglu Redshift Config schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow.storage/redshift_config/jsonschema/2-1-0) because I couldn't get this feature to work at all until I updated my key to use a passphrase and updated the key in SSM, but passphrase is not a required parameter in the schema to indicate this would be a problem.

May also need to update the [blog post](https://snowplowanalytics.com/blog/2017/11/13/rdb-loader-r28-released/) that lists an example config without a passphrase implying that this works.

If there's an alternate solution to the 'invalid privatekey' error beyond setting a passphrase, feel free to close this, but that solved it for me.

**Comment by chuwy** [comment]
Hello @jethron,

Thank you very much for detailed report. However, I'm not sure I understand how the key **with** passphrase worked in the end, having that RDB Loader does not allow to use it and "passpharsed" key is basically useless without passpharse being applied.

I think most likely issue was in incorrectly uploaded key. Probably, you tried to copy key in buffer and paste it through AWS Console. This approach corrupts a key by adding special characters in the end. I recommend to upload key via following command:

```bash
$ aws ssm put-parameter --name "storage.redshift.tunnelkey" --type SecureString --value $(cat secret.key)
```

Where `$(cat secret.key)` ensures that key was uploaded correctly.

Please, let us know if this assumption is true - and thanks for reminder, I'm adding it to docs.

**Comment by chuwy** [comment]
I'm closing this, but @jethron, feel free to re-open if I misunderstood something.
