### ISSUE TITLE
Scala Common Enrich: add static analysis check

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3586]
Add scalastyle check either through an sbt plugin or through https://www.codacy.com/

**Comment by knservis** [comment]
@BenFradet Added scapegoat and scalastyle and made the test dependant on them (this can fail the tests). 
We should look into the rules here http://www.scalastyle.org/rules-1.0.0.html  and make a decision on scalastyle-config.xml

**Comment by alexanderdean** [comment]
De-milestoning pending our workshop

**Comment by benjben** [comment]
https://github.com/snowplow/snowplow-scala-project.g8/issues/11 will establish the tools that we want to use and we'll create issues based on the decisions.
