### ISSUE TITLE
Scala Stream Collector: truncate events exceeding the configured maximum size into a BadRow

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3587]
At the moment, only bad rows saying that the event was too big for the configured sink (e.g. 1mb for kinesis) are produced.

It would be useful to log those events for debugging purposes.

**Comment by alexanderdean** [comment]
As in log out in the stderr?

**Comment by BenFradet** [comment]
either that or truncate it into the BadRow

**Comment by alexanderdean** [comment]
I like the truncation as I don't want us to ever *have* to do log collection on the containers...

**Comment by BenFradet** [comment]
yeah I reread and remembered the original intent of this issue and it is indeed to log the row to stdout as it is already turned into bad rows.

**Comment by BenFradet** [comment]
Actually we could do both as oversized bad rows just take the size and not the content as input.

**Comment by alexanderdean** [comment]
I think from a PII / GDPR perspective we can't have bad rows going to stdout - as that represents a potential PII leak...

**Comment by BenFradet** [comment]
in this case I'll just truncate the initial event into the bad row as we originally discussed (going in circles on this one :fearful: )
