### ISSUE TITLE
Clojure Collector: unecoded URLs break payload parsing

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3592]
Payloads like the following:

```
2017-12-22 06:12:24    -   -   127.0.0.1 POST    127.0.0.1 /com.snowplowanalytics.snowplow/tp2 200 https://mywebsite.com?a=unencoded query param Mozilla   &cv=clj-1.1.0-tom-0.2.0   -   -   -   application%2Fjson%3B+charset%3DUTF-8   base64stuff
```

breaks with:

```
Line does not match raw event format for Clojure Collector
```

 during enrich because the referer is not encoded (`https://mywebsite.com?a=unencoded query param`)

Alternatively, we could consolidate payload parsing in [CljTomcatLoader](https://github.com/snowplow/snowplow/blob/03eae62dd366dd558ffc7c0e3e49d9c069290bee/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CljTomcatLoader.scala).

**Comment by chuwy** [comment]
Isn't it same as https://github.com/snowplow/snowplow/issues/2322?

**Comment by BenFradet** [comment]
exactly yes, should have looked into the closed tickets too :(.

@alexanderdean should we fix it anyway?

**Comment by alexanderdean** [comment]
Yes, we probably should keep it at least on our radar... Re-opened it and closing this as a dupe...
