### ISSUE TITLE
Spark Enrich: change Twitter repository url to https

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3593]
Currently the build is failing on a dependency issue: https://travis-ci.org/snowplow/snowplow/jobs/333179642 however the artefact seems to be there. 

Even though the artefact can be downloaded, there is a redirect http-> https for that request, which seems to cause the failure.

Changing the twitter repo to https fixes the issue (also sbt 1.1.0 did not seem to have that issue).

**Comment by BenFradet** [comment]
>however the artefact seems to be there.

I thought there was a redirect? so it's not actually there, changing the issue title to reflect that

**Comment by knservis** [comment]
@BenFradet I don't understand. There is a redirect to https.

**Comment by BenFradet** [comment]
The way I read the above desc is that we don't know why the build is failing. And by chance, we tried https and it worked.

A better desc would be that the old repo is issuing redirects to the same repo in https.

**Comment by BenFradet** [comment]
same issue here snowplow/scala-maxmind-iplookups#37 :(

**Comment by knservis** [comment]
👍  Build fixed by that change. We should probably add issues to upgrade sbt across the board anyway.

**Comment by BenFradet** [comment]
yup feel free to add it do the "SCE modernization" milestone (maybe not a great name), that's the milestone I created to do a massive cleanup of those kind of issues (moving away from scalaz, updating libraries, scala 2.12 and such).

**Comment by knservis** [comment]
@BenFradet sounds good although we should change the milestone name if we are going to add this issue (as this is SE not SCE).

**Comment by BenFradet** [comment]
yeah feel free to rename (pretty much every project will be affected)

**Comment by BenFradet** [comment]
welp I'm gonna have to steal this for #3250
