### ISSUE TITLE
EmrEtlRunner: add bootstrap action to prepare AMI 5.x for Snowplow

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3601]
Migrated from https://github.com/snowplow/snowplow-rdb-loader/issues/85

**Comment by chuwy** [comment]
To continue discussion...

> I don't know if this should go alongside snowplow-ami4-bootstrap-0.2.0.sh, or if we should create a snowplow-ami5-bootstrap-0.3.0.sh and include this in it...

I think this should be a separate script that is not added by EER automatically as it happens with `snowplow-ami4-bootstrap-0.2.0.sh` now, but user can enable it explicitly in `config.yml`. In the end this is unnecessary script helpful to only small portion of users with:

1. RDB Loader
2. NAT Gateway
3. Long enough loading times

**Comment by jbeemster** [comment]
I guess the other-side of this is if we think that this script will have any adverse impact on the "normal" setup using either a NAT Instance or with EMR being able to communicate with Redshift without having to traverse a NAT.

If it will not have any impact it is much easier to add it to the existing script which means less updating for us internally and ensuring that others that stumble on this issue won't have to figure out what extra script they need to add into their config to have things working again.

**Comment by alexanderdean** [comment]
Agree with @jbeemster - the whole point of EmrEtlRunner is to reduce the "support surface area" for new users and ourselves...

**Comment by chuwy** [comment]
Ok, fixing title.

**Comment by chuwy** [comment]
Some more context on this. 

1. I've added this as new `snowplow-ami5-bootstrap.sh` with **only** this NAT Gateway fix.
2. All previous bootstrap fixes are for AMI 3 and 4 and need to be deleted (https://github.com/snowplow/snowplow/issues/3497)
3. Right now we're adding this manually, but this should be done by EER, created ticket here https://github.com/snowplow/snowplow/issues/3609

**Comment by alexanderdean** [comment]
Thanks, scheduled those in!

**Comment by alexanderdean** [comment]
Thanks @chuwy - @BenFradet please ack this plan.
