### ISSUE TITLE
Scala Common Enrich: refactor EnrichmentRegistry to use only schema key for parsing

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3614]
There is no need to have the vendor and name in the config instance since they are already in the config schema. 
https://github.com/snowplow/iglu-central/issues/721#issuecomment-363732578

**Comment by alexanderdean** [comment]
Yes, this makes sense. @chuwy could you flesh out this ticket with your suggestions for replacing this?

**Comment by chuwy** [comment]
https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentRegistry.scala#L141

I think we can use this as a master-ticket with [EnrichmentRegistry](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentRegistry.scala#L141) refactoring. When parsing for specific enrichment's configuration it should rely only on `schema`. 

* `name` should be human-readable
* `vendor` should be dropped altogether
* optional `id` should be added to identify configuration instance (?)

It also requires to create tickets in Iglu Central for each configuration.

It can be paired with this [enrichments refactoring](https://github.com/snowplow/snowplow/issues/2260), looks like a good fit.

**Comment by alexanderdean** [comment]
Yes, we should add the optional `id` to help identify the configuration instance.

I also wonder if we should use this to properly vendor all the enrichment configs, as some are a bit non-standard...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/237
