### ISSUE TITLE
Snowplow wiki code example typo

### ISSUE THREAD

**Issue by pm-fawkes** [snowplow/snowplow#3615]
on the wiki page
https://github.com/snowplow/snowplow/wiki/Integrating-javascript-tags-with-Google-Tag-Manager#snowplow-setup

one of the examples:
```javascript
<!-- Snowplow structured event tracking -->
<script type="text/javascript">
window.snowplow('trackStructEvent', '{{eventCategory}}', '{{eventAction}}', '{{eventLabel}}', '{{eventProperty}}' '{{eventValue}}');
</script>
````
The method is **missing a comma in between the last 2 arguments.**
A tiny change but it just might save someone else the pain of wondering why the example code is not working :smile:

**Comment by alexanderdean** [comment]
Thanks @pm-fawkes ! Assigning...
