### ISSUE TITLE
./snowplow-emr-etl-runner: rule 24: exec: java: not found

### ISSUE THREAD

**Issue by brent1991** [snowplow/snowplow#3616]
Hi all, 

I'm at the stage to run my snowplow-emr-etl-runner with the following command: ./snowplow-emr-etl-runner run -c config/config.yml -r config/iglu_resolver.json. I'm ending up with the following message: 

./snowplow-emr-etl-runner: rule 24: exec: java: not found

Does anyone know how to solve this?

Perhapse necessary: 
I just finished configuring my config.yml and created the following structure:

snowplow-etl
snowplow-emr-etl-runner
- config
  - targets
  config.yml
   iglu_resolver
- snowplow
   the whole repository.

If anyone knows how to solve this please let me know. 

Thanks in advance.

**Comment by alexanderdean** [comment]
Please direct support questions to our forums:

https://discourse.snowplowanalytics.com/
