### ISSUE TITLE
Zendesk webhook doesn't work when content is localized

### ISSUE THREAD

**Issue by razius** [snowplow/snowplow#3622]
The value of the `status` field is unfortunately translated when it is pushed to the collector making it fail during validation.

```
error: instance value ("Løst") not found in enum (possible values: ["New","Open","Pending","On-hold","Solved","Closed"]) level: "error" schema: {"loadingURI":"#","pointer":"/properties/status"} instance: {"pointer":"/status"} domain: "validation" keyword: "enum" value: "Løst" enum: ["New","Open","Pending","On-hold","Solved","Closed"]
```

See [here](https://support.zendesk.com/hc/en-us/community/posts/204083438-Language-Independent-Ticket-Field-Values) for additional details.

**Comment by alexanderdean** [comment]
Thanks for flagging - what a terrible implementation decision by Zendesk...

**Comment by miike** [comment]
@razius Could you list all the fields you've seen that are subject to the translation issue and I'll patch and update them?

**Comment by razius** [comment]
`status` for which you can get the translations from [here](https://gist.github.com/jadrol/8d530cfd726856c3b1199103eb83f4eb) and `ticketType` for which I couldn't find the translations so I've just set it to null. 

Do you want to do the language mapping or drop the validation?

**Comment by alexanderdean** [comment]
Good Q @razius - adding @ihortom to the ticket who built the webhook integration on our side...

**Comment by ihortom** [comment]
@alexanderdean, looks like we do not have much choice as to drop `enum`:

```
    . . .
    "priority": {
        "type": ["string", "null"]
    },
    "status": {
        "type": ["string"]
    },
    "tags": {
        "type": ["string", "null"]
    },
    "ticketType": {
        "type": ["string", "null"]
    },
    . . .
```

That also means amending the table `com_zendesk_snowplow_ticket_updated_1` with the extended length of the corresponding `VARCHAR` fields to cater for longer (non-English) values.

**Comment by alexanderdean** [comment]
I think you are probably right... It's probably safest to fix this in @stdfalse's data model...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/238
