### ISSUE TITLE
Common: fix CHANGELOG entry for R97

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3630]
It's a mess - I'm disappointed this got merged:

* The entry for Spark Enrich's scala-common-enrich bump is missing
* The entry for Scala Common Enrich's own version bump is missing 

/cc @knservis

**Comment by BenFradet** [comment]
yes that's my bad I did the diff between the commits and the entries instead of between the issues and the entries.

Problem is there are no commits for those entries

**Comment by alexanderdean** [comment]
Np - we can just put placeholder entries in so the CHANGELOG coheres...
