### ISSUE TITLE
leaked connection

### ISSUE THREAD

**Issue by sowieso-fruehling** [snowplow/snowplow#3641]
I'm using your snowplow-java-tracker:0.8.2 and I have a following issue occuring:

> WARN  [OkHttp ConnectionPool][][] c.s.o.OkHttpClient 305: A connection to <my_url> was leaked. Did you forget to close a response body?

After debugging it I saw that your code is calling AbstractHttpClientAdapter.post(SelfDescribingJson payload) which calls OkHttpClientAdapter.doPost(String url, String payload) which calls com.squareup.okhttp.Call.execute() and documentation for this method says:

> The caller may read the response body with the response's
>    * {@link Response#body} method.  To facilitate connection recycling, callers
>    * should always {@link ResponseBody#close() close the response body}.

and you're not doing it in your library. OkHttpClientAdapter.doPost(String url, String payload) returns response code and never closes response body. Reading other resources it seems that the warning I get is exactly the consequence of not closing it 

Did I get something wrong here, or it's a bug?

**Comment by alexanderdean** [comment]
Hi @sowieso-fruehling - please open your issue in the relevant repo:

https://github.com/snowplow/snowplow-java-tracker/issues
