### ISSUE TITLE
Stream Enrich: rename etl version from kinesis to stream-enrich

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3642]
At the moment it's `kinesis-0.14.0` which doesn't make a lot of sense anymore.

**Comment by alexanderdean** [comment]
Are yout alking about the variable name or its value?

**Comment by BenFradet** [comment]
value

**Comment by alexanderdean** [comment]
What do you want the new value to be?

**Comment by BenFradet** [comment]
either `enrich-0.14.0` or `{{stream-processing-tech}}-enrich-0.14.0`

**Comment by alexanderdean** [comment]
Why not just stream-enrich-0.14.0? That's the component name?

**Comment by BenFradet** [comment]
yup, don't have strong opinions, just don't want to leave kinesis

**Comment by alexanderdean** [comment]
Cool, let's go with stream-enrich-${version}
