### ISSUE TITLE
Scala Common Enrich: bump user-agent-utils to 1.21

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3656]
Or we could find a replacement as this library just entered eol: https://github.com/HaraldWalker/user-agent-utils

assigning to the next milestone working on sce

for reference: https://snowplow.zendesk.com/agent/tickets/8035

**Comment by knservis** [comment]
I am not brave enough to change libraries for this for now (and deal with the fallout). I think it would need extended testing including measuring impact in client data. Bumping the library for now I think is the right thing for now and schedule a new library soon in 2018. What do you think @alexanderdean ?

**Comment by alexanderdean** [comment]
Yes, we just bump for now. We are looking at Wurfl as another enrichment option (we would never swap out the underlying implementation of the existing enrichment).
