### ISSUE TITLE
Scala Common Enrich: update IP Lookups Enrichment to support non-legacy database

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3672]

**Comment by alexanderdean** [comment]
This is separate from #3675 because that bump doesn't *itself* dictate the change of behavior (merely that the new behavior is available).

**Comment by tmacedo** [comment]
@alexanderdean that was the case initially but https://github.com/snowplow/scala-maxmind-iplookups/pull/35/commits/4ffd84b78469a367f7cf1c756b71d4aafddd49f6 actually changed the IpLocation class.

**Comment by alexanderdean** [comment]
No problem @tmacedo, thanks for clarifyin
