### ISSUE TITLE
Python tracker documentation errors

### ISSUE THREAD

**Issue by jethron** [snowplow/snowplow#3678]
Documentation examples for the [Python tracker](https://github.com/snowplow/snowplow/wiki/Python-Tracker#set-useragent) methods `set_timezone`, `set_ip_address`, `set_useragent`, `set_domain_user_id`, and `set_network_user_id` are incorrect.

- `set_timezone` suggests using a method `timezone`, which doesn't exist
- The rest all indicate they are members of a `Tracker` instance (`tracker.set_useragent` etc), but are actually members of `Subject` instances. (`tracker.subject.set_useragent`) and should follow the convention of using e.g. `s.set_useragent`

**Comment by BenFradet** [comment]
Thanks for flagging :+1:

**Comment by alexanderdean** [comment]
This ticket was in the right place @BenFradet - @ihortom will tackle this.

**Comment by ihortom** [comment]
Done.
