### ISSUE TITLE
EmrEtlRunner: add CI/CD to update AMI bootstrap scripts

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3683]
From https://github.com/snowplow/snowplow/tree/master/3-enrich/emr-etl-runner/bin to s3://snowplow-hosted-assets

Hey @BenFradet, am I right that we can use existing credentials for that?

**Comment by chuwy** [comment]
I think we should make it very explicit in CI/CD process that we want to upload/update those scripts, it looks like a bit scary for me to re-upload them on each EmrEtlRunner release.

**Comment by BenFradet** [comment]
>Hey @BenFradet, am I right that we can use existing credentials for that?

yup
