### ISSUE TITLE
EmrEtlRunner: add stream_config.yml.sample

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3685]
`aws.s3.buckets.enrich.stream` required for https://github.com/snowplow/snowplow/issues/3606. Empty by default

**Comment by chuwy** [comment]
Renamed ticket to reflect the fact that config.yml for stream mode has a lot of differences.

**Comment by alexanderdean** [comment]
Commit doesn't correspond yet

**Comment by alexanderdean** [comment]
Why is there a change to `emr_job.rb` in this commit?

**Comment by chuwy** [comment]
Wondering about it too. Will fix.
