### ISSUE TITLE
Common: install Ruby 2.4.3 before deploy

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3689]
Since dpl 1.9.0, it is not possible to get away with only jruby for deployments (c.f. travis-ci/dpl#778).

**Comment by chuwy** [comment]
Are we also going to avoid `rvm implode` as advised in that ticket?

**Comment by BenFradet** [comment]
We can't as specified in the ticket:

>We've had to reinstall rvm manually because of travis-ci/travis-ci#8717, maybe this is linked?

Unless you want to update bundler, I think it's been fixed in the latest version

**Comment by BenFradet** [comment]
I'll log an issue detailing that
