### ISSUE TITLE
EmrEtlRunner: bump bundler to 1.16.2

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3691]
Bundler is part of the default gems on travis and has to be reinstalled through hacks (c.f. https://github.com/snowplow/snowplow/blob/a1bf0921418d96b5a0948d16ed72be518f2d6919/.travis.yml#L54-L59 and travis-ci/travis-ci#8717).

However, jruby is the only ruby version which remains and so we've had to reinstall a ruby version before deploy in #3689 because of travis-ci/dpl#778.

Once we upgrade bundler, all of this can hopefully be removed.

**Comment by BenFradet** [comment]
descheduling, bundler on travis is 1.16.0 which doesn't contain the necessary fix.

**Comment by peel** [comment]
Triage: not needed, bumped to 2.x series in snowplow/emr-etl-runner new home
