### ISSUE TITLE
Add possibility to set timeout

### ISSUE THREAD

**Issue by asamoilich** [snowplow/snowplow#3693]
During integration of your tool we found out that with slow connection we got canceled status with error : **net_error = -3 (ERR_ABORTED)** for requests with > **5sec** time.

I had load https://d1fc8wv8zag5ca.cloudfront.net/2.6.2/sp.js and change there timeout to 10seconds.
After this changes our requests got success status.

**Question:** is it possible to add new param to set timeout ?

**For example:**
window.snowplow('newTracker', 'cj', '${TRACKER_PIXEL}', {
    appId: '${APP_ID}',
    cookieDomain: '${COOKIE_DOMAIN}',
    **timeout: 10000**
});

**Comment by BenFradet** [comment]
Could you mention your issue to [our Discourse forum](https://discourse.snowplowanalytics.com/), people will be able to help you there?

We try to keep github issues for code changes in the appropriate code base.

**Comment by asamoilich** [comment]
Ok, will do. thx!
