### ISSUE TITLE
Scala Common Enrich: add OpenCageData reverse geocoding enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3695]
For converting lat,long into location.

Using @nmdguerreiro's https://github.com/nmdguerreiro/scala-opencage-geocoder

Would be useful in cases where either the event already has lat,long at time of creation, or the IP Lookups Enrichment has already been run.

**Comment by freyfogle** [comment]
@tonicebrian is available to work on this, will follow up with Yali via email

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/81
