### ISSUE TITLE
iOS Tracker: add application_foreground event

### ISSUE THREAD

**Issue by keanerobinson** [snowplow/snowplow#3696]
Issue opened to push for automatic app foreground tracking  on iOS equivalent to the [Android 0.6.0](https://snowplowanalytics.com/blog/2016/08/29/snowplow-android-tracker-0.6.0-released-with-automatic-crash-tracking/) release.

**Comment by alexanderdean** [comment]
Let's migrate this into the iOS Tracker's own issue tracker

**Comment by keanerobinson** [comment]
Closing in favour of Obj C Tracker issue [349](https://github.com/snowplow/snowplow-objc-tracker/issues/349).
