### ISSUE TITLE
Documentation: update on GCP setup guides

### ISSUE THREAD

**Issue by misterpig** [snowplow/snowplow#3700]
## Snowplow GCP Setup Guide edit

The "Setting up the Scala Stream Collector on GCP" link on https://github.com/snowplow/snowplow/wiki/GCP:-Getting-Started is broken.

#### 1. Setting up the Scala Stream Collector 
[[link](https://github.com/snowplow/snowplow/wiki/GCP:-Setting-up-the-Scala-Stream-Collector)]
- gcloud command should be “$ gcloud auth application-default login”

**4b-1. via the dashboard**

- *Source filter* allows IP ranges instead of “Allow from any source”
- *Allowed protocols and ports* name changed to *Protocols and ports*

**4c. a load balanced auto-scaling GCP cluster**

- Following texts are wrapped in markdown code format:

```
* Under _Networking_, add a tag, such as "collector". (This is needed to add a Firewall rule)
* Under _Management_ "Startup script" add the following script (changing the relevant fields for
```

- Following text should be in bullet form:

_ Under Host and path rules: you can just make sure that the backend service selected is the one we just created

#### 2. Setting up Stream Enricher
[[link](https://github.com/snowplow/snowplow/wiki/GCP:-Setting-up-Stream-Enrich)]
- Also need to enable the *Datastore* API
- gcloud command should be “$ gcloud auth application-default login”

**4a. locally (useful for testing)**

- "To run the collector locally..." should be "To run the enricher locally..."

**4c. a load balanced auto-scaling GCP cluster**

- Remove ‘$’ sign in front of command, jar name is missing a ‘b’ in pubsub in:

`$ java -jar snowplow-stream-enrich-google-pusub-<VERSION>.jar --config <YOUR-CONFIG-FILE-NAME> --resolver datastore:resolver/iglu --enrichments datastore:enrichment/enrichment`

**Comment by BenFradet** [comment]
Thanks a lot, everything should be fixed now.

**Comment by alexanderdean** [comment]
Cheers @misterpig !
