### ISSUE TITLE
Stream Enrich: force jackson-dataformat-cbor to 2.9.3

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3701]
Currently the maxmind library uses `jackson-core` version 2.9.3 while the aws sdk uses `jackson-dataformat-cbor` version 2.6.7.

Downgrading makes the enrichment fail at runtime.
Doing nothing forces us to disable the CBOR wire-protocol by passing the `-Dcom.amazonaws.sdk.disableCbor` property which can have a performance impact.
Upgrading solves our situation.

**Comment by alexanderdean** [comment]
What does force mean in this context (I guess I'll see in the commit!)

**Comment by BenFradet** [comment]
we have to add the dependency ourself despite the fact that we don't use it
