### ISSUE TITLE
EmrEtlRunner Not working

### ISSUE THREAD

**Issue by miteshup** [snowplow/snowplow#3706]
Hi All,

I am trying to run the EmrEtlRunner for ernichment the data.

I have done the basic setup for it by downloading the required resources and run below command to run.

$ ./snowplow-emr-etl-runner run --config Emr_Config.yml

Here Emr_Config.yml is my configuration file , that i am using .

While , i am executing above command . i am getting below error.

![error](https://user-images.githubusercontent.com/30036395/38083200-8c40d32c-3366-11e8-858c-0086a3aa2e17.png)

You also can find the attached configuration file , that i have used.

[Emr_Config.txt](https://github.com/snowplow/snowplow/files/1859586/Emr_Config.txt)

Please suggest the above issue.

**Comment by BenFradet** [comment]
Please, log your support requests to [our Discourse forum](https://discourse.snowplowanalytics.com/).
