### ISSUE TITLE
Clojure Collector: retrieve configuration only through JVM properties

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3709]
java 8 tomcat 8 AMIs do not rely on environment variables at all, all configuration is passed through JVM properties.

This is in contrast with the clojure collector where `PARAMX` configuration parameters are retrieved through JVM properties whereas `SP_` configuration parameters are retrieved through env variables.

**Comment by alexanderdean** [comment]
How is this behavior change going to look in the Beanstalk configuration UI?

**Comment by BenFradet** [comment]
`SP_XX` configurations will work while right now on recent AMIs they don't, nothing wrt to the ui will change.

**Comment by alexanderdean** [comment]
Got it, thanks
