### ISSUE TITLE
Scala Common Enrich: add Flatfile Enrichment 

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3713]
Supporting S3 and Blob Storage as a back-end.

Need to think about how the schema for the flatfile is defined. Maybe we finally need to add TSVs to Iglu.

**Comment by chuwy** [comment]
I just hope this is not going to involve JSONPaths...

**Comment by alexanderdean** [comment]
Why would it involve JSON Paths?

**Comment by alexanderdean** [comment]
When we do this, it would be cool to use this as a test case or tutorial:

https://github.com/TheEconomist/big-mac-data

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/84
