### ISSUE TITLE
Wiki: add --resume-from rdb_load to the recovery instructions on the Batch pipeline steps page

### ISSUE THREAD

**Issue by bsweger** [snowplow/snowplow#3714]
Adding this as an issue because I don't think you can PR a GitHub wiki.

We rely heavily on the great [Batch pipeline steps](https://github.com/snowplow/snowplow/wiki/Batch-pipeline-steps) wiki page when recovering from problems in our snowplow pipeline job. I have a suggestion for improving the recovery instructions on step 13 (_i.e._, a failure in the rdbloader step).

In our case, rdbloader failed at the beginning, during data discovery. As part of our fix, we needed to run the pipeline starting at rdbloader, but the information on the wiki page doesn't explicitly say how to do that:

> The data load cannot result in partial load due to the use of COMMIT. However, if more than one data target is used you would need to rerun the EmrEtlRunner with the successfully loaded target removed from the config.yml configuration file to retry loading the "failed" target.

> Note: If the failure occurred at analyze stage, you can skip it with --resume-from archive_enriched option. To analyze, resume with --resume-from analyze

It would be helpful to have more specificity here about the individual pieces of rdbloader. Perhaps something like:

> The data loads are wrapped in a single transaction, so an rdbloader failure will not result in a partial load. However, if multiple data targets are used and some targetes already been loaded, you may need to temporarily remove those from `config.yml` during your recovery process.

> To start rdbloader from the beginning, use the `--resume-from rdb_load`option

> If the failure occurred at the analyze stage (_i.e._, after the data was successfully loaded), you can skip the analyze with the `--resume-from archive_enriched option`. To analyze, resume with `--resume-from analyze`

Am only speaking for one person here, but I followed the existing instructions and ended up archiving our enriched and shredded files w/o actually loading them to our Redshift target, which resulted in some extra recovery time. Hope that adding `--resume-from rdb_load` here can help someone else!

**Comment by BenFradet** [comment]
Good idea :+1: , @chuwy can you have a look?

**Comment by alexanderdean** [comment]
Adding @ihortom too

**Comment by ihortom** [comment]
Updated.

**Comment by bsweger** [comment]
Thanks--the new wording makes things clearer and is much appreciated!
