### ISSUE TITLE
Scala Common Enrich: allow cache to be disabled for API Request Enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3715]
Could be done by setting cacheSize to 0.

**Comment by alexanderdean** [comment]
This is already supported by the SQL Query Enrichment:

https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow.enrichments/sql_query_enrichment_config/jsonschema/1-0-0

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/85
