### ISSUE TITLE
EmrEtlRunner: check if whole enriched.good is non-empty in Stream Enrich mode

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3717]
In Stream Enrich mode, EmrEtlRunner check for non-emptiness only run folder `enriched/good/run=2018...`, while it should check whole `enriched/good`.

We need to change this: 

https://github.com/snowplow/snowplow/blob/ef39fdcdd957d4da9ffad25de2fde71eb8171dee/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb#L400-L402

to 

```ruby
csbe_good_loc = Sluice::Storage::S3::Location.new(csbe[:good])
unless Sluice::Storage::S3::is_empty?(s3, csbe_good_loc)
  raise DirectoryNotEmptyError, "Cannot safely add stream staging step to jobflow, #{csbe_good_loc} is not empty"
end
```

**Comment by alexanderdean** [comment]
Thanks @chuwy, good catch.

**Comment by alexanderdean** [comment]
Updated title
