### ISSUE TITLE
EmrEtlRunner: factor out steps-generating function

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3718]
It became quite hard to reason about after we added too much logic to it and I'd like to see it as a separate testable function:

https://github.com/snowplow/snowplow/blob/ef39fdcdd957d4da9ffad25de2fde71eb8171dee/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb#L55-L77

**Comment by alexanderdean** [comment]
Good idea
