### ISSUE TITLE
EmrEtlRunner: uncompress enriched files when copying to HDFS

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3719]
When combining the shred job with the output of stream enrich, files have to be gzipped by the s3 loader because lzo is not handled by shred (handling lzo files in the shredder could be an alternative solution).

This is #3525 waiting to happen all over again.

**Comment by alexanderdean** [comment]
Good point!

**Comment by alexanderdean** [comment]
> handling lzo files in the shredder

This probably wouldn't work so well (as the LZO format we use with raw events is a bit non-standard)...
