### ISSUE TITLE
Scala Common Enrich: unable to get salt from AWS Simple Systems Management

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3720]
This is likely just a configuration issue and I adding it here as a reminder (to at least document the configuration)

To replicate add something like ` "salt": {"ec2ParameterStore": {"parameterName":"pii-enrichment-test-salt"}}` in the pii enrichment config.

**Comment by knservis** [comment]
Closing this as a result of discussion here: https://github.com/snowplow/snowplow/pull/3669#issuecomment-382663457

**Comment by BenFradet** [comment]
descheduling
