### ISSUE TITLE
Stream Enrich: add context for parent event when generating PII event

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3724]
As per https://github.com/snowplow/snowplow/pull/3646#issuecomment-376171506
Corresponding schema https://github.com/snowplow/iglu-central/issues/768

**Comment by alexanderdean** [comment]
Please create something like https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/duplicate/jsonschema/1-0-0 but with a better name.
