### ISSUE TITLE
Beam Enrich: support enrichments relying on local files

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3736]
This is the trickiest enrichment since it relies on local files and so is treated separately.

Beam has a distributed cache similar to hadoop: http://spotify.github.io/scio/examples/DistCacheExample.scala.html

**Comment by BenFradet** [comment]
renamed since we now have other enrichments relying on local files, c.f. #3750

**Comment by alexanderdean** [comment]
We will have a third soon (referer-parser).
