### ISSUE TITLE
Beam Enrich: retrieve configuration from Google Cloud Datastore

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3738]

**Comment by BenFradet** [comment]
pushing back:

- scio has a stripped-down datastore dependency which will conflict with the "usual" sdk
- this is not aligned with the approach we want to take with the control plane

**Comment by alexanderdean** [comment]
Pushing back makes sense.

**Comment by peel** [comment]
Moved to: https://github.com/snowplow/beam-enrich/issues/28
