### ISSUE TITLE
Stream Enrich: make storeEnrichedEvents and flush behaviour uniform across sinks

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3741]
It seems that flush should be a blocking call to avoid queuing too many requests to the sink (backpressure?). That behaviour should be controlled by storeEnrichedEvents which, returning a true causes a flush in Source.scala. Currently that behaviour is not uniformly implemented across sinks:
* KinesisSink: Seems to follow that behaviour
* KafkaSink: storeEnrichedEvents always returns true, causing always a blocking call to flush
* NsqSink: 
  * storeEnrichedEvents returns !events.isEmpty (whats wrong with .nonEmpty?) 
  * Doc on  storeEnrichedEvents reads ` Whether to checkpoint` but that seems incorrect.
  * Flush does nothing anyway
* GooglePubSubSink: 
  *  storeEnrichedEvents creates futures and always returns true
  * flush does nothing

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/86
