### ISSUE TITLE
Stream Enrich: force jackson-databind to 2.9.3

### ISSUE THREAD

**Issue by asgergb** [snowplow/snowplow#3744]
Related to #3701 and #3702, we see a `java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)` error at runtime when using R103 (which is equivalent to master at the time of writing).

The solution for spark-enrich in #3702 fixes the problem in stream-enrich. That is, downgrading `geoip2` to version 2.5.0 for stream-enrich. I am unsure if this is the correct approach. If it is, I can easily submit a PR.

### Steps to reproduce:
```bash
git clone https://github.com/snowplow/snowplow
cd 3-enrich/stream-enrich
sbt "project kinesis" assembly
# Run target/scala-2.11/snowplow-stream-enrich-kinesis-0.16.0.jar with a config setup for Kinesis.
java -jar ...
```
We see `ERROR com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Worker.run caught exception, sleeping for 1000 milli seconds!` and the underlying error is `java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)`.

**Comment by BenFradet** [comment]
hey @asgergb , thanks for the report.

Could you help us reproduce as I haven't able to using the published artifacts in https://bintray.com/snowplow/snowplow-generic/snowplow-stream-enrich/0.16.0#files?

**Comment by asgergb** [comment]
@BenFradet Good idea, I'll try the official artifacts.

@alexanderdean Sure sounds like it if you can't reproduce the error. We're just doing a simple `sbt "project kinesis" assembly`, however, we are using a custom Docker image. There's really only Scala installed in that image except for some configuration files, though, and it has worked fine for the last ~1.5 years.

**Comment by asgergb** [comment]
Using the official artifact works. For now I have simply changed our build setup to use those instead. It will make the build simpler, and although we will lose the flexibility gained from building directly from source, it will work fine for us for now.

We are still using our custom Docker image so the only change I made is switching from `sbt "project kinesis" assembly` and a copy of the jar to the Docker image to using `wget artifact.zip` and unzipping. Hence, the build process does not work as expected for us. I will close the issue as there's not much point investigating it unless we run into the problem again later.

Anyway, thanks your time!

**Comment by BenFradet** [comment]
Reopening til we get to the bottom of this.

Also you might be interested in https://github.com/snowplow/snowplow-docker 👍

**Comment by alexanderdean** [comment]
Hey @asgergb - would you mind pinging me an email? Would love to have a chat about your Snowplow adoption.

**Comment by asgergb** [comment]
I can still reproduce this from a completely fresh clone and build. Here's a [log file](https://github.com/snowplow/snowplow/files/1952814/stream_enrich_jackson_error_issue_3744.txt). The referenced configuration is [here](https://github.com/Jyllands-Posten/SnowplowDeployments/tree/d8a99db93daa2c3a1bf0cc2f5dad7c8441c1f01a/stream-enrich/configuration).

Let me know if you need any more info.

**Comment by BenFradet** [comment]
I was able to find the root cause:

- our travis uses [`publishLocal` for SCE](https://github.com/snowplow/snowplow/blob/master/.travis.yml#L13) and that includes `jackson-databind-2.9.3`
- when releasing we use [publish](https://github.com/snowplow/snowplow/blob/master/.travis/deploy_sce.sh#L38) and that includes `jackson-databind-2.2.3` (c.f. http://search.maven.org/#artifactdetails%7Ccom.snowplowanalytics%7Csnowplow-common-enrich_2.11%7C0.32.0%7Cjar)

Apparently `publishLocal` relies on ivy2 whereas `publish` relies on maven and I guess they have different dependency resolution mechanisms.

**Comment by knservis** [comment]
@BenFradet I am curious how that is not an issue either way as com.maxmind.geoip2 requires databind 2.9.3 (https://github.com/maxmind/GeoIP2-java/blob/v2.11.0/pom.xml) which is required by com.snowplowanalytics:scala-maxmind-iplookups_2.11:0.4.0. 

If it works in some version I would not trust it as it works by coincidence. 

I had an issue just yesterday related to databind: https://github.com/snowplow/iglu-scala-client/issues/80

Our version is quite old (5 years old) and it is bound to get evicted.

**Comment by romansalin** [comment]
@BenFradet Thank you for the fix, but I have the same problem with "project kafka". I guess we should add this dependency as a common dependency for all projects.
