### ISSUE TITLE
Placeholder for encrypting S3 in Snowplow S3 Loader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3746]
This ticket is here to remind us that EmrEtlRunner should be able to support encrypted data when operating in "Stream Enrich" mode.

**Comment by BenFradet** [comment]
closing as duplicate of snowplow/snowplow-s3-loader#53

**Comment by BenFradet** [comment]
didn't read the desc, reopening

**Comment by BenFradet** [comment]
This doesn't result in any changes, closing

**Comment by alexanderdean** [comment]
De-scheduled
