### ISSUE TITLE
Scala Stream Collector: add options to configure secure, same-site and http-only for the cookie

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#3753]

**Comment by BenFradet** [comment]
maps nicely to https://doc.akka.io/api/akka-http/current/akka/http/scaladsl/model/headers/HttpCookie.html

**Comment by rammohan** [comment]
Is same-site option for cookie available?

**Comment by BenFradet** [comment]
not at the moment no, hence this issue :+1:

**Comment by aparra** [comment]
Hey folks. I've created a PR #4119 to address this issue. Looking forward to feedbacks.
