### ISSUE TITLE
Add Blackduck credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3754]
- `BLACKDUCK_HUB_USERNAME`
- `BLACKDUCK_HUB_PASSWORD`

**Comment by alexanderdean** [comment]
@jbeemster can you confirm which creds we should use here?

**Comment by BenFradet** [comment]
My investigations revealed that we'd need admin-level creds

**Comment by BenFradet** [comment]
pushing back

**Comment by BenFradet** [comment]
Moved away from blackduck, closing.
