### ISSUE TITLE
Scala Common Enrich: check PII event size

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3755]
When stream enrich sends a "good" event to the enriched-good stream it checks it's size and if it's beyond the preconfigured size limit it sends it to bad. 

With the addition of the PII stream we have decided to only use the "smallEnough" events to generate PII, **without checking the size of the PII event**, assuming that they will always be smaller than the parent event (which seems reasonable) but that is not the only option. 

Read [***here***](https://github.com/snowplow/snowplow/pull/3646#discussion_r187265023) for more info.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/30
