### ISSUE TITLE
Explore the possibility of fragmenting large Enriched Events

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3756]
In stream enrich if the event is too large, it cannot be transmitted and it is dropped. Further more we assume that PII events are small enough when their parent event is small enough (Read more [***here***](https://github.com/snowplow/snowplow/pull/3646#discussion_r187265023) and [***here***](https://github.com/snowplow/snowplow/issues/3755). 

One alternative would be to create an event fragmentation and reassembly protocol. 

We will need to remember that most products operate on single events so that may not be practicable.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/31
