### ISSUE TITLE
Scala Common Enrich: add HTTP remote adapter

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow#3760]
I was thinking about offloading some of the processes that the Adapter does, via Akka to the other machines. This might help a lot for performance and scalability of stream enrich component when handling different amount of traffic during the day.

My design would be like this:
- Hocon config file:  It would have a setting for RemoteAdapters, with the vendor name.
- AdapterRegistry: It would receive the setting from config file for the new vendor names.
- RemoteAdaptor: This is the new class that will extend **Adapter**.  Its **toRawEvents** happens in the remote Akka Actor and it returns the result when ready.

What do you folks think?

**Comment by alexanderdean** [comment]
I don't think I understand this one. Why would we add a whole new technology stack (Akka actors) when you could just add Stream Enrich instances to handle additional load? Stream Enrich scales horizontally already.

**Comment by szareiangm** [comment]
I think looking as Akka Actors as a separate stack or something that changes the enricher as a whole is not really the case. We Akka Actor is just a way to talk to other machine as TCP with a protocol. It could be done via simple TCP/HTTP or REST. but I thought now that we are Scala, why not to use the common way.

You are right, we can have additional enrichers but I want to bring up other use-cases:

1. Payload with some data-science model fields involved: This is the case with data science models that we have in the organization. First, we need to feed the payload of our custom events to the data model machines and ask their verdict and generate the rawEvent payload based on the schema. The model response can be slow. Here comes the performance. Nowadays the models are written in Python/R so we cannot even put them here in this project too. Even if we could, many organizations have data science models that are tuned and trained based on their sales data and not suitable for others.

2. Proprietary software: Usually old-school legacy softwares that nobody dares to touch them because the original owners left the organization long time ago. They just send out some webhook notifications that we need to add other fields to them before putting them in RawEvent formant. Those softwares do not have public audience and organizations cannot share the details, too. But based on the Apache2 license we should.

3. Vendor software: There are cases that we cannot publish logic of the schemas or anything related to the vendors. This is totally out of our control. We just bought them to use them internally. This becomes very sensitive to managements when we want to process financial event data. Some companies are not comfortable to share anything about financial systems. 

Did I answer to your question?

**Comment by alexanderdean** [comment]
Hey @szareiangm - thanks for this. I think I am starting to see your idea.

It doesn't seem to be about scalability - it seems to be about pluggability, and the ability to extend the enrichment process with out-of-band code which isn't part of the assembled jarfile.

This is something we've considered before with enrichments - see eg:

* https://github.com/snowplow/snowplow/issues/2054
* https://github.com/snowplow/snowplow/issues/2055

I think your suggestion specifically relates to Snowplow adapters - i.e. you would like to support non-standard input sources via Akka? Is that right?

**Comment by szareiangm** [comment]
Hello @alexanderdean 

You are right. The benefit of this work, shows itself more on the side of extendibility and support for non-standard input payloads that collector has received. 

Yes. I want to use Akka to process the payloads externally and format them as the expected rawEvent model for the Enricher. 

I started from Adapter as the entry point for enricher but enrichments were my next stop and I was going to ask after this. I saw almost every issue tickets for enrichments and EnrichmentManager. There is a room for improvement there to have the enrichments via TCP and Akka actors in a non-blocking fashion.

**Comment by alexanderdean** [comment]
It's a cool idea. We don't have the concept of configurable adapters yet - that would be a fair chunk of work to do this, but would be a nice complement to our enrichment engine.

Feel free to create a separate ticket for an Akka-powered enrichment.

**Comment by szareiangm** [comment]
Sure thing. Thanks.

The PR for this issue will be created soon in 1-2 weeks. I am finalizing some work in snowplow-elasticsearch-loader for now.
