### ISSUE TITLE
Stream Enrich: force jackson-databind to 2.9.3 for all projects

### ISSUE THREAD

**Issue by romansalin** [snowplow/snowplow#3767]
Related to #3744, we see a `java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.node.ArrayNode.<init>(Lcom/fasterxml/jackson/databind/node/JsonNodeFactory;Ljava/util/List;)` error at runtime when using R105 (which is equivalent to master at the time of writing).

Steps to reproduce:
```bash
git clone https://github.com/snowplow/snowplow
cd 3-enrich/stream-enrich
sbt "project kafka" assembly
# Run scala-stream-collector, stream-enrich 
```
Try to send test event like http://collector-server/i?e=pv. Stream-enrich will be down with this error as well as the previous bug with Kinesis.

**Comment by alexanderdean** [comment]
Scheduled into R109

**Comment by BenFradet** [comment]
it's already in 107: #3799

**Comment by alexanderdean** [comment]
Cool - is it in the CHANGELOG?

**Comment by BenFradet** [comment]
I'm about to have a final review on the pr so I'll soon find out
