### ISSUE TITLE
IPv6 anonimization

### ISSUE THREAD

**Issue by apiddubnyi** [snowplow/snowplow#3768]
Hi Snowplow Team!

According to GDPR rules I have to anonymize IP addresses.
**IP anonymization enrichment** work fine for IPv4 addresses but I'm not sure about IPv6.

Please update documentation if IPv6 support already done or add IPv6 IP anonymization support
https://github.com/snowplow/snowplow/wiki/IP-anonymization-enrichment

Thanks in advance

**Comment by apiddubnyi** [comment]
Actually I have no sensitive data except IP addresses.
So IP anonymization is enought for me.

**Comment by alexanderdean** [comment]
Closing, support questions should go to our forums: https://discourse.snowplowanalytics.com/
