### ISSUE TITLE
Wiki: update trackConsentWithdrawn argument order

### ISSUE THREAD

**Issue by zwacky** [snowplow/snowplow#3769]
Hey all, I had two problems with the docs/wiki:
- parameter ordering of `trackConsentWithdrawn` ([core.ts](https://github.com/snowplow/snowplow-javascript-tracker/blob/c61951ebab11f9e918a5f632a84599f8c21c8468/core/lib/core.ts#L895))
- string type of `id` and `version` ([consent_document](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/consent_document/jsonschema/1-0-0#L13-L20))

here's a fork of the wiki with the changes: https://github.com/zwacky/snowplow-wiki/commit/b9d941f48295b21f7994189cb326817735d52688

**Comment by ihortom** [comment]
Thanks.
