### ISSUE TITLE
Spark Enrich: fix file loading so that it is recursive and filters out directories 

### ISSUE THREAD

**Issue by knservis** [snowplow/snowplow#3770]
https://github.com/snowplow/snowplow/blob/9b67ff48fbdc6dde0fa11dfd7653a8eed4196647/3-enrich/spark-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.spark/EnrichJob.scala#L234

Fails when the input provided contains a directory e.g. :
`--input-folder hdfs:///local/some-dir/*`

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/32
