### ISSUE TITLE
Data modelling documentation seems be out of date?

### ISSUE THREAD

**Issue by nicokruger** [snowplow/snowplow#3774]
Hey guys,

I've got the basic snowplow setup working, ETL EMR running in AWS and can see the data in the atomic.events table.

I know want to move towards the data modelling step, with my eye on potentially using looker.com as the frontend for our snowplow data.

However, the documentation seems out of date - I'm trying to follow the redshift steps here https://github.com/snowplow/snowplow/wiki/getting-started-with-data-modeling and they don't seem to exist anymore. Ie. the github links etc. return 404.

What is the next stop to get data modelling into redshift?

**Comment by chuwy** [comment]
Hi @nicokruger,

Please direct support questions to [our forum](https://discourse.snowplowanalytics.com/).

Thanks!
