### ISSUE TITLE
Storage Kinesis-s3: Allow override of kinesis and s3 endpoints in configuration file

### ISSUE THREAD

**Issue by arihantsurana** [snowplow/snowplow#3785]
As this module does not seem to be open for contribution yet, I could not add the endpoint override as done in the PR - https://github.com/snowplow/snowplow/pull/3777

Adding optional override is helpful in testing with localstack.
I'd be happy to PR against that module If I can. (Let me know how)

**Comment by arihantsurana** [comment]
I think I might have isolated the code which needs to be ammended-
https://github.com/snowplow/snowplow-s3-loader/blob/bdb6ca547467ad62774af5c1148291cfc57e6cbf/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/SinkApp.scala#L147-L150

https://github.com/snowplow/snowplow-s3-loader/blob/bdb6ca547467ad62774af5c1148291cfc57e6cbf/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/SinkApp.scala#L140

https://github.com/snowplow/snowplow-s3-loader/blob/bdb6ca547467ad62774af5c1148291cfc57e6cbf/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/SinkApp.scala#L94

**Comment by BenFradet** [comment]
yes please, open the corresponding issue in https://github.com/snowplow/snowplow-s3-loader and the associated PR :+1: 

closing this one.
