### ISSUE TITLE
EmrEtlRunner: update rdb_shredder version in config samples to 0.13.1

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3790]
Assuming R106 will go out after RDB Loader R29. @knservis can you handle this?

**Comment by knservis** [comment]
I think it makes no sense to do r106 first. Why don't you send a PR to `release/gdpr-2` and I do the rest?

**Comment by chuwy** [comment]
> If this is only the sample config

Yes, it is only one line in sample config. You can check other similar commits.

> Does it involve doc changes in the blog and the wiki?

I think it would be nice to briefly mention [my post](https://github.com/snowplow/snowplowanalytics.com/pull/751) in a section where you describe a JSON Path bug.
