### ISSUE TITLE
EmrEtlRunner

### ISSUE THREAD

**Issue by vokurka** [snowplow/snowplow#3792]
Hi there! 

We are running a binary of EmrEtlRunner on our infrastructure and we assigned it 1.5GB of RAM. We also monitored the consumption of the RAM by the component and it varies wildly. It even failed with 1.5GB of RAM, which seems quite excessive considering it does only few REST API calls. But that's another story.

My main question is - if we want to limit the RAM of the machine this component is running on, would 2GB of RAM be enough? I saw you recommend t2.small instance in AWS, does it cover the production deployment? Or what is the limit for RAM?

Thanks a lot and have a great day!

**Comment by BenFradet** [comment]
Hey @vokurka , please share your community support requests on [our Discourse](https://discourse.snowplowanalytics.com/). This way more people will be able to answer and refer back to your question.
