### ISSUE TITLE
IP Enrichment failing with 'OpenWeatherMap ErrorResponse New city' and caching transient response

### ISSUE THREAD

**Issue by jwhansome** [snowplow/snowplow#3794]
I've been able to reproduce this by making a OWM request as the weather enrichment would between [approximately] midnight and 1AM UTC -- I placed the start timestamp less than one hour in the past. The 'New city' response is given, and no weather data is supplied. Since the start and end of day are used as parameters from the weather enrichment, this would leave requests during the first hour failing. Additionally, since start and end parameters are used in the cache key, the new response is cached for all responses for all coordinates within the failing time period and [potentially] kept the entire day (in the case of steam enrichment).

**Comment by chuwy** [comment]
Hey @jwhansome, thanks for you report! 

Just to clarify, does the following model describe bug in a way it you observed it?

1. Wall clock: 1nd June 0:55AM, enrichment processes an event
2. Event time: 1st June 0:10AM
3. Request: give all weather data starting from 1st June 0:00 to 1st June 23:59
4. Response: failure

Also does OWM just returns `New city` string as a response? No actual JSON data?

**Comment by jwhansome** [comment]
Your model is accurate accurate. It returns json. Example request/response:.

```
https://history.openweathermap.org/data/2.5/history/city?lat=1&lon=1&appid=[redacted]&type=hour&start=1528430820&cnt=24

{"message":"New city","cod":"200","city_id":2302357,"calctime":0.028488455}
```

Just change the start parameter to a recent unix timestamp to reproduce. It may not require a full hour to provide a weather result, so to be sure, the more recent the better.

**Comment by jwhansome** [comment]
I should probably note, that for us, this was causing the majority of events to fail during enrichment. For those running this enrichment, especially in streaming environment, and further, with a low `geoPrecision` setting, it has a very large impact.

As for a solutions, I wonder if it would make sense to leave the cache key the same, but offset the OWM request start [and end] one hour prior. This should prevent the 'New city' response from ever happening...just a thought. Additionally, 'New city' errors should probably be retried similar to [timeout errors](https://github.com/snowplow/scala-weather/blob/caf776543d4e16914be92a6ada908e4ae5e9690e/src/main/scala/com.snowplowanalytics/weather/providers/openweather/OwmCacheClient.scala#L72).

Hope this is helpful information.

**Comment by BenFradet** [comment]
@jwhansome thanks for the bug report :+1: 

We've discussed this internally and we think that the easiest short-term solution would be to give a "free pass" to those "New city" events meaning that we don't attach a weather context to the event but we don't fail the whole event's enrichment phase at the same time.

As for the longer term, I think the strategy needs to be two-fold:

- We need to evaluate and integrate other weather providers (e.g. [darksky](https://github.com/snowplow/scala-weather/issues/42)) as this is a serious shortcoming for OWM
- We need to evolve our enrichment engine in order to make it possible to have "optional" enrichments meaning that a failure of a specific enrichment doesn't necessarily mean a failure of the whole enrichment phase. We actually have a planned RFC on this subject.

Please tell us what you think.

**Comment by jwhansome** [comment]
I agree, this is a reasonable short term fix. You're probably implying this, but to be clear, the 'New city' error should be retried if it's retrieved from the cache, or skip being cached. 

I wonder if you couldn't also evaluate another endpoint with OWM, current weather by coordinates perhaps (api.openweathermap.org/data/2.5/weather)? I'm unsure how/if the hourly historical data is getting used, but it seems that if the cached responses persist for the day (in the case of stream enrich), you're likely to only ever get the first hour anyways. I assume this would eliminate the 'New city' response, but have not verified.

Within our recovery process, we exclude certain enrichments due to potential transient errors that fail enrichment -- so this approach in general would eliminate much of our reprocessing. Consider this a definite up vote on "optional" enrichments.

Thank you for your attention to this issue.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/34
