### ISSUE TITLE
Current approach to running RDBLoader

### ISSUE THREAD

**Issue by c4l3b** [snowplow/snowplow#3796]
I'm currently using the snowplow docker containers for the collector, enrich, and storage (to s3) steps. Every piece of documentation I can find on RDB Loader indicates I need to run it with EmrEtlRunner. Since I used the docker containers for the others steps I never had to set that up, and don't quite know how that fits in. I've also seen talk that EmrEtlRunner is being replaced with the DataFlow Runner.. so I'm a little confused at the current best approach for this.

**Comment by BenFradet** [comment]
Please ask general questions on [our Discourse forum](https://discourse.snowplowanalytics.com/), this way more people from the community will be able to help you.

We use GitHub issues for things that will result in code changes.

We're working on better communicating that :+1:
