### ISSUE TITLE
Missing DDL for 1-0-1 version of mobile context

### ISSUE THREAD

**Issue by keanerobinson** [snowplow/snowplow#3808]
Despite the `networkType` and `networkTechnology` fields appearing in the Android documentation for the [mobile_context](https://github.com/snowplow/snowplow/wiki/Android-Tracker#321-mobile_context)  as well as there being a [1-0-1 schema](https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/mobile_context/jsonschema/1-0-1), the associated redshift DDL is missing.

**Comment by BenFradet** [comment]
logged snowplow/iglu-central#823, closing
