### ISSUE TITLE
Confusion 

### ISSUE THREAD

**Issue by Arsalan9002** [snowplow/snowplow#3817]
i am setting up the postgresql for snowplow on ec2 instance.
i have followed all the steps and connected to the postgresql successfully using navicat.

Now when coming to creating the atomic.events table
I am running following command in the navicat query editor

"$ cd 4-storage/postgres-storage/sql
psql -h myhostname -U power_user -d snowplow -p portNum -f atomic-def.sql"

and it is continuously giving me the error  syntax error near psql or near

**Comment by BenFradet** [comment]
Hey @Arsalan9002, please log your support requests on [our Discourse](https://discourse.snowplowanalytics.com/), more people will be able to help you there.
