### ISSUE TITLE
Redshift: widen geo_region to 3 characters

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3822]
This is related to shredding/data modelling but putting here for visibility.

Recently Maxmind has started including more ISO-3166-2 region codes in their GeoIP lookup databases as opposed to older FIPS 10-4 region codes of only two characters. Many of these ISO-8166-2 region codes are three characters in length rather than two.

At the moment the pipeline truncates the region (the [ISO code](https://github.com/snowplow/scala-maxmind-iplookups/blob/61ef850b67aff0b550c0f8805e37eaa1c5b1e062/src/main/scala/com.snowplowanalytics.maxmind.iplookups/model.scala#L46) for the most specific subdivision) in two places which currently results in a discrepancy in enriched data (with full ISO-3166-2 codes) and the shredded data (where the ISO code has been truncated).

Currently this occurs in two places:
- The logic that enforces the Postgres constraints in [rdb-shredder](https://github.com/snowplow/snowplow-rdb-loader/blob/2343b1d512b6997b8b9cc4b81b238b996688e756/shredder/src/main/scala/com.snowplowanalytics.snowplow.storage/spark/ShredJob.scala#L199) and
- The atomic.events model for both Redshift and Postgres itself which has historically always been a `char(2)` (of which `TRUNCATECOLUMNS` will prevent three character codes being inserted).

In some countries this is less of an issue but for others the truncation can introduce ambiguity, e.g., in GB
```
SWK => Southwark
SWD => Swindon
SWA => Swansea
```

The Postgres enforcement logic in rdb-shredder and the atomic.events model should both be updated to accept three character region codes.

**Comment by BenFradet** [comment]
Excellent find, I logged snowplow/snowplow-rdb-loader#110 :+1:
