### ISSUE TITLE
Scala Common Enrich: Make IP lookups enrichment optional for some events

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow#3826]
GeoIP lookup might not be necessary for all of the events that we receive i.e. page pings or webhook events coming from other systems. Reducing the size of GeoIP duplicate data will help a lot for efficiency and clarity of the data. 

I am proposing that we add an optional list field to its setting schema to specify the list of `event.event_name` that we are interested have geo ip lookup. Then we just have GeoIP lookup for those specific events. The other change would be an `if` in `EnrichmentManager` to limit the the events for GeoIP lookup if the optional list is set in configuration. 

CC: @nafid

**Comment by alexanderdean** [comment]
This would be an opportunity to standardise this kind of selective-enrich across all enrichments (some enrichments e.g. API Lookup have a flavor of this already).

**Comment by szareiangm** [comment]
There we go. I am keen to take on this opportunity.
PS: I could not find the flavor for API lookup in the docs or settings for it. Any URLs or hints?

**Comment by alexanderdean** [comment]
https://github.com/snowplow/snowplow/wiki/API-Request-enrichment

> If a key required in the uri was not found in any of the inputs, then the lookup will not proceed, but this will not be flagged as a failure.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/35
