### ISSUE TITLE
Redshift copy failure due to missing break-lines

### ISSUE THREAD

**Issue by anistal** [snowplow/snowplow#3831]
Hi guys! I currently have a stream-enricher which is generating and publishing events (TSV's) to a Kinesis topic. I have a Kinesis Firehose connected to a Kinesis topic, and the problem I'm facing is that the generated file is a single line document (all tsv's records are appended in the same line). For this reason when Firehose tries to do a COPY command to Redshift, it fails.

I have a fix ready for this, and I can submit a PR if it makes sense to you guys. But I'd like to make sure I'm not doing anything wrong and the approach I'm following is right.

Please, let me know if you have any questions or concerns. Thanks a lot in advance for you guidance!

**Comment by BenFradet** [comment]
Hey, @anistal thanks :+1:

We don't use kinesis firehose ourselves yet, that's why it might not be supported out of the box.

Can you open the PR so we know what the change entails?

**Comment by anistal** [comment]
Thanks for your fast answr @BenFradet 

I just have created this PR: https://github.com/snowplow/snowplow/pull/3832

Also I would like to inform that fields of the event (that it is a tsv) don't match with the database schema that it is defined here: https://github.com/snowplow/snowplow/blob/master/4-storage/redshift-storage/sql/atomic-def.sql

I think that this sql script should have the same fields that this POJO: 

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala

Otherwise the copy command fails. I also did modifications in this sql script and I could make another PR for it.

**Comment by BenFradet** [comment]
We don't directly load the enriched events into redshift.

We have [a shredding process](https://github.com/snowplow/snowplow-rdb-loader#rdb-shredder), which, amongst other things, extracts the different contexts into their own entities.

Those entities are then loaded into separate Redshift tables along with the atomic.events table you just linked by [a dedicated loader](https://github.com/snowplow/snowplow-rdb-loader#rdb-loader).

**Comment by anistal** [comment]
Reading the documentation deeply, I have realized that I misunderstood how Snowplow components were working and my PR has not sense.

I have understood that (correct me if I am wrong, please):

1. I have to publish events in Kinesis with the "stream-enrich" component without andy kind of break line.
2. I have to use the "snowplow-s3-loader" to load data from my Kinesis topic to S3; furthermore this component as the documentation says:
> The records are treated as byte arrays containing UTF-8 encoded strings (whether CSV, JSON or TSV). New lines are used to separate records written to a file.

3. Finally, I should use  the "snowplow-rdb-loader" to load data from S3 to my Redshift cluster

**Comment by alexanderdean** [comment]
That's right @anistal - you want to configure EmrEtlRunner with "stream enrich" mode per:

https://github.com/snowplow/snowplow/wiki/EmrEtlRunner#stream-enrich-mode
