### ISSUE TITLE
Stream Enrich: Cannot access Iglu schema repo over HTTPS

### ISSUE THREAD

**Issue by dnedev** [snowplow/snowplow#3845]
Hey there,

We recently started running our Iglu repository, and since we use API keys for authentication, we allowed only HTTPS connection to it. After we configured the resolver to get the schemas from the repo with an HTTPS URI,  we got the following errors during enrichment:
```"error: Could not find schema with key iglu:<redacted> in any repository, tried: level: "error" repositories: "Private Snowplow Iglu [HTTP]"```.
This lets us think that the process only supports HTTP connections to the repos.

We did not test if other components of the pipeline (e.g. EMR Spark enrichment) also had issues accessing a repo over HTTPS.

**Comment by chuwy** [comment]
Hello @dnedev,

This is an interesting issue. I'm sure that Stream Enrich supports HTTPS. All our internal pipelines use https, but not with Iglu Server (Static S3 Registry, instead).

Could you please show you resolver.json? Very likely that you've missed `/api` part in the endpoint. If not - could you please try to `curl` your schema.

**Comment by dnedev** [comment]
Hey @chuwy, you are right. Adding `/api` at the end of the resolver URI for HTTP fixed the issue. Thanks!
