### ISSUE TITLE
Scala Common Enrich: add base64-alphabet detection for POST requests

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3847]
Our trackers use [URL/filename-safe Base64 alphabet](https://tools.ietf.org/html/rfc4648#page-7) for encoding JSON data, which was explicitly chosen to make GET-requests safe. 

However, it doesn't make much sense to use this encoding for POST-requests.

This is a non-backward compatible change that also should be reflected in trackers and tracker protocol.

**Comment by alexanderdean** [comment]
Would this be a Tracker Protocol v3?

**Comment by chuwy** [comment]
Probably. Do we have a dedicated milestone for these changes?

**Comment by alexanderdean** [comment]
No - that would be a great idea. TP3 feeds into the atomic.events refactor too.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/20
