### ISSUE TITLE
Scala Common Enrich: validate enrichments relying on downloaded local files

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3849]
When building the `EnrichmentRegistry`, SCE should take on the burden of downloading a copy of the files necessary for the different enrichment (e.g. ip lookups db) to check they can be properly downloaded.

**Comment by benjben** [comment]
I'm not sure that I understand this one. SCE is a library that can be used in different runtimes (Dataflow, Spark, standalone app). It seems to me that SCE can't be in charge of downloading the files but needs to have these files provided. What do you understand @chuwy ?

**Comment by chuwy** [comment]
I agree with you @benjben. But we can explore if there's at least any code duplication inside user-facing assets that can be extracted into SCE. But this is certainly not for R119.

**Comment by chuwy** [comment]
I think it likely be a wontfix due https://github.com/snowplow/snowplow/issues/4269, as we don't want to add S3/GCS SDKs to SCE.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/19
