### ISSUE TITLE
Stream Enrich: partition enriched bad output by day

### ISSUE THREAD

**Issue by keanerobinson** [snowplow/snowplow#3856]
When using Athena to attempt debugging a real-time pipeline last week I realised that the `enriched/bad` data isn't partitioned. Whilst querying the dataset is still possible as I covered in [this tutorial](https://discourse.snowplowanalytics.com/t/debugging-bad-rows-in-athena-real-time-tutorial/2189), there are big performance implications without partitions. There is effectively no way to reduce table scans with partitions in a real-time pipeline. I've created this issue so that we eventually partition the data in `enriched/bad` by day. This would be a better experience than the current batch `enriched/bad` data which is partitioned by run.

**Comment by alexanderdean** [comment]
I think this relates to the S3 Loader - and may already be available as a feature (just not configured like this). Please raise a ZD to L3 Eng.

**Comment by keanerobinson** [comment]
thanks @alexanderdean will do!
