### ISSUE TITLE
Scala Common Enrich: support POST requests in API Request enrichment

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#3857]
Currently the API request enrichment only supports GET requests where each of the `inputs` is either added as part of the URL path or alternatively as part of the query parameters.

Supporting POST would make it possible to reliably send significantly larger payloads that may either involve a large number of inputs or a smaller number of inputs but with a large amount of text (e.g., encrypted data, large arrays etc).

**Comment by alexanderdean** [comment]
Not particularly nice from a RESTful perspective, but probably a good idea in terms of utility...

**Comment by miike** [comment]
Agreed - it isn't semantically ideal from a REST point of view but could also make it quite a bit easier to support POST queries to GraphQL APIs.

**Comment by aparra** [comment]
I am also interested in this feature for the same reason: send large payload to enrichment endpoint. 

So I was taking a look at the code to create a PR supporting this feature. However there is one point that requires a deal: `cache`. Current implementation offers an in-memory cache mechanism where the [key is the URL](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/apirequest/ApiRequestEnrichment.scala#L129) - it makes sense for GET requests where the parameters are in the URL. Also it is an interesting feature when you are using a third-party API.

But now with the plan to support POST calls - with post body - we need new deal for cache key. Maybe we could have a function that creates an UUID using URL and Request Body: `(URL, Option[Request Body]) => UUID`.

I have one more point related to cache. I think cache should be optional. For example if you are controlling the API, maybe you would like to take care of cache mechanism. I think optional cache brings more flexibility to use this kind of enrichment.

What do you think @miike @alexanderdean ?

**Comment by aparra** [comment]
I've created a PR to handle #3885 to support POST calls with body but it does not switch cache to optional.

**Comment by alexanderdean** [comment]
> I think cache should be optional.

Agree, I think that's as simple as changing the minimum cache size to 0, currently it's... 1?

https://github.com/snowplow/snowplow/wiki/API-Request-enrichment#cache

**Comment by aparra** [comment]
@alexanderdean Yes, currently it is 1.

```json
				"cache": {
					"type": "object",
					"properties": {
						"size": {
							"type": "integer",
							"minimum": 1
						},
						"ttl": {
							"type": "integer",
							"minimum": 0,
							"maximum": 86400
						}
					},
					"additionalProperties": false,
					"required": ["size", "ttl"]
				}
```
I think in this case, we need only create a new version of [JSON Schema](http://iglucentral.com/schemas/com.snowplowanalytics.snowplow.enrichments/api_request_enrichment_config/jsonschema/1-0-0) when `"size": { "type": "integer", "minimum": 0 }`.

[Current implementation](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/apirequest/Cache.scala#L36) of cache supports `size = 0`:

```scala
val cache = Cache(size = 0, ttl = 0)
val key   = ApiRequestEnrichment.cacheKey(url = "http://api.acme.com/url", body = None)

cache.put(key, JInt(42).success)
cache.get(key) must beNone and (cache.actualLoad must beEqualTo(0))
```

**Comment by BenFradet** [comment]
@aparra yup that would be the way to go about it :+1:

**Comment by aparra** [comment]
Great @BenFradet! iglu-central's PR: https://github.com/snowplow/iglu-central/pull/835
