### ISSUE TITLE
Event Manifest Populator: support s3a uri scheme

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3870]
At the moment, only s3 and s3n are supported:

https://github.com/snowplow/snowplow/blob/7ea7feb7a3b7634cd20641c4484171124c0da7f5/5-data-modeling/event-manifest-populator/run.py#L44-L47

**Comment by palash25** [comment]
Hi @BenFradet I would like to work on this issue. 

Is it as straightforward as it seems just adding an elif for `s3a://` ?

**Comment by chuwy** [comment]
Hi @arunma! Not yet, unfortunately - it will be out with R112.
