### ISSUE TITLE
Clojure Collector: add ebextension to increase the number of file descriptors to 65536

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3876]
This ensures that the collector is never throttled on the number of open file handles it can accept.

https://github.com/vinayselvaraj/elasticbeanstalk-docker-ulimit-example/blob/master/.ebextensions/update-ulimit.config
https://forums.aws.amazon.com/thread.jspa?threadID=122787

Should be a fairly simple addition and would likely have performance improvements at the higher end.  By default we should have 1024 so would be good to bump this up to something much much higher.

**Comment by BenFradet** [comment]
hey @jbeemster, are you happy with 65536?

**Comment by jbeemster** [comment]
Sounds good to me!
