### ISSUE TITLE
AMP - structEventValue shouldn't be a required keyval

### ISSUE THREAD

**Issue by mattleong** [snowplow/snowplow#3884]
**Project**: AMP Tracker

**Version**: Latest (0.2)

**Expected behavior**:
According to the documentation for [structured events with the AMP tracker](https://github.com/snowplow/snowplow/wiki/Google-AMP-Tracker#32-structured-events), the keyval pair `structEventValue` is not required. If I do not set the keyval at all within the config object, the event should still be recorded.

**Actual behavior**:

Because no `structEventValue` keyval is defined, the tracker will simple append an empty value for `?se_va` on the request url. This causes `Field [se_va]: cannot convert [] to Double-like String` to be logged in /enriched/bad.

Current workaround is sending an arbitrary value along with the event. 

**Steps to reproduce**:

 1. Send an event using the AMP Tracker without setting the `structEventValue` keyval pair.

**Comment by alexanderdean** [comment]
Raising here is fine as we don't have a dedicated issue tracker for our AMP support

**Comment by colmsnowplow** [comment]
@mattleong - thanks for raising this issue. We're working on a v2 of the AMP tracker and I'm optimistic that we'll have a fix for this issue in there - which will default `se_va` to send a null string where no value is provided.

I don't yet have a timeline for release, but it's looking in good shape so hopefully not too long!

**Comment by colmsnowplow** [comment]
Closing - this was resolved with the [AMP v2 release](https://snowplowanalytics.com/blog/2020/04/29/snowplow-amp-tracker-1-0-1-released/)
