### ISSUE TITLE
Add StorageLoader CLI argument for loading specific bucket/folder

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#389]
There should be a CLI option where I can just specify on the CLI:

`--load s3://snowplow-data/archive/events`

And then specifically this folder is loaded. It should automatically `--skip` the archive stage, on the assumption that this is some kind of ad hoc load.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow/issues/389
