### ISSUE TITLE
Typo in the batch pipeline schema

### ISSUE THREAD

**Issue by pocin** [snowplow/snowplow#3892]
**Project**: WIKI

**Version**: current

**Expected behavior**:
the last step 15 in the schema ![schema](https://raw.githubusercontent.com/wiki/snowplow/snowplow/images/batch_pipeline_steps.png)

 https://github.com/snowplow/snowplow/wiki/Batch-pipeline-steps  should be `archive_shredded`. 

Here https://discourse.snowplowanalytics.com/t/disable-shredding-on-emr/2285/2 
 @ihortom mentions step `archive_shredded` which is not in the diagram

**Actual behavior**:
it's `archive_enriched`

**Steps to reproduce**:
visit  https://github.com/snowplow/snowplow/wiki/Batch-pipeline-steps

**Comment by ihortom** [comment]
Updated
