### ISSUE TITLE
Beam Enrich: volume mount permissions in containers

### ISSUE THREAD

**Issue by jrluis** [snowplow/snowplow#3896]
Currently Snowplow containers run as snowplow user. 

When mounting a volume, it gets mounted as root, this makes impossible to access files from the program that is running as snowplow user.

The use case for this was on a gcp container, we tried to pass the service account file to the container using a volume, so the program running there could do the authentication and connect to gcp.

Example: 
```
docker run --rm -v /root:/cfg -e GOOGLE_APPLICATION_CREDENTIALS='/cfg/sp-loader.json' snowplow-docker-registry.bintray.io/snowplow/snowplow-bigquery-mutator:0.1.0-rc13 listen --resolver=$RESOLVER --config=$CONFIG --verbose
```

This seems to be an old issue yet to have a proper solution https://github.com/moby/moby/issues/2259

**Comment by jrluis** [comment]
Interesting link on this issue https://denibertovic.com/posts/handling-permissions-with-docker-volumes/

**Comment by chuwy** [comment]
Changed title as it seems only Beam Enrich now is affected?

**Comment by chuwy** [comment]
So, basically what we need to do is to copy our entrypoint approach from snowplow-docker https://github.com/snowplow/snowplow-docker/blob/develop/iglu-server/0.4.0/docker-entrypoint.sh

**Comment by peel** [comment]
Moved to: https://github.com/snowplow/beam-enrich/issues/27
