### ISSUE TITLE
Wiki: add --resume-from shred to the recovery instructions on the Batch pipeline steps page

### ISSUE THREAD

**Issue by yohan233** [snowplow/snowplow#3898]
Similar to [this issue](https://github.com/snowplow/snowplow/issues/3714), we use the [batch recovery steps](https://github.com/snowplow/snowplow/wiki/Batch-pipeline-steps) to recover from problems with our batch pipeline.

We recently encountered an extended (9+ hour) shred step that did not seem to be progressing.  After finding nothing obviously wrong, we decided to kill the EMR job and rerun the pipeline starting from the shred step.  We found that `shred` was not an explicit parameter to the `--resume-from` option, but that it worked just fine.  It'd be nice to have that listed as a possible way to continue forward from steps 6 or 7.

**Comment by ihortom** [comment]
Updated. Thanks.
