### ISSUE TITLE
Add ability to enable/disable storage targets in StorageLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#390]
Basic idea: each storage target gets 2 new fields in `config.yml`:
1. `tag:` short-form name for this target
2. `enabled:` whether this target is enabled or disabled

Then we also add CLI option:
- `--targets`

So you can manually specify the targets to load into for a given load (overrides `config.yml` setting).

**Comment by alexanderdean** [comment]
Design needs further work but there's something useful in it...

**Comment by chuwy** [comment]
Can be closed due https://github.com/snowplow/snowplow/issues/2992
