### ISSUE TITLE
Reference Python version in Python tracker docs

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3907]
Failed to pip install the tracker in a Python3 environment, worked in Python 2. Couldn't find a reference to version compatibility in the docs.

**Comment by miike** [comment]
Was it because of the greenlet dependency? I believe @mhadam has fixed this in the yet to be released 0.8.1 https://github.com/snowplow/snowplow-python-tracker/pull/209

**Comment by paulboocock** [comment]
This is resolved now.
