### ISSUE TITLE
Hadoop Event Recovery: remove

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3908]

**Comment by miike** [comment]
What's the plan with event recovery? Is there going to be a new Spark version / overhaul?

**Comment by BenFradet** [comment]
yes, you can track our progress here: https://github.com/snowplow-incubator/snowplow-event-recovery

**Comment by miike** [comment]
Well this is exciting.

**Comment by BenFradet** [comment]
postponing until snowplow-event-recovery works with events coming from the batch pipeline.
