### ISSUE TITLE
Link to pixel tracker wizard broken

### ISSUE THREAD

**Issue by qbatten** [snowplow/snowplow#3916]
**Project**: Pixel Tracker

**Version**: N/A

**Steps to reproduce**:
It looks like the link to the pixel tracker wizard may be broken on the Github docs. On [this page](https://github.com/snowplow/snowplow/wiki/pixel-tracker-setup) there are two links to the pixel tracker creation wizard at "http://snowplowanalytics.com/no-js-tracker.html". But when I follow the link, it gives a 301 redirect to "http://snowplowanalytics.com/".

**Comment by BenFradet** [comment]
Thanks for the report :+1:

**Comment by paulboocock** [comment]
This has been updated to point to the appropriate html and js files within this repo. We no longer host this page but you should be able to clone the repo and load the html page in your browser.
