### ISSUE TITLE
Add explicit advice on avoiding concurrency issues for Android tracker

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3917]
Add explicit advice on avoiding concurrency issues for Android tracker

The iOS docs make it explicit that only one Tracker should exist at once, I believe the case is the same for Android - the docs should make this explicit.

https://github.com/snowplow/snowplow/wiki/Android-Tracker#5-sending-event-emitter

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow/snowplow-android-tracker/issues/297
