### ISSUE TITLE
iOS & Android tracker: automatically resend failed data when connection is re-established

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3918]
Currently, for the iOS and Android tracker, I believe they deal with failures to send data as follows:

If no 200 response is found from the collector, it will attempt to re-send n times (I think 5 times)

If it still hasn't got a 200 for that event, it will put the event back in the queue.

The event will then be sent next time the Emitter attempts to send events. (This is definitely the case for POST requests, I assume it's the same for GET).

Where a user isn't active often, or doesn't trigger events often, this can lead to apparently missing data, or very late arriving events.

Ideally, the tracker would have a feature which detects when a connection has dropped then re-connected, then sends any failed events on re-establishment of the connection.

An additional nice to have (not sure if this is a separate issue or not) would be an optional setting to always automatically flush the tracker once the tracker detects that a connection was dropped and re-established.

**Comment by alexanderdean** [comment]
Thanks @colmsnowplow! @mhadam can you take a look?

**Comment by miike** [comment]
Could we add a random delay parameter to this?

This would help avoid any thundering herd scenarios in which a load balancer may become unhealthy and then when it returns again a large number of clients flush their local buffers simultaneously.

**Comment by BenFradet** [comment]
migrated to:

- https://github.com/snowplow/snowplow-objc-tracker/issues/398
- https://github.com/snowplow/snowplow-android-tracker/issues/290
