### ISSUE TITLE
Setup Enrich - While executing  emretlrunner - Throws an Error

### ISSUE THREAD

**Issue by dpssrini2014** [snowplow/snowplow#3919]
Facing the below issue while setting up Enrich.  Wondering, how to resolve this issue

1. Setup Enrich
2. Setup EmrEtlRunner as instructed on https://github.com/snowplow/snowplow/wiki/1-Installing-EmrEtlRunner
3.  Resources downloaded related to snowplow
All the buckets created in AWS.
Respective  buckets updated on the config.yml 
4.  Execute the emretlrunner using this command -- ./snowplow-emr-etl-runner run --config snowplow/3-enrich/emr-etl-runner/config/config.yml --resolver snowplow/3-enrich/config/iglu_resolver.json --enrichments snowplow/3-enrich/config/enrichments/

5. following error occured: 

uri:classloader:/gems/avro-1.8.1/lib/avro/schema.rb:350: warning: constant ::Fixnum is deprecated
D, [2018-09-17T15:44:42.899475 #3858] DEBUG -- : Initializing EMR jobflow
ArgumentError: AWS EMR API Error (ValidationException): The supplied bootstrap action(s): 
     'Elasticity Bootstrap Action' are not supported by release 'emr-5.17.0'.

**Comment by BenFradet** [comment]
Hello, please redirect your support requests to [our Discourse](https://discourse.snowplowanalytics.com/).

In your case, emr version 5.17 is not supported.

The last supported version is 5.9.0:

https://github.com/snowplow/snowplow/blob/08d2f51b44148169427e5f423f7ea4dd489af9e5/3-enrich/emr-etl-runner/config/config.yml.sample#L29

You can check our compatibility matrix here: https://docs.google.com/spreadsheets/d/1oI3n7nUzNfCwuNJk-LNdMdkAwUt6kI1irPg1FCFyxKc/pubhtml?gid=1937493131&single=true
