### ISSUE TITLE
EmrEtlRunner: rename EMR steps

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3925]
The current steps are named as so:

- Elasticity S3DistCp Step: Raw {raw location} -> Raw Staging S3 (there is one per input bucket)
- Elasticity S3DistCp Step: Raw S3 -> Raw HDFS
- Elasticity Spark Step: Enrich Raw Events
- Elasticity S3DistCp Step: Enriched HDFS -> S3
- Elasticity Custom Jar Step: Empty Raw HDFS
- Elasticity S3DistCp Step: Enriched HDFS _SUCCESS -> S3
- Elasticity S3DistCp Step: Stream Enriched {enriched location} -> Enriched Staging S3
- Elasticity S3DistCp Step: : Enriched S3 -> HDFS
- Elasticity Spark Step: Shred Enriched Events
- Elasticity S3DistCp Step: : Shredded HDFS -> S3
- Elasticity S3DistCp Step: Shredded HDFS _SUCCESS -> S3
- Elasticity S3DistCp Step: Raw Staging S3 -> Raw Archive S3
- Elasticity Custom Jar Step: Load {storage target} Storage Target (there is one per storage target)
- Elasticity S3DistCp Step: Enriched S3 -> Enriched Archive S3
- Elasticity S3DistCp Step: Enriched S3 -> S3 Enriched Archive
- Elasticity S3DistCp Step: Shredded S3 -> Shredded Archive S3
- Elasticity S3DistCp Step: Shredded S3 -> S3 Shredded Archive

we need to find a more machine readable referencing the pipeline stage (e.g. staging, enrich, shred, etc).

cc @ihortom

**Comment by chuwy** [comment]
I think "Elasticity" was always most confusing part, which doesn't bear any useful information. Is it possiblt to remove it?

**Comment by BenFradet** [comment]
yup

**Comment by BenFradet** [comment]
Here's what I currently have, feedback welcome:

```bash
[staging] s3-dist-cp: Raw {raw location} -> Raw Staging S3
[staging] s3-dist-cp: Raw S3 -> HDFS
[enrich] spark: Enrich Raw Events
[enrich] s3-dist-cp: Enriched HDFS -> S3
[enrich] s3-dist-cp: Enriched HDFS _SUCCESS -> S3
[enrich] s3-dist-cp: Stream Enriched {enriched stream location} -> Enriched Staging S3
[shred] s3-dist-cp: Enriched S3 -> HDFS
[shred] spark: Shred Enriched Events
[shred] s3-dist-cp: Shredded HDFS -> S3
[shred] s3-dist-cp: Shredded HDFS _SUCCESS -> S3
[archive_raw] s3-dist-cp: Raw Staging S3 -> Raw Archive S3
[rdb_load] Load {storage target} Storage Target
[archive_enriched] s3-dist-cp: Enriched S3 -> Enriched Archive S3
[archive_shredded] s3-dist-cp: Enriched S3 -> Shredded Archive S3
```

cc @ihortom @stdfalse

**Comment by stdfalse** [comment]
Looks good!

> [staging] s3-dist-cp: Raw S3 -> HDFS

It's a part of `enrich` step and requires `--resume-from enrich` arg. 

> [enrich] s3-dist-cp: Stream Enriched {enriched stream location} -> Enriched Staging S3

It's a `staging_stream_enrich`.

What about the maintenance step: `...Empty Raw HDFS`?  In https://github.com/snowplow/snowplow/pull/3933 we are going to introduce some more to clean up  HDFS. Should we include them?

**Comment by BenFradet** [comment]
Thanks! edited my previous message
