### ISSUE TITLE
Scala Common Enrich: add PubSubAdapter

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3927]
Adapter that transforms collectorless PubSub payloads into `RawPayload`s

**Comment by chuwy** [comment]
Right now I'm thinking that Tracker just needs to send Thrift payloads, mimicking Stream Collector, but leaving this PR as just reminder of work we've done on hackathon.

/cc @mikeh

**Comment by alexanderdean** [comment]
> I'm thinking that Tracker just needs to send Thrift payloads

That was my first thought at the hackathon presentation, but I didn't mention it at the time.

**Comment by chuwy** [comment]
Moved to https://github.com/snowplow/enrich/issues/12
