### ISSUE TITLE
BigQuery Loader: add field descriptions from schema to atomic.events

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3934]
BigQuery offers [column-level descriptions](https://cloud.google.com/bigquery/docs/schemas#column_descriptions). Ideally field descriptions in the schema would populate these fields.

I believe a similar functionality might be present for Snowflake, not sure about Redshift. Where possible taking advantage of these two would be favourable.

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow-incubator/snowplow-bigquery-loader/issues/11. We have separate repositories for loaders these days.

**Comment by colmsnowplow** [comment]
Ah good to know! I searched snowplow/snowplow for it, didn't think of the incubator!
