### ISSUE TITLE
EmrEtlRunner: step optimisation and HDFS

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#3936]
Hey @BenFradet @chuwy - so with the work I have been doing on getting persistent runs to work it seems like there are a few options for speeding things up further and maintaining the cluster in a simpler way.

1. For RDB Shredder is there a reason we do not push directly to S3 rather than first pushing to HDFS and then pushing to S3?  RDB Loader does not use the data on HDFS so this seems like extra work without much gain (but possibly I am missing something here!)
2. For HDFS would it be recommended that we are actively clearing it out?  Would it be possible to also add `--deleteOnSuccess` when copying from HDFS to S3 for archiving if we do not need it on disk any longer?

**Comment by chuwy** [comment]
I believe [this](https://github.com/snowplow-incubator/snowplow-snowflake-loader/issues/67) is the reason to use S3DistCp for RDB Shredder. Problem that without HDFS, due weak S3 consistency guarantees, Spark would have to first write data to `_temporary` S3 directory, then start renaming (which for S3 is copying) all files one by one, which would take way longer.

**Comment by jbeemster** [comment]
Makes sense @chuwy thanks for the context.  After a good amount of investigation and chatting with AWS support I think I will just need to implement some manual cleanup steps for HDFS to ensure that it does not get out of hand.

Will close this one for the moment.
