### ISSUE TITLE
Application context on Android tracker

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3939]
Didn't find this issue anywhere else - for iOS enabling the application context on tracker build auto-tracks app build and version - it would be nice to have parity on this for the Android tracker.

**Comment by BenFradet** [comment]
please move it to https://github.com/snowplow/snowplow-android-tracker

**Comment by colmsnowplow** [comment]
Ah that's why I couldn't find the issue. Sorry Ben Deleting this.
