### ISSUE TITLE
EmrEtlRunner: leverage compaction steps when copying to S3

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3940]
In specific cases, we're making too heavy usage of S3 and hitting S3 rate limits.

This is accentuated by the fact that:

- people can be making use of the data in s3 in parallel to the pipeline which gets us closer to hitting the rate limit
- drip feeding means that we're making heavier usage of s3 with less data (a lot of very small files)
- over-provisioning clusters leads to more smaller files

This behaviour has already been noticed by oss users:

- https://discourse.snowplowanalytics.com/t/service-amazon-s3-status-code-503-error-code-503-slow-down-issues/1608
- https://discourse.snowplowanalytics.com/t/how-to-engage-emrfs-consistency-when-running-snowplow-emr-etl-runner/1603

What I'm suggesting are compaction steps when going from hdfs to s3 and s3 to s3 (when archiving) so that the number of requests made to s3 is lower.

**Comment by alexanderdean** [comment]
This seems very wise.

**Comment by BenFradet** [comment]
The problem with compaction in s3-dist-cp occurs if we have alternatives in the groupBy regex, e.g. for the step moving the results of the shred step from hdfs to s3: `.*\/atomic-events\/(part-)\d+-(.*)|.*\/shredded-types\/vendor=(.+)\/name=(.+)\/format=(.+)\/version=(.+)\/(part-)\d+-(.*)`.

Groups are filled with `null` even if they don't match, resulting in filenames like:

- `nullnullcom.amazon.aws.cloudfrontwd_access_logjsonschema1-0-6part-b417c9a0-e69f-4b20-b958-ffb939d675c1-c000.txt.gz` for shredded types
- `part-b417c9a0-e69f-4b20-b958-ffb939d675c1-c000.txtnullnullnullnullnullnull.gz` for atomic events

And if we choose to split this step in two, the step moving shredded types can fail if they are absent.

**Comment by BenFradet** [comment]
We've decided to split this step in two.

To not cause issues to people not having shredded types, it will be disabled by default in the configuration.
