### ISSUE TITLE
Stream Enrich: add the possibility to override the DynamoDB endpoint

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow#3942]
**Project**: Stream Enrich

**Version**: r111

**Expected behavior**: Be able to override Dyanmodb endpoint to the localhost one

**Actual behavior**: This feature is missing

**Steps to reproduce**: Using Localstack instead of AWS

 1. We need to override the Endpoints for Dynamodb, because KCL keeps the checkpoints there. 
 2. snowplow/snowplow#3344  has address it different by the region selection. but we need to add the whole endpoint URL for it.
3. I propose that we add a setting similar to kinesisEndpoint in the settings file .

**Comment by BenFradet** [comment]
Good idea, we've done something similar for the s3 loader: https://github.com/snowplow/snowplow-s3-loader/commit/48364eea128b19a4dfa085afb731eb12885ca671

**Comment by dmytrokarpovych** [comment]
@BenFradet 
Any news about this feature at the official repo?
Is it possible to use a code like this?
https://github.com/globeandmail/snowplow/commit/d2a8bcbd8eab15c8a9a4924c7a9c64e454ced449

**Comment by BenFradet** [comment]
@benjben

**Comment by benjben** [comment]
Adding it to R119, which will be our next release.
