### ISSUE TITLE
Scala Common Enrich: fix incompatibility between IAB enrichment and Iglu Webhook

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#3952]
There's a general problem of data being sent to bad bucket due one failed enrichment: https://github.com/snowplow/snowplow/issues/351, https://github.com/snowplow/snowplow/issues/3485.

This is a particular case, where Iglu webhook does not set UserAgent, but enabled IAB enrichment requires it, so whenever Iglu webhook is used with IAB enrichment enabled - all data goes to bad.

From another perspective it can be seen as a enrichment dependency graph https://github.com/snowplow/snowplow/issues/2260

Short-term fix probably should include just skipping IAB if there's no useragent.

**Comment by chuwy** [comment]
Related https://github.com/snowplow/snowplow/issues/3953

**Comment by benjben** [comment]
Skipping IAB enrichment if no user agent.
