### ISSUE TITLE
Scala Common Enrich: add preference for successful skip to IAB Bots and Spiders Enrichment

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#3953]
The IAB enrichment only accepts IPv4 as an input, which according to the comment in [this issue](https://github.com/snowplow/snowplow/issues/3951) appears to be down to the underlying Java library.

There are instances where IPv6 addresses are populated in the `user_ipaddress` field - commonly where a DNS service like cloudflare is used, but I'm sure there are also use cases where IPv6 is preferred for other reasons.

In this scenario, we don't have control over the IP format, so enabling the IAB enrichments causes all such data to go to bad rows - the only solution appears to be to disable cloudflare (which may be depended upon for other reasons), or disable the IAB enrichment.

In this issue [here](https://github.com/snowplow/snowplow/issues/3485), a good solution is proposed for the API enrichment - if it were possible to configure the enrichment to skip such rows, we don't risk failing data. 

I'm not sure of the viability of this but I think it would be a great feature (for all enrichments potentially).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/22
