### ISSUE TITLE
Fix example for IAB enrichment on wiki page

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#3958]
# https://github.com/snowplow/snowplow/wiki/IAB-enrichment
The wiki page for the IAB enrichment shows a JSON example. Trying to start the enricher failes with this error:

   
    NonEmptyList(
      error: NonEmptyList(
        error: ECMA 262 regex "^iglu:[a-zA-Z0-9-_.]+/[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+/[0-9]+-[0-9]+-[0-9]+$" does not match input string "com.snowplowanalytics.snowplow.enrichments/iab_spiders_and_robots_enrichment/jsonschema/1-0-0"
        level: "error"
        schema: {"loadingURI":"#","pointer":"/items/properties/schema"}
        instance: {"pointer":"/2/schema"}
        domain: "validation"
        keyword: "pattern"
        regex: "^iglu:[a-zA-Z0-9-_.]+/[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+/[0-9]+-[0-9]+-[0-9]+$"
        string: "com.snowplowanalytics.snowplow.enrichments/iab_spiders_and_robots_enrichment/jsonschema/1-0-0"
      )
      level: "error"
    )

First line of the config:
    
    "schema": "com.snowplowanalytics.snowplow.enrichments/iab_spiders_and_robots_enrichment/jsonschema/1-0-0",

Needs to be prefixed with `iglu:`
    
    "schema": "iglu:com.snowplowanalytics.snowplow.enrichments/iab_spiders_and_robots_enrichment/jsonschema/1-0-0",

Can you pleasw fix the wiki? Or is there any other way to contribute a PR for the wiki page?
Thank you.

**Comment by BenFradet** [comment]
Thanks, fixed! And no unfortunately there is no easy way to contribute to the wiki.
