### ISSUE TITLE
Add first-class email_open event

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#398]
Need to define the fields for this event. Maybe checkout the fields in the Sendgrid data model?

Also: should the user's email address be put in as a dedicated field, or should it go into `uid`?

Once this is done, then think about:

* Redshift and Postgres table definitions and any recipes/cubes
* Adding this to the no-js wizard

**Comment by fblundun** [comment]
We support ingest of email events from MailChimp and Mandrill already, with SendGrid (#1161) on the way, so this should be covered now, closing...
