### ISSUE TITLE
Documentation: Incorrect (old) reference to Reachability dependency for iOS integration

### ISSUE THREAD

**Issue by iur-kaia** [snowplow/snowplow#3993]
**Project**: Snowplow Wiki: iOS Tracker Setup
https://github.com/snowplow/snowplow/wiki/iOS-Tracker-Setup#reach-setup

**Expected behavior**:
Links and examples should point to https://github.com/ashleymills/Reachability.swift which is the dependency installed by the latest Snowplow iOS tracker

**Actual behavior**:
Points to older https://github.com/tonymillion/Reachability.git which has this in its README:
"WARNING there have been reports of apps being rejected when Reachability is used in a framework. The only solution to this so far is to rename the class."

**Comment by mhadam** [comment]
Thanks @iur-kaia for pointing this out, but we've started using a new site for documentation (linked in the README).

**Comment by BenFradet** [comment]
thanks, closing
