### ISSUE TITLE
Scala Stream Collector: allow multiple cookie domains to be used

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3994]
The idea, if I got it right, would be to investigate the content of the `Origin` header and send back a `Set-Cookie` with the corresponding domain, e.g.:

```hocon
collector.cookie {
    enabled = true
    expiration =  365 days"
    name = cookie
    domains = {
      "snowplowanalytics.com" = ".snplow.com"
      "other-domain.com" = ".something-else.com"
      // we could have a fallback / catch all here
    }
}
```

cc @jbeemster

**Comment by szareiangm** [comment]
This is very interesting and something that we are interested, too.  Has anyone started working on it?

 what is your suggested fallback? like a default domain? how about mirroring whatever domain that they come from?

**Comment by BenFradet** [comment]
No, no one has started on this yet.

Regarding the fallback I think we'd want to mirror the existing functionality to avoid breakage.

>how about mirroring whatever domain that they come from?

I think this would constitute a security liability.
