### ISSUE TITLE
Scala Common Enrich: make JSON camelizing function stack-safe

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#4013]
https://github.com/snowplow/snowplow/blob/dd8eec21d75da7ba56f2a2ee37971c981d1b9ac9/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/Adapter.scala#L431-L434

might be possible through the yet unpublished circe recursion scheme module: https://github.com/circe/circe/tree/master/modules/rs/src/main/scala/io/circe/rs

**Comment by BenFradet** [comment]
same for https://github.com/snowplow/snowplow/blob/dd8eec21d75da7ba56f2a2ee37971c981d1b9ac9/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/MailchimpAdapter.scala#L169-L173

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/23
