### ISSUE TITLE
Scala Common Enrich: make IpAddressExtractor fall back to the Forwarded: for= header as a last resort

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#4014]
`X-Forwarded-For` should take priority over `Forwarded: for=`

also make sure the regex doesn't capture the port

**Comment by BenFradet** [comment]
https://snowplow.zendesk.com/agent/tickets/13808

**Comment by ihortom** [comment]
We also should keep in mind that `X-Forwarded-For` could have a few IP addresses listed. I guess the order is significant and we need to extract the 1st one:

```
X-Forwarded-For: 105.167.230.20, 82.145.209.195
```

**Comment by BenFradet** [comment]
yes that's already the case
