### ISSUE TITLE
Scala Common Enrich: get rid of dependencies not published on Maven Central

### ISSUE THREAD

**Issue by rverma-nikiai** [snowplow/snowplow#4015]
**Project**: 
 Stream Enrich

**Version**:
com.snowplowanalytics:snowplow-common-enrich_2.11:0.36.0

**Expected behavior**:
While importing lib com.snowplowanalytics:snowplow-common-enrich_2.11:0.36.0, it should automatically resolve the additional deps. These should be available in maven repo(bintray/maven central)

**Actual behavior**:
Can't resolve 
com.snowplowanalytics:collector-payload-1:0.0.0
com.snowplowanalytics:referer-parser_2.11:0.3.0
com.snowplowanalytics:schema-sniffer-1:0.0.0
com.snowplowanalytics:snowplow-thrift-raw-event:0.1.0

**Steps to reproduce**:
Create an empty Gradle project and add dependency as  `com.snowplowanalytics:snowplow-common-enrich_2.11:0.36.0`

Will it be possible to set up a publish artifact to bintray ci for those additional snowplow deps. This would be really helpful with the new architecture.

Though I would suggest rather than splitting all bases in different repos, would be awesome if we aggregate all base(*common) project in one repo and publish reusable artifacts from there.

Then in snowplow code, we only have enrichers codes. I understand that this would make development lengthy but will have abstraction advantages.

**Comment by BenFradet** [comment]
Hello yes, we have old artifacts that are only available in our repo: https://github.com/snowplow/snowplow/blob/dd8eec21d75da7ba56f2a2ee37971c981d1b9ac9/3-enrich/scala-common-enrich/project/Dependencies.scala#L28-L29

These repos are also in stream enrich: https://github.com/snowplow/snowplow/blob/dd8eec21d75da7ba56f2a2ee37971c981d1b9ac9/3-enrich/stream-enrich/project/Dependencies.scala#L19-L20

Could you expand on what you want us to do?

**Comment by rverma-nikiai** [comment]
@BenFradet Are we maintaining 2 repositories, an old one and a new one (bintray). I read somewhere that you are moving to https://snowplow.bintray.com/snowplow-maven, so expecting those artifacts there as well. Using the old repo url does solved my issue.

**Comment by BenFradet** [comment]
We are moving as much as possible to central (through bintray) but old artifacts are still in http://maven.snplow.com/releases/

**Comment by rverma-nikiai** [comment]
I am building a new sink in java 'cloudwatch logs sink' for bad stream and another enricher aws-batch. Thinking of using common libraries to build over it. Any guidelines would be highly appreciated :)

**Comment by BenFradet** [comment]
for the bad stream sink, I wouldn't pull scala-common-enrich. Also keep in mind that we're working on a new bad data format: https://discourse.snowplowanalytics.com/t/a-new-bad-row-format/2558.

As for the new enricher, could you post your gradle file as a github gist so we can have a look?

Also if you want to open source those projects we can create repos for you in https://github.com/snowplow-incubator/ if you want :+1:

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/24
