### ISSUE TITLE
Scala Common Enrich: Support multiple instances of API request enrichment

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow#4022]
The goal is to have multiple instances of one enrichment. This could be first step toward more complex enrichment process. 

This issue is more focused on on the popular API request enrichment and can be extended to the other ones, as soon as the design is streamline with everybody's thoughts.

I have created this issue as per guidance from Ben in  #2260

**Comment by exilitco** [comment]
Any progress on this?

**Comment by chuwy** [comment]
@exilitco yes, we plan to release this feature early 2020.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/26
