### ISSUE TITLE
Use https for the artifact repo

### ISSUE THREAD

**Issue by marshallpierce** [snowplow/snowplow#4025]
In 2019, it's not too controversial to serve artifacts over https.

An easy way to do this is simply to use [Bintray](https://bintray.com/).

**Comment by BenFradet** [comment]
Hello, which artifacts are you talking about in particular? The majority of our artifacts are in bintray: https://bintray.com/snowplow

**Comment by marshallpierce** [comment]
Argh, my mistake - I meant to have filed this on https://github.com/snowplow/snowplow-java-tracker, which is documented to use an http-only repo: https://github.com/snowplow/snowplow/wiki/Java-Tracker-Setup#setup

However, I'm delighted to see https://bintray.com/snowplow/snowplow-maven/snowplow-java-tracker -- does that mean the only change needed is updating those docs?

**Comment by BenFradet** [comment]
yup :+1: , ping @mhadam
