### ISSUE TITLE
Scala Common Enrich: bump iglu-scala-client to 0.6.1

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#4029]

**Comment by chuwy** [comment]
Hey @benjben! Can we update it to 0.6.1? So far only 0.6.1-M1 is published (final version will be availiable soon). It fixes a criitical bug for enrichment.

**Comment by benjben** [comment]
Sure @chuwy ! I created #4213 to avoid rebase conflicts

**Comment by chuwy** [comment]
Closing this since iglu-scala-client is brought into SCE by snowplow-badrows.

**Comment by chuwy** [comment]
On the other hand, this commit happened before we added snowplow-badrows.
