### ISSUE TITLE
Scala Common Enrich: separate EnrichmentRegistry parsing from its construction

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#4033]
the workflow for an enrichment platform should be:

1. parse and validate enrichment jsons: `Json -> F[List[EnrichmentConf]]` (enrichment configs contain the files to cache)
2. cache files: `List[EnrichmentConf] -> F[Unit]` or `Unit`, this is up to the enricher
3. construct `EnrichmentRegistry`: `List[EnrichmentConf] -> F[List[Enrichment]]`
4. enrich: `List[Enrichment] -> F[List[EnrichedEvent]]`

We need to separate parsing from construction because some enrichments' constructions are side-effectful, for example referer parser which reads a file

**Comment by szareiangm** [comment]
can we have step3 produce `[EnrichmentConf] -> F[List[Enrichment]]`? It would help to have multiple API Request Enrichments

**Comment by BenFradet** [comment]
I added `List` instead of `[]` so it's clearer, however supporting multiple api request enrichments is not planned for this release.

**Comment by szareiangm** [comment]
That's okay. At least I will use the result of this issue for my issue. It would be ways more straight-forward.
