### ISSUE TITLE
EmrEtlRunner: initialize S3::Aws constant

### ISSUE THREAD

**Issue by kramerc** [snowplow/snowplow#4036]
**Project**: EmrEtlRunner

**Version**: R113 Filitosa

**Expected behavior**: To initialize an EMR jobflow

**Actual behavior**:
```
$./snowplow-emr-etl-runner run --config stream_config.yml --resolver resolver.json --targets targets         [14:21:53]
uri:classloader:/gems/avro-1.8.1/lib/avro/schema.rb:350: warning: constant ::Fixnum is deprecated
uri:classloader:/gems/json-schema-2.7.0/lib/json-schema/util/array_set.rb:18: warning: constant ::Fixnum is deprecated
D, [2019-04-11T14:22:04.448961 #58001] DEBUG -- : Initializing EMR jobflow
NameError: uninitialized constant Snowplow::EmrEtlRunner::S3::AWS
             const_missing at org/jruby/RubyModule.java:3526
              list_objects at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/s3.rb:106
       block in empty_impl at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/s3.rb:85
                      loop at org/jruby/RubyKernel.java:1418
                empty_impl at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/s3.rb:84
                    empty? at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/s3.rb:36
                initialize at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb:457
                   send_to at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_reference.rb:43
                 call_with at uri:classloader:/gems/contracts-0.11.0/lib/contracts/call_with.rb:76
  block in redefine_method at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_handler.rb:138
                       run at uri:classloader:/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:135
                   send_to at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_reference.rb:43
                 call_with at uri:classloader:/gems/contracts-0.11.0/lib/contracts/call_with.rb:76
  block in redefine_method at uri:classloader:/gems/contracts-0.11.0/lib/contracts/method_handler.rb:138
                    <main> at uri:classloader:/emr-etl-runner/bin/snowplow-emr-etl-runner:41
                      load at org/jruby/RubyKernel.java:994
                    <main> at uri:classloader:/META-INF/main.rb:1
                   require at org/jruby/RubyKernel.java:970
                    (root) at uri:classloader:/META-INF/main.rb:1
                    <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
ERROR: org.jruby.embed.EvalFailedException: (NameError) uninitialized constant Snowplow::EmrEtlRunner::S3::AWS
```

**Steps to reproduce**:

 1. Run EmrEtlRunner with a valid configuration

---

It seems this is happening due to a change in the constant name from `AWS` to `Aws` in recent versions of the AWS SDK. EmrEtlRunner runs correctly when I change the constant name in [3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3.rb](https://github.com/snowplow/snowplow/blob/dd8eec21d75da7ba56f2a2ee37971c981d1b9ac9/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/s3.rb#L107) from `AWS` to `Aws`.

**Comment by BenFradet** [comment]
hey, did you build EmrEtlRunner yourself?

We don't have this issue internally so I'm thinking https://github.com/snowplow/snowplow/blob/dd8eec21d75da7ba56f2a2ee37971c981d1b9ac9/3-enrich/emr-etl-runner/Gemfile#L28 might not be conservative enough?

**Comment by kramerc** [comment]
This happens with [the R113 version from Bintray](https://bintray.com/snowplow/snowplow-generic/snowplow/r113-filitosa#files) and when I was building it myself.

**Comment by BenFradet** [comment]
mmh weird, I'll try reproducing

**Comment by BenFradet** [comment]
Was able to reproduce, scheduling, thanks a lot :+1:

**Comment by BenFradet** [comment]
nvm false alarm, I wasn't able to reproduce in the end

**Comment by kramerc** [comment]
Do you know what changed that made it so you weren't able to reproduce in the end?

**Comment by BenFradet** [comment]
I heard about `undefined errors` internally so I immediately thought about this one, but it turns out it wasn't related.

Anyway, we've decided to do a bit of work around eer in the next release, so I might as well tackle this one :+1:, unless you want to open a PR?
