### ISSUE TITLE
Scala Common Enrich: IAB enrichment fails for Opera Mini

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#4038]
**Project**: All Enrich / Scala Stream Collector

**Version**: All

**Expected behavior**: For valid IP addresses events sent via Opera Mini for pipelines using the IAB enrichment should not return bad rows.

**Actual behavior**:
The IP address is flagged as invalid as the address contains a port
>IP address 49.195.X.X:27817 was invald

**Steps to reproduce**:
Headers truncated for readability

```
val headers = List("Device-Stock-UA: Mozilla/5.0 (Linux; U; Android 4.0.4) ...", "Forwarded: for=\"102.146.1.1:39817\"", "User-Agent: Opera/9.80 (Android; Opera Mini/7.0.32026/138.54; U; en) Presto/2.12.423 Version/12.16", "X-OperaMini-Phone-UA: Mozilla/5.0 (Linux; U; Android 4.0.4; en-gb; GT-S5301 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30", "X-Forwarded-For: 102.146.1.1, 185.26.1.1", "X-Forwarded-Port: 443")
extractIpAddress(headers, "")
res1: String = 102.146.1.1:39817
```

Opera Mini prepends the Forwarded header which contains the port (which is technically valid under RFC7239) and then due to the cons operator the Forwarded regex matches and the iteration terminates resulting in the IP address and the port being returned. This then causes additional downstream issues in the IAB enrichment where `InetAddress.getByName` is used and due to the colon being present in the address errors out with an UnknownHostException as it tries to parse it as a IPv6 address.

**Comment by BenFradet** [comment]
Thanks, it seems the IAB enrichment isn't that resilient between this, #3951 and #3952

**Comment by benjben** [comment]
Handled by #3951.
