### ISSUE TITLE
Scala Common Enrich: add timeout to API Request Enrichment

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow#4041]
**Project**:  Scala Common Enrich

**Version**: 0.36.0

**Expected behavior**: Support timeout

**Actual behavior**: There is no code that would handle timeout

**Steps to reproduce**: did a code search and turned out that timeout was not passed to ScalaJ.

I was reading the code for API Request Enrichment to understand how it would handle the timeout to reuse the same code for `HTTP Remote Adapter` It turned out the settings are passed to `com.snowplowanalytics.snowplow.enrich.common.enrichments.registry.apirequest.HttpApi`
 but likely it is not passed to the Scalaj library in `perform` function. 

This is a quick change, so I will add it after my current PR. Before that, I have one question. What was the intention for this timeout setting? Was it `connectionTimeout` or `readTimeout`?

I could not find it in the documentations but I prefer to have both because they could handle different cases. 

CC: @Nafid @dmatth

**Comment by BenFradet** [comment]
nicely spotted :+1:

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/27

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/36
