### ISSUE TITLE
Beam Enrich: add possibility to specify conf for remote adapters

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4080]
Remote adapters require some configuration, for example : 
```
remoteAdapters = [
￼	   {
￼	       vendor: "special-vendor"
￼	       version: "v1"
￼	       url: "http://remote-adapter.com:9090"
￼	       connectionTimeout: 1000
￼	       readTimeout: 5000
￼	   }
￼]
```
Currently there is no way to pass this configuration to `beam-enrich`, as it only accepts command-line arguments.

A solution could be to add an optional argument containing the path to the configuration file with the remote adapters.

**Comment by BenFradet** [comment]
I think the way forward is to add a specific optional configuration like for enrichments which is schema'ed

**Comment by peel** [comment]
Moved to https://github.com/snowplow/beam-enrich/issues/24
