### ISSUE TITLE
Scala Stream Collector: add support for TLS port binding and certificate

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow#4085]
At the moment the SSC only binds over an unsecured port which means we cannot achieve end-to-end encryption when tracking data.  It would be great to add an optional TLS port for the collector so that we could achieve this ability.

**Comment by yalisassoon** [comment]
@dilyand - can you remind me why we removed this from r116? Talking to @jbeemster to see when we can get this added

**Comment by dilyand** [comment]
@yalisassoon It was considered a nice-to-have but not immediately required by customers.

**Comment by yalisassoon** [comment]
I think this would be a big win for Tech Ops, who are having to do some custom engineering around it. @jbeemster can you provide some more details in the thread?

**Comment by peel** [comment]
In #4204 I added a possibility to set it up using JSSE-wrapper [ssl-config](https://lightbend.github.io/ssl-config/index.html) which comes with akka-http. 

It should be as simple as enabling `collector.ssl = true` and tuning `akka.ssl-config` to your liking. Should support all the [options](https://github.com/lightbend/ssl-config/blob/master/ssl-config-core/src/main/resources/reference.conf) available in ssl-config.

**Comment by yalisassoon** [comment]
That looks great @peel - do you know what release this is likely to go into?

**Comment by peel** [comment]
@yalisassoon So far we're aiming for R117
