### ISSUE TITLE
Stream Enrich: support private Kinesis endpoints

### ISSUE THREAD

**Issue by Manjunath07** [snowplow/snowplow#4107]
**Project**:  Stream Enrich
**Version**: 0.21.0

**Error**: Received error response: com.amazonaws.services.kinesis.model.AmazonKinesisException: Credential should be scoped to a valid region, not ‘vpce’ (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidSignatureException.

Debug logs shows that credentialscope for AWS4 Canonical Request coming as 20190611/vpce/kinesis/aws4_request.  This is coming for only enricher not for collector.

**Steps to reproduce**:
Providing customendpoint as private kinesis endpoint
customEndpoint = vpce-XXXXXXXXXXX-XXXXXXXXXXX.kinesis.eu-west-1.vpce.amazonaws.com

More Info.
https://discourse.snowplowanalytics.com/t/snowplow-enrcihment-not-working-for-private-kinesis-endpoints/2923

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/39
