### ISSUE TITLE
Enable YAUAA enrichment to reference the engine and ruleset by http/s3 URI

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/snowplow#4113]
Thanks for integrating the YAUAA as a new enrichment. However, there is already a newer version of the engine plus ruleset released. Can you enable the enrichment config to reference the engine jar and the ruleset file to be refrenced by an HTTP or S3 URI, like the ip-lookup or the iab enrichment? Both those files need to be automatically downloaded and added the classpath. We made it happen locally in a pretty hacky way. But ideally it is properly supported by snowplow.

Thank you!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/41
