### ISSUE TITLE
Scala Common Enrich: return capitalised Unknown value in YAUAA enrichment

### ISSUE THREAD

**Issue by miike** [snowplow/snowplow#4114]
Currently the YAUUA enrichment returns the `UNKNOWN` as a default value however this string is not in the enum schema for the deviceClass property and therefore fails schema validation.

Instead of returning `UNKNOWN` return `Unknown` instead as is expected by the schema. I don't think there is any value in differentiating between YAUUA unknown and Snowplow unknown.

**Comment by benjben** [comment]
The schema has been [patched](https://github.com/snowplow/iglu-central/commit/adf35996082e49e88ae7f09087bc1f0b605105a6) but we still should update to `Unknown` so that the default matches with what YAUAA API returns to not have both `UNKNOWN` and `Unknown` in the data warehouse.
