### ISSUE TITLE
Common: publish Docker images for scala-stream-collector, beam-enrich and stream-enrich to Docker Hub

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4122]

**Comment by benjben** [comment]
@jbeemster can you add the env vars to publish to Docker Hub, similarly to what have been done for Snowplow Micro [here](https://github.com/snowplow-incubator/snowplow-micro/blob/master/.travis.yml#L23) please?

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/snowplow/issues/4237
