### ISSUE TITLE
Wiki: Postgres initdb command

### ISSUE THREAD

**Issue by lancerutkin** [snowplow/snowplow#4125]
**Expected behavior**:
Per the suggestion given by Linux shell, the new preferred command for postgres initdb is:
`sudo postgresql-setup initdb`

This generates the following message from the shell:
`Initializing database ... OK`

**Actual behavior**:
The wiki currently instructs users to use the command:
`sudo service postgresql initdb`

This generates the following response from the shell:
`Hint: the preferred way to do this is now "postgresql-setup initdb"
Initializing database ... OK`

**Steps to reproduce**:
Follow the wiki instructions on [setting up Postgres](https://github.com/snowplow/snowplow/wiki/Setting-up-PostgreSQL)

Fix: Edit wiki to reflect the recommendation by the shell

**Comment by chuwy** [comment]
Thanks, @lancerutkin. Fixed.
