### ISSUE TITLE
Iglu Webhook Adapter: Accept array POST requests

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/snowplow#4127]
Currently sending a JSON-array to the webhook adapter causes the data to fail validation if sent like so:

```
curl http://acme.com/com.snowplowanalytics.iglu/v1 -H "Content-Type: application/json" -d '[{
    "schema":"iglu:com.acme/event/jsonschema/1-0-0",
    "data": {
      "key":"value"
    }
  }, {
    "schema":"iglu:com.acme/event/jsonschema/1-0-0",
    "data": {
      "key":"value"
    }
  }, {
    "schema":"iglu:com.acme/event/jsonschema/1-0-0",
    "data": {
      "key":"value"
    }
  }]'
```
Validation error message:

> "message": "Iglu event failed: detected SelfDescribingJson but schema key is missing"

Sending a malformed array with no square braces, however, is successful:

```
curl http://acme.com/com.snowplowanalytics.iglu/v1 -H "Content-Type: application/json" -d '{
    "schema":"iglu:com.acme/event/jsonschema/1-0-0",
    "data": {
      "key":"value"
    }
  }, {
    "schema":"iglu:com.acme/event/jsonschema/1-0-0",
    "data": {
      "key":"value"
    }
  }, {
    "schema":"iglu:com.acme/event/jsonschema/1-0-0",
    "data": {
      "key":"value"
    }
  }'
```

Iglu webhook adapter should be able to handle a legitimate JSON array of data.

**Comment by jbeemster** [comment]
https://github.com/snowplow/snowplow/issues/3858

This should already be supported - but it seems like the schema should be defined on the querystring for this to work?

**Comment by colmsnowplow** [comment]
Yes, sorry my original message is unclear. It is possible to send multiple events via POST request. However I find it odd that an invalid array of SD-jsons `{"schema": "foo", "data":"bar}, {"schema":"foo","data":"baz"}` works, this method but a valid array `"[{"schema": "foo", "data":"bar}, {"schema":"foo","data":"baz"}]` doesn't.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/42
