### ISSUE TITLE
Beam Enrich: split `EnrichWithLocalFileSpec` test into two

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplow#4130]
This test currently tests two things at the same time:

- that we can successfully download and use the latest version of the Maxmind DB for IP lookups from the `hosted-assets` bucket;
- that the enrichment produces the expected output.

However, when a new version of the DB is uploaded to `hosted-assets`, this test can start failing because the data points associated with the hardcoded IP address in it might have changed.

It will be better to split this into two tests. One will test the download works as expected. The other one will use the same DB file every time, eliminating the need to re-write the test every so often.

**Comment by dilyand** [comment]
https://github.com/snowplow/snowplow/issues/4129#issuecomment-527397799

**Comment by peel** [comment]
Moved: https://github.com/snowplow/beam-enrich/issues/23
