### ISSUE TITLE
Stream Enrich: bump iglu-scala-client to 0.6.0

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4146]

**Comment by chuwy** [comment]
Wondering why do we have Iglu Client in Stream Enrich listed as it is a transitive dependency from SCE.

**Comment by benjben** [comment]
Good question. I'll remove it from the dependencies

**Comment by benjben** [comment]
Handled by #4148 , `iglu-client` is now a transitive dependency from SCE
