### ISSUE TITLE
CLV queries in documentation need small updates

### ISSUE THREAD

**Issue by kingo55** [snowplow/snowplow#415]
Hey guys,

Just figured I'd make the code on the CLV docs a little more n00b friendly. I needed to make a few adjustments to the code on the page in order for it to run:

http://snowplowanalytics.com/analytics/customer-analytics/customer-lifetime-value.html

The first query should be:

``` sql
/* PostgreSQL / Redshift */
SELECT
domain_userid,
SUM(tr_total)
FROM "atomic".events
WHERE event = 'transaction'
GROUP BY 1
```

You may need a schema for the calculations and STRING didn't work under Postgres:

``` sql
CREATE SCHEMA clv_calculation;

CREATE TABLE clv_calculation.events_by_value (
    se_action VARCHAR(10),
    value FLOAT);
```

And here's one for adding the values:

``` sql
INSERT INTO clv_calculation.events_by_value VALUES
    ('social', 2.5), ('email', 2.5);
```

Also fixed the group by clause for combining the indirect values with events by user:

``` sql
SELECT
e.domain_userid,
SUM(v.value)
FROM "atomic".events e
JOIN clv_calculation.events_by_value v
ON e.se_action = v.se_action 
GROUP BY 1
```

Note, I haven't gotten so far as to ascribe future values based on segments etc. Hope that helps.

**Comment by BenFradet** [comment]
not the same website, closing
