### ISSUE TITLE
Scala Common Enrich: put CollectorPayload in an external library

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4207]
[CollectorPayload](https://github.com/snowplow/snowplow/blob/scala_common_enrich/0.37.0/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/collectorPayload.scala#L140) should be put in an external library, so that it can be used by `scala-common-enrich` and `snowplow-badrows`, instead of manually defining it in both, thus opening the way for mistakes and incompatibility.

**Comment by chuwy** [comment]
It seems that we're getting our dependency graph very complicated. Many libraries define core components and some of these libs depend on each other.

1. `snowplow-scala-analytics-sdk`
2. `snowplow-badrows` (depends on SDK)
3. `scala-common-enrich` (depends on badrows)
4. `iglu-scala-core` (all above depend on it)
5. Some core structures also implemented in Scala Tracker

Maybe this could be a library that defines tracker-collector protocol communication? Pretty much like `snowplow-scala-analytics-sdk` defines enrich-loader communication.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/43
