### ISSUE TITLE
Common: add assembly step to CI

### ISSUE THREAD

**Issue by lukeindykiewicz** [snowplow/snowplow#4217]
`sbt assembly` could fail after changes (i.e. on merge policy), so good to add this step to CI

**Comment by chuwy** [comment]
IIRC sbt assembly runs tests by default. It could be worth to omit separate `sbt test` to safe some time (by not executing tests twice).

**Comment by chuwy** [comment]
Also, does it belong to R117?

**Comment by lukeindykiewicz** [comment]
`assembly` does run tests, but I wanted to leave it as to be clear which step failed exactly. I can remove it if you like.

> Also, does it belong to R117?

What do you mean?

**Comment by chuwy** [comment]
>> Also, does it belong to R117?
> What do you mean?

I wondered if implementation of this ticket is going to end up in https://github.com/snowplow/snowplow/pull/4218

**Comment by lukeindykiewicz** [comment]
It's already there :)

**Comment by chuwy** [comment]
Adding a milestone then. Please double-check that all your implemented tickets are in their milestone (and vice versa - that milestone has all assigned tickets implemented)

**Comment by lukeindykiewicz** [comment]
Removed from R117. The impl was producing false positives! Might be reopen when needed.
