### ISSUE TITLE
Scala Common Enrich: remove shred function

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4233]
We used to have a big `Shred` object with logic related to extraction and validation of self-describing data, but only very few methods were used in actual enrichers, everything else was used in RDB Shredder. Since [R31](https://github.com/snowplow/snowplow-rdb-loader/issues/138) we use Scala Analytics SDK for these purposes and many shredding methods are unused.

**Comment by benjben** [comment]
By remove shredding you mean removed unused methods in `Shredder` right?
We still [need](https://github.com/snowplow/snowplow/blob/release/r115-morgantina/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala#L177) `Shredder` to validate the contexts and the unstructured event.

**Comment by benjben** [comment]
Maybe we could do it at the same time as #3795

**Comment by chuwy** [comment]
> By remove shredding you mean removed unused methods in Shredder right?

Yes, sorry I didn't know how to phrase it better. The actual `shred` method is not used anywhere, but `extractAndValidate`-like are necessary for enrichment (though can be simplified).

**Comment by chuwy** [comment]
Also removed unnecessary `TypeHierarchy` class, added some tests and simplified types in few related functions.
