### ISSUE TITLE
Spark Enrich: use hadoop-lzo 0.4.20 from Snowplow Bintray maven

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4238]
As `hadoop-lzo` is not available there anymore and we need to re-publish it to our own repo.

https://github.com/twitter/hadoop-lzo/issues/140

**Comment by lukeindykiewicz** [comment]
Published at the moment to: https://bintray.com/lukeindykiewicz/maven/hadoop-lzo/0.4.20

**Comment by lukeindykiewicz** [comment]
Published under Snowplow: https://bintray.com/snowplow/snowplow-maven/hadoop-lzo/0.4.20

**Comment by chuwy** [comment]
We technically could remove Twitter maven repository altogether, but `elephant-bird-core:4.14` depends on `hadoop-lzo:0.4.19`. It is not used in compile-time because replaced by `0.4.20`, but SBT tries to pull `pom.xml` and fails. Can you also publish `0.4.19`, @lukeindykiewicz and remove the repo?

**Comment by lukeindykiewicz** [comment]
We leave the Twitter repo, cause the groupId is different and we hope the jars will come back to the repo eventually.
