### ISSUE TITLE
Scala Common Enrich: add contexts validating enrichment

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4240]
An enrichment where we can specify a rule like "if event_type == com.acme/video_view/jsonschema/1-0-0 then event must contain a context com.acme/user/jsonschema/1-0-0 else send event to bad with specific error"

**Comment by alexanderdean** [comment]
Interesting to consider:

1. How the ruleset is expressed - what is the grammar
2. Where the ruleset lives - inside an event schema, outside it but still inside the schema registry, somewhere else

**Comment by chuwy** [comment]
1. I don't think we should try too hard to make the grammar super generic. Very basic logical operations should be enough:

```json
[{
  "type": "event",
  "schema": "iglu:com.acme/checkin/jsonschema/1-*-*",
  "requires": [
    {
      "type": "context",
      "schema": "iglu:com.acme/maxmind_geolocation/jsonschema/1-0-0",
      "or": [{
        "type": "context",
        "schema": "iglu:com.acme/gps_geolocation/jsonschema/*-*-*",
      }]
    }
  ],

  "type": "context",
  "schema": "iglu:com.acme/ecommerce_item/jsonschema/1-0-0",
  "requires": [
    {
      "type": "event",
      "schema": "iglu:com.acme/ecommerce_transaction/jsonschema/1-0-0"
    }
  ]
}]
```

Everything inside root and `requires` is logical `AND`. Everything inside `or` is logical `OR`. We can express deeper conditions, but I doubt it is necessary.

2. The ruleset lives in enrichment config. Putting this into schema or registry makes it too rigid IMO.

**Comment by alexanderdean** [comment]
1. Agree, best to start simple.

2. Agree. It will be faster to iterate the design and implementation of this in an enrichment. Once it comes out of R&D phase, if there is a more logical home for these event definitions (e.g. the schema registry), should be relatively straightforward to migrate.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/45
