### ISSUE TITLE
Beam Enrich: use test Maxmind databases

### ISSUE THREAD

**Issue by dilyand** [snowplow/snowplow#4242]
Whenever a new version of the Maxmind DB for ip lookups is uploaded to the hosted assets bucket, the `EnrichWithLocalFileSpec` test in Beam Enrich can start failing if the data points associated with the IP address used in it have changed.

Maxmind provides stable test DBs that we can use to make the test less flaky: https://github.com/maxmind/MaxMind-DB/tree/master/test-data

**Comment by peel** [comment]
Moved to: https://github.com/snowplow/beam-enrich/issues/22
