### ISSUE TITLE
Scala Common Enrich: add an enrichment extracting canonical properties into dedicated contexts

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4244]
In order to refactor atomic events we need to extract all non-generic information from a fat table into dedicated contexts and preserve only common properties. As a first step, we can have those properties in atomic event (as we do now, to not break data models) and in their deciated tables/columns (to start writing new data models).

I tried to summarize what contexts and event-specific properties can be extracted out of `Event`:
1. `app_id`                   
1. `platform`                 
1. `etl_tstamp`               
1. `collector_tstamp`         
1. `dvce_created_tstamp`      
1. `event`                    
1. `event_id`                 
1. `txn_id`                   
1. `name_tracker`             
1. `v_tracker`                
1. `v_collector`              
1. `v_etl`                    
1. `user_id`                  
1. `user_ipaddress`           
1. `user_fingerprint`         
1. `domain_userid`            
1. `domain_sessionidx`        
1. `network_userid`           
1. `geo_country`               - MaxMind context 
1. `geo_region`                - MaxMind context
1. `geo_city`                  - MaxMind context
1. `geo_zipcode`               - MaxMind context
1. `geo_latitude`              - MaxMind context
1. `geo_longitude`             - MaxMind context
1. `geo_region_name`           - MaxMind context
1. `ip_isp`                    - MaxMind context
1. `ip_organization`           - MaxMind context
1. `ip_domain`                 - MaxMind context
1. `ip_netspeed`               - MaxMind context
1. `page_url`                  - Web page context (source of truth)
1. `page_title`                - Web page context (source of truth)
1. `page_referrer`             - Referrer context (source of truth)
1. `page_urlscheme`            - Web page context
1. `page_urlhost`              - Web page context
1. `page_urlport`              - Web page context
1. `page_urlpath`              - Web page context
1. `page_urlquery`             - Web page context
1. `page_urlfragment`          - Web page context
1. `refr_urlscheme`            - Referrer context
1. `refr_urlhost`              - Referrer context
1. `refr_urlport`              - Referrer context
1. `refr_urlpath`              - Referrer context
1. `refr_urlquery`             - Referrer context
1. `refr_urlfragment`          - Referrer context
1. `refr_medium`               - Referrer context
1. `refr_source`               - Referrer context
1. `refr_term`                 - Referrer context
1. `mkt_medium`                - Marketing campaign context
1. `mkt_source`                - Marketing campaign context
1. `mkt_term`                  - Marketing campaign context
1. `mkt_content`               - Marketing campaign context
1. `mkt_campaign`              - Marketing campaign context
1. `contexts`                 
1. `se_category`               - Struct event self-describing event
1. `se_action`                 - Struct event self-describing event
1. `se_label`                  - Struct event self-describing event
1. `se_property`               - Struct event self-describing event
1. `se_value`                  - Struct event self-describing event
1. `unstruct_event`           
1. `tr_orderid`                - Ecommerce transaction self-describing event
1. `tr_affiliation`            - Ecommerce transaction self-describing event
1. `tr_total`                  - Ecommerce transaction self-describing event
1. `tr_tax`                    - Ecommerce transaction self-describing event
1. `tr_shipping`               - Ecommerce transaction self-describing event
1. `tr_city`                   - Ecommerce transaction self-describing event
1. `tr_state`                  - Ecommerce transaction self-describing event
1. `tr_country`                - Ecommerce transaction self-describing event
1. `ti_orderid`                - Ecommerce transaction item context
1. `ti_sku`                    - Ecommerce transaction item context
1. `ti_name`                   - Ecommerce transaction item context
1. `ti_category`               - Ecommerce transaction item context
1. `ti_price`                  - Ecommerce transaction item context
1. `ti_quantity`               - Ecommerce transaction item context
1. `pp_xoffset_min`            - Page ping self-describing event
1. `pp_xoffset_max`            - Page ping self-describing event
1. `pp_yoffset_min`            - Page ping self-describing event
1. `pp_yoffset_max`            - Page ping self-describing event
1. `useragent`                 - Browser context (but populated from different places)
1. `br_name`                   - Browser context (but populated from different places)
1. `br_family`                 - Browser context (but populated from different places)
1. `br_version`                - Browser context (but populated from different places)
1. `br_type`                   - Browser context (but populated from different places)
1. `br_renderengine`           - Browser context (but populated from different places)
1. `br_lang`                   - Browser context (but populated from different places)
1. `br_features_pdf`           - Browser context (but populated from different places)
1. `br_features_flash`         - Browser context (but populated from different places)
1. `br_features_java`          - Browser context (but populated from different places)
1. `br_features_director`      - Browser context (but populated from different places)
1. `br_features_quicktime`     - Browser context (but populated from different places)
1. `br_features_realplayer`    - Browser context (but populated from different places)
1. `br_features_windowsmedia`  - Browser context (but populated from different places)
1. `br_features_gears`         - Browser context (but populated from different places)
1. `br_features_silverlight`   - Browser context (but populated from different places)
1. `br_cookies`                - Browser context (but populated from different places)
1. `br_colordepth`             - Browser context (but populated from different places)
1. `br_viewwidth`              - Browser context (but populated from different places)
1. `br_viewheight`             - Browser context (but populated from different places)
1. `os_name`                   - Browser context (but populated from different places)
1. `os_family`                 - Browser context (but populated from different places)
1. `os_manufacturer`           - Browser context (but populated from different places)
1. `os_timezone`               - Browser context (but populated from different places)
1. `dvce_type`                 - Browser context (but populated from different places)
1. `dvce_ismobile`             - Browser context (but populated from different places)
1. `dvce_screenwidth`          - Browser context (but populated from different places)
1. `dvce_screenheight`         - Browser context (but populated from different places)
1. `doc_charset`               - Web page (or document) context
1. `doc_width`                 - Web page (or document) context
1. `doc_height`                - Web page (or document) context
1. `tr_currency`               - Ecommerce transaction self-describing event
1. `tr_total_base`             - Ecommerce transaction self-describing event
1. `tr_tax_base`               - Ecommerce transaction self-describing event
1. `tr_shipping_base`          - Ecommerce transaction self-describing event
1. `ti_currency`               - Ecommerce transaction item context
1. `ti_price_base`             - Ecommerce transaction item context
1. `base_currency`             - Ecommerce transaction self-describing event
1. `geo_timezone`              - MaxMind context
1. `mkt_clickid`               - Marketing campaign context
1. `mkt_network`               - Marketing campaign context
1. `etl_tags`                 
1. `dvce_sent_tstamp`         
1. `refr_domain_userid`        - Referrer context
1. `refr_dvce_tstamp`          - Referrer context
1. `derived_contexts`         
1. `domain_sessionid`         
1. `derived_tstamp`           
1. `event_vendor`             
1. `event_name`               
1. `event_format`             
1. `event_version`            
1. `event_fingerprint`        - This should remain in canonical event
1. `true_tstamp`              

Their grouping is not very semantic, but should be based mostly on the info source, e.g. although browser/device info semantically is the same information, some of properties are passed thourgh the tracker protocol and some derived through user-agent enrichment.

#### Contexts

* MaxMind context
* Web page context
* Referrer context 
* Marketing campaign context
* Ecommerce transaction item
* Browser/device context (potentially multiple of them)

#### Self-describing events

* Struct event
* Ecommerce transaction
* Page ping

#### Common properties

It leaves us with 31 core properties that can be set almost for all events/pipelines. Maybe some of them (user/device identification) can/should be moved into dedicated contexts.

1. `event_id` - event identification
1. `app_id` - event identification
1. `event` - eventually will be discarded in favor of vendor/name/version
1. `txn_id` - event identification        
1. `event_vendor` - event identification
1. `event_name` - event identification            
1. `event_format`  - event identification            
1. `event_version` - event identification
1. `event_fingerprint` - event identification
1. `platform` - probably should be moved as well
1. `dvce_created_tstamp` - timestamps
1. `dvce_sent_tstamp` - timestamps     
1. `collector_tstamp` - timestamps
1. `etl_tstamp` - timestamps
1. `derived_tstamp` - timestamps        
1. `true_tstamp` - timestamps
1. `user_id` - user/device identification
1. `user_ipaddress` - user/device identification
1. `user_fingerprint` - user/device identification
1. `domain_userid` - user/device identification
1. `domain_sessionidx` - user/device identification
1. `domain_sessionid` - user/device identification
1. `network_userid` - user/device identification
1. `name_tracker` - pipeline/aux
1. `v_tracker` - pipeline/aux
1. `v_collector` - pipeline/aux            
1. `v_etl` - pipeline/aux
1. `etl_tags` - pipeline/aux   
1. `unstruct_event` - payload
1. `contexts`- payload
1. `derived_contexts` - payload

**Comment by alexanderdean** [comment]
See also atomic.events audit from 2016:

https://docs.google.com/spreadsheets/d/188MRbzFMQ_IKnL5wQkOPtRk-JJXI_xP89aJeYErqj1k/edit#gid=0

**Comment by dilyand** [comment]
I think further entities can be extracted from the common properties:

```
User
user_id

Device
domain_userid
refr_domain_userid
network_userid
useragent
user_fingerprint

Network
user_ipaddress
geo_lattitude
geo_longitude
```

Also, maybe the pipeline can also be seen as an entity, with properties like `v_tracker`, `v_collector` etc?

**Comment by alexanderdean** [comment]
Good catch-up just now Anton!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/47
