### ISSUE TITLE
Scala Common Enrich: attach configuration as a derived context

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4248]
We often want to filter out events based on some configuration enabled, e.g. we updated version of Beam Enrich or MaxMind DB and got an unexpected behavior - we want to analyze only that set of events, but currently cannot do this in a predictable way.

Should it be a hash of all config files? How we can make sure the hash can be reversed?

**Comment by alexanderdean** [comment]
If the config files only evolved in a version-controlled way (think of an append-only store with cursor/reference, not literally git), then you would only need to store the cursor reference.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/50
