### ISSUE TITLE
Common: split the monorepo into individual repositories

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4251]
Reasoning is that it becomes too cumbersome to release patch releases of individual components and split work between different engineers. Also I expect it should help with CI/CD process and external contributions.

We have came up with options on what to do with `snowplow/snowplow` as we don't want to lose this entrypoint.

1. Transform all projects into submodules as we did with `1-trackers` and periodically update them. That would also allow us to bring loaders back to a `snowplow/snowplow` as technically they're core part of pipeline.
2. Use this repo for documentation and publish it to GH pages
3. Combination of 1 and 2, where we have most of docs on a dedicated docs.snowplowanalytics.com and in repo just a summary of all components and links to extensive docs (my personal preference)
4. Make this repo a repo for one of core components (Scala Common Enrich most probably)

Regardless of above decision we need to:

1. Overhaul the main `README` and point to our commercial offer and Snowplow Mini for those who just wants to try out the technology.
2. Write a script that will move all (~600) existing issues into their appropriate projects with cross-reference to original ticket

**Comment by paulboocock** [comment]
Should it not become part of the release process of a tracker that we update the link here so they stay in sync with the latest releases?

**Comment by chuwy** [comment]
@paulboocock that's a good idea! I think it probably used to be the case, but we abandoned it.

**Comment by schafdog** [comment]
Please update the submodules on https://github.com/snowplow/snowplow/tree/master/1-trackers 
(which I think Paul is say as well). It's very confusing clicking on a link that takes your very old code.

**Comment by chuwy** [comment]
Happens in https://github.com/snowplow/snowplow/pull/4352
