### ISSUE TITLE
Scala Common Enrich: bump iglu-scala-client to 1.0.0

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4265]
1.0.0 will bring:

* Update to cats 2.1 and cats-effect 2.0
* Update to circe 0.13.0 (or 0.12)
* MiMa compatibility

**Comment by benjben** [comment]
Handled by https://github.com/snowplow-incubator/snowplow-badrows/issues/31 and #4292

**Comment by benjben** [comment]
Reopening as `snowplow-badrows_0.2.0` does not come with `iglu-scala-client_1.0.0`

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/52
