### ISSUE TITLE
Stream Enrich: investigate the WARNING Unknown keyword exclusiveMinimum

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4268]
There is always this warning in Stream Enrich's logs:
```
     [main] WARN com.networknt.schema.JsonMetaSchema - Unknown keyword exclusiveMinimum - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
```

**Comment by chuwy** [comment]
The problem is in Iglu Client. Likely will be fixed by https://github.com/snowplow/snowplow/issues/4265

**Comment by benjben** [comment]
Awesome!

**Comment by benjben** [comment]
Pushing back as #4265 is being pushed back as well

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/53
