### ISSUE TITLE
Stream Enrich: allow to download data from private S3 or GCS

### ISSUE THREAD

**Issue by chuwy** [snowplow/snowplow#4269]
Snowplow Mini can download data only via HTTPS and we need to stop hosting MaxMind publicly.

/cc @oguzhanunlu @benjben

**Comment by chuwy** [comment]
Scheduling this for R119 as we want to ship R119 with Snowplow Mini, but likely will have to be pushed back.

**Comment by jbeemster** [comment]
This should likely be broader to cover _any_ external DB we download like IAB, Referrer Parser, UA Parser etc
