### ISSUE TITLE
Beam Enrich: add support for GCP labels in dataflow launcher docker image

### ISSUE THREAD

**Issue by jrluis** [snowplow/snowplow#4281]
When deploying more than 1 pipeline on the same GCP project there is no way to know where the costs are coming from.

GCP supports labeling the resources and to export the billing information into BigQuery. The cost can then be breakdown by using SQL queries that filter by label.

For reference, the google documentation on labels: https://cloud.google.com/compute/docs/labeling-resources

The plan is to label all the resources with "sp_env=prod1" or "sp_env=qa1"

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/beam-enrich/issues/6
