### ISSUE TITLE
EmrEtlRunner: set ig.count

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4285]
In R117, EER has been updated with the possibility to use spot instances.

The [documentation](https://github.com/rslifka/elasticity#on-demand-instance-groups) shows
```
ig = Elasticity::InstanceGroup.new
ig.count = 10 # Provision 10 instances
ig.type = 'c1.medium' # See the EMR docs for a list of supported types
ig.set_on_demand_instances # This is the default setting

jobflow.set_core_instance_group(ig)
```
But the code is missing `ig.count` and thus a default value of 1 is always used for the number of instances.

If `jobflow.set_core_instance_group` is set, `@jobflow.instance_count` is not used.

**Comment by zehua** [comment]
I think the same change also overwrites the `core_instance_ebs` info that was set in

https://github.com/snowplow/snowplow/blob/922aaa73852bf807f334394c80298b324972b383/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb#L236

This should be addressed in the same fix.
