### ISSUE TITLE
Scala Common Enrich: change maxColumns to 140 in .scalafmt.conf 

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4314]
The codebase is barely readable when everything is squashed vertically

**Comment by ahoora08** [comment]
Hi benjben,
It's a real  "good first commit" one!
Can I work on this?

**Comment by ahoora08** [comment]
@benjben I've sent pull request for this. Feel free to comment or ask for any changes.

**Comment by benjben** [comment]
Closed by 696fcd35d62d4d82f84c24b8ab087a5588b63fea
