### ISSUE TITLE
Scala Common Enrich: Loader.toCollectorPayload should emit only one bad row and not a list

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow#4315]
```scala
Loader[T] {
  def toCollectorPayload(
    line: T,
    processor: Processor
  ): ValidatedNel[BadRow.CPFormatViolation, Option[CollectorPayload]]
```

The function signature indicates that several `CPFormatViolation` bad rows can be emitted for one `CollectorPayload`, whereas it should be maximum one.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/56
