### ISSUE TITLE
Stream Enrich: bump AWS SDK to 2.13.42

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow#4367]
**Project**: Stream Enrich

**Version**: 1.1.0

**Expected behavior**: Credentials provider is not compatible with KCL v2.

**Actual behavior**: Use the latest library.

**Steps to reproduce**:

I am on my way to upgrade KCL to v2: https://github.com/globeandmail/snowplow/pull/10

However, between source and sink there is a `provider` mutual variable. The KCL v2 uses a new class from SDK v2 and the Sink is still on v1. Here is the migration guide that [shows differences](https://docs.aws.amazon.com/sdk-for-java/v2/migration-guide/client-credential.html
) I need to upgrade the sink to make the authentication consistent in the enricher.

**Comment by chuwy** [comment]
Hi @szareiangm! We're in process of migrating the enrich assets (and all others) into their dedicated repos, e.g. https://github.com/snowplow/enrich in order to make releases faster. Feel free to migrate the ticket there.

This repo will remain for high level discussions and historical purposes.

**Comment by szareiangm** [comment]
Hello @chuwy , for sure. I moved to https://github.com/snowplow/enrich/issues/259.
