### ISSUE TITLE
JS Tracker: Inaccurate documentation

### ISSUE THREAD

**Issue by rjerue** [snowplow/snowplow#4370]
**Project**: Javascript tracker

**Version**: Latest

**Expected behavior**:

Docs and schema are in sync.

**Actual behavior**:

Docs show targetUrl in trackAdImpression as optional, schema shows as required.

**Steps to reproduce**:

While looking at the docs for the snowplow JS tracker, we noticed that under trackAdImpression ( https://github.com/snowplow/snowplow/wiki/2-Specific-event-tracking-with-the-Javascript-tracker#361-trackadimpression ) that targetUrl is marked as not required. However in the schema validation used by Snowplow, it is marked as required ( https://github.com/snowplow/iglu-central/blob/b85fe4e002056a6c2b27a41f4ac7135dea87d9d3/schemas/com.snowplowanalytics.snowplow/ad_impression/jsonschema/1-0-0#L30 ) through a minimum length

**Comment by paulboocock** [comment]
Hi @rjerue 
Thanks for the report.

It's `minProperties: 1` that makes it fail if you don't pass in any parameters to a `trackAdImpression` call. It's fine to have an optional field with `minLength: 1`, this means `targetUrl` is not required.
Technically, none of the fields are required but you need to specify at least one of them. I agree the docs could make this clearer so I'll update them.
