### ISSUE TITLE
Step to configure StorageLoader is not on the wiki

### ISSUE THREAD

**Issue by riquedev** [snowplow/snowplow#4374]
Good afternoon!
I'm trying to upload the whole environment to my cloud but on the part:

[https://github.com/snowplow/snowplow/wiki/Setting-up-PostgreSQL](https://github.com/snowplow/snowplow/wiki/Setting-up-PostgreSQL)

Cannot access step "setup the StorageLoader"

**Comment by chuwy** [comment]
Hi @riquedev,

That page should be actually deprecated and removed (and we're moving to [our new docs website](docs.snowplowanalytics.com/)) - we're not supporting this method anymore. We're about to release new Postgres Loader in coming weeks.

Also, if you have any support questions - you're welcome on our [discorse forums](discourse.snowplowanalytics.com/) we're trying to keep GitHub for bugreports and feature requests only.
