### ISSUE TITLE
Configuration Of Scala-stream-collector

### ISSUE THREAD

**Issue by lalspicesresearch** [snowplow/snowplow#4375]
Hello, I am new in this field and I am not able to run run scal-stream-collector with below command
java -jar stdout/target/scala-2.12/snowplow-stream-collector-stdout-1.0.1.jar --config my.conf
It gives error my.conf not found. I could not found where should i put the configuration file in the scala-stream-collector according to documentation. Can you help me where to put the configuration file and what it should contain?
![Screenshot from 2020-08-31 12-24-06](https://user-images.githubusercontent.com/59685884/91690006-ee090380-eb84-11ea-9d05-e14d28041367.png)

**Comment by paulboocock** [comment]
Hi @lalspicesresearch 
Thanks for your question. Please could you post this and other setup questions to our [Discourse](https://discourse.snowplowanalytics.com/), the community there is more likely to be able to help you with set-up issues.

You might find our docs helpful too. For instance, with this question, following our Scala Stream Collector setup guides [here](https://docs.snowplowanalytics.com/docs/setup-snowplow-on-aws/setup-the-snowplow-collector/overview-of-the-scala-stream-collector/) might help.
