### ISSUE TITLE
Run Snowplow in Local Server(Ubuntu)

### ISSUE THREAD

**Issue by lalspicesresearch** [snowplow/snowplow#4376]
Is it possible to run snowplow in our local server (ubuntu) without hosting anything in third-party server? According to documentation, we need to host sp.js for Javascript Trcaker Setup. But i want to test in my local computer without hosting anything online sever.

**Comment by paulboocock** [comment]
You could try out [snowplow-mini](https://github.com/snowplow/snowplow-mini) which offers a Snowplow pipeline that loads into ElasticSearch, you can spin that up locally using Vagrant and VirtualBox. 

Snowplow is a cloud first platform though, so typically leverages a number of pieces from the cloud providers platforms. If you want to discuss this further, and with our community, then our [discourse](https://discourse.snowplowanalytics.com/) is probably a better place for questions than GitHub issues :-)
