### ISSUE TITLE
Port Analytics SDK pages to docs.snowplowanalytics.com

### ISSUE THREAD

**Issue by gvacaliuc** [snowplow/snowplow#4419]
**Project**: [Scala Analytics SDK](https://github.com/snowplow/snowplow-scala-analytics-sdk)

[Wiki](https://github.com/snowplow/snowplow/wiki/Scala-Analytics-SDK-setup#3-setup) lists 1.0.0 as the latest version, but [there is a newer version](https://mvnrepository.com/artifact/com.snowplowanalytics/snowplow-scala-analytics-sdk).

**Comment by chuwy** [comment]
Thanks, Gabriel. I updated the page, but all docs should be migrated to docs.snowplowanalytics.com/ soon.

**Comment by benjben** [comment]
Hi @gvacaliuc ,

We've now migrated documentation related to the Analytics SDK to our [documentation website](https://docs.snowplowanalytics.com/docs/analytics-sdk-scala/).
