### ISSUE TITLE
Trackers section in docs.snowplowanalytics.com is missing snowplow-tracking-cli

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#4421]
From here:

https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/

is missing:

https://github.com/snowplow/snowplow-tracking-cli

**Comment by paulboocock** [comment]
Done https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/snowplow-tracking-cli/

**Comment by alexanderdean** [comment]
That was fast!
