### ISSUE TITLE
Automate submodules update

### ISSUE THREAD

**Issue by adatzer** [snowplow/snowplow#4435]
Using Github Actions

**Comment by benjben** [comment]
I think that Github Actions need to be setup for each individual repo that appears as a sub-module on `snowplow/snowplow`.

It should be possible to create one generic action that we reuse for each repo.

**Comment by adatzer** [comment]
Indeed that would be a possible approach, for each child repository to create `repository_dispatch` events upon releases, which would then be received by `snowplow/snowplow` and trigger the workflow to update it.
The other option we've been thinking is for `snowplow/snowplow` to run a workflow on a cron schedule to check `foreach` submodule and commit the bumps that may find. This approach means that the sub-repositories continue to have no concern of updating the parent, and their release process (automated or not) remains independent. 
What do you think?

**Comment by benjben** [comment]
I like your approach better, as it will be way simpler to setup and anyway we don't need to update `snowplow/snowplow` in the second after a child repo has been updated.
