### ISSUE TITLE
SnowPlow logs not working

### ISSUE THREAD

**Issue by DmitrievaAlisa** [snowplow/snowplow#4443]
Hello. Our team use SnowPlow analytics for Android application.
In last release (1.7.1) logs are not working, we can not see them in LogCat in Android Studio. We used SnowPlow version 1.3.3 before and on that version logs were visible. 
What's the reason of this behavior? Maybe there are any special new flags for logging now?

**Comment by chuwy** [comment]
Hello @DmitrievaAlisa!

I recommend you to use our [forums](discourse.snowplowanalytics.com/) for troublshooting. Our discourse is community-driven and you'll hit a much broader audience there, while we keep our GitHub tracker for  bugreports and feature requests only.
