### ISSUE TITLE
Snowplow mobile data model

### ISSUE THREAD

**Issue by carabaestlein** [snowplow/snowplow#4458]
A standard mobile data model for all three warehouses (Redshift, Snowflake and BigQuery) that models the Snowplow data into screen views, sessions and users tables.

https://github.com/snowplow/data-models/tree/master/mobile/v1

**Comment by paulboocock** [comment]
This is now complete! 🎉 

We've started a new blog series on Mobile tracking, of which Part 1 is now available here: https://snowplowanalytics.com/blog/2021/05/07/the-state-of-mobile-analytics-in-2021/

The release posts for each model are here:
Redshift: https://discourse.snowplowanalytics.com/t/redshift-mobile-model-1-0-0-released/4943
BigQuery: https://discourse.snowplowanalytics.com/t/bigquery-mobile-model-1-0-0-released/5068
Snowflake: https://discourse.snowplowanalytics.com/t/snowflake-mobile-model-1-0-0-released/5132
