### ISSUE TITLE
A new and improved Snowplow dbt package

### ISSUE THREAD

**Issue by carabaestlein** [snowplow/snowplow#4466]
Snowplow's [out of the box web and mobile data models](https://github.com/snowplow/data-models) are available for [dbt](https://www.getdbt.com/), replacing the existing [Snowplow dbt package](https://hub.getdbt.com/fishtown-analytics/snowplow/latest/). This will bring the benefits of our new generation of data models to dbt, including a more modular structure as well as performance improvements and better testing.

**Comment by paulboocock** [comment]
This is now complete for the web model
