### ISSUE TITLE
Improvements to Snowplow Mini

### ISSUE THREAD

**Issue by mikejongbloet** [snowplow/snowplow#4470]
We plan on making some improvements to Snowplow Mini to make it a more robust QA tool.

These changes may include:
- Replacing Elasticsearch with Postgres
- Supporting full set of configs in each component

**Comment by stanch** [comment]
As it stands, we are more likely to replace Mini with a combination of Micro and lightweight QA pipelines.
There is no immediate plan to deprecate Mini, and we would make sure that any replacement supports existing use cases.
Will create a different roadmap item once the plan is fleshed out.
