### ISSUE TITLE
Integrate with data catalogs

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#4471]
Explore publishing metadata (e.g. schema definitions) to data catalogs e.g. Amundsen, DataHub.

**Comment by lepkamartin** [comment]
@yalisassoon  Super important topic nowadays. Data Engineering teams are opening topics about Data Quality and Governance almost every day and having native integration with data catalogues will be quite important... Quite like this overview of all data catalogues - https://www.notion.so/Catalog-of-Catalogs-4bcbee621de243b6a34deaebd28180d0

**Comment by paulboocock** [comment]
This has been superseeded by our new issue: https://github.com/snowplow/snowplow/issues/4542
