### ISSUE TITLE
Improved usability of the Collector

### ISSUE THREAD

**Issue by ebedford420** [snowplow/snowplow#4498]
Value: 
- Configuration setup is easier & better documented for open source users - example config file is no longer the source of truth for configuring the collector 
- Refactor of collector code to make it easier to maintain & for open source users to contribute features

**Comment by paulboocock** [comment]
v2.4 brought new configuration file examples and some other new features: https://discourse.snowplowanalytics.com/t/stream-collector-2-4-1-released/5795

v2.5 introduced graceful shutdowns: https://discourse.snowplowanalytics.com/t/snowplow-collector-2-5-0-released/6330
