### ISSUE TITLE
Video tracking in the JavaScript tracker

### ISSUE THREAD

**Issue by carabaestlein** [snowplow/snowplow#4513]
Video engagement can be tracked across all major media players.

**Comment by paulboocock** [comment]
There's been a bit of open discussion on this in the JS Tracker repo that I thought would be worth linking to: https://github.com/snowplow/snowplow-javascript-tracker/issues/805

**Comment by paulboocock** [comment]
See: https://discourse.snowplowanalytics.com/t/snowplow-javascript-tracker-3-2-released/6223

And: https://snowplowanalytics.com/blog/2022/01/31/how-snowplow-web-video-tracking-is-implemented/
