### ISSUE TITLE
Identify the GET OR POST on Snowplow collected data

### ISSUE THREAD

**Issue by arjun-s** [snowplow/snowplow#4555]
Hi Team, 
Is there an option to identify the usage data of GET or POST collected using Snowplow collector

**Comment by paulboocock** [comment]
Not out of the box. You could attach an entity to your event (using global contexts in some trackers) which would give you that information (create your own object based on your tracker configuration)

**Comment by arjun-s** [comment]
Thanks for the response. Would you be able to share any document to implement this . Appreciate your help!

**Comment by arjun-s** [comment]
Hi paulboocock,
Would you be able to share relevant document for me to implement .

**Comment by miike** [comment]
Hi Arun,

For this you would take the configuration for your tracker initialisation (specifically `eventMethod`) and then use the [global contexts](https://docs.snowplow.io/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracking-events/#global-context) functionality to attach this.
