### ISSUE TITLE
Is snowplow supports custom events in their js(Add to cart or Purchase) and send to their specific kafka topics or Hadoop

### ISSUE THREAD

**Issue by prk2331** [snowplow/snowplow#4557]
Hi team can you please let me know Is snowplow supports custom events in their JS (Add to cart or Purchase) and send to their specific kafka topics or Hadoop?
and pricing for OnPrem and Cloud

**Comment by ujjawal-4664** [comment]
Yes, Snowplow supports custom events in their JavaScript tracker. You can use the tracker API to create custom events, such as "Add to cart" or "Purchase", and send them to specific Kafka topics or Hadoop. You can also configure the tracker to send events to different streams or topics based on the event type, which can help you organize your data and make it easier to process downstream.

**Comment by ujjawal-4664** [comment]
For OnPrem, Snowplow offers a Community edition that is free to use and includes basic features, as well as a Professional edition that includes additional features and support options. Pricing for the Professional edition depends on the number of events you want to track and starts at $2,000 per year.

**Comment by stanch** [comment]
> For OnPrem, Snowplow offers a Community edition that is free to use and includes basic features, as well as a Professional edition that includes additional features and support options. Pricing for the Professional edition depends on the number of events you want to track and starts at $2,000 per year.

This is not quite correct, we don’t have Community/Professional editions, or at least we don’t use these terms. I am also not sure what the source for the $2000 price quote is.

You can check our offerings (free and paid) here: https://snowplow.io/pricing/
