### ISSUE TITLE
Scala Common Enrich: add weather enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#456]
Resources:

* http://www.simoahava.com/web-development/universal-analytics-weather-custom-dimension/
* http://mattaster.com/weather-universal-analytics/
* http://www.wunderground.com/weather/api/d/pricing.html
* http://www.ncdc.noaa.gov/oa/climate/isd/
* http://openweathermap.org/API

**Comment by fblundun** [comment]
A first step here would be to reboot https://github.com/snowplow/scala-weather to be a Scala client of Open Weather Map with an LRU cache (obviously not necessary if there's an excellent Java client already, but we will need some LRU caching).

**Comment by christoph-buente** [comment]
Or maybe a background worker could fetch the bulk data hourly and all lookups would be local then. http://openweathermap.org/current#bulk

**Comment by christoph-buente** [comment]
Oh, i just saw bulk downloading comes with a price of at least $470/month
