### ISSUE TITLE
Scala Stream Collector: Setting the encoding?

### ISSUE THREAD

**Issue by bamos** [snowplow/snowplow#470]
Hi @alexanderdean, in the Scala collector, I currently have the encoding hard-coded to UTF-8, but I assume this isn't correct in general. Will trackers always set a `cs` attribute in the query param we can access for this?

https://github.com/snowplow/snowplow/blob/feature/scala-rt-coll/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/ResponseHandler.scala#L59

**Comment by alexanderdean** [comment]
This hasn't cropped up again, closing
