### ISSUE TITLE
Change PostgresSQL COPY to \copy

### ISSUE THREAD

**Issue by luxerama** [snowplow/snowplow#487]
Is there a reason why the Postgres storage loader uses `COPY` rather than something like `\copy`?
The problem with `COPY` is that it requires a superuser to be run which is less than ideal.

https://github.com/thebeansgroup/snowplow/compare/copy-command-change

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/snowplow-rdb-loader/issues/10
