### ISSUE TITLE
Clean up enrich.common.CanonicalInput based on Thrift SnowplowRawEvent

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#493]
The schema for raw events has evolved a little with the new Thrift SnowplowRawEvent.

Let's tidy up CanonicalInput (including a rename) to reflect learnings fomr Thrift SnowplowRawEvent.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/198
