### ISSUE TITLE
Populate Collector logging formats page

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#494]
Can we update the existing page:

https://github.com/snowplow/snowplow/wiki/Collector-logging-formats

**Comment by alexanderdean** [comment]
Hi @ihortom - could you prioritize this page this week? It is getting quite a lot of interest, and I think writing it will be a good introduction to how the collectors work...

**Comment by ihortom** [comment]
@alexanderdean the first link seems invalid. Could you verify, please?

**Comment by ihortom** [comment]
@alexanderdean, is the valid link will be https://github.com/snowplow/snowplow/blob/64a789273047d33c186cf00e2a0d8aabe52339f3/2-collectors/thrift-schemas/snowplow-raw-event/src/main/thrift/snowplow-raw-event.thrift now?

**Comment by alexanderdean** [comment]
I have tidied up the ticket description - it was out of date. Here are some notes for the updated page:

```
    CloudFront access log format
        Documentation: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html
        Supports single events sent via GET only
        No support for network_userid
        Example: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/test/scala/com.snowplowanalytics.snowplow.enrich.hadoop/good/TransactionCfLineSpec.scala#L39
    Tomcat access logs
        A custom textual format based on Apache logfile format
        Supports GET but also multiple events sent via POST
        Supports network_userid
        Example: https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/test/scala/com.snowplowanalytics.snowplow.enrich.hadoop/good/CljTomcatTp2MultiEventsSpec.scala#L39
    Snowplow Thrift Raw Event:
        Thrift IDL is here: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/CollectorPayload/thrift/1-0-0#L10
        Build for Java/Scala is here: https://github.com/snowplow/snowplow/tree/master/2-collectors/thrift-schemas
        Note that these events are packaged in a Twitter Protobuf: https://github.com/snowplow/iglu-central/blob/master/schemas/com.twitter/SerializedBlock/protobuf/1-0-0 (a format output by https://github.com/snowplow/kinesis-s3)

These are just the message envelopes - the event data itself will be encapsulated within the GET querystring or the POST response object. If it's inside the POST response object, then the events will be contained within this JSON:

https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/payload_data/jsonschema/1-0-3

With either GET or POST, the lowest level will be a set of name-value pairs that respect the Snowplow Tracker Protocol: https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol
```

**Comment by ihortom** [comment]
@alexanderdean - Done. Please, review the Thrift events format if the info is sufficient. If so the ticket could be closed. Also that section could cover yet another ticket #2231.

**Comment by alexanderdean** [comment]
Looks good! Have pushed. A few things:

* "Kineses-S3 sink." is misspelt
* " Kinesis-S3 reads records from an Amazon Kinesis stream, compresses them using splittable LZO, and writes them to S3 " misses the Protocol Buffer array layer of the encoding that we discussed. Can you talk to @fblundun to get the details of this and add it in?
* Would be great to have a diagram of the various layers of the onion (Thrift, PB, LZO, gzip)

**Comment by ihortom** [comment]
@alexanderdean - Updated as per recommendation.

**Comment by alexanderdean** [comment]
Nice work! Closing
