### ISSUE TITLE
Option to load maxmind GeoIP from remote url with refresh interval rather than locally

### ISSUE THREAD

**Issue by bamos** [snowplow/snowplow#510]
Hi @alexanderdean  - currently, `scala-kinesis-enrich` requires the user to manually download the GeoIP database to pass in as a file to `scala-common-enrich`. The [config](https://github.com/snowplow/snowplow/blob/feature/kinesis-enrich/3-enrich/scala-kinesis-enrich/src/main/resources/default.conf) is currently:

```
    geo_ip: {
      enabled: true # false not yet suported
      maxmind_file: "/tmp/GeoLiteCity.dat"
    }
```

Because the file can become outdated, the user should manually refresh the database and restart the application shortly. However, Maxmind [publishes](http://dev.maxmind.com/geoip/legacy/geolite/) the GeoIP databases at static locations. To utilize this, what if `scala-kinesis-enrich` is changed t o automate this by support the following config?

```
    geo_ip: {
      enabled: true # false not yet suported
      # 'remote' reads `maxmind_file` as a URL and refreshes every `interval`.
      # 'local' reads `maxmind_file` as an absolute path locally and does not refresh.
      location: remote

      maxmind_file: "http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
      refresh: 1 day
    }
```

**Comment by alexanderdean** [comment]
Closing as this is a deployment problem not a stream processing problem
