### ISSUE TITLE
IAM permissions more permissive than they need to be?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#530]
Referencing https://github.com/snowplow/snowplow/wiki/Setup-IAM-permissions-for-users-installing-Snowplow

it says:

> Warning: these permissions are still more permissive than they need to be. We will be
> putting in time to narrow them down further over the coming weeks.

Let's tighten these up if they are more permissive than required.

**Comment by manjitkumar** [comment]
Can someone look into it and close the issue? It been here for like more than 3 years now. @alexanderdean @yalisassoon :(

**Comment by alexanderdean** [comment]
Assigning @BenFradet, @ihortom and @jbeemster to liaise and come up with an improvement here.

**Comment by BenFradet** [comment]
As we've discussed with @jbeemster and @ihortom this is a huge job in itself.

One needs to start from scratch (no permissions at all) and build one's way up from there which is very much time-consuming.

De-scheduling.

**Comment by dserodio** [comment]
The required permissions are **insane**. Hard-coding an Access Key with `iam:*` permission allows any user with login access to the instance running Snowplow to completely destroy an AWS account.

**Comment by BenFradet** [comment]
I'd be in favor of removing it, wdyt @jbeemster ? Ultimately, we're just providing bad information.

**Comment by jbeemster** [comment]
There is a bit of confusion here @dserodio - those are not the permissions for _running_ Snowplow so much as the permissions required to setup all of the infrastructure and associated sub-users you would in practice need.

However I think that whole section needs a lot of rework and we likely need to provide the minimal policy set needed for running Snowplow somewhere...

**Comment by paulboocock** [comment]
Closing as there is now a complimentary `IAM permissions for operating Snowplow`: https://docs.snowplowanalytics.com/docs/getting-started-on-snowplow-open-source/setup-snowplow-on-aws/setting-up-your-aws-environment/iam-permissions-for-operating-snowplow/
