### ISSUE TITLE
IAM permissions for users installing Snowplow misses EC2 permissions

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#531]
Spotted by one of our clients - the user installing Snowplow needs EC2 permissions so that they can create a box to run EmrEtlRunner and StorageLoader on.

**Comment by alexanderdean** [comment]
Is this done?

**Comment by ihortom** [comment]
@alexanderdean - I believe so: https://github.com/snowplow/snowplow/wiki/Setup-IAM-permissions-for-users-installing-Snowplow

**Comment by alexanderdean** [comment]
Awesome, closing...
