### ISSUE TITLE
Scala Common Enrich: add support for GET querystring containing N raw events as JSON

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#543]
As well as the current approach, we would also support:

a GET with &p={JSON} and then {JSON} is validated as per the POST Tracker Protocol JSON Schema.

Note: we need to do this to Scala Hadoop Enrich eventually too, but it should be easier with Scala Kinesis Enrich, because 1 Kinesis record in -> N Kinesis records out is super-easy to implement (whereas it's an additional processing phase in Hadoop).

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/200
