### ISSUE TITLE
Scala Stream Collector: add click redirect mode

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#549]
This would be useful for tracking:

1. Clicks from your site to external websites
2. Ad clicks
3. Social media redirects (Bit.ly-style)

The idea is: you create a link which is routed via the Scala Stream Collector. The Scala Stream Collector manages the redirect to the final destination, but crucially also fires a 'redirect' event type to Kinesis.

**Comment by fblundun** [comment]
What's the desired redirection behaviour for a malformed URL with path "/r" and no "u" parameter on the querystring?

**Comment by alexanderdean** [comment]
400 for Bad Request - https://github.com/snowplow/snowplow/blob/feature/uri-redirects/2-collectors/clojure-collector/java-servlet/src/snowplow/clojure_collector/responses.clj#L83

**Comment by fblundun** [comment]
Thanks!

**Comment by fblundun** [comment]
Should we make this configurable so that it can be switched off? This would slightly improve performance for people not using click redirects, since the collector wouldn't need to do any querystring parsing

**Comment by alexanderdean** [comment]
If that's easily doable, yes please...

**Comment by fblundun** [comment]
Shouldn't be too hard!

**Comment by fblundun** [comment]
Actually the configuration option is unnecessary - querystring parsing only needs to happen for requests to the /r path.
