### ISSUE TITLE
Explore partitioning strategies & tech for enriched events on disk

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#566]
Possible technologies:
- Cascading PartitionTap
- Pail

From @pkallos:

> It seems like the partition and directory scheme in S3 should be agnostic of the enrichment job scheduling, and should match the data instead so that it can create even partitions for the time-series data. This is especially important when considering that you may want to reprocess raw data or batch import old data.

In any event having it be in some way configurable would be great, so we could have date=YYYY-MM-DD or even year=YYYY/month=MM/day=DD/hour=HH. If the issue is avoiding filename collisions there are ways around that!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/201
