### ISSUE TITLE
Change ThriftLoader to accept SnowplowRawEvent

### ISSUE THREAD

**Issue by pkallos** [snowplow/snowplow#568]
I think the signature for `ThriftLoader` in `scala-common-enrich` should be changed from
```scala
object ThriftLoader extends CollectorLoader[Array[Byte]] {
```
to
```scala
object ThriftLoader extends CollectorLoader[SnowplowRawEvent] {
```
Because the thrift deserialization is already done in `scala-hadoop-enrich`
see #538

**Comment by fblundun** [comment]
Closing this since we decided to pass the binary Thrift records to the loader directly as byte arrays.
