### ISSUE TITLE
Leverage LZO compression for storing TSVs

### ISSUE THREAD

**Issue by pkallos** [snowplow/snowplow#574]
Redshift COPY [appears to support the LZOP option](http://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html), and scalding 0.9.0 has built in [support for writing LZO compressed TSVs](https://github.com/twitter/scalding/blob/0.9.0rc15/scalding-commons/src/main/scala/com/twitter/scalding/commons/source/LzoTraits.scala#L75) so it would be possible to change the `scala-hadoop-etl` process to save compressed files.

Could save over 50% storage space in S3!

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/203
