### ISSUE TITLE
Add lzo decompression to StorageLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#578]
Required alongside #574 for Postgres support (PG can't install LZO'ed files).

**Comment by esurdam** [comment]
Hey @alexanderdean any update on this? Have everything setup and working but Postgres doesn't like to import the LZO'd files. Any alternate solutions on getting Kinesis streamed events loaded into Postgres?

**Comment by alexanderdean** [comment]
Hey @esurdam, the recommended way to load Redshift or Postgres from the Kinesis pipeline is a lambda architecture: http://snowplowanalytics.com/blog/2015/06/16/snowplow-r66-oriental-skylark-released/#lambda

**Comment by chuwy** [comment]
StorageLoader has been deprecated.
