### ISSUE TITLE
Add doc on 2.1 Granting access to an EC2 instance

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#613]
https://github.com/snowplow/snowplow/wiki/Setting-up-Redshift#21-granting-access-to-an-ec2-instance

**Comment by paulboocock** [comment]
Docs updated since this ticket and moved to https://docs.snowplowanalytics.com/docs/getting-started-on-snowplow-open-source/setup-snowplow-on-aws/setup-destinations/setup-redshift/launch-a-redshift-cluster/
