### ISSUE TITLE
Rebuild SnowplowRawEvent against JDK 6

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#615]
It's currently built against JDK 7. This causes issues in the batch pipeline, which is still built against JDK 6. Note: it looks like Scalding might be moving to JDK 7. So maybe we can enforce building against JDK 7 for everything instead.

http://stackoverflow.com/a/19618654/255627

**Comment by BenFradet** [comment]
everything moved to 1.8, closing.
