### ISSUE TITLE
One or two files left in processing bucket 

### ISSUE THREAD

**Issue by smugryan** [snowplow/snowplow#617]
We run our snowplow-runner-and-loader.sh script hourly and about once or twice a week we have one or two files left over in the processing bucket.

Our logs don't show any errors output by the script, is there a way to figure out why files are left behind? Files leftover in the processing bucket prevent the script from running and we aren't sure if they were processed or not.

**Comment by alexanderdean** [comment]
I have yet to see this one occur, with many 1000s of jobs run, so I'm closing...
