### ISSUE TITLE
EmrEtlRunner: update unmaintained Ruby 1.9.3 to Ruby 2.1.x

### ISSUE THREAD

**Issue by smugryan** [snowplow/snowplow#633]
Was installing RVM + Ruby 1.9.3 today for Snowplow and got this error message:

    WARNING: Please be aware that you just installed a ruby that is no longer maintained (2014-02-23), for a list of maintained rubies visit:

    http://bugs.ruby-lang.org/projects/ruby/wiki/ReleaseEngineering

    Please consider upgrading to ruby-2.1.1 which will have all of the latest security patches.

Should snowplow's dependencies be updated to something more modern? It causes problems because we have to compile 1.9.3 and the warning will probably scare new users.

**Comment by alexanderdean** [comment]
I think we can close this as a won't fix given the move to JRuby.
