### ISSUE TITLE
EmrEtlRunner: add ability to run Spark jobs

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#641]

**Comment by alexanderdean** [comment]
Moving this into @BenFradet's milestone...

**Comment by BenFradet** [comment]
I'm wondering if it'd make sense to have a `SparkStep` directly in Elasticity

**Comment by alexanderdean** [comment]
That sounds good to me @BenFradet !

**Comment by alexanderdean** [comment]
You could migrate over the ScaldingStep too...
