### ISSUE TITLE
Add recursive shredding

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#647]
Example: replace `atomic.com_snowplowanalytics_link_click.element_classes` with a ptr off to a new table, called strings or com_snowplowanalytics_strings.

**Comment by dashirov-ga** [comment]
What was the rationale for this?
Found a reference to this issue in atomic.com_snowplowanalytics_snowplow_submit_form_1 DDL as a TODO item.

**Comment by alexanderdean** [comment]
The idea here is that if you have a `objectA[array[objectB]]`, the best handling of this in Redshift would be to shred this recursively into a dedicated table representing `objectB`. At the moment, Snowplow's shredding code (and all related Iglu functionality) just downgrades the `array[objectB]` into a varchar containing that JSON.

**Comment by dashirov-ga** [comment]
This is for arrays only if n elements, correct?

**Comment by alexanderdean** [comment]
Superceded.
