### ISSUE TITLE
Scala Stream Collector: support any {api-vendor}/{api-version} for GET and POST

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#652]
So that different vendors (Snowplow, Sendgrid etc) can send events in their own payload format to the same collector, just by adjusting the URI to the collector.

In other words, currently we have:

```
collector-endpoint.com/i
```

We should move to:

```
collector-endpoint/com.snowplowanalytics/i
```

/cc @yalisassoon

**Comment by alexanderdean** [comment]
Hey @fblundun - I think this has been done, please close if so!

**Comment by fblundun** [comment]
I think this is currently in the branch for adding post support. The code is here: https://github.com/snowplow/snowplow/blob/feature/ssc-post-support/2-collectors/scala-stream-collector/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorService.scala

Is that what you had in mind @alexanderdean ?

**Comment by alexanderdean** [comment]
Aha - we need to update this to be more permissive - see the Clojure Collector:

https://github.com/snowplow/snowplow/blob/master/2-collectors/clojure-collector/java-servlet/src/snowplow/clojure_collector/core.clj#L44

Note how a tracker or webhook can post or get to any {api-vendor}/{api-version} ?

**Comment by fblundun** [comment]
Understood! I'll replicate this behaviour with Spray.

**Comment by alexanderdean** [comment]
Thanks Fred!
