### ISSUE TITLE
StorageLoader: add support for loading JSONs into Postgres

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#657]

**Comment by chuwy** [comment]
Duplicate of https://github.com/snowplow/snowplow/issues/3204

**Comment by ganeshsp** [comment]
Hello Guys,

Can you please help me to load shredded-tyes into postgresql?
all events are getting enriched and shredded properly.
atomic.events are getting loaded properly . but other tables like link_click_1 are not loading.
Please help me out to resolve this

**Comment by chuwy** [comment]
Hey @ganeshsp! Please direct support questions to [our forums](https://discourse.snowplowanalytics.com/).
