### ISSUE TITLE
Redshift load domain_sessionidx overflow

### ISSUE THREAD

**Issue by pkallos** [snowplow/snowplow#664]
I'm in the process of migrating to the latest version of snowplow, including the redshift v0.3.0 definitions and the version new version scala-hadoop-enrich+scala-common-enrich that's sitting in master.

I re-enriched all my raw events with success, then I dropped my atomic.events and rebuilt it with the new schema. Now I am batch-loading my events and I am seeing a few errors for field "domain_sessionidx" -> reason "Overflow (Short valid range -32768 to 32767)". Sample values are pretty consistent, getting `1397231177`, `1397231322`, `1397231494`.

What's suspicious is that those numbers are sensible unix timestamps, is it possible there is some sort of bug with field order? I have looked through my old `stl_load_errors` entries from previous loads of the same data (enriched and loaded with v0.2.0) and I don't see these overflow errors.

Happy to provide more info as requested, the error rate doesn't seem to be that high so for now I will just up my MAXERRORS.

**Comment by alexanderdean** [comment]
Fixed the problem (if not the underlying cause, which I don't think we uncovered) in:

https://github.com/snowplow/snowplow/issues/1788
