### ISSUE TITLE
Add Snowplow event tracking to StorageLoader

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#679]
Using https://github.com/snowplow/snowplow-ruby-tracker

**Comment by alexanderdean** [comment]
Let's start with some super basic tracking - just load failures and load successes.

**Comment by fblundun** [comment]
The load_failure can have an `error` field. I don't know if there are any fields we want in the load_success event. We can add add an application_context to both events as well...

**Comment by alexanderdean** [comment]
Sounds good!

**Comment by fblundun** [comment]
At the moment the `error` field contains the text of the exception. But this contains the AWS credentials, as in this anonymized example:

```
Java::OrgPostgresqlUtil::PSQLException error executing COPY and ANALYZE statements: BEGIN;
COPY atomic.events FROM 's3://fred-test-out/enriched/good/' CREDENTIALS 'aws_access_key_id=xxxxxxxxxxxxx;aws_secret_access_key=xxxxxxxxxxxxx' REGION AS 'eu-west-1' DELIMITER '\t' MAXERROR  EMPTYASNULL FILLRECORD TRUNCATECOLUMNS  TIMEFORMAT 'auto' ACCEPTINVCHARS GZIP;
ANALYZE atomic.events;
COMMIT;: ERROR: syntax error at or near "EMPTYASNULL"
  Position: 225
```

Is there a useful error message that doesn't risk including credentials? We could try to anonymize the credentials in the query before sending the event, but I don't know if it is possible to make that watertight.

**Comment by alexanderdean** [comment]
Hey Fred - good catch. It should be possible to make this pretty watertight - just search for CREDENTIALS '...' and replace with CREDENTIALS ''. This is what Redshift does in the console when reporting loads.

**Comment by fblundun** [comment]
That should work for the actual COPY statement but I'm also thinking about the "syntax error" part of the message containing private information, something like this:

```
ERROR:  syntax error at or near "BADTOKEN"
LINE 1: ...ess_key=xxxxxxxxxxxx' BADTOKEN REGIO...
```

We could work around this by doing find and replace on the whole error message for every substring of length at least 7 which is identical to any substring of either credential string.

**Comment by alexanderdean** [comment]
Sounds good. Where does the >=7 constraint come from?

**Comment by fblundun** [comment]
Suppose we decide to use this method of choosing some n and erasing all substrings of the error message which match a substring of a credential of length at least n. Then n should be large enough that it's unlikely that any credential substring of length n will appear in the error message outside the credentials. (For example, if n = 3 and the credentials contain the substring "ERR", then all instances of "ERR" in the error message will be replaced.) But if n is too large, then we risk substantial chunks of the credentials appearing in the error message. 7 is my guess at an intermediate value of n to avoid both these problems...

**Comment by alexanderdean** [comment]
Sounds good to me!

**Comment by alexanderdean** [comment]
@fblundun - can we take the above approach and apply it to the StorageLoader's stdout too? In other words, the credentials-scrubbing code should be applied to stdout/stderr/Snowplow... Please create another ticket in this release as necessary...
