### ISSUE TITLE
no-js tracker wizard on website doesn't generate a tag anymore

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#685]

**Comment by alienware** [comment]
Hey guys,

Is there an alternative way to generate tags?

**Comment by alexanderdean** [comment]
Hey @alienware - it's pretty straightforward using the Snowplow Tracker Protocol: https://github.com/snowplow/snowplow/wiki/snowplow-tracker-protocol

Make sure to setup a JavaScript Tracker on a friendly website to get a better handle on what valid payloads look like...

**Comment by alienware** [comment]
Thanks a lot for pointing that out. Love the documentation. :)

**Comment by BenFradet** [comment]
no the same website, closing
