### ISSUE TITLE
Explore browser fingerprinting

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#70]
1. HTTP_ACCEPT Headers
2. Browser Plugin Details
3. (Maybe system fonts?)

Create and store a hash?

See:
- https://panopticlick.eff.org/index.php?action=log&js=yes
- https://panopticlick.eff.org/browser-uniqueness.pdf
- http://browserspy.dk/

**Comment by ryanrozich** [comment]
I have a question about this feature, not sure if this is the right place to ask it - feel free to point me to another venue.

We have just started looking at switching to Snowplow for our web analytics. So far I've been very impressed. We have just loaded our first batch of about a days worth of data into redshift. We are running snowplow on a single website (domain) at the moment.

In comparing the number of distinct `user_fingerprint` values (in redshift) to the number of distinct `domain_userid` values, we noticed much higher counts of domain ids than user fingerprints. For example: we are seeing about 102K distinct domain ids and 35.6K distinct user fingerprint values (or about 2.87 domain ids per user fingerprint on average). So a couple questions:

(1) Is it safe to say that for a days worth of event data measured from events coming from a single domain that the difference in fingerprints and domain IDs represent "collisions", where multiple users (browser-installs) hash to the same fingerprint, or is there another explanation for the difference?

(2) Is this ratio of domain ids to fingerprints about what you would expect?

**Comment by yalisassoon** [comment]
@ryanrozich the best place for this sort of question is our [discourse](http://discourse.snowplowanalytics.com/). We already have the user fingerprinting explored on it [here](http://discourse.snowplowanalytics.com/t/is-the-user-fingerprint-unique-and-when-should-it-be-used/333) - if any of that isn't clear if you reply on the thread we can continue the discussion there!

Thanks


Yali

**Comment by ryanrozich** [comment]
thanks!
