### ISSUE TITLE
Referer url containing unencoded % character generates bad rows

### ISSUE THREAD

**Issue by murphybob** [snowplow/snowplow#706]
I've noticed a bunch of bad rows being generated in our logging. The cause seems to be an unencoded % character in the referring page's url making it technically in violation of the spec and crucially not parseable by URI.create(String uri) as used in stringToUri in [ConversionUtils.scala](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/ConversionUtils.scala#L205).

The offending referer url looks like: http://www.retailer.co.uk/category/20%-off-selected/

As this is a referer it is not one we control and not something we can change, so I think the url parsing needs to be a little more flexible about these urls which browsers are ok with despite not conforming to spec.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/207
