### ISSUE TITLE
sessions_technology sets:detail typo

### ISSUE THREAD

**Issue by akhill** [snowplow/snowplow#782]
@yalisassoon - I noticed a potential typo in sessions_technology.view.lookml.

sets:
    detail:
      - visits.visit_count
      - visits.bounce_rate
      - events.approx_usgae_per_visitor_in_minutes
      - events.events_per_visit

Shouldn't the 3rd detail be: events.approx_user_usage_in_minutes.

**Comment by alexanderdean** [comment]
Can't find this in the file anymore: https://github.com/snowplow/snowplow/blob/master/5-data-modeling/looker/lookml/sessions_technology.view.lookml

Closing; please re-open if this is still a thing.
