### ISSUE TITLE
Add additional EMR job that sums number of good and bad rows generated in last job

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#822]
This will run immediately after the core Scalding Enrichment process as run.
As a result, all the data processed will still be in HDFS (rather than S3)
It should be a simple reduce job, that writes the output to S3. The output will also be loaded into ElasticSearch

**Comment by alexanderdean** [comment]
We can potentially implement this as a Spark job which embeds a Snowplow Tracker and just fires the summary counts to a collector on completion...
