### ISSUE TITLE
Add process to load aggregate monitoring data generated in #822 into Elastic Search

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow#825]
As well as loading bad rows themselves into Elastic Search (see https://github.com/snowplow/snowplow/issues/824), we will also want to load the sums of the number of good and bad rows by run ID into Elastic Search. (I.e. the output of the EMR job documented in https://github.com/snowplow/snowplow/issues/822). This means that it will be possible in ElasticSearch to monitor the numer of bad rows as a percentage of total rows.

**Comment by alexanderdean** [comment]
When we do this, we will likely emit the aggregates as Snowplow events rather than tie to a specific storage target...
