### ISSUE TITLE
Scala Common Enrich: add ability to use AES encryption in AnonIp enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#846]
The idea is that we completely anonymize the IP address but still make it usable for analytics.

Unscheduled. Resources:
- https://medium.com/@vijayp/of-taxis-and-rainbows-f6bc289679a1
- http://stackoverflow.com/questions/4100445/encryption-of-ip-address
- http://www.keyczar.org/
- http://www.bouncycastle.org/java.html

/cc @yalisassoon

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/210
