### ISSUE TITLE
Move enrichments to Akka

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#867]
Essentially use Akka as a module system (instead of e.g. OSGI).
- http://benninger.ca/posts/creating-an-akka-actor-from-a-dynamically-loaded-jar-file-in-scala/
- https://gist.github.com/earldouglas/877999

Initially enrichments will still be blocking and sequential. We can parallelize them later.

**Comment by chuwy** [comment]
Came to this conclusion (and googled same links) while thinking about Sauna extension mechanisms.

**Comment by alexanderdean** [comment]
Cool!

**Comment by chuwy** [comment]
Wontfix.
