### ISSUE TITLE
Canonical event model fields not present in atomic.events

### ISSUE THREAD

**Issue by akhill** [snowplow/snowplow#869]
Referring to the canonical event model, I'm seeing a few fields that are not present in atomic.events:

[page_type](https://github.com/snowplow/snowplow/wiki/canonical-event-model#221-web-specific-fields) - I don't see anything else that would make sense as a replacement potential for this field.
[mkt_referrerurl](https://github.com/snowplow/snowplow/wiki/canonical-event-model#221-web-specific-fields) - I think this is actually page_referrer.

There may be others, but wanted to bring attention to these as I just noticed.

**Comment by BenFradet** [comment]
It has been fixed in the doc, closing
