### ISSUE TITLE
Contracts in cli.rb not working

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow#906]
I can't make any of the contracts in cli.rb fail. Even adding functions which obviously violate their contracts doesn't work. The Contracts library must be getting loaded since

```ruby
Contract None => Num
```
doesn't cause NameError: uninitialized constant Num.

Contracts seem to working as expected in the other files.

I don't think this is a recent issue - I've checked out tags/0.9.4 and reproduced it there.

**Comment by alexanderdean** [comment]
I believe that the combination of #1497 and #1438 should fix this, closing...
