### ISSUE TITLE
Enrichment outputs more characters than acceptable in fields for storage

### ISSUE THREAD

**Issue by kingo55** [snowplow/snowplow#926]
Hi guys,

I'm getting more failed loads now that some stuff I'm tracking in se_action is exceeding the character limit. Might need to truncate data rather than stop storage from loading:

PG::Error error executing BEGIN;
COPY atomic.events FROM '/usr/tmp/spevents/run=2014-07-28-08-00-02/part-00001' W                                   ITH CSV ESCAPE E'\x02' QUOTE E'\x01' DELIMITER '        ' NULL '';
COPY atomic.events FROM '/usr/tmp/spevents/run=2014-07-28-08-00-02/part-00000' W                                   ITH CSV ESCAPE E'\x02' QUOTE E'\x01' DELIMITER '        ' NULL '';
COMMIT;: ERROR:  value too long for type character varying(255)
CONTEXT:  COPY events, line 98550, column se_action: "https://interyield.jmp9.co                                   m/InterYield/getSnoozing.do?affiliate=adpkyield3&subid=A1E42196-7B72-4448-..."

Should we consider truncation by default across all fields where data is at risk of exceeding field character limits / types? It's the behaviour I've come to expect from GA, so when I adapt tracking for Snowplow, it has a tendency to break and cause problems when I need to 

Cheers,
Rob

**Comment by quorak** [comment]
+1 

```
2015-04-27 10:49:26 CEST STATEMENT:  COPY atomic.events FROM STDIN WITH CSV ESCAPE E'\x02' QUOTE E'\x01' DELIMITER '	' NULL ''
2015-04-27 10:49:27 CEST ERROR:  value too long for type character varying(255)
2015-04-27 10:49:27 CEST CONTEXT:  COPY events, line 2841, column mkt_source: "facebook.se/lp/limited/xxxxx."
```

**Comment by chuwy** [comment]
Hey @BenFradet, do you think we can do something about it in near future? Maybe along with https://github.com/snowplow/iglu-central/issues/778

It will be quite useful downstream of enrich stage to have more assumptions about the format of an event we'd like to consume. We already had issues with RDB Shredder [not properly truncating columns](https://github.com/snowplow/snowplow-rdb-loader/issues/103) also we have similar problems in Snowflake. We can go around all of them, but I'm wondering if this is a right path and why not to restrict the schema upstream.

**Comment by BenFradet** [comment]
Sure, if I can validate the final event :+1:

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/214
