### ISSUE TITLE
Scala Common Enrich: add ability to merge querystring and payload data

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#929]
This is a nice-to-have.

The idea is that if the user sets up a webhook like this:

```
http://collector.acme.com/com.sendgrid/v2/i?aid=email
```

Then we can merge the `aid` field into each event which is sent by Sendgrid to that endpoint.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/215
