### ISSUE TITLE
snowplowctl: add ability to target existing persistent cluster

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#936]
Instead of spinning up a new cluster.

**Comment by alexanderdean** [comment]
Covered by #1173?

**Comment by ngocthanhit** [comment]
Hi all, 

I am facing with this problem : 
Before merging, remember that the contents of HDFS [1] [2] is not cleared out between "runs" in a persistent cluster, so you could easily end up reprocessing the same data...
[1] hdfs:///local/snowplow/enriched-events/
[2] hdfs:///local/snowplow/raw-events/

So the next running was  re-processing the old data. Did any one solve this issue ? 

Thanks for read and help.

**Comment by alexanderdean** [comment]
Hi @ngocthanhit - my suggestion would be to add some startup code into Scala Hadoop Enrich and Hadoop Shred to clear out those file paths. You should be able to use something like `fullyDelete`: https://hadoop.apache.org/docs/r1.2.1/api/

**Comment by ngocthanhit** [comment]
Thanks so much @alexanderdean. I need to implement those code now to use in my existing cluster.

**Comment by alexanderdean** [comment]
Yep, please open a PR when you have it working! This code will give you a flavor of how to do one-time setup tasks in our Hadoop jobs:

https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-hadoop-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich.hadoop/EtlJob.scala#L72

**Comment by ngocthanhit** [comment]
Yes sure i will :+1:

**Comment by alexanderdean** [comment]
Actually - what I suggested won't work... What I suggested will delete precisely the files that you want to process - the ones that S3DistCp just copied into hdfs for this run.

Alternative suggestions:

1. Update the hdfs pathing in EmrEtlRunner to include the run ID, or
2. Add a scripting step after enrich and shred to delete everything from hdfs

In fact, with option 1 you would still need 2, because otherwise your HDFS cluster will run out of space. So I would jump straight to step 2.

Resources:

* http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-hadoop-script.html
* http://stackoverflow.com/a/16797599/255627

**Comment by ngocthanhit** [comment]
Can you send me the file which process for  after enrich and shred, so i will try to add the setup for delelete everything from hdfs? I am too new with scala so still investigating your code now :) 
Thanks

**Comment by alexanderdean** [comment]
You don't need to write any Scala. Instead, you:

1. Write a Bash script which uses the hadoop hdfs command line tools to empty the HDFS path
2. Update the EmrEtlRunner to add a new job step which invokes your Bash script using Amazon's  script-runner.jar step

All as per the links I've shared.

**Comment by ngocthanhit** [comment]
I will try to apply to my current cluster now.

**Comment by ngocthanhit** [comment]
@alexanderdean  I can run with an existing cluster using feature/existing-emr branch and add the customer jar step for empty the HDFS path. So will i create an PR for your to process ? 
Thanh/

**Comment by alexanderdean** [comment]
Sounds good to me! Thanks @ngocthanhit

**Comment by alexanderdean** [comment]
Bringing forwards

**Comment by BenFradet** [comment]
done in #3945 , closing
