### ISSUE TITLE
Scala Common Enrich: add IAB Spiders & Robots Enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#937]
* A new enrichment which leverages the IAB bots and spiders database to enrich Snowplow events
* The enrichment is configured using the JSON Schema already generated by Rostyslav
* The enrichment adds a new context, already defined by Rostyslav, to the derived contexts of the enriched event (viz most of our other enrichments)

- https://plus.google.com/+GoogleAnalytics/posts/2tJ79CkfnZk
- http://www.iab.net/1418/spiders

TODO: I need to talk to IAB to figure out a more practical licensing approach for an open-source project like Snowplow.

---

The IAB Spiders & Robots Enrichment uses the [IAB/ABC International Spiders and Bots List](https://www.iab.com/guidelines/iab-abc-international-spiders-bots-list/) to determine whether an event was produced by a user or a robot/spider based on its' IP address and user agent.

There are five fields that can be added to the "parameters" section of the enrichment configuration JSON: `ipFile`, `excludeUseragentFile`, `includeUseragentFile`, `httpUsername` and `httpPassword`. The first three fields in particular correspond to one of the IAB/ABC database files, and need to have two inner fields:

* The `database` field containing the name of the database file.
* The `uri` field containing the URI of the bucket in which the database file is found.

The table below describes the three types of database fields:

| **Field name** | **Database description** | **Accepted database filenames**|
|---------------:|:-------------------------|:-------------------------------|
| `ipFile` | Blacklist of IP addresses considered to be robots of spiders | `"ip_exclude_current_cidr.txt"` |
| `excludeUseragentFile` | Blacklist of useragent strings considered to be robots or spiders | `"exclude_current.txt"` |
| `includeUseragentFile` | Whitelist of useragent strings considered to be browsers | `"include_current.txt"` |

All three of these fields **must** be added to the enrichment JSON, as the IAB lookup process uses all three databases to detect robots and spiders.

In addition to these, the IAB enrichment config can contain two optional fields: `httpUsername` and `httpPassword`, which will be used if any of the database files are secured by basic HTTP authentication. Either **none** or **both** of these should be present in the enrichment config at the same time.

### Examples

Here is an example configuration JSON, containing all required and optional fields:

```json
{
    "schema": "com.snowplowanalytics.snowplow.enrichments/iab_spiders_and_robots_enrichment/jsonschema/1-0-0",
    "data": {
        "name": "iab_spiders_and_robots_enrichment",
        "vendor": "com.snowplowanalytics.snowplow.enrichments",
        "enabled": true,
        "parameters": {
            "ipFile": {
                "database": "ip_exclude_current_cidr.txt",
                "uri": "s3://my-private-bucket/iab"
            },
            "excludeUseragentFile": {
                "database": "exclude_current.txt",
                "uri": "s3://my-private-bucket/iab"
            },
            "includeUseragentFile": {
                "database": "include_current.txt",
                "uri": "s3://my-private-bucket/iab"
            },
            "httpUsername": "USERNAME_PLACEHOLDER",
            "httpPassword": "PASSWORD_PLACEHOLDER"
        }
    }
}
```

### Data sources

This enrichment uses the following fields of a Snowplow event:
- `useragent` to determine an event's useragent
- `user_ipaddress` to determine an event's IP address
- `derived_tstamp` to determine an event's datetime (some entries in the Spiders & Robots List can be considered "stale")

### Algorithm

As mentioned previously, this enrichment uses the IAB/ABC International Spiders & Robots List to look up information about an event based on it's IP address and useragent. It processes IAB/ABC database files using the Snowplow [IAB Spiders And Robots Java Client](https://github.com/snowplow/iab-spiders-and-robots-java-client).

### Data generated

The enrichment adds a new derived context to the enriched event, which is based on the [com.iab.snowplow/spiders_and_robots/jsonschema/1-0-0](https://github.com/snowplow/iglu-central/pull/767/files) schema and contains the following data:

Field | Purpose
:---|:---
`spiderOrRobot` | true if the event checked against the list is a spider or robot, false otherwise
`category` | a category based on activity if event is a spider or robot, BROWSER otherwise
`reason` | the type of database that caused the event to be flagged as a spider or robot, PASSED_ALL otherwise
`primaryImpact` | whether the spider or robot would affect page impression measurement, ad impression measurement, both or none

**Comment by nesbtesh** [comment]
@alexanderdean  How do you determine which event is from a bot?

**Comment by alexanderdean** [comment]
Updated ticket name, please update commit etc

**Comment by alexanderdean** [comment]
@rzats - I think your spec above for the enrichment is excellent, really well done. Just a couple of points:

* Are there any failure states / error handling where we need to document how the enrichment behaves (if not, still add a section making that clear)
* In your example JSON, wouldn't it make more sense for one of the paths to be HTTP, given that you are supplying the HTTP basic auth keys
* Can you mention the authentication approach used to access the S3 buckets
* Can you put a warning that the database files are commercial and proprietary and are not to be stored publically (e.g. on unprotected HTTPS) anywhere
* Can you clarify what happens if an unprotected HTTPS path is used - do we error?

**Comment by paulboocock** [comment]
> Do I need to subscribe to IAB Spiders & Robots and pay their fee to use it?

Yes you do. I added a more complete answer here: https://discourse.snowplow.io/t/iab-enrichment-snowplow-documentation/7983/2
