### ISSUE TITLE
Scala Stream Collector: add splitter for large event arrays

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#941]
Maximum record size for Kinesis is 50 KB (http://docs.aws.amazon.com/kinesis/latest/dev/service-sizes-and-limits.html), so we will need a mechanism to split larger payloads coming from POSTs.

This will need to support:

* Self-describing JSONs where the `data:` field is an array
* Payloads containing vanilla JSON arrays

**Comment by alexanderdean** [comment]
This is pretty important actually...

**Comment by fblundun** [comment]
Is the second case for POSTs whose body is an array of individual event JSONs, e.g.

```json
[{
  "e": "se",
  "p": "srv",
  "tv": "py-0.9.0"
}, ...]
```

?

**Comment by alexanderdean** [comment]
Hey @fblundun - I think the only important case is the one you cite - splitting out a `payload_data` into multiple smaller `payload_datas`...

**Comment by alexanderdean** [comment]
We will also need to support an event being a) oversized and b) failing splitting, so necessitating a bad stream...

**Comment by alexanderdean** [comment]
We still need this, it just splits at 1Mb...
