### ISSUE TITLE
Aggregate Device Category reporting in Snowplow Analytics skewed

### ISSUE THREAD

**Issue by digdeep** [snowplow/snowplow#969]
#### Background

Aggregate mobile reporting is highly skewed. There is a similar thread running for the `device_type` field (link to this thread available below). However, for **Aggregate Device Category reporting**, an accurate report is unavailable that produces basic reports with a dimension breakdown of `deviceCategory` (using a GA reference here, I think they have nailed this definition, sorry) that is, `deviceCategory` field values is either `mobile` OR `tablet` OR `desktop`
#### Available Snowplow Analytics fields:
- **platform** This is user defined but limited to the following field values as per table [Common parameters (platform and event independent)](https://github.com/snowplow/snowplow/wiki/SnowPlow-Tracker-Protocol#1-common-parameters-platform-and-event-independent) 
- **device_type** An example field value == `computer`
### Question about device category related fields in SP:
- Will platform table going to be finalised and enabled without it being user defined?
- Will platform table values going to split `Mobile/Tablet` into  separate field values?
#### Current Hack/ Solution deployed

**Required**
- GTM Macro using detect device type .js
- IGLU Schema to store this value

**Steps to replicate this client side:** 
- Create **GTM Macro** as **custom javascript** called `{{SPplatformCategory}}` and insert the below js in the field. 

``` javascript
function deviceType(){
if( navigator.userAgent.match(/Mobi/i) ) {
var windowWidth = window.screen.width < window.outerWidth ?
window.screen.width : window.outerWidth;
if(windowWidth < 500){
deviceType = 'mobile';
} else {
deviceType = 'tablet';
}
}
else if( navigator.userAgent.match(/iPad/i) ){
deviceType = 'tablet';
}
else if( navigator.userAgent.match(/Tablet/i) ){
deviceType = 'tablet';
}
else {
deviceType = 'desktop'
};
return deviceType;
}
```
- To test just create a tag in GTM and push the above into the dataLayer with firing rule `global onload`

``` javascript
dataLayer.push({
    'simonrumble': 'pornstar',
    'event': '{{SPplatformCategory}}'
 });
```
- Create GTM tag for Snowplow Analytics initialisation script with IGLU - async with firing rule of all pages `{{url}} matches RegEx .*`

``` javascript
<!-- Snowplow starts plowing -->
<script type = "text/javascript"> ;
    (function (p, l, o, w, i, n, g) {
        if (!p[i]) {
            p.GlobalSnowplowNamespace = p.GlobalSnowplowNamespace || [];
            p.GlobalSnowplowNamespace.push(i);
            p[i] = function () {
                (p[i].q = p[i].q || []).push(arguments)
            };
            p[i].q = p[i].q || [];
            n = l.createElement(o);
            g = l.getElementsByTagName(o)[0];
            n.async = 1;
            n.src = w;
            g.parentNode.insertBefore(n, g)
        }
    }(window, document, "script", "//XXXXXXXX.cloudfront.net/2.0.0/sp.js", "snowplow"));
    window.snowplow('newTracker', 'cf', 'XXXXXX.cloudfront.net', {
        appId: '{{MY_appId}}', 
        platform: '{{SPplatformCategory}}' //would be great to have SPplatformCategory placed here!
    });
     // window.snowplow('setUserId', 'alex 123'); 
     // window.snowplow('setUserIdFromLocation', 'id'); 
     // window.snowplow('setUserIdFromCookie', '_sp_id.4209') 
     // window.snowplow('setCustomUrl', '/overridden-url/'); 
    window.snowplow('enableActivityTracking', 10, 10);
    window.snowplow('enableLinkClickTracking');
       // window.snowplow('trackPageView', 'Async Test'); 
    window.snowplow('trackPageView', null); 

// This is an example custom context using SPplatformCategory as a field
    window.snowplow('trackPageView', null); [{
    schema: 'iglu:com.au.narbehisawesome/user/jsonschema/1-0-0', 
    data: {
        SPplatformCategory: 'mobile' 
    }
}]);
</script>
<!-- Snowplow stops plowing -->
```

Thoughts on the client side approach?

Related issues:
- [#756](https://github.com/snowplow/snowplow/issues/756)

**Comment by benhoyt** [comment]
Just a plug for this: it'd be great to add a `dvce_category` field alongside the other `dvce_*` fields that's one of "desktop", "mobile", "tablet". We do this kind of query via GA all the time.

**Comment by alexanderdean** [comment]
Superceded by new useragent enrichment.
