### ISSUE TITLE
Documentation: add page on working with Scala codebase

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#976]
Vagrant, publish-local, IDEs etc. See here for starter material: https://groups.google.com/forum/#!topic/snowplow-user/_Ym9zhwRc8Q

**Comment by paulboocock** [comment]
Not sure this is too relevant anymore. Most repositories now have a CONTRIBUTING.md, maintainer quickstart, they all use the same `sbt` tooling and/or have built in Docker/Vagrant quickstarts.
