### ISSUE TITLE
Documentation: Broken sidebar links 

### ISSUE THREAD

**Issue by nniiicc** [snowplow/snowplow#979]
Top two pages on customized sidebar are broken (direct to 404)
1. Trackers
2. Overview (404)
3. JavaScript Tracker (404)

**Comment by alexanderdean** [comment]
Re-assigning to @ihortom to check if this is still live

**Comment by ihortom** [comment]
Found no broken links. Must have been fixed since.

**Comment by alexanderdean** [comment]
Thanks
