### ISSUE TITLE
Scala Common Enrich: add support for /vendor/version to GET requests

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#991]
Currently we expect GET requests to come into /i.

There is no reason why GET requests shouldn't be able to come into /vendor/version in future tracker versions. This should be as simple as adding support for com.snowplowanalytics.snowplow/tp(1/2) to `isIceRequest()`.

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/218
