### ISSUE TITLE
Scala Common Enrich: nearest store enrichment

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#997]
Enrichment configured with:
- An array of: store name + store long/lat
- Unit of measurement: km or mile
- Formula: greatest-circle (aka crow flies)

Then it uses the event's lat long (from MaxMind) to figure out which is the nearest store, its lat long and its distance. That gets stored in a context.

Super interesting for mobile apps and mobile web, as you can potentially identify customers who are inside your store (or en route to your store) while they are browsing...

**Comment by chuwy** [comment]
Migrated to https://github.com/snowplow/enrich/issues/219
